import assert from 'node:assert/strict'
import {chromium} from '../../../web/node_modules/playwright/index.mjs'
import {readFile,writeFile} from 'node:fs/promises'
import {fileURLToPath} from 'node:url'
import {createHash} from 'node:crypto'
const out=new URL('./',import.meta.url),origin='http://127.0.0.1:5180',href=origin+'/?workspace=tenant-a&view=market-data&area=testing&section=market-data'
const browser=await chromium.launch({headless:true}),report={cases:[],errors:[],blocked:[]}
const dataset={dataset_id:'independent-fixture-'+ 'a'.repeat(64),instrument_id:'EURUSDm',timeframe:'60s',provider_id:'local-catalog',row_count:2,source:{provider:'Exness-MT5Trial14 / MT5',license_use:'isolated QA',retrieved_at_utc:'2026-10-07T00:00:00Z'},available_range:{from_utc:'2026-01-01T00:00:00Z',to_utc:'2026-01-01T00:01:00Z'},quality_status:'unverified',artifact_sha256:'a'.repeat(64),instrument_spec:{},holdout_policy:{mode:'none'}}
const preview={dataset_id:dataset.dataset_id,row_count:2,unique_row_count:2,quality:{disposition:'pass',duplicates:0,out_of_order:0,gaps:[]},available_range:dataset.available_range,raw_sha256:'a'.repeat(64),normalized_sha256:'b'.repeat(64)}
const csv='time,open,high,low,close\n2026-01-01T00:00:00Z,1,1.1,0.9,1\n2026-01-01T00:01:00Z,1,1.1,0.9,1'
async function setup({theme='dark',width=360,fixture='empty',pending=false}={}){
 const context=await browser.newContext({viewport:{width,height:987},reducedMotion:'reduce'}),traffic=[],writes=[],gates={};let imported=false
 await context.addInitScript(theme=>{localStorage.setItem('tw-theme',theme);localStorage.setItem('tw-language','vi')},theme)
 await context.routeWebSocket('**/*',s=>s.close())
 await context.route('**/*',async route=>{const r=route.request(),u=new URL(r.url());if(u.pathname.startsWith('/api/'))traffic.push({method:r.method(),path:u.pathname})
  if(![origin,'http://127.0.0.1:8010'].includes(u.origin)||/^\/api\/v2\/(live|data\/(market-assets|providers))/.test(u.pathname)){report.blocked.push({method:r.method(),url:r.url()});return route.abort()}
  if(r.method()==='POST'&&u.pathname.startsWith('/api/v2/data/csv/')){writes.push({path:u.pathname,body:r.postDataJSON()});if(pending)await new Promise(resolve=>gates[u.pathname.endsWith('/preview')?'preview':'import']=resolve);if(fixture==='failed')return route.fulfill({status:422,json:{detail:'Independent CSV rejection'}});if(u.pathname.endsWith('/preview'))return route.fulfill({json:{preview}});imported=true;return route.fulfill({json:{dataset}})}
  if(!['GET','HEAD','OPTIONS'].includes(r.method())){report.blocked.push({method:r.method(),url:r.url()});return route.abort()}
  if(u.pathname==='/api/v2/data/datasets'&&fixture==='failed')return route.fulfill({status:503,json:{detail:'Independent catalog unavailable'}})
  if(u.pathname==='/api/v2/data/datasets'&&fixture!=='real')return route.fulfill({json:{items:fixture==='catalog'||imported?[dataset]:[]}})
  return route.continue()
 })
 const page=await context.newPage();page.on('pageerror',e=>report.errors.push(String(e)));await page.goto(href);await page.locator(fixture==='failed'?'[data-testid="data-desk-retry"]':'.data-library-count').waitFor();return{context,page,traffic,writes,gates}
}
async function screen(page,name){await page.screenshot({path:fileURLToPath(new URL(name+'.png',out)),fullPage:true})}
async function closeAndFocus(page,opener,method='escape'){
 if(method==='escape')await page.keyboard.press('Escape');else if(method==='backdrop')await page.mouse.click(2,2);else await page.locator('dialog[open]').getByRole('button',{name:'Đóng',exact:true}).click()
 await page.locator('dialog[open]').waitFor({state:'hidden'});assert.equal(await opener.evaluate(e=>e===document.activeElement),true)
}
async function dialogGeometry(page){const geometry=await page.locator('dialog[open]').evaluate(e=>{const r=e.getBoundingClientRect(),body=e.querySelector('.data-library-dialog-body');return{left:r.left,right:r.right,top:r.top,bottom:r.bottom,viewport:innerWidth,pageOverflow:document.documentElement.scrollWidth-innerWidth,bodyOverflow:body.scrollWidth-body.clientWidth,bodyScrollHeight:body.scrollHeight,bodyClientHeight:body.clientHeight}});assert(geometry.left>=0&&geometry.right<=geometry.viewport);assert.equal(geometry.pageOverflow,0);assert.equal(geometry.bodyOverflow,0);return geometry}
async function run(name,fn){const c={name};report.cases.push(c);try{await fn(c);c.pass=true}catch(e){c.pass=false;c.failure=String(e);console.log(JSON.stringify(c))}}
try{
 for(const theme of ['dark','light'])for(const width of [360,1428])await run(`empty-${theme}-${width}`,async item=>{const{context,page,traffic}=await setup({theme,width,fixture:'real'});try{
  const root=page.getByTestId('data-desk-root'),opener=root.locator('.data-library-import');assert.match(await root.locator('.data-library-count').innerText(),/^0 /);assert.equal(await root.locator('.data-library-disclosure').count(),0);assert.equal(await root.getByTestId('data-desk-empty').count(),0);assert.equal(await root.locator('.data-library-paging').count(),0);await screen(page,item.name)
  for(const method of ['escape','backdrop','button']){await opener.focus();await page.keyboard.press('Enter');await page.locator('dialog[open]').waitFor();assert.equal(await page.getByTestId('data-desk-file-input').evaluate(e=>e===document.activeElement),true);item.geometry=await dialogGeometry(page);if(method==='escape'){await screen(page,item.name+'-csv');for(let n=0;n<8;n++){await page.keyboard.press('Tab');assert(await page.locator('dialog[open]').evaluate(e=>e.contains(document.activeElement)||document.activeElement===document.body),'Native tab sequence must not focus underlying controls')}}await closeAndFocus(page,opener,method)}item.traffic=traffic
 }finally{await context.close()}})
 for(const theme of ['dark','light'])await run(`details-${theme}-360`,async item=>{const{context,page,traffic}=await setup({theme,fixture:'catalog'});try{
  const opener=page.getByTestId('dataset-row-'+dataset.dataset_id);await opener.focus();await page.keyboard.press('Enter');await page.getByTestId('dataset-details').waitFor();item.geometry=await dialogGeometry(page);assert.equal(await page.getByTestId('dataset-details').locator('.rd-detail-grid > div').nth(1).locator('dd').innerText(),dataset.source.provider);assert(await page.locator('dialog[open]').evaluate(e=>e.contains(document.activeElement)));await screen(page,item.name);await page.locator('.data-library-dialog-body').evaluate(e=>e.scrollTop=e.scrollHeight);assert(await page.locator('.data-library-dialog-body').evaluate(e=>e.scrollTop>0));await screen(page,item.name+'-bottom');await closeAndFocus(page,opener);item.traffic=traffic
 }finally{await context.close()}})
 for(const theme of ['dark','light'])await run(`pending-${theme}-360`,async item=>{const{context,page,traffic,writes,gates}=await setup({theme,pending:true});try{
  const opener=page.locator('.data-library-import');await opener.click();const dialog=page.locator('dialog[open]'),file=page.getByTestId('data-desk-file-input');await file.setInputFiles({name:'isolated.csv',mimeType:'text/csv',buffer:Buffer.from(csv)});await page.getByTestId('data-desk-preview-button').click();await page.waitForFunction(()=>document.querySelector('dialog[open]')?.getAttribute('aria-busy')==='true')
  for(const phase of ['preview','import']){await page.locator('dialog[open] [aria-label="Đóng"]').waitFor();assert(await dialog.getByRole('button',{name:'Đóng',exact:true}).isDisabled());assert(await file.isDisabled());await page.keyboard.press('Escape');await page.mouse.click(2,2);assert.equal(await dialog.count(),1);await screen(page,item.name+'-'+phase);while(!gates[phase])await page.waitForTimeout(10);gates[phase]();if(phase==='preview'){await page.getByTestId('data-desk-quality-report').waitFor();await page.getByTestId('data-desk-import-button').click();await page.waitForFunction(()=>document.querySelector('dialog[open]')?.getAttribute('aria-busy')==='true')}}
  await page.getByTestId('dataset-details').waitFor();assert.equal(await page.locator('dialog[open]').count(),1);item.geometry=await dialogGeometry(page);await screen(page,item.name+'-success');await page.keyboard.press('Escape');await page.locator('dialog[open]').waitFor({state:'hidden'});assert.equal(await opener.evaluate(e=>e===document.activeElement),true);assert.equal(writes.length,2);item.interceptedWrites=writes.map(w=>w.path);item.traffic=traffic
 }finally{for(const release of Object.values(gates))release();await context.close()}})
 for(const theme of ['dark','light'])await run(`error-${theme}-360`,async item=>{const{context,page,traffic,writes}=await setup({theme,fixture:'failed'});try{
  await page.getByTestId('data-desk-retry').waitFor();const opener=page.locator('.data-library-import');await opener.click();await page.getByTestId('data-desk-file-input').setInputFiles({name:'isolated.csv',mimeType:'text/csv',buffer:Buffer.from(csv)});await page.getByTestId('data-desk-preview-button').click();await page.getByTestId('data-desk-import-error').waitFor();assert.equal(await page.locator('dialog[open]').getAttribute('aria-busy'),'false');assert.equal(await page.locator('dialog[open]').getByRole('button',{name:'Đóng',exact:true}).isDisabled(),false);item.geometry=await dialogGeometry(page);await screen(page,item.name);await closeAndFocus(page,opener);assert.equal(writes.length,1);item.interceptedWrites=writes.map(w=>w.path);item.traffic=traffic
 }finally{await context.close()}})
 report.pass=report.cases.every(c=>c.pass)&&!report.errors.length&&!report.blocked.length
}finally{report.hashes={};for(const f of ['DataDeskWorkspace.jsx','data-library.css'])report.hashes[f]=createHash('sha256').update(await readFile(new URL('../../../web/src/'+f,out))).digest('hex');await writeFile(new URL('review.json',out),JSON.stringify(report,null,2));await browser.close();console.log(JSON.stringify({pass:report.pass,cases:report.cases,errors:report.errors,blocked:report.blocked,hashes:report.hashes},null,2))}
