import assert from 'node:assert/strict'
import {chromium} from '../../../web/node_modules/playwright/index.mjs'
import {readFile,writeFile} from 'node:fs/promises'
import {fileURLToPath} from 'node:url'
import {createHash} from 'node:crypto'
const out=new URL('./',import.meta.url),origin='http://127.0.0.1:5180',base=origin+'/?workspace=tenant-a&view=market-data&area=testing&section=market-data'
const browser=await chromium.launch({headless:true}),report={cases:[],errors:[],blocked:[]}
const categories=[['stock','AAPL','Cổ phiếu'],['futures','ES','Hợp đồng tương lai'],['fx','EURUSD','Forex'],['crypto','BTCUSD','Crypto'],['index','US500','Chỉ số'],['metal','XAUUSD','Kim loại'],['energy','BRENT','Năng lượng'],['agriculture','WHEAT','Nông sản']]
const spec={asset_class:'metal',base_ccy:'XAU',quote_ccy:'USD',account_ccy:'USD',tick_size:'0.01',pip_size:'0.1',contract_size:'100',quantity_min:'0.01',quantity_step:'0.01',effective_from_utc:'1970-01-01T00:00:00Z'}
const dataset={dataset_id:'independent-old',instrument_id:'XAUUSD',timeframe:'60s',timeframe_seconds:60,provider_id:'local-catalog',instrument_spec:spec,row_count:2,source:{provider:'isolated-QA',source_id:'isolated-source',license_use:'qa-only',retrieved_at_utc:'2026-10-07T00:00:00Z'},available_range:{from_utc:'2026-01-01T00:00:00Z',to_utc:'2026-01-01T00:01:00Z'},quality_status:'unverified',artifact_sha256:'a'.repeat(64),created_at_utc:'2026-01-01T00:00:00Z',holdout_policy:{mode:'none'}}
const instruments=categories.map(([asset_class,instrument_id])=>({asset_class,instrument_id,provider_id:'qa-only-provider',provider:'isolated-QA',name:'Independent fixture '+instrument_id}))
const updated={...dataset,dataset_id:'independent-new',created_at_utc:'2026-10-07T00:00:00Z',artifact_sha256:'b'.repeat(64)}
const preview={dataset_id:updated.dataset_id,row_count:2,unique_row_count:2,quality:{disposition:'pass',duplicates:0,out_of_order:0,gaps:[]},available_range:dataset.available_range,raw_sha256:'a'.repeat(64),normalized_sha256:'b'.repeat(64)}
async function setup({theme='dark',width=360,fixture='real',dashboard=false}={}){
 const context=await browser.newContext({viewport:{width,height:987},reducedMotion:'reduce'}),traffic=[],writes=[];let imported=false
 await context.addInitScript(theme=>{localStorage.setItem('tw-theme',theme);localStorage.setItem('tw-language','vi')},theme);await context.routeWebSocket('**/*',s=>s.close())
 await context.route('**/*',async route=>{const r=route.request(),u=new URL(r.url());if(u.pathname.startsWith('/api/'))traffic.push({method:r.method(),path:u.pathname})
 if(![origin,'http://127.0.0.1:8010'].includes(u.origin)||/^\/api\/v2\/(live|data\/(market-assets|providers))/.test(u.pathname)){report.blocked.push({method:r.method(),url:r.url()});return route.abort()}
 if(r.method()==='POST'&&fixture==='update'&&u.pathname.startsWith('/api/v2/data/csv/')){writes.push({path:u.pathname,body:r.postDataJSON()});if(u.pathname.endsWith('/preview'))return route.fulfill({json:{preview}});imported=true;return route.fulfill({json:{dataset:updated}})}
 if(!['GET','HEAD','OPTIONS'].includes(r.method())){report.blocked.push({method:r.method(),url:r.url()});return route.abort()}
 if(u.pathname==='/api/v2/data/datasets'&&fixture!=='real')return route.fulfill({json:{items:imported?[dataset,updated]:[dataset],catalog_items:instruments}})
 if(dashboard&&u.pathname==='/api/v2/overview')return route.fulfill({json:{performance:{schema_version:'dashboard-replay-performance-v1',status:'ready',scope:{session_count:0,readable_session_count:0},metrics:{closed_trade_count:0},months:[],symbols:[],sessions:[],sources:[],excluded:[]}}})
 return route.continue()})
 const page=await context.newPage();page.on('pageerror',e=>report.errors.push(String(e)));await page.goto(dashboard?origin+'/?workspace=tenant-a&view=overview&area=testing&section=dashboard':base);await page.locator(dashboard?'[data-testid=dashboard-performance]':'[data-testid=data-desk-dataset-table]').waitFor();return{page,context,traffic,writes}
}
async function screen(page,name){await page.screenshot({path:fileURLToPath(new URL(name+'.png',out)),fullPage:true})}
async function choose(page,label,option){const button=page.getByRole('button',{name:label,exact:true});await button.click();await page.getByRole('option',{name:option,exact:true}).click()}
async function run(name,fn){const item={name};report.cases.push(item);try{await fn(item);item.pass=true}catch(e){item.pass=false;item.failure=String(e);console.log(JSON.stringify(item))}}
try{
 for(const theme of ['dark','light'])for(const width of [360,1428])await run(`real-${theme}-${width}`,async item=>{const{page,context,traffic}=await setup({theme,width});try{
 assert.equal(await page.locator('.data-library-count,.data-library-create,.data-library-disclosure').count(),0);assert.equal(await page.locator('.rd-table th').count(),7);assert.equal(await page.getByTestId('data-desk-dataset-table').locator('tbody tr').count(),0);assert.equal(await page.locator('.data-library-toolbar').getByRole('button',{name:'Tạo phiên'}).count(),0)
 item.toolbar=await page.locator('.data-library-toolbar').evaluate(e=>{const search=e.querySelector('.data-library-search').getBoundingClientRect(),filters=e.querySelector('.data-library-filters').getBoundingClientRect();return{search:{left:search.left,top:search.top,right:search.right},filters:{left:filters.left,top:filters.top,right:filters.right},overflow:document.documentElement.scrollWidth-innerWidth}});assert.equal(item.toolbar.overflow,0);if(width===1428)assert(item.toolbar.search.right<item.toolbar.filters.left+2);await screen(page,item.name);item.traffic=traffic
 }finally{await context.close()}})
 for(const theme of ['dark','light'])for(const width of [360,1428])await run(`fixture-${theme}-${width}`,async item=>{const{page,context,traffic}=await setup({theme,width,fixture:'grid'});try{
 const rows=page.locator('.rd-table tbody tr');assert.equal(await rows.count(),8);assert.equal(await rows.getByRole('button',{name:'Tạo phiên'}).count(),0);assert.equal(await rows.locator('.data-library-download:disabled').count(),8);assert.equal(await rows.locator('.data-library-more').count(),8);await screen(page,item.name)
 await page.locator('.data-library-filter-toggle').click();for(const [category,,label]of categories){await choose(page,'Danh mục',label);assert.equal(await rows.count(),1);assert.equal(await rows.first().locator('td').nth(1).innerText(),label)}await choose(page,'Danh mục','Tất cả danh mục');await choose(page,'Nguồn dữ liệu','isolated-QA');assert.equal(await rows.count(),8);await page.locator('.data-library-filter-toggle').click();assert.equal(await rows.count(),8)
 await choose(page,'Sắp xếp dữ liệu','Tên Z–A');assert.equal(await rows.first().locator('td').first().locator('strong').innerText(),'XAUUSD');await choose(page,'Sắp xếp dữ liệu','Đã tải trước');assert.equal(await rows.first().locator('td').first().locator('strong').innerText(),'XAUUSD');await page.locator('.data-library-search input').fill('btc');assert.equal(await rows.count(),1);await page.locator('.data-library-search input').fill('');
 const trigger=rows.first().locator('.data-library-more');await trigger.focus();await page.keyboard.press('ArrowDown');const menu=page.getByRole('menu');await menu.waitFor();assert.equal(await page.locator('dialog[open]').count(),0);assert.equal(await menu.getByRole('menuitem').count(),2);assert.equal(await menu.getByRole('menuitem').first().evaluate(e=>e===document.activeElement),true);item.menu=await menu.evaluate(e=>{const r=e.getBoundingClientRect();return{left:r.left,right:r.right,bottom:r.bottom,viewport:innerWidth}});assert(item.menu.left>=0&&item.menu.right<=width&&item.menu.bottom<=987);await screen(page,item.name+'-menu');await page.keyboard.press('End');assert.match(await page.locator(':focus').innerText(),/Nhập bản cập nhật/);await page.keyboard.press('Escape');assert.equal(await trigger.evaluate(e=>e===document.activeElement),true)
 await trigger.click();await menu.getByRole('menuitem',{name:'Xem chi tiết',exact:true}).click();await page.getByTestId('dataset-details').waitFor();await page.keyboard.press('Escape');assert.equal(await trigger.evaluate(e=>e===document.activeElement),true)
 await page.locator('.data-library-search input').fill('BTCUSD');const unloaded=rows.first().locator('.data-library-more');await unloaded.click();assert(await page.getByRole('menuitem',{name:'Xem chi tiết',exact:true}).isDisabled());assert.equal(await page.getByRole('menuitem',{name:'Nhập CSV cho tài sản',exact:true}).evaluate(e=>e===document.activeElement),true);await page.getByRole('menuitem',{name:'Nhập CSV cho tài sản',exact:true}).click();await page.getByTestId('data-desk-file-input').waitFor();assert.equal(await page.locator('input[name=instrumentId]').inputValue(),'BTCUSD');assert.equal(await page.locator('select[name=assetClass]').inputValue(),'crypto');await screen(page,item.name+'-csv');await page.keyboard.press('Escape');assert.equal(await unloaded.evaluate(e=>e===document.activeElement),true);item.traffic=traffic
 }finally{await context.close()}})
 await run('immutable-update-fixture',async item=>{const{page,context,traffic,writes}=await setup({width:1428,fixture:'update'});try{
 const trigger=page.locator('.rd-table tbody tr').filter({has:page.getByTestId('dataset-row-'+dataset.dataset_id)}).locator('.data-library-more');await trigger.click();await page.getByRole('menuitem',{name:'Nhập bản cập nhật',exact:true}).click();await page.getByTestId('data-desk-file-input').waitFor();assert.equal(await page.locator('input[name=instrumentId]').inputValue(),'XAUUSD');assert.equal(await page.locator('select[name=assetClass]').inputValue(),'metal');assert.equal(await page.locator('input[name=timeframeSeconds]').inputValue(),'60');await page.getByTestId('data-desk-file-input').setInputFiles({name:'isolated.csv',mimeType:'text/csv',buffer:Buffer.from('time,open,high,low,close\n2026-01-01T00:00:00Z,1,1.1,0.9,1\n2026-01-01T00:01:00Z,1,1.1,0.9,1')});await page.getByTestId('data-desk-preview-button').click();await page.getByTestId('data-desk-quality-report').waitFor();await page.getByTestId('data-desk-import-button').click();await page.getByTestId('dataset-details').waitFor();assert.match(await page.getByTestId('dataset-details').innerText(),/independent-new/);await page.keyboard.press('Escape');assert.equal(await page.getByTestId('dataset-row-independent-old').count(),1);assert.equal(await page.getByTestId('dataset-row-independent-new').count(),1);assert.equal(writes.length,2);assert.equal(writes[1].body.instrument.asset_class,'metal');assert.equal(writes[1].body.timeframe_seconds,60);assert.equal(writes[1].body.source.provider,'isolated-QA');assert.equal(writes[1].body.dataset_id,undefined);item.interceptedWrites=writes.map(w=>({path:w.path,instrument:w.body.instrument.instrument_id,timeframe:w.body.timeframe_seconds}));item.traffic=traffic;await screen(page,item.name)
 }finally{await context.close()}})
 await run('dashboard-zero-trades-fixture',async item=>{const{page,context,traffic}=await setup({width:1428,dashboard:true});try{assert.equal(await page.getByTestId('dashboard-data-state').innerText(),'');assert.equal(await page.getByText('Không có giao dịch đóng trong phạm vi này.',{exact:true}).count(),0);item.traffic=traffic;await screen(page,item.name)}finally{await context.close()}})
 report.pass=report.cases.every(c=>c.pass)&&!report.errors.length&&!report.blocked.length
}finally{report.hashes={};for(const f of ['DataDeskWorkspace.jsx','DataLibraryActions.jsx','dataLibraryModel.js','data-library.css','dataDeskApi.js','DashboardPerformance.jsx'])report.hashes[f]=createHash('sha256').update(await readFile(new URL('../../../web/src/'+f,out))).digest('hex');for(const f of ['api.py','data_sources.py'])report.hashes[f]=createHash('sha256').update(await readFile(new URL('../../../trading_workspace_v2/'+f,out))).digest('hex');await writeFile(new URL('review.json',out),JSON.stringify(report,null,2));await browser.close();console.log(JSON.stringify({pass:report.pass,cases:report.cases.map(c=>({name:c.name,pass:c.pass,failure:c.failure})),errors:report.errors,blocked:report.blocked,hashes:report.hashes},null,2))}
