import assert from 'node:assert/strict'
import { chromium } from '../../../web/node_modules/playwright/index.mjs'
import { readFile,writeFile,mkdir } from 'node:fs/promises'
import { createHash } from 'node:crypto'
import path from 'node:path'
import { DEMO_LEDGER } from '../../../web/src/demoFixtures.js'
import { filterAnalyticsRows,readAnalyticsExtraFilters } from '../../../web/src/tradingAnalyticsModel.js'
const out=path.dirname(new URL(import.meta.url).pathname.replace(/^\/(\w:)/,'$1'));await mkdir(out,{recursive:true})
const files=['SessionActions.jsx','session-actions.css','DashboardSessionCard.jsx','DashboardSessions.jsx','SessionPicker.jsx','SessionPerformance.jsx','DemoPreview.jsx','SessionFilter.jsx','session-filter.css','FxSelect.jsx','fx-select.css','AnalyticsFilterBar.jsx','AnalyticsFilterControls.jsx','analytics-filter-controls.css','AnalyticsWorkspace.jsx','FxAnalytics.jsx','tradingAnalyticsModel.js','page-layout.css','FxTradeLedger.jsx','ledger-controls.css','fx-analytics.css']
const pins=async()=>Promise.all(files.map(async f=>({file:f,sha256:createHash('sha256').update(await readFile('foundation_v2/web/src/'+f)).digest('hex')})))
const report={checks:[],failures:[],errors:[],blocked:[],requests:[],scrollbars:[],before:await pins()}
const b=await chromium.launch({headless:true,ignoreDefaultArgs:['--hide-scrollbars']}),c=await b.newContext(),p=await c.newPage();let fixture=false,fixtureCatalog
await c.routeWebSocket('**/*',ws=>ws.close())
await c.route('**/*',async r=>{const q=r.request(),u=new URL(q.url());if(!['http://127.0.0.1:5180','http://127.0.0.1:8010'].includes(u.origin)||!['GET','HEAD','OPTIONS'].includes(q.method())){report.blocked.push({method:q.method(),url:q.url()});return r.abort()}if(u.pathname.startsWith('/api/')){report.requests.push({path:u.pathname,demo:new URL(q.frame().url()).searchParams.get('demo'),fixture});if(fixture&&u.pathname==='/api/v2/replay/sessions')return r.fulfill({json:fixtureCatalog});const response=await r.fetch({url:'http://127.0.0.1:8010'+u.pathname+u.search});return r.fulfill({response})}return r.continue()})
p.on('pageerror',e=>report.errors.push(e.message))
const get=async path=>{const r=await c.request.get('http://127.0.0.1:8010'+path,{headers:{'X-Workspace-Id':'tenant-a'}});assert.ok(r.ok());return r.json()}
const catalog=await get('/api/v2/replay/sessions'),recordId=catalog.items.find(x=>!x.archived)?.record_id,record=await get('/api/v2/replay/sessions/'+recordId)
const url=(view,demo=true,extra='')=>`http://127.0.0.1:5180/?workspace=tenant-a&view=${view}&area=testing&section=${{overview:'dashboard',replay:'sessions',trade:'trades',analytics:'analytics'}[view]}&select=1&session=${recordId}${demo?'&demo=1':''}${extra}`
let contentBaseline
const goto=async(view,demo=true,extra='')=>{await p.goto(url(view,demo,extra));await p.waitForLoadState('networkidle');contentBaseline=await p.locator('.fx-content').evaluate(e=>({scroll:e.scrollWidth,client:e.clientWidth}));(report.contentBaselines ||= []).push({phase:report.phase,...contentBaseline})}
const button=name=>p.getByRole('button',{name,exact:true})
const metric=()=>p.locator('.fxa-metric').filter({has:p.locator('span',{hasText:/^Total trades$/})}).locator('strong').first()
const count=async()=>Number((await metric().innerText()).replaceAll('.',''))
const themeSet=async theme=>{if(await p.getByTestId('fxreplay-shell').getAttribute('data-theme')!==theme)await p.getByTestId('theme-toggle').click()}
const contentFits=async()=>{const state=await p.locator('.fx-content').evaluate(e=>({scroll:e.scrollWidth,client:e.clientWidth}));assert.ok(state.scroll<=Math.max(state.client,contentBaseline.scroll)+1,'new content horizontal overflow '+JSON.stringify({baseline:contentBaseline,state}))}
const fit=async selector=>{await contentFits();const box=await p.locator(selector).boundingBox(),clip=await p.locator('.fx-content').evaluate(e=>({left:e.getBoundingClientRect().left,right:e.getBoundingClientRect().left+e.clientWidth}));assert.ok(box.x>=clip.left-1&&box.x+box.width<=clip.right+1,'popup cropped by content '+JSON.stringify({box,clip}));assert.ok(box.x>=-1&&box.x+box.width<=p.viewportSize().width+1,'horizontal popup overflow '+JSON.stringify(box));assert.ok(box.y>=-1&&box.y+box.height<=p.viewportSize().height+1,'vertical popup overflow '+JSON.stringify(box));return box}
const trap=async d=>{for(const key of ['Tab','Shift+Tab'])for(let n=0;n<12;n++){await p.keyboard.press(key);assert.ok(await d.evaluate(e=>e.contains(document.activeElement)),'dialog focus escape')}}
const scrollbar=async list=>{await contentFits();const bounds=await list.boundingBox(),state=await list.evaluate(e=>({gutter:e.offsetWidth-e.clientWidth,height:e.clientHeight,full:e.scrollHeight,top:e.scrollTop}));report.scrollbars.push({phase:report.phase,stage:'before',...state,bounds});await p.evaluate(()=>{window.qaScrollEvents=[];for(const type of ['pointerdown','focusout'])document.addEventListener(type,e=>window.qaScrollEvents.push({type,target:e.target.className||e.target.tagName,related:e.relatedTarget?.className||e.relatedTarget?.tagName,x:e.clientX,y:e.clientY}),{capture:true,once:true})});await p.screenshot({path:path.join(out,report.phase+'-scrollbar-before.png')});assert.ok(state.gutter>2,'native gutter unavailable');assert.ok(state.full>state.height+10,'fixture not scrollable');await p.mouse.move(bounds.x+bounds.width-3,bounds.y+bounds.height*.65);await p.mouse.click(bounds.x+bounds.width-3,bounds.y+bounds.height*.65);await p.waitForTimeout(500);assert.ok(await list.isVisible(),'scrollbar click closed menu');const scrolled=await list.evaluate(e=>e.scrollTop);assert.ok(scrolled>state.top,'track click did not scroll');const thumb=Math.max(18,state.height*state.height/state.full),thumbY=bounds.y+scrolled/(state.full-state.height)*(state.height-thumb)+thumb/2;await p.mouse.move(bounds.x+bounds.width-3,thumbY);await p.mouse.down();await p.mouse.move(bounds.x+bounds.width-3,Math.min(bounds.y+state.height-3,thumbY+40),{steps:5});await p.mouse.up();await p.waitForTimeout(300);assert.ok(await list.isVisible(),'scrollbar drag closed menu');const after=await list.evaluate(e=>e.scrollTop);assert.ok(after!==scrolled,'thumb drag did not scroll');report.scrollbars.push({phase:report.phase,...state,scrolled,after})}
const run=async(name,work)=>{if(process.env.QA_ONLY && !new RegExp(process.env.QA_ONLY).test(name))return;report.phase=name;try{await work();report.checks.push({name,pass:true})}catch(e){report.failures.push({name,error:String(e),stack:e.stack,events:await p.evaluate(()=>window.qaScrollEvents)});await p.screenshot({path:path.join(out,'failure-'+name+'.png')}).catch(()=>{})}await writeFile(path.join(out,'progress.json'),JSON.stringify(report,null,2))}
try{
for(const theme of ['dark','light'])for(const width of [360,768,1440])for(const view of ['overview','replay','trade','analytics'])await run(`${view}-${theme}-${width}`,async()=>{
 await p.setViewportSize({width,height:width===360?700:987});await goto(view);await themeSet(theme)
 if(view==='overview'||view==='replay'){
  const name=view==='overview'?'Gold Swing':'London Breakout',del=button('Xóa '+name),archive=button('Lưu trữ '+name);assert.equal(await del.locator('svg').count(),1);await del.click();const d=p.getByRole('dialog',{name:'Xóa phiên',exact:true});await d.waitFor();assert.ok(await d.getByLabel('Tên phiên xác nhận xóa').evaluate(e=>document.activeElement===e));await trap(d);await p.keyboard.press('Escape');await d.waitFor({state:'hidden'});assert.ok(await del.evaluate(e=>document.activeElement===e));await archive.click();await p.getByRole('dialog').waitFor();await p.keyboard.press('Escape');await p.getByRole('dialog').waitFor({state:'hidden'});if(view==='replay'){assert.equal(await p.locator('.fxs-metric-info').first().locator('svg').count(),1);await button('Chọn phiên replay').click();assert.equal(await p.getByRole('option',{name:'Chọn phiên replay',exact:true}).count(),0);await fit('.fx-select-menu');await p.keyboard.press('Escape')}
 }
 if(view==='trade'){
  const detail=p.locator('.fxa-detail-button').first(),box=await detail.boundingBox();assert.ok(Math.abs(box.width-box.height)<1);assert.equal(await detail.evaluate(e=>getComputedStyle(e).borderRadius),'50%');const pag=p.getByTestId('analytics-ledger-pagination'),size=button('Số dòng Trades'),pb=await pag.boundingBox(),sb=await size.boundingBox();assert.ok(sb.x+sb.width<=width+1&&sb.y+sb.height<=p.viewportSize().height+1);assert.ok(Math.abs(sb.y+sb.height/2-pb.y-pb.height/2)<2);await p.getByRole('button',{name:/^Session:/}).click();await contentFits();const all=p.getByRole('checkbox',{name:'Tất cả phiên',exact:true});await all.click();await p.getByRole('checkbox',{name:/Gold Swing/}).press('Space');assert.equal(await p.getByRole('checkbox',{name:/Gold Swing/}).getAttribute('aria-checked'),'true');assert.equal(await all.getAttribute('aria-checked'),'mixed');assert.equal(await p.locator('.fxa-table-scroll tbody tr').count(),10);await p.keyboard.press('Escape');await button('Cột hiển thị').click();await fit('.fx-select-menu');await p.keyboard.press('Escape')
 }
 if(view==='analytics'){
  const original=await count();assert.equal(original,20);await button('Type').click();await p.getByRole('option',{name:'App',exact:true}).click();assert.ok(await p.getByRole('option',{name:/^Battles/}).isDisabled());assert.equal(await count(),original);await fit('.fx-select-menu');await p.keyboard.press('Escape');await button('Apply').click();assert.equal(await count(),0);await button('Clear filters').click();assert.equal(await count(),original)
  await button('Time').click();const time=p.getByRole('dialog',{name:'Time filter',exact:true});await time.getByLabel('Time Start').fill('20:00');await time.getByLabel('Time End').fill('09:00');assert.equal(await count(),original);await fit('.fx-filter-popover');await p.keyboard.press('Escape');await button('Apply').click();const expected=DEMO_LEDGER.filter(x=>x.session_id==='demo-london').filter(x=>{const d=new Date(x.close_time_utc),m=d.getUTCHours()*60+d.getUTCMinutes();return m>=1200||m<=540}).length;assert.equal(await count(),expected);await button('Clear filters').click()
  await button('Timezone').click();await scrollbar(p.getByRole('listbox',{name:'Timezone',exact:true}));await p.getByRole('searchbox',{name:'Tìm Timezone',exact:true}).fill('Ho Chi');await p.getByRole('option',{name:/Ho Chi Minh/}).click();assert.equal(await count(),original);await button('Apply').click();assert.equal(await count(),original);await button('Bỏ lọc Timezone').waitFor();await button('Clear filters').click()
  await button('Backtesting Date').click();const date=p.getByRole('dialog',{name:'Backtesting date filter',exact:true});await date.getByLabel('Analytics from date').fill('2026-07-01');await date.getByRole('button',{name:'2026-07-10',exact:true}).click();await date.getByRole('button',{name:'2026-07-08',exact:true}).click();assert.equal(await date.getByLabel('Analytics from date').inputValue(),'2026-07-08');assert.equal(await date.getByLabel('Analytics to date').inputValue(),'2026-07-10');assert.equal(await count(),original);await fit('.fx-filter-popover');await date.screenshot({path:path.join(out,`${view}-${theme}-${width}-calendar.png`)});await p.keyboard.press('Escape');await button('Apply').click();assert.equal(await count(),DEMO_LEDGER.filter(x=>x.session_id==='demo-london'&&x.close_time_utc.slice(0,10)>='2026-07-08'&&x.close_time_utc.slice(0,10)<='2026-07-10').length);await button('Clear filters').click()
 }
 await contentFits();assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth-innerWidth),0);await p.screenshot({path:path.join(out,`${view}-${theme}-${width}.png`)})
})
await run('minute-timezone-kind-domain-oracle',async()=>{
 const rows=[{tradeId:'early',close_time_utc:'2026-10-05T16:59:59Z',report_kind:'app'},{tradeId:'start',close_time_utc:'2026-10-05T17:00:00Z',report_kind:'prop'},{tradeId:'end',close_time_utc:'2026-10-05T18:30:59Z',report_kind:'prop'},{tradeId:'late',close_time_utc:'2026-10-05T18:31:00Z',report_kind:'app'}];assert.deepEqual(filterAnalyticsRows(rows,{timezone:'Asia/Ho_Chi_Minh',timeStart:'00:00',timeEnd:'01:30'}).map(x=>x.tradeId),['start','end']);assert.deepEqual(filterAnalyticsRows(rows,{reportKinds:'["prop"]'}).map(x=>x.tradeId),['start','end']);assert.deepEqual(filterAnalyticsRows(rows,{reportKinds:'[]'}),[]);assert.equal(readAnalyticsExtraFilters(new URLSearchParams('analytics_timezone=invalid&analytics_timeStart=29:00')).timezone,'UTC')
})
fixtureCatalog={items:[...catalog.items,...Array.from({length:15},(_,i)=>({...catalog.items[0],record_id:'qa-scroll-'+i,name:'QA catalog scrollbar '+String(i).padStart(2,'0')}))]}
for(const view of ['replay','trade'])await run('synthetic-catalog-native-scrollbar-'+view,async()=>{fixture=true;await p.setViewportSize({width:768,height:987});await goto(view,false);await themeSet('light');if(view==='replay'){await button('Chọn phiên replay').click();await scrollbar(p.getByRole('listbox',{name:'Chọn phiên replay',exact:true}))}else{await p.getByRole('button',{name:/^Session:/}).click();await scrollbar(p.locator('.fxa-session-options'))}await p.keyboard.press('Escape');fixture=false})
for(const view of ['overview','replay','trade','analytics'])await run('actual-get-only-'+view,async()=>{await p.setViewportSize({width:1440,height:987});await goto(view,false);if(view==='overview'||view==='replay'){const del=p.getByRole('button',{name:/^Xóa /}).first();await del.click();await p.getByRole('dialog').waitFor();await p.keyboard.press('Escape')}else if(view==='analytics'){await button('Timezone').click();await p.keyboard.press('Escape')}else await p.getByTestId('fx-trade-ledger').waitFor();await contentFits();assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth-innerWidth),0)})
assert.deepEqual(await get('/api/v2/replay/sessions'),catalog);assert.deepEqual(await get('/api/v2/replay/sessions/'+recordId),record);report.actualRecordsUnchanged=true;report.after=await pins();report.sourceUnchanged=JSON.stringify(report.before)===JSON.stringify(report.after);assert.deepEqual(report.errors,[]);assert.deepEqual(report.blocked,[]);assert.equal(report.requests.filter(x=>x.demo==='1').length,0);assert.deepEqual(report.failures,[]);assert.ok(report.sourceUnchanged);report.pass=true
}catch(e){report.failure=String(e);process.exitCode=1}finally{await c.unrouteAll({behavior:'wait'});await b.close();await writeFile(path.join(out,'report.json'),JSON.stringify(report,null,2));console.log(JSON.stringify({pass:report.pass,checks:report.checks.length,failures:report.failures.map(x=>({name:x.name,error:x.error})),errors:report.errors,blocked:report.blocked,sourceUnchanged:report.sourceUnchanged}))}
