import assert from 'node:assert/strict'
import { chromium } from '../../../web/node_modules/playwright/index.mjs'
import { readFile,writeFile } from 'node:fs/promises'
import { createHash } from 'node:crypto'
import { dashboardDurationParts } from '../../../web/src/dashboardModel.js'
const out='foundation_v2/evidence/dashboard-kpi-20261007/independent/'
const files=['DashboardPerformance.jsx','dashboard.css','dashboard-session.css','dashboardModel.js','demoFixtures.js','testing-standard.css','testing-copy.json','FxReplayShell.jsx','DashboardSessionCard.jsx','DashboardSessions.jsx','SessionPerformance.jsx']
const pins=()=>Promise.all([...files,'ui/project-palette.md'].map(async file=>({file,sha256:createHash('sha256').update(await readFile(file.startsWith('ui/')?file:'foundation_v2/web/src/'+file)).digest('hex')})))
const report={scope:'Frozen Dashboard KPI refinement only; actual/demo read-only UI',before:await pins(),cases:[],failures:[],errors:[],blocked:[]}
const browser=await chromium.launch({headless:true,ignoreDefaultArgs:['--hide-scrollbars']})
const close=(a,b,label)=>assert.ok(Math.abs(a-b)<=1,`${label}: ${a} vs ${b}`)
const rgb=hex=>'rgb('+hex.replace('#','').match(/../g).map(n=>parseInt(n,16)).join(', ')+')'
async function setup(theme,language,width,coarse=false){
 const context=await browser.newContext({viewport:{width,height:987},hasTouch:coarse}),page=await context.newPage()
 await page.addInitScript(({theme,language})=>{localStorage.setItem('tw-theme',theme);localStorage.setItem('tw-language',language)},{theme,language})
 await context.routeWebSocket('**/*',s=>s.close());await context.route('**/*',route=>{const r=route.request(),u=new URL(r.url());if(!['http://127.0.0.1:5180','http://127.0.0.1:8010'].includes(u.origin)||!['GET','HEAD','OPTIONS'].includes(r.method())){report.blocked.push({method:r.method(),url:r.url()});return route.abort()}return route.continue()})
 page.on('pageerror',e=>report.errors.push(String(e)));return{context,page}
}
async function inventory(page){return page.evaluate(()=>{
 const box=e=>{const r=e.getBoundingClientRect();return{x:r.x,right:r.right,y:r.y,bottom:r.bottom,width:r.width,height:r.height,cy:r.y+r.height/2}}
 const css=e=>{const s=getComputedStyle(e);return{font:s.fontFamily,fontSize:s.fontSize,fontWeight:s.fontWeight,color:s.color,bg:s.backgroundColor,image:s.backgroundImage,outline:s.outline,padding:s.padding}}
 const charts=[...document.querySelectorAll('.fx-dashboard-chart-panel')].map(e=>({title:e.querySelector('h3').textContent,accent:getComputedStyle(e).getPropertyValue('--chart-accent').trim(),expectedAccent:getComputedStyle(e).getPropertyValue(e.matches('.is-blue')?'--report-blue':e.matches('.is-purple')?'--report-violet':'--report-peach').trim(),box:box(e),css:css(e),ticks:[...e.querySelectorAll('.fx-dashboard-chart-axis>span')].map(e=>({text:e.textContent,box:box(e)})),grid:[...e.querySelectorAll('.fx-dashboard-plot-grid i')].map(e=>({box:box(e),style:getComputedStyle(e).borderTopStyle})),bars:[...e.querySelectorAll('.fx-dashboard-bar')].map(e=>({text:e.textContent,style:e.style.height,box:box(e),track:box(e.parentElement),css:css(e)})),symbols:[...e.querySelectorAll('.fx-dashboard-symbol-row')].map(e=>({label:e.children[0].textContent,value:e.children[2].textContent,bar:box(e.querySelector('.fx-dashboard-symbol-bar')),track:box(e.querySelector('.fx-dashboard-symbol-track')),style:e.querySelector('.fx-dashboard-symbol-bar').style.width,css:css(e.querySelector('.fx-dashboard-symbol-bar'))})),symbolAxis:[...e.querySelectorAll('.fx-dashboard-symbol-axis span')].map(e=>({text:e.textContent,box:box(e)}))}))
 const cards=[...document.querySelectorAll('.fx-dashboard-session-card')].map(e=>({id:e.dataset.sessionId,summary:{box:box(e.querySelector('.fx-dashboard-card-summary')),css:css(e.querySelector('.fx-dashboard-card-summary'))},actions:box(e.querySelector('.fx-dashboard-card-actions')),progress:box(e.querySelector('.fx-dashboard-card-progress')),progressTextBox:box(e.querySelector('.fx-dashboard-card-progress small')),progressText:css(e.querySelector('.fx-dashboard-card-progress small')),icons:[...e.querySelectorAll('.fx-dashboard-card-icon')].map(e=>box(e))}))
 return{overflow:document.documentElement.scrollWidth-innerWidth,charts,cards,metrics:[...document.querySelectorAll('.fx-dashboard-metric')].map(e=>{const range=document.createRange();range.selectNodeContents(e.querySelector('strong'));return {title:e.children[0].textContent,value:e.querySelector('strong').textContent,box:box(e),strong:box(e.querySelector('strong')),textBounds:box(range),css:css(e.querySelector('strong')),detail:e.querySelector('small')?.textContent}}),sourceText:document.querySelector('.fx-content').innerText}
})}
try{
 const oracle=[[0,[[0,'minute']]],[59,[[0,'minute']]],[60,[[1,'minute']]],[3600,[[1,'hour']]],[67200,[[18,'hour'],[40,'minute']]],[3135600,[[36,'day'],[7,'hour']]],[-1,null],[null,null],['60',null],[true,null],[NaN,null],[Infinity,null]]
 for(const [input,expected]of oracle)assert.deepEqual(dashboardDurationParts(input),expected);report.durationOracles=oracle.length
 const configs=[];for(const demo of[false,true])for(const theme of['dark','light'])for(const language of['vi','en'])for(const width of[1440,768,360])configs.push({demo,theme,language,width,coarse:false});for(const theme of['dark','light'])configs.push({demo:true,theme,language:'en',width:1440,coarse:true})
 for(const config of configs){const{demo,theme,language,width,coarse}=config,name=`${demo?'demo':'actual'}-${theme}-${language}-${width}${coarse?'-coarse':''}`,r={name,config};const{context,page}=await setup(theme,language,width,coarse)
  try{
   await page.goto('http://127.0.0.1:5180/?'+new URLSearchParams({workspace:'tenant-a',view:'overview',area:'testing',section:'dashboard',...(demo?{demo:'1'}:{})}));await page.waitForLoadState('networkidle');await page.getByTestId('dashboard-performance').waitFor()
   r.inventory=await inventory(page);const inv=r.inventory;assert.ok(inv.overflow<=1,'page overflow');assert.equal(inv.metrics.length,4);assert.ok(!/Buy:|Sell:|Mua:|Bán:/.test(inv.sourceText),'fabricated side KPI')
   if(demo){assert.match(inv.metrics[0].value,language==='en'?/18hr40min/:/18giờ40phút/);assert.match(inv.metrics[1].value,language==='en'?/36d7hr/:/36ngày7giờ/);assert.equal(inv.metrics[2].value,'60');assert.equal(inv.metrics[3].value,'50%')}
   else{assert.equal(inv.metrics[0].value,'—','actual timing fabricated');assert.equal(inv.metrics[1].value,'—','actual replay duration fabricated')}
   for(const metric of inv.metrics){assert.equal(metric.css.fontSize,'32px');assert.equal(metric.css.fontWeight,'600');assert.ok(metric.textBounds.right<=metric.strong.right+1&&metric.textBounds.x>=metric.strong.x-1,'KPI text clipped')}
   for(const card of inv.cards){assert.equal(card.summary.css.fontSize,'13px');assert.equal(card.summary.css.fontWeight,'500');close(card.summary.box.height,width===360||coarse?44:32,'Summary height');for(const icon of card.icons)close(icon.height,card.summary.box.height,'adjacent action size');if(width===1440)close(card.progressTextBox.cy,card.actions.cy,'progress label/actions center')}
   for(const chart of inv.charts){assert.equal(chart.accent,chart.expectedAccent,'named palette role');for(const bar of chart.bars){close(bar.box.height,bar.track.height*parseFloat(bar.style)/100,'value-height');assert.equal(bar.css.bg,rgb(chart.accent),'solid role fill');assert.equal(bar.css.image,'none','gradient bar remains');if(parseFloat(bar.style)===0)assert.equal(bar.box.height,0,'fake zero sliver')};for(const grid of chart.grid)assert.equal(grid.style,'dashed');for(let i=0;i<chart.ticks.length;i++)close(chart.ticks[i].box.y,chart.grid[i].box.y,'grid/tick alignment');if(chart.ticks.length===6)assert.deepEqual(chart.ticks.map(t=>t.text),['100%','80%','60%','40%','20%','0%']);for(const row of chart.symbols){close(row.bar.width,row.track.width*parseFloat(row.style)/100,'symbol width');assert.equal(row.css.image,'none');assert.equal(row.css.bg,rgb(chart.accent),'solid violet symbol fill');if(parseFloat(row.style)===0)assert.equal(row.bar.width,0)}if(chart.symbols.length){close(chart.symbolAxis[0].box.x,chart.symbols[0].track.x,'symbol axis zero');close(chart.symbolAxis.at(-1).box.right,chart.symbols[0].track.right,'symbol axis maximum')}}
   const cards=page.locator('.fx-dashboard-session-card');if(await cards.count()){
    await cards.first().locator('.fx-dashboard-card-expand').click();await cards.first().locator('.fx-dashboard-card-charts').waitFor();await page.waitForTimeout(160)
    const empty=cards.first().locator('.fxs-no-analytics');if(await empty.count()){r.emptyPanelHeight=await cards.first().locator('.fx-dashboard-card-charts').evaluate(e=>e.getBoundingClientRect().height);assert.ok(r.emptyPanelHeight<=44,'empty expanded panel not compact')}
    else r.expandedState=await cards.first().locator('.fx-dashboard-card-charts').innerText()
    if(demo&&((width===1440&&language==='vi')||(width===360&&language==='en')))await page.screenshot({path:out+name+'-expanded.png'})
    await cards.first().locator('.fx-dashboard-card-expand').click();await page.keyboard.press('Tab');await cards.first().locator('.fx-dashboard-card-summary').focus();r.summaryFocus=await cards.first().locator('.fx-dashboard-card-summary').evaluate(e=>getComputedStyle(e).outline);assert.match(r.summaryFocus,/2px/)
   }
   if(!coarse&&((width===1440&&language==='vi')||(width===360&&language==='en')||(width===768&&demo&&language==='en'))){await page.addScriptTag({path:'../../.artifacts/wm-integration-quality-tools/node_modules/axe-core/axe.min.js'});r.axe=await page.evaluate(async()=>({violations:(await axe.run(document)).violations.map(({id,impact,nodes})=>({id,impact,nodes:nodes.map(n=>({target:n.target,summary:n.failureSummary}))}))}));assert.equal(r.axe.violations.length,0,'axe violations')}
   if(!coarse&&(width===1440&&language==='vi'||width===360&&language==='en'||width===768&&demo&&language==='en')){await page.locator('.fx-content').evaluate(e=>e.scrollTop=0);await page.screenshot({path:out+name+'.png'})}
   report.cases.push(r)
  }catch(e){report.failures.push({name,error:String(e),result:r});await page.screenshot({path:out+name+'-failure.png'})}finally{await context.close();await writeFile(out+'progress.json',JSON.stringify(report,null,2))}
 }
 report.after=await pins();report.sourceUnchanged=JSON.stringify(report.before)===JSON.stringify(report.after);assert.ok(report.sourceUnchanged);assert.equal(report.failures.length,0);assert.equal(report.errors.length,0);assert.equal(report.blocked.length,0);report.pass=true
}catch(e){report.failure=String(e);process.exitCode=1}
finally{await browser.close();await writeFile(out+'report.json',JSON.stringify(report,null,2));console.log(JSON.stringify({pass:report.pass,cases:report.cases.length,failures:report.failures.map(({name,error})=>({name,error})),errors:report.errors,blocked:report.blocked,sourceUnchanged:report.sourceUnchanged}))}
