import assert from 'node:assert/strict'
import { chromium } from '../../../web/node_modules/playwright/index.mjs'
import { readFile,writeFile } from 'node:fs/promises'
import { createHash } from 'node:crypto'
const out='foundation_v2/evidence/dashboard-kpi-20261007/independent/',src='foundation_v2/web/src/'
const files=['DashboardPerformance.jsx','dashboard.css','dashboard-session.css','dashboardModel.js','testing-standard.css','testing-copy.json','DashboardSessionCard.jsx','SessionPerformance.jsx']
const pins=()=>Promise.all(files.map(async file=>({file,sha256:createHash('sha256').update(await readFile(src+file)).digest('hex')})))
const base={performance:{schema_version:'dashboard-replay-performance-v1',status:'ready',scope:{session_count:1,readable_session_count:1},metrics:{closed_trade_count:4,wins:2,losses:1,breakeven:1,win_rate_pct:50},months:[{month:'2026-09',closed_trade_count:4,win_rate_pct:50},{month:'2026-10',closed_trade_count:0,win_rate_pct:0}],symbols:[{symbol:'EURUSD',closed_trade_count:4},{symbol:'XAUUSD',closed_trade_count:0}],sessions:[],sources:[],excluded:[]}}
const item={record_id:'qa-empty',revision:1,name:'QA empty session',instrument_id:'EURUSD',dataset_id:'qa-none',row_count:100,cursor_index:30,dataset_available:true,archived:false}
const report={scope:'Synthetic independent intercepted GET states; not actual positive feed evidence',before:await pins(),cases:[],failures:[],errors:[],blocked:[]},browser=await chromium.launch({headless:true,ignoreDefaultArgs:['--hide-scrollbars']})
for(const[theme,language,width]of[['dark','en',1440],['light','vi',360]])for(const state of['positive-empty-session','unknown','zero','blocked','loading','error','stale']){
 const name=`${state}-${theme}-${language}-${width}`,context=await browser.newContext({viewport:{width,height:987}}),page=await context.newPage(),r={name};let status=state==='error'?500:200,payload=structuredClone(base),hold=null,release
 try{
  await page.addInitScript(({theme,language})=>{localStorage.setItem('tw-theme',theme);localStorage.setItem('tw-language',language)},{theme,language})
  await context.routeWebSocket('**/*',s=>s.close());await context.route('**/*',route=>{const q=route.request(),u=new URL(q.url());if(!['http://127.0.0.1:5180','http://127.0.0.1:8010'].includes(u.origin)||!['GET','HEAD','OPTIONS'].includes(q.method())){report.blocked.push({name,method:q.method(),url:q.url()});return route.abort()}return route.continue()})
  await context.route('**/api/v2/replay/sessions',route=>route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({items:[item]})}))
  await context.route('**/api/v2/data/datasets',route=>route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({items:[]})}))
  await context.route('**/api/v2/replay/sessions/qa-empty/analytics',route=>route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({schema_version:'analytics-read-model-v1',analytics_available:false,scope:{selected_trade_count:0,total_trade_count:0}})}))
  await context.route('**/api/v2/replay/sessions/qa-empty',route=>route.fulfill({status:200,contentType:'application/json',body:JSON.stringify(item)}))
  if(state==='unknown'){payload.performance.metrics={closed_trade_count:null,win_rate_pct:null};payload.performance.months=[{month:'2026-08',closed_trade_count:null,win_rate_pct:null},{month:'2026-09',closed_trade_count:'1',win_rate_pct:'50'},{month:'2026-10',closed_trade_count:-1,win_rate_pct:101}];payload.performance.symbols=[{symbol:'UNKNOWN',closed_trade_count:null},{symbol:'STRING',closed_trade_count:'1'},{symbol:'NEG',closed_trade_count:-1}]}
  if(state==='zero'){payload.performance.metrics={closed_trade_count:0,wins:0,losses:0,breakeven:0,win_rate_pct:0};payload.performance.time_invested_seconds=0;payload.performance.historical_time_replayed_seconds=0;payload.performance.months=[{month:'2026-10',closed_trade_count:0,win_rate_pct:0}];payload.performance.symbols=[{symbol:'EURUSD',closed_trade_count:0}]}
  if(state==='blocked'){payload.performance.status='blocked';payload.performance.scope.readable_session_count=0;payload.performance.metrics={};payload.performance.months=[];payload.performance.symbols=[]}
  if(state==='loading')hold=new Promise(resolve=>release=resolve)
  await context.route(/\/api\/v2\/overview(?:\?|$)/,async route=>{if(hold)await hold;await route.fulfill({status,contentType:'application/json',body:JSON.stringify(status===200?payload:{detail:'qa-overview-read-failed'})})})
  page.on('pageerror',e=>report.errors.push({name,error:String(e)}))
  await page.goto('http://127.0.0.1:5180/?workspace=tenant-a&view=overview&area=testing&section=dashboard',{waitUntil:state==='loading'?'domcontentloaded':'load'})
  const metrics=page.locator('.fx-dashboard-metric>strong'),notice=page.getByTestId('dashboard-data-state'),perf=page.locator('.fx-dashboard-results')
  if(state==='loading'){await perf.locator('.wm-skeleton').waitFor();assert.equal(await perf.getAttribute('aria-busy'),'true');assert.equal(await page.getByTestId('dashboard-performance').count(),0);await page.screenshot({path:out+name+'-held.png'});release();hold=null}
  await page.getByTestId('dashboard-performance').waitFor();await page.waitForLoadState('networkidle')
  if(!['zero'].includes(state)){assert.deepEqual((await metrics.allTextContents()).slice(0,2),['—','—'])}else assert.deepEqual((await metrics.allTextContents()).slice(0,2),language==='en'?['0min','0min']:['0phút','0phút'])
  if(state==='unknown'){assert.deepEqual(await metrics.allTextContents(),['—','—','—','—']);assert.equal(await page.locator('.fx-dashboard-bar,.fx-dashboard-symbol-bar').count(),0);assert.equal(await page.locator('.fx-dashboard-outcome-bar').count(),0)}
  if(['zero','positive-empty-session'].includes(state)){
   r.zeroBars=await page.locator('.fx-dashboard-bar.is-zero,.fx-dashboard-symbol-bar[style="width: 0%;"]').evaluateAll(es=>es.map(e=>({width:e.getBoundingClientRect().width,height:e.getBoundingClientRect().height,axis:e.matches('.fx-dashboard-symbol-bar')?'width':'height'})))
   assert.ok(r.zeroBars.length>=2);for(const bar of r.zeroBars)assert.equal(bar[bar.axis],0,'fake >0 zero sliver')
   if(state==='positive-empty-session'){const rows=await page.locator('.fx-dashboard-month-column').evaluateAll(es=>es.map(e=>({value:e.querySelector('.fx-dashboard-bar').title,barHeight:e.querySelector('.fx-dashboard-bar').getBoundingClientRect().height,trackHeight:e.querySelector('.fx-dashboard-bar-track').getBoundingClientRect().height})));r.heights=rows;assert.ok(rows.some(row=>row.value.includes('50%')&&Math.abs(row.barHeight/row.trackHeight-.5)<.01));assert.equal(await page.locator('.fx-dashboard-outcome-bar span').count(),3)}
  }
  if(state==='blocked'){assert.match(await notice.innerText(),language==='en'?/insufficient/:/Chưa đủ dữ liệu/);assert.ok((await metrics.allTextContents()).every(t=>t==='—'))}
  if(state==='error'){assert.equal(await notice.getAttribute('role'),'alert');assert.match(await notice.innerText(),language==='en'?/Could not load performance/:/Chưa tải được hiệu suất/)}
  if(state==='stale'){const prior=await metrics.allTextContents();status=500;await page.evaluate(()=>window.dispatchEvent(new Event('online')));await notice.filter({hasText:language==='en'?'Data is out of date.':'Dữ liệu chưa cập nhật.'}).waitFor();assert.deepEqual(await metrics.allTextContents(),prior);assert.equal(await perf.getAttribute('aria-busy'),'false')}
  if(state==='positive-empty-session'){await page.locator('.fx-dashboard-card-expand').click();await page.locator('.fxs-no-analytics').waitFor();r.emptyHeight=await page.locator('.fx-dashboard-card-charts').evaluate(e=>e.getBoundingClientRect().height);assert.ok(r.emptyHeight<=44,'empty expanded panel too tall');await page.screenshot({path:out+name+'-empty-expanded.png'});await page.locator('.fx-dashboard-card-expand').click();assert.equal(await page.locator('.fx-dashboard-card-charts').count(),0)}
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth-innerWidth)<=1);if(['positive-empty-session','zero','unknown','blocked','error','stale'].includes(state)){await page.locator('.fx-content').evaluate(e=>e.scrollTop=0);await page.screenshot({path:out+name+'.png'})}
  report.cases.push(r)
 }catch(e){report.failures.push({name,error:String(e),result:r,content:await page.locator('.fx-content').innerText().catch(()=>'' )});await page.screenshot({path:out+name+'-failure.png'}).catch(()=>{})}finally{if(release)release();await context.close();await writeFile(out+'states-progress.json',JSON.stringify(report,null,2))}
}
report.after=await pins();report.sourceUnchanged=JSON.stringify(report.before)===JSON.stringify(report.after);report.pass=report.failures.length===0&&report.errors.length===0&&report.blocked.length===0&&report.sourceUnchanged;if(!report.pass)process.exitCode=1;await browser.close();await writeFile(out+'states-report.json',JSON.stringify(report,null,2));console.log(JSON.stringify({pass:report.pass,cases:report.cases.length,failures:report.failures.map(({name,error})=>({name,error})),errors:report.errors,blocked:report.blocked,sourceUnchanged:report.sourceUnchanged}))
