import assert from 'node:assert/strict'
import {chromium}from'../../../web/node_modules/playwright/index.mjs'
import{readFile,writeFile}from'node:fs/promises'
import{createHash}from'node:crypto'
import {DEMO_LEDGER,demoOverview}from'../../../web/src/demoFixtures.js'
const out='foundation_v2/evidence/dashboard-side-split-20261007/independent/'
const files=['foundation_v2/trading_workspace_v2/dashboard_read_model.py','foundation_v2/trading_workspace_v2/replay_analytics.py','foundation_v2/web/src/DashboardPerformance.jsx','foundation_v2/web/src/dashboard.css','foundation_v2/web/src/dashboard-session.css','foundation_v2/web/src/demoFixtures.js','foundation_v2/web/src/testing-standard.css','foundation_v2/web/src/testing-copy.json','ui/testing-standard.md']
const pins=()=>Promise.all(files.map(async file=>({file,sha256:createHash('sha256').update(await readFile(file)).digest('hex')})))
const report={scope:'Dashboard side split, minimal overall-win card, progress cluster only; local read-only',before:await pins(),cases:[],failures:[],errors:[],blocked:[],fixtures:[]}
const browser=await chromium.launch({headless:true,ignoreDefaultArgs:['--hide-scrollbars']})
const close=(a,b,label)=>assert.ok(Math.abs(a-b)<=1,`${label}: ${a} vs ${b}`)
async function setup(theme,language,width){const context=await browser.newContext({viewport:{width,height:987}}),page=await context.newPage();await page.addInitScript(({theme,language})=>{localStorage.setItem('tw-theme',theme);localStorage.setItem('tw-language',language)},{theme,language});await context.routeWebSocket('**/*',s=>s.close());await context.route('**/*',r=>{const q=r.request(),u=new URL(q.url());if(!['http://127.0.0.1:5180','http://127.0.0.1:8010'].includes(u.origin)||!['GET','HEAD','OPTIONS'].includes(q.method())){report.blocked.push({method:q.method(),url:q.url()});return r.abort()}return r.continue()});page.on('pageerror',e=>report.errors.push(String(e)));return{context,page}}
const url=demo=>'http://127.0.0.1:5180/?workspace=tenant-a&view=overview&area=testing&section=dashboard'+(demo?'&demo=1':'')
const pct=(v,language)=>new Intl.NumberFormat(language==='vi'?'vi-VN':'en-US',{minimumFractionDigits:2,maximumFractionDigits:2}).format(v)+'%'
async function inspect(page,counts,total,language,width){
 const closed=page.locator('.fx-dashboard-metric').nth(2),win=page.locator('.fx-dashboard-metric').nth(3),split=closed.locator('.fx-dashboard-side-split')
 assert.equal(await win.locator(':scope>small,.fx-dashboard-outcome-bar,.fx-dashboard-side-split').count(),0,'overall win has extra supporting text/bar')
 assert.equal(await win.locator(':scope>span,:scope>strong').count(),2);assert.equal(await win.evaluate(e=>e.children.length),2,'overall win has extra children')
 const positive=counts&&Number.isSafeInteger(counts.buy)&&Number.isSafeInteger(counts.sell)&&counts.buy>=0&&counts.sell>=0&&Number.isSafeInteger(total)&&total>0&&counts.buy+counts.sell===total
 const result={positive:Boolean(positive),closed:await closed.locator(':scope>strong').innerText(),win:await win.locator(':scope>strong').innerText()}
 if(positive){assert.equal(await split.count(),1);const buy=counts.buy/total*100,sell=counts.sell/total*100;assert.equal(await split.locator('small .is-buy').innerText(),pct(buy,language)+' '+(language==='vi'?'Mua':'Buy'));assert.equal(await split.locator('small .is-sell').innerText(),pct(sell,language)+' '+(language==='vi'?'Bán':'Sell'));result.bar=await split.evaluate(e=>{const rect=e=>{const r=e.getBoundingClientRect();return{x:r.x,right:r.right,width:r.width,height:r.height}},bar=e.querySelector('.fx-dashboard-side-bar'),a=bar.querySelector('.is-buy'),b=bar.querySelector('.is-sell');return{box:rect(bar),buy:rect(a),sell:rect(b),colors:[getComputedStyle(a).backgroundColor,getComputedStyle(b).backgroundColor],labels:e.querySelector('small').textContent}});close(result.bar.buy.width,result.bar.box.width*buy/100,'buy width');close(result.bar.sell.width,result.bar.box.width*sell/100,'sell width');close(result.bar.buy.right,result.bar.sell.x,'joined side bar');if(buy===0)assert.equal(result.bar.buy.width,0);if(sell===0)assert.equal(result.bar.sell.width,0);assert.notEqual(result.bar.colors[0],result.bar.colors[1])}
 else assert.equal(await split.count(),0,'unknown/malformed/empty split rendered')
 result.progress=await page.locator('.fx-dashboard-session-card').evaluateAll(es=>es.map(e=>{const box=e=>{const r=e.getBoundingClientRect();return{x:r.x,y:r.y,right:r.right,bottom:r.bottom,width:r.width,height:r.height,cy:r.y+r.height/2}};const group=e.querySelector('.fx-dashboard-card-progress'),track=group.querySelector('progress'),label=group.querySelector('small');return{id:e.dataset.sessionId,group:box(group),track:track?box(track):null,label:box(label),actions:box(e.querySelector('.fx-dashboard-card-actions')),position:track?getComputedStyle(track).position:null,gap:getComputedStyle(group).gap}}))
 for(const p of result.progress){const top=p.track?Math.min(p.track.y,p.label.y):p.label.y,bottom=p.track?Math.max(p.track.bottom,p.label.bottom):p.label.bottom;close((top+bottom)/2,p.group.cy,'progress contents/group center');if(width===1710)close((top+bottom)/2,p.actions.cy,'progress cluster/action center');if(p.track){assert.equal(p.position,'static');assert.equal(p.gap,'6px');close(p.track.height,6,'progress height')}}
 assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth-innerWidth)<=1,'horizontal page overflow');return result
}
try{
 assert.deepEqual(demoOverview().performance.side_counts,{buy:DEMO_LEDGER.filter(r=>r.side==='buy').length,sell:DEMO_LEDGER.filter(r=>r.side==='sell').length})
 for(const demo of[false,true])for(const theme of['dark','light'])for(const language of['en','vi'])for(const width of[1710,768,360]){
  const name=`${demo?'demo':'actual'}-${theme}-${language}-${width}`,r={name},{context,page}=await setup(theme,language,width)
  try{
   const response=demo?null:page.waitForResponse(r=>new URL(r.url()).pathname==='/api/v2/overview')
   await page.goto(url(demo));await page.waitForLoadState('networkidle');await page.getByTestId('dashboard-performance').waitFor()
   let performance=demo?demoOverview().performance:(await(await response).json()).performance
   if(!demo){const ledger=await page.evaluate(async()=>{const r=await fetch('/api/v2/replay/trades',{headers:{'X-Workspace-Id':'tenant-a'}});if(!r.ok)throw Error('ledger GET '+r.status);return r.json()});const counts={buy:ledger.ledger.filter(t=>t.side==='BUY').length,sell:ledger.ledger.filter(t=>t.side==='SELL').length};assert.equal(ledger.ledger.length,performance.metrics.closed_trade_count);assert.deepEqual(performance.side_counts,counts);r.actualOracle={counts,ledgerCount:ledger.ledger.length,sideCounts:performance.side_counts,duplicateCount:performance.scope.duplicate_trade_count};assert.equal(performance.time_invested_seconds,null);assert.equal(performance.historical_time_replayed_seconds,null);assert.deepEqual((await page.locator('.fx-dashboard-metric>strong').allTextContents()).slice(0,2),['—','—'])}
   r.ui=await inspect(page,performance.side_counts,performance.metrics.closed_trade_count,language,width)
   if(width===1710||width===360){await page.addScriptTag({path:'../../.artifacts/wm-integration-quality-tools/node_modules/axe-core/axe.min.js'});r.axe=await page.evaluate(async()=>({violations:(await axe.run(document)).violations.map(({id,impact,nodes})=>({id,impact,nodes:nodes.map(n=>({target:n.target,summary:n.failureSummary}))}))}));assert.equal(r.axe.violations.length,0,'Axe violations');await page.screenshot({path:out+name+'.png'})}
   if(width===1710&&demo){await page.locator('.fx-dashboard-session-card').first().scrollIntoViewIfNeeded();await page.screenshot({path:out+name+'-progress.png'})}
   report.cases.push(r)
  }catch(e){report.failures.push({name,error:String(e),result:r});await page.screenshot({path:out+name+'-failure.png'})}finally{await context.close();await writeFile(out+'progress.json',JSON.stringify(report,null,2))}
 }
 const cases=[['empty',{buy:0,sell:0},0,false],['single-buy',{buy:4,sell:0},4,true],['single-sell',{buy:0,sell:4},4,true],['mixed-50',{buy:2,sell:2},4,true],['mixed-third',{buy:1,sell:2},3,true],['unknown',{buy:null,sell:null},null,false],['string',{buy:'2',sell:2},4,false],['fractional',{buy:1.5,sell:2.5},4,false],['negative',{buy:-1,sell:5},4,false],['mismatch',{buy:1,sell:1},4,false],['unsafe',{buy:9007199254740992,sell:0},9007199254740992,false],['total-string',{buy:2,sell:2},'4',false]]
 for(const[theme,language,width]of[['dark','en',1710],['light','vi',360]])for(const[name,counts,total,expected]of cases){const{context,page}=await setup(theme,language,width),r={name,theme,language,width,counts,total}
  try{
   await context.route('**/api/v2/replay/sessions',r=>r.fulfill({status:200,contentType:'application/json',body:'{"items":[]}'}));await context.route('**/api/v2/data/datasets',r=>r.fulfill({status:200,contentType:'application/json',body:'{"items":[]}'}));const p=demoOverview().performance;p.metrics={closed_trade_count:total,win_rate_pct:50};p.side_counts=counts;p.time_invested_seconds=null;p.historical_time_replayed_seconds=null
   await context.route(/\/api\/v2\/overview(?:\?|$)/,r=>r.fulfill({status:200,contentType:'application/json',body:JSON.stringify({performance:p})}));await page.goto(url(false));await page.waitForLoadState('networkidle');r.ui=await inspect(page,counts,total,language,width);assert.equal(r.ui.positive,expected);if(['single-buy','single-sell','mixed-50','unknown'].includes(name))await page.screenshot({path:out+`fixture-${name}-${theme}-${language}-${width}.png`});report.fixtures.push(r)
  }catch(e){report.failures.push({name:`fixture-${name}-${theme}-${language}-${width}`,error:String(e),result:r})}finally{await context.close();await writeFile(out+'progress.json',JSON.stringify(report,null,2))}
 }
 report.after=await pins();report.sourceUnchanged=JSON.stringify(report.before)===JSON.stringify(report.after);assert.ok(report.sourceUnchanged);assert.equal(report.failures.length,0);assert.equal(report.errors.length,0);assert.equal(report.blocked.length,0);report.pass=true
}catch(e){report.failure=String(e);process.exitCode=1}
finally{await browser.close();await writeFile(out+'report.json',JSON.stringify(report,null,2));console.log(JSON.stringify({pass:report.pass,cases:report.cases.length,fixtures:report.fixtures.length,failures:report.failures.map(({name,error})=>({name,error})),errors:report.errors,blocked:report.blocked,sourceUnchanged:report.sourceUnchanged}))}
