use axum::{
    body::Body,
    http::{Request, StatusCode},
};
use http_body_util::BodyExt;
use serde_json::{Value, json};
use tower::ServiceExt;
use trading_workspace_api::{catalog, config::Config, state::AppState};

/// Run through run_catalog_parity.py, which owns and stops a disposable PostgreSQL cluster.
#[tokio::test]
#[ignore = "requires disposable PostgreSQL + Python reference generated by run_catalog_parity.py"]
async fn native_catalog_matches_python_http_contract() {
    let golden_path = std::env::var("TW_CATALOG_PARITY_GOLDEN").expect("fixture golden required");
    let cases: Value = serde_json::from_slice(&std::fs::read(golden_path).unwrap()).unwrap();
    let state = AppState::connect(Config::from_environment().unwrap())
        .await
        .unwrap();
    let client = state.pool.get().await.unwrap();
    let database: String = client
        .query_one("SELECT current_database()", &[])
        .await
        .unwrap()
        .get(0);
    assert!(
        database.starts_with("catalog_parity_"),
        "refuse non-fixture database"
    );
    let app = catalog::routes().with_state(state.clone());
    let mut checked = 0;
    for case in cases.as_array().unwrap() {
        if let Some(mutation) = case.get("mutation") {
            let sql = match mutation["target"].as_str().unwrap() {
                "session" => {
                    "UPDATE prop_sessions SET snapshot_json=$1 WHERE workspace_id='tenant-a' AND session_id='prop-1'"
                }
                "attempt" => {
                    "UPDATE prop_attempts SET snapshot_json=$1 WHERE workspace_id='tenant-a' AND session_id='prop-1' AND attempt_id='attempt-1'"
                }
                "phase" => {
                    "UPDATE prop_attempts SET phase_json=$1 WHERE workspace_id='tenant-a' AND session_id='prop-1' AND attempt_id='attempt-1'"
                }
                _ => panic!("unknown fixture mutation"),
            };
            client.execute(sql, &[&mutation["value"]]).await.unwrap();
        }
        if let Some(id) = case["corrupt_record_id"].as_str() {
            client.execute("UPDATE workspace_record_revisions SET payload_json=jsonb_set(payload_json,'{cursor_index}','-1'::jsonb) WHERE workspace_id='tenant-a' AND kind='replay' AND record_id=$1",&[&id]).await.unwrap();
        }
        let mut request = Request::builder()
            .method(case["method"].as_str().unwrap())
            .uri(case["path"].as_str().unwrap());
        if let Some(workspace) = case["workspace"].as_str() {
            request = request.header("x-workspace-id", workspace);
        }
        let response = app
            .clone()
            .oneshot(request.body(Body::empty()).unwrap())
            .await
            .unwrap();
        assert_eq!(
            response.status(),
            StatusCode::from_u16(case["status"].as_u64().unwrap() as u16).unwrap(),
            "status for {}",
            case["path"]
        );
        let mut actual: Value =
            serde_json::from_slice(&response.into_body().collect().await.unwrap().to_bytes())
                .unwrap();
        let mut expected = case["body"].clone();
        if case["path"] == "/api/v2/session/status" && case["status"] == 200 {
            assert!(
                actual["session"]["issued_at_utc"]
                    .as_str()
                    .unwrap()
                    .ends_with('Z')
            );
            actual["session"]["issued_at_utc"] = json!("variable clock");
            expected["session"]["issued_at_utc"] = json!("variable clock");
        }
        assert_eq!(actual, expected, "body for {}", case["path"]);
        if let Some(mutation) = case.get("mutation") {
            let sql = match mutation["target"].as_str().unwrap() {
                "session" => {
                    "UPDATE prop_sessions SET snapshot_json=$1 WHERE workspace_id='tenant-a' AND session_id='prop-1'"
                }
                "attempt" => {
                    "UPDATE prop_attempts SET snapshot_json=$1 WHERE workspace_id='tenant-a' AND session_id='prop-1' AND attempt_id='attempt-1'"
                }
                "phase" => {
                    "UPDATE prop_attempts SET phase_json=$1 WHERE workspace_id='tenant-a' AND session_id='prop-1' AND attempt_id='attempt-1'"
                }
                _ => panic!("unknown fixture mutation"),
            };
            client.execute(sql, &[&mutation["restore"]]).await.unwrap();
        }
        checked += 1;
    }
    println!("{checked} native catalog HTTP contract cases matched Python reference");
    state.pool.close();
}
