import assert from 'node:assert/strict'
import {browser,open} from './browser-helper.mjs'
import {writeFile} from 'node:fs/promises'
const report={scope:'Actual widget localStorage/screenshot/objects fixtures, no actual session writes',checks:[],errors:[],blocked:[],vendorBlocked:[]};let ctx
try {
 const state=await open(report,{width:1710,theme:'light',language:'en'});ctx=state.ctx;const{p,f,canonical}=state,before=await canonical();await f.locator('[data-save-state=saved]').waitFor({state:'attached'});
 await p.evaluate(()=>{const original=Storage.prototype.setItem;window.__qaStorageOriginal=original;window.__qaStorageFail=true;Storage.prototype.setItem=function(k,v){if(window.__qaStorageFail&&k.startsWith('tw:advanced-chart:v1:'))throw new DOMException('FIXTURE quota exceeded','QuotaExceededError');return original.call(this,k,v)};window.__qaWidget.activeChart().setChartType(2)});await f.locator('[data-save-state=dirty]').waitFor({state:'attached'});await f.getByTestId('legacy-native-market').locator('button').first().focus();await p.keyboard.press('Control+s');await f.locator('[data-save-state=error]').waitFor({state:'attached'});assert.equal(await f.locator('.legacy-save-layout').isDisabled(),false);assert.ok(await p.locator('.advanced-chart-save-status').count());await p.evaluate(()=>window.__qaStorageFail=false);await f.locator('.legacy-save-layout').click();await f.locator('[data-save-state=saved]').waitFor({state:'attached'});report.checks.push('actual localStorage quota error enables Retry, iframeCtrlS, manualRetry saves');
 await p.evaluate(()=>{window.__qaWrites=[];window.__qaCopyFail=false;Object.defineProperty(navigator,'clipboard',{configurable:true,value:{write:async items=>{if(window.__qaCopyFail)throw new DOMException('FIXTURE clipboard denied','NotAllowedError');const blob=await items[0].getType('image/png');window.__qaWrites.push({type:blob.type,size:blob.size})}}})});await p.keyboard.press('Control+Shift+s');await p.waitForFunction(()=>window.__qaWrites.length===1);assert.ok((await p.evaluate(()=>__qaWrites[0])).size>100);await p.evaluate(()=>window.__qaCopyFail=true);await f.getByTestId('legacy-native-market').locator('button').first().focus();await p.keyboard.press('Control+Shift+s');await p.locator('.advanced-chart-save-status').filter({hasText:'FIXTURE clipboard denied'}).waitFor();report.checks.push('copyPNG actualBlob success fixture/topdocShortcut and permissionFailure/iframeShortcut notice');
 await p.evaluate(()=>{window.__qaOriginalScreenshot=__qaWidget.takeClientScreenshot.bind(__qaWidget);__qaWidget.takeClientScreenshot=()=>new Promise(resolve=>window.__qaScreenshotResolve=resolve);window.__qaCopyFail=false});await p.keyboard.press('Control+Shift+s');await p.waitForFunction(()=>typeof window.__qaScreenshotResolve==='function');await p.evaluate(()=>__qaWidget.activeChart().setResolution('5'));await p.waitForFunction(()=>__qaWidget.activeChart().resolution()==='5');await p.evaluate(()=>{const canvas=document.createElement('canvas');canvas.width=20;canvas.height=20;window.__qaScreenshotResolve(canvas)});await p.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));report.raceStatus=await p.locator('.advanced-chart-save-status').allTextContents();assert.equal(await p.evaluate(()=>__qaWrites.length),1);await p.evaluate(()=>__qaWidget.takeClientScreenshot=__qaOriginalScreenshot);report.checks.push('deferred screenshot + resolution race cancels copy; status recorded separately');
 const download=p.waitForEvent('download');await p.keyboard.press('Control+Alt+s');assert.match((await download).suggestedFilename(),/-5-cutoff-.*\.png$/);report.checks.push('Download shortcut after resolutionchange actualPNG');
 const drawing=await p.evaluate(async()=>{const chart=__qaWidget.activeChart(),range=chart.getVisibleRange();return await chart.createShape({time:range.to,price:1.1},{shape:'horizontal_line'})});await p.locator('.legacy-rail-tools button').click();await p.locator('.legacy-object-tree').waitFor();const row=p.locator('.legacy-object-row').last();await row.locator('button').first().click();assert.ok(await p.evaluate(id=>__qaWidget.activeChart().selection().allSources().includes(id),drawing));await row.locator('button').nth(1).click();assert.equal(await p.evaluate(id=>__qaWidget.activeChart().getShapeById(id).getProperties().visible,drawing),false);await row.locator('button').nth(2).click();assert.equal(await p.evaluate(id=>__qaWidget.activeChart().getAllShapes().some(s=>s.id===id),drawing),false);await p.keyboard.press('Escape');report.checks.push('actual drawing local selection/hide/remove, bridge reconciles native state');
 assert.deepEqual(await canonical(),before);report.pass=!report.errors.length&&!report.blocked.length;
}catch(e){report.pass=false;report.failure=String(e);process.exitCode=1}finally{await ctx?.close();await browser.close();await writeFile(new URL('edges-report.json',import.meta.url),JSON.stringify(report,null,2));console.log(JSON.stringify(report))}
