import assert from 'node:assert/strict'
import {chromium} from '../../../web/node_modules/playwright/index.mjs'
import {writeFile} from 'node:fs/promises'
const browser=await chromium.launch({headless:true,ignoreDefaultArgs:['--hide-scrollbars']}),report={scope:'Real useChartOrder + LegacyOrderDialog, labeled submit callback fixture, no service writes',cases:[],errors:[],blocked:[],axe:[]}
try { for(const[theme,width]of[['dark',1710],['light',360]]) {
 const ctx=await browser.newContext({viewport:{width,height:987}});await ctx.routeWebSocket('**/*',s=>s.close());await ctx.route('**/*',route=>{const r=route.request(),u=new URL(r.url());if(['GET','HEAD','OPTIONS'].includes(r.method())&&['http://127.0.0.1:5180','http://127.0.0.1:8010'].includes(u.origin))return route.continue();report.blocked.push({method:r.method(),url:r.url()});return route.abort()});const p=await ctx.newPage();p.on('pageerror',e=>report.errors.push(String(e)));await p.goto('http://127.0.0.1:5180/?view=overview',{waitUntil:'networkidle'});
 await p.evaluate(async theme=>{
  const src=await(await fetch('/src/LegacyOrderDialog.jsx')).text(),reactUrl=src.match(/from\s+["']([^"']*\/react\.js[^"']*)["']/)[1],localeUrl=src.match(/from\s+["']([^"']*testingLocale\.jsx[^"']*)["']/)[1],R=(await import(reactUrl)).default,D=await import(reactUrl.replace('react.js','react-dom_client.js')),P=(await import(localeUrl)).TestingLocaleProvider,O=(await import('/src/LegacyOrderDialog.jsx')).default,C=await import('/src/ChartOrderPanel.jsx');await import('/src/ChartWorkbench.css');
  const host=document.createElement('div');host.id='qa-order';host.style.cssText='position:fixed;inset:0;z-index:100';document.body.append(host);const root=(D.default||D).createRoot(host);window.__qaSubmits=[];window.__qaOutcome='success';window.__qaOrderClose=0;window.__qaJournal=0;
  const instrument={asset_class:'fx',pip_size:'0.0001',tick_size:'0.0001',quantity_min:'0.001',quantity_step:'0.001'};
  function Fixture({active,blocked,asset}) {const [opened,setOpened]=R.useState(true);const spec={...instrument,asset_class:asset||'fx'},execution={cursor_index:500,instrument_spec:spec,cost_model:{account_ccy:'USD'},spread_price:'0.0002',...(active?{position:{position_id:'FIXTURE-position',side:'BUY',quantity:'0.001',stop_loss:'1.0979',take_profit:'1.1039',entry_fill:'1.1'}}:{})};const replay=R.useMemo(()=>({record_id:'FIXTURE-only',revision:1,payload:{cursor_index:500,execution},visible_rows:[{timestamp:1791374400,close:'1.1'}]}),[]);const order=C.useChartOrder({workspace:'FIXTURE-only',replay,dataset:{instrument_spec:spec,timeframe_seconds:60},ready:true,blocked,submit:async(endpoint,body)=>{window.__qaSubmits.push({fixture:'fx-controls-independent',endpoint,body});if(window.__qaOutcome==='error')throw new Error('FIXTURE submit rejected');if(window.__qaOutcome==='false')return false;if(window.__qaOutcome==='defer')return new Promise(resolve=>window.__qaResolve=resolve);return true}});return opened?R.createElement(O,{order,blockedReason:blocked?'FIXTURE historical view':null,theme,onClose:()=>{window.__qaOrderClose++;setOpened(false)},onJournal:()=>window.__qaJournal++}):R.createElement('div',{id:'qa-order-closed'},'Fixture closed')}
  window.__qaRenderOrder=opts=>root.render(R.createElement(P,{language:'en'},R.createElement(Fixture,{...opts,key:Math.random()})));window.__qaRenderOrder({});
 },theme);
 let modal=p.getByRole('dialog');await modal.waitFor();const qty=modal.locator('input[type=number]').first(),sl=modal.locator('input[type=number]').nth(1),save=modal.locator('button[type=submit]');assert.equal(await qty.inputValue(),'0.001');assert.equal(await qty.getAttribute('step'),'0.001');assert.equal(await modal.getByRole('switch').count(),3);assert.equal(await modal.getByRole('switch').nth(0).isChecked(),true);assert.equal(await modal.getByRole('switch').nth(1).isChecked(),true);assert.equal(await modal.getByRole('switch').nth(0).isDisabled(),true);
 await sl.fill('1.2');await save.click();await modal.getByRole('alert').waitFor();assert.equal(await p.evaluate(()=>__qaSubmits.length),0);assert.equal(await modal.count(),1);await sl.fill('1.098');await p.evaluate(()=>window.__qaOutcome='error');await save.click();await modal.getByRole('alert').filter({hasText:'FIXTURE submit rejected'}).waitFor();assert.equal(await p.evaluate(()=>__qaOrderClose),0);
 await p.evaluate(()=>window.__qaOutcome='false');await save.click();assert.equal(await modal.count(),1);assert.equal(await p.evaluate(()=>__qaOrderClose),0);await p.evaluate(()=>window.__qaOutcome='defer');await modal.locator('footer input[type=checkbox]').check();await save.click();assert.equal(await save.isDisabled(),true);await p.evaluate(()=>window.__qaResolve(true));await modal.waitFor({state:'hidden'});assert.equal(await p.evaluate(()=>__qaOrderClose),1);assert.equal(await p.evaluate(()=>__qaJournal),1);const market=await p.evaluate(()=>__qaSubmits.at(-1));assert.equal(market.endpoint,'orders/market');assert.equal(market.body.quantity,'0.001');assert.equal(market.body.stop_loss,'1.098');assert.match(market.body.operation_id,/^chart-/);
 await p.evaluate(()=>{window.__qaOutcome='success';__qaRenderOrder({active:true})});await modal.waitFor();assert.equal(await modal.locator('select').first().isDisabled(),true);assert.equal(await modal.locator('input[type=number]').first().isDisabled(),true);await modal.locator('input[type=number]').nth(2).fill('1.104');await modal.locator('button[type=submit]').click();await modal.waitFor({state:'hidden'});const protection=await p.evaluate(()=>__qaSubmits.at(-1));assert.equal(protection.endpoint,'orders/protection');assert.equal(protection.body.target_id,'FIXTURE-position');assert.equal(protection.body.take_profit,'1.104');assert.ok(!('quantity' in protection.body));
 await p.evaluate(()=>__qaRenderOrder({blocked:true,asset:'crypto'}));await modal.waitFor();assert.equal(await modal.locator('button[type=submit]').isDisabled(),true);assert.match(await modal.innerText(),/quantity/i);await p.addScriptTag({path:'../../.artifacts/wm-integration-quality-tools/node_modules/axe-core/axe.min.js'});const axe=await p.evaluate(()=>axe.run({include:[['.legacy-order-overlay']]},{rules:{region:{enabled:false}}}));report.axe.push({theme,width,violations:axe.violations.map(v=>({id:v.id,targets:v.nodes.map(n=>n.target)}))});assert.equal(axe.violations.length,0);report.cases.push({theme,width,pass:true,market,protection,checks:['real hook validation blocks invalidSL','error and false keep modal open','pending disables Save','successfulmarket closes + Journalcallback','active protectioncontract preserves target','blocked and nonFX units','Axe focused 0']});await ctx.close();
 }report.pass=!report.errors.length&&!report.blocked.length
}catch(e){report.pass=false;report.failure=String(e);process.exitCode=1}finally{await browser.close();await writeFile(new URL('order-report.json',import.meta.url),JSON.stringify(report,null,2));console.log(JSON.stringify({pass:report.pass,cases:report.cases.length,errors:report.errors,blocked:report.blocked,failure:report.failure}))}
