import assert from 'node:assert/strict'
import {chromium} from '../../../web/node_modules/playwright/index.mjs'
import {readFile,writeFile} from 'node:fs/promises'
import {fileURLToPath} from 'node:url'
import {createHash} from 'node:crypto'
const out=new URL('./',import.meta.url),origin='http://127.0.0.1:5180',browser=await chromium.launch({headless:true}),report={cases:[],errors:[],blocked:[]}
async function setup(theme,width,view){const context=await browser.newContext({viewport:{width,height:987},reducedMotion:'reduce'}),traffic=[];await context.addInitScript(theme=>{localStorage.setItem('tw-theme',theme);localStorage.setItem('tw-language','vi')},theme);await context.routeWebSocket('**/*',s=>s.close());await context.route('**/*',route=>{const r=route.request(),u=new URL(r.url());if(u.pathname.startsWith('/api/'))traffic.push({method:r.method(),path:u.pathname});if(!['GET','HEAD','OPTIONS'].includes(r.method())||![origin,'http://127.0.0.1:8010'].includes(u.origin)||/^\/api\/v2\/(live|data\/(market-assets|providers))/.test(u.pathname)){report.blocked.push({method:r.method(),url:r.url()});return route.abort()}return route.continue()});const page=await context.newPage();page.on('pageerror',e=>report.errors.push(String(e)));await page.goto(origin+'/?workspace=tenant-a&view='+view+'&area=testing&section='+(view==='overview'?'dashboard':'market-data'));const input=page.locator(view==='overview'?'.fx-dashboard-search input':'.data-library-search input');await input.waitFor();return{context,page,input,traffic}}
const snapshot=e=>{const s=getComputedStyle(e),p=getComputedStyle(e,'::placeholder'),icon=e.parentElement.querySelector('svg'),r=e.getBoundingClientRect(),i=icon.getBoundingClientRect(),keys=['borderRadius','height','minHeight','paddingTop','paddingRight','paddingBottom','paddingLeft','borderTopWidth','borderTopStyle','borderTopColor','backgroundColor','color','fontFamily','fontSize','fontWeight','lineHeight','outlineStyle','boxShadow'];return{style:Object.fromEntries(keys.map(k=>[k,s[k]])),placeholder:{color:p.color,opacity:p.opacity},icon:{width:i.width,height:i.height,color:getComputedStyle(icon).color,left:i.left-r.left,centerDelta:Math.abs(i.top+i.height/2-r.top-r.height/2)},geometry:{left:r.left,right:r.right,width:r.width,pageOverflow:document.documentElement.scrollWidth-innerWidth},focusVisible:e.matches(':focus-visible')}}
async function capture(page,input,name,state){if(state==='rest'){await input.evaluate(e=>e.blur());await page.mouse.move(2,2)}else if(state==='hover')await input.hover();else{await input.click();await page.keyboard.press('Shift+Tab');await page.keyboard.press('Tab');await page.mouse.move(2,2);assert.equal(await input.evaluate(e=>e===document.activeElement),true)}await page.waitForTimeout(180);const result=await input.evaluate(snapshot);await input.scrollIntoViewIfNeeded();await page.screenshot({path:fileURLToPath(new URL(name+'-'+state+'.png',out)),fullPage:true});return result}
try{for(const theme of ['dark','light'])for(const width of [360,1710]){const item={name:theme+'-'+width,states:{}};report.cases.push(item);const references={};try{
 for(const view of ['overview','market-data']){const{context,page,input,traffic}=await setup(theme,width,view);try{references[view]={traffic,states:{}};for(const state of ['rest','hover','focus'])references[view].states[state]=await capture(page,input,item.name+'-'+view,state)}finally{await context.close()}}
 item.references=references;for(const state of ['rest','hover','focus']){const dashboard=references.overview.states[state],library=references['market-data'].states[state];assert.deepEqual(library.style,dashboard.style,`${state} input style parity`);assert.deepEqual(library.placeholder,dashboard.placeholder,`${state} placeholder parity`);assert.deepEqual(library.icon,dashboard.icon,`${state} icon parity`);assert.equal(library.geometry.pageOverflow,0);assert.equal(dashboard.geometry.pageOverflow,0);if(state==='focus'){assert(library.focusVisible);assert(dashboard.focusVisible)}item.states[state]='PASS'}assert.equal(references['market-data'].states.rest.geometry.width,width===1710?420:270);item.pass=true
 }catch(e){item.pass=false;item.failure=String(e);console.log(JSON.stringify({name:item.name,failure:item.failure}))}}
 report.pass=report.cases.every(c=>c.pass)&&!report.errors.length&&!report.blocked.length
}finally{report.hashes={};for(const f of ['data-library.css','dashboard.css'])report.hashes[f]=createHash('sha256').update(await readFile(new URL('../../../web/src/'+f,out))).digest('hex');await writeFile(new URL('review.json',out),JSON.stringify(report,null,2));await browser.close();console.log(JSON.stringify({pass:report.pass,cases:report.cases.map(c=>({name:c.name,pass:c.pass,states:c.states,failure:c.failure})),errors:report.errors,blocked:report.blocked,hashes:report.hashes},null,2))}
