import assert from 'node:assert/strict'
import {chromium} from '../../../web/node_modules/playwright/index.mjs'
import {writeFile,readFile} from 'node:fs/promises'
import {fileURLToPath} from 'node:url'
import {createHash} from 'node:crypto'
const out=new URL('./',import.meta.url),origin='http://127.0.0.1:5180',browser=await chromium.launch(),report={cases:[],errors:[],blocked:[]}
const instruments=[{instrument_id:'EUR/USD',name:'Euro US Dollar (isolated fixture)',provider:'Dukascopy',provider_id:'dukascopy-catalog',asset_class:''},{instrument_id:'XAU/USD',name:'Gold (isolated fixture)',provider:'Dukascopy',provider_id:'dukascopy-catalog',asset_class:''}]
const baseState={provider_id:'dukascopy-catalog',configured:true,status:'cached',retrieved_at_utc:'2026-10-08T00:00:00+00:00',item_count:1,stale:false,error:null,refresh_available:true,retry_after_seconds:0}
const cachedDataset={dataset_id:'qa-retained',instrument_id:'OFFLINE-QA',timeframe:'60s',row_count:2,instrument_spec:{asset_class:'fx'},source:{provider:'isolated-QA'},quality_status:'unverified'}
async function setup(theme,width,scenario){let posts=0,gets=0;const context=await browser.newContext({viewport:{width,height:987},reducedMotion:'reduce'}),traffic=[];await context.addInitScript(theme=>{localStorage.setItem('tw-theme',theme);localStorage.setItem('tw-language','vi')},theme);await context.routeWebSocket('**/*',s=>s.close());
 const initial={...baseState};if(scenario==='missing'){Object.assign(initial,{configured:false,status:'empty',item_count:0,retrieved_at_utc:null,refresh_available:false})}if(scenario.startsWith('bootstrap'))Object.assign(initial,{status:'empty',item_count:0,retrieved_at_utc:null});if(scenario==='stale')initial.stale=true;if(scenario==='error')Object.assign(initial,{error:'rate_limited',refresh_available:false,retry_after_seconds:300});if(scenario==='cooldown')Object.assign(initial,{refresh_available:false,retry_after_seconds:1})
 await context.route('**/*',async route=>{const r=route.request(),u=new URL(r.url());if(u.pathname.startsWith('/api/'))traffic.push({method:r.method(),path:u.pathname});if(![origin,'http://127.0.0.1:8010'].includes(u.origin)||/^\/api\/v2\/(live|data\/(market-assets|providers))/.test(u.pathname)){report.blocked.push({method:r.method(),url:r.url()});return route.abort()}
 if(u.pathname==='/api/v2/data/catalog/refresh'&&r.method()==='POST'){posts++;if(scenario==='manual-http-error'||scenario==='bootstrap-http-error')return route.fulfill({status:503,json:{detail:'Independent no upstream request'}});await new Promise(resolve=>setTimeout(resolve,100));return route.fulfill({json:{catalog_items:instruments,catalog_state:{...baseState,item_count:2,refresh_available:false,retry_after_seconds:60}}})}
 if(!['GET','HEAD','OPTIONS'].includes(r.method())){report.blocked.push({method:r.method(),url:r.url()});return route.abort()}
 if(u.pathname==='/api/v2/data/datasets'){gets++;return route.fulfill({json:{items:[cachedDataset],catalog_items:initial.status==='cached'?[instruments[0]]:[],catalog_state:initial}})}return route.continue()});const page=await context.newPage();page.on('pageerror',e=>report.errors.push(String(e)));await page.goto(origin+'/?workspace=tenant-a&view=market-data&area=testing&section=market-data');await page.getByTestId('data-desk-dataset-table').waitFor();return{page,context,traffic,count:()=>({posts,gets})}
}
async function screen(page,name){await page.screenshot({path:fileURLToPath(new URL(name+'.png',out)),fullPage:true})}
async function geometry(page){const g=await page.evaluate(()=>({overflow:document.documentElement.scrollWidth-innerWidth,buttons:[...document.querySelectorAll('.data-library-toolbar button')].map(e=>{const r=e.getBoundingClientRect();return{label:e.getAttribute('aria-label')||e.textContent,left:r.left,right:r.right,top:r.top,bottom:r.bottom}})}));assert.equal(g.overflow,0);for(const b of g.buttons)assert(b.left>=0&&b.right<=page.viewportSize().width);return g}
async function run(theme,width,scenario){const item={name:scenario+'-'+theme+'-'+width};report.cases.push(item);const{page,context,traffic,count}=await setup(theme,width,scenario);try{const refresh=page.locator('.data-library-refresh'),rows=page.locator('.rd-table tbody tr'),status=page.locator('.data-library-catalog-status');assert.equal(await page.getByTestId('dataset-row-qa-retained').count(),1);assert.equal(await page.locator('.data-library-download:not(:disabled)').count(),0)
 if(scenario==='missing'){assert.equal(await rows.count(),1);assert(await refresh.isDisabled());assert.match(await status.innerText(),/Chưa cấu hình Dukascopy API key/)}
 else if(scenario==='cached'){assert.equal(await rows.count(),2);assert.equal(await refresh.isDisabled(),false);assert.equal(await status.count(),0)}
 else if(scenario==='stale'){assert.equal(await rows.count(),2);assert.match(await status.innerText(),/đã cũ.*bản đã lưu/)}
 else if(scenario==='error'){assert.equal(await rows.count(),2);assert(await refresh.isDisabled());assert.match(await status.innerText(),/giới hạn.*bản đã lưu/)}
 else if(scenario==='cooldown'){assert(await refresh.isDisabled());await page.waitForTimeout(1150);assert.equal(await refresh.isDisabled(),false)}
 else if(scenario.startsWith('manual')){await refresh.click();if(scenario==='manual-success'){await page.waitForFunction(()=>document.querySelectorAll('.rd-table tbody tr').length===3);assert(await refresh.isDisabled());assert.equal(await status.count(),0)}else{await status.waitFor();assert.match(await status.innerText(),/Không cập nhật.*bản đã lưu/);assert.equal(await rows.count(),2);assert.equal(await refresh.isDisabled(),false)}}
 else if(scenario==='bootstrap-success'){assert.equal(await rows.count(),3);assert(await refresh.isDisabled())}
 else if(scenario==='bootstrap-http-error'){assert.equal(await rows.count(),1);assert.match(await status.innerText(),/Không cập nhật/);assert.equal(await refresh.isDisabled(),false)}
 item.geometry=await geometry(page);await screen(page,item.name);await page.waitForTimeout(450);item.requests=count();assert.equal(item.requests.gets,1);assert.equal(item.requests.posts,scenario.startsWith('bootstrap')||scenario.startsWith('manual')?1:0);item.traffic=traffic;item.pass=true
 }catch(e){item.pass=false;item.failure=String(e);console.log(JSON.stringify(item))}finally{await context.close()}}
try{for(const scenario of ['missing','cached','stale','error'])for(const theme of ['dark','light'])for(const width of [360,1710])await run(theme,width,scenario);for(const scenario of ['bootstrap-success','bootstrap-http-error','manual-success','manual-http-error'])for(const theme of ['dark','light'])await run(theme,360,scenario);await run('dark',360,'cooldown');report.pass=report.cases.every(c=>c.pass)&&!report.errors.length&&!report.blocked.length}
finally{report.hashes={};for(const f of ['web/src/DataDeskWorkspace.jsx','web/src/dataDeskApi.js','web/src/data-library.css','trading_workspace_v2/dukascopy_catalog.py','trading_workspace_v2/api.py','scripts/serve_exness_history.py'])report.hashes[f]=createHash('sha256').update(await readFile(new URL('../../../'+f,out))).digest('hex');await writeFile(new URL('review.json',out),JSON.stringify(report,null,2));await browser.close();console.log(JSON.stringify({pass:report.pass,cases:report.cases.map(c=>({name:c.name,pass:c.pass,failure:c.failure})),errors:report.errors,blocked:report.blocked,hashes:report.hashes},null,2))}
