import assert from 'node:assert/strict'
import { chromium } from '../../../web/node_modules/playwright/index.mjs'
import { readFile,writeFile } from 'node:fs/promises'
import { createHash } from 'node:crypto'
const files=['DashboardPerformance.jsx','dashboard.css','SessionDetails.jsx','SessionPerformance.jsx','session-performance.css','FxAnalytics.jsx','fx-analytics.css','page-layout.css','DemoPreview.jsx'],pins=async()=>Promise.all(files.map(async f=>({file:f,sha256:createHash('sha256').update(await readFile('foundation_v2/web/src/'+f)).digest('hex')})))
const report={checks:[],errors:[],blocked:[],before:await pins()};const b=await chromium.launch({headless:true,ignoreDefaultArgs:['--hide-scrollbars']}),c=await b.newContext({viewport:{width:1710,height:987}}),p=await c.newPage()
await c.routeWebSocket('**/*',ws=>ws.close())
await c.route('**/*',async r=>{const q=r.request(),u=new URL(q.url());if(!['http://127.0.0.1:5180','http://127.0.0.1:8010'].includes(u.origin)||!['GET','HEAD','OPTIONS'].includes(q.method())){report.blocked.push({method:q.method(),url:q.url()});return r.abort()}if(u.pathname.startsWith('/api/')){const response=await r.fetch({url:'http://127.0.0.1:8010'+u.pathname+u.search});return r.fulfill({response})}return r.continue()})
p.on('pageerror',e=>report.errors.push(e.message))
const get=async path=>{const r=await c.request.get('http://127.0.0.1:8010'+path,{headers:{'X-Workspace-Id':'tenant-a'}});assert.ok(r.ok());return r.json()}
try{const catalog=await get('/api/v2/replay/sessions'),id='476f4b498e1a49ed9d48a75719f4d270';assert.ok(catalog.items.some(x=>x.record_id===id));const record=await get('/api/v2/replay/sessions/'+id)
for(const view of ['overview','replay','analytics']){await p.goto('http://127.0.0.1:5180/?workspace=tenant-a&view='+view+'&area=testing&section='+({overview:'dashboard',replay:'sessions',analytics:'analytics'}[view])+'&session='+id+'&select=1');await p.waitForLoadState('networkidle');if(view==='overview'){const info=p.locator('.fx-dashboard-scope-info');report.dashboard={notice:await p.getByTestId('dashboard-data-state').innerText(),partial:await info.count()?await info.getAttribute('aria-label'):null};if(await info.count()){assert.match(report.dashboard.partial,/phiên có dữ liệu/);await info.focus();assert.ok(await p.locator('.fx-dashboard-scope-tooltip').isVisible())}}if(view==='replay'){await p.getByTestId('session-trades-empty').waitFor();const summary=p.locator('.fxr-session-links .fxs-go-chart'),cta=p.getByTestId('session-trades-empty').locator('.fxs-go-chart');assert.equal(await summary.getAttribute('href'),await cta.getAttribute('href'));assert.equal(await cta.innerText(),'Go to chart');assert.equal(await cta.locator('svg').evaluate(e=>e.getBoundingClientRect().width),18);report.ctaHref=await cta.getAttribute('href');await cta.scrollIntoViewIfNeeded()}if(view==='analytics'){if(!(await p.getByRole('tablist',{name:'Phân tích',exact:true}).count())){await p.getByTestId('analytics-blocked').waitFor();report.analytics='blocked_by_data';}else{const tab=p.getByRole('tab',{name:'Performance',exact:true});await tab.focus();await p.keyboard.press('End');assert.equal(await p.getByRole('tab',{name:'Simulation',exact:true}).getAttribute('aria-selected'),'true');await p.keyboard.press('Home')}}await p.screenshot({path:new URL('./actual-'+view+'.png',import.meta.url).pathname.replace(/^\/(\w:)/,'$1')});report.checks.push({view,pass:true})}
assert.deepEqual(await get('/api/v2/replay/sessions'),catalog);assert.deepEqual(await get('/api/v2/replay/sessions/'+id),record);report.actualRecordsUnchanged=true;report.after=await pins();report.sourceUnchanged=JSON.stringify(report.before)===JSON.stringify(report.after);assert.ok(report.sourceUnchanged);assert.deepEqual(report.errors,[]);assert.deepEqual(report.blocked,[]);report.pass=true
}catch(e){report.failure=String(e);process.exitCode=1}finally{await b.close();await writeFile(new URL('./actual-report.json',import.meta.url),JSON.stringify(report,null,2));console.log(JSON.stringify(report))}
