import assert from 'node:assert/strict'
import { chromium } from '../../../web/node_modules/playwright/index.mjs'
import { readFile,writeFile,mkdir } from 'node:fs/promises'
import { createHash } from 'node:crypto'
import path from 'node:path'
import { DEMO_SESSIONS,DEMO_DATASETS,demoOverview,demoDashboardAnalytics,demoReplayContext } from '../../../web/src/demoFixtures.js'
const out=path.dirname(new URL(import.meta.url).pathname.replace(/^\/(\w:)/,'$1'));await mkdir(out,{recursive:true})
const files=['DashboardPerformance.jsx','dashboard.css','SessionDetails.jsx','SessionPerformance.jsx','session-performance.css','FxAnalytics.jsx','fx-analytics.css','page-layout.css','DemoPreview.jsx'],pins=async()=>Promise.all(files.map(async f=>({file:f,sha256:createHash('sha256').update(await readFile('foundation_v2/web/src/'+f)).digest('hex')})))
const report={checks:[],failures:[],errors:[],blocked:[],requests:[],geometry:[],before:await pins()}
const b=await chromium.launch({headless:true,ignoreDefaultArgs:['--hide-scrollbars']}),c=await b.newContext(),p=await c.newPage();let fixture=null
const qaItem={...DEMO_SESSIONS[0],record_id:'qa-page-polish',name:'QA page polish',archived:false},qaContext={...demoReplayContext(DEMO_SESSIONS[0]),record_id:qaItem.record_id}
await c.routeWebSocket('**/*',ws=>ws.close())
await c.route('**/*',async r=>{const q=r.request(),u=new URL(q.url());if(u.origin!=='http://127.0.0.1:5180'||!['GET','HEAD','OPTIONS'].includes(q.method())){report.blocked.push({method:q.method(),url:q.url()});return r.abort()}if(!u.pathname.startsWith('/api/'))return r.continue();report.requests.push({phase:report.phase,path:u.pathname,fixture});if(!fixture){report.blocked.push({method:q.method(),url:q.url(),reason:'unexpected demoAPI'});return r.abort()}if(u.pathname==='/api/v2/overview'){if(fixture==='dashboard-error')return r.fulfill({status:500,json:{detail:'QA fixture server error'}});const payload=demoOverview();if(fixture==='dashboard-partial'){payload.performance.status='partial';payload.performance.scope={session_count:5,readable_session_count:3}}if(fixture==='dashboard-blocked'){payload.performance.status='blocked';payload.performance.scope={session_count:5,readable_session_count:0};payload.performance.metrics={};payload.performance.months=[];payload.performance.symbols=[]}return r.fulfill({json:payload})}if(u.pathname==='/api/v2/replay/sessions')return r.fulfill({json:{items:[{...qaItem,...(fixture==='session-archived'?{archived:true}:{}),...(fixture==='session-missing-dataset'?{dataset_available:false}:{})}]}});if(u.pathname==='/api/v2/data/datasets')return r.fulfill({json:{items:DEMO_DATASETS}});if(u.pathname==='/api/v2/replay/sessions/'+qaItem.record_id)return r.fulfill({json:qaContext});if(u.pathname==='/api/v2/replay/sessions/'+qaItem.record_id+'/analytics'){if(fixture==='session-error')return r.fulfill({status:500,json:{detail:'QA analytics error'}});const payload=demoDashboardAnalytics(qaItem,'tenant-a');payload.provenance.preview=false;payload.ledger=[];payload.scope={selected_trade_count:0,total_trade_count:0};payload.metrics={...payload.metrics,closed_trade_count:0,net_pnl:0,wins:0,losses:0,breakeven:0,ending_closed_trade_balance:10000,closed_trade_balance_curve:[{sequence:0,closed_trade_balance:10000}]};if(fixture==='session-blocked'){payload.analytics_available=false;payload.blocked_by_data=['replay_execution_not_initialized']}return r.fulfill({json:payload})}return r.fulfill({json:{items:[]}})})
p.on('pageerror',e=>report.errors.push({phase:report.phase,error:e.message}))
const goto=async(view,theme,width,mode=null)=>{fixture=mode;await p.setViewportSize({width,height:width===360?700:987});await p.goto('http://127.0.0.1:5180/?workspace=tenant-a&view='+view+'&area=testing&section='+({overview:'dashboard',replay:'sessions',analytics:'analytics'}[view])+'&select=1'+(mode?'&session='+qaItem.record_id:'&demo=1'));await p.waitForLoadState('networkidle');if(await p.getByTestId('fxreplay-shell').getAttribute('data-theme')!==theme)await p.getByTestId('theme-toggle').click()}
const shot=async()=>p.screenshot({path:path.join(out,report.phase+'.png')})
const run=async(name,work)=>{report.phase=name;try{await work();report.checks.push({name,pass:true})}catch(e){report.failures.push({name,error:String(e),stack:e.stack});await shot()}await writeFile(path.join(out,'progress.json'),JSON.stringify(report,null,2))}
const style=async loc=>loc.evaluate(e=>{const s=getComputedStyle(e);return {radius:s.borderRadius,minHeight:s.minHeight,height:e.getBoundingClientRect().height,padding:s.padding,fontSize:s.fontSize,fontWeight:s.fontWeight,display:s.display,align:s.alignItems,justify:s.justifyContent,background:s.backgroundColor,color:s.color}})
try{
for(const theme of ['dark','light'])for(const width of [360,768,1710]){
 for(const view of ['overview','replay','analytics'])await run('demo-'+view+'-'+theme+'-'+width,async()=>{await goto(view,theme,width);if(view==='overview'){assert.equal(await p.locator('.fx-dashboard-scope-info').count(),0);assert.equal((await p.getByTestId('dashboard-data-state').innerText()).trim(),'')}if(view==='analytics'){const list=p.getByRole('tablist',{name:'Phân tích',exact:true});await list.scrollIntoViewIfNeeded();const geometry=await list.evaluate(e=>{const r=e.getBoundingClientRect(),s=getComputedStyle(e),after=getComputedStyle(e,'::after'),content=e.closest('.fx-content');return {box:r.toJSON(),paddingTop:s.paddingTop,paddingBottom:s.paddingBottom,display:s.display,children:[...e.children].map(n=>n.getBoundingClientRect().toJSON()),separator:{left:parseFloat(after.left),right:parseFloat(after.right),height:after.height,content:after.content},content:{left:content.getBoundingClientRect().left,right:content.getBoundingClientRect().left+content.clientWidth},filterBottom:document.querySelector('.fxa-analytics-filters').getBoundingClientRect().bottom}});report.geometry.push({phase:report.phase,...geometry});assert.equal(geometry.display,'grid');assert.equal(geometry.paddingTop,geometry.paddingBottom);assert.equal(geometry.children.length,3);assert.ok(Math.max(...geometry.children.map(x=>x.width))-Math.min(...geometry.children.map(x=>x.width))<1,'unequal tab columns');assert.ok(Math.max(...geometry.children.map(x=>x.y))-Math.min(...geometry.children.map(x=>x.y))<1,'tabs not on same row');assert.ok(Math.abs(geometry.box.x+geometry.separator.left-geometry.content.left)<1);assert.ok(Math.abs(geometry.box.x+geometry.box.width-geometry.separator.right-geometry.content.right)<1);assert.equal(geometry.separator.height,'1px');const topGap=geometry.children[0].y-geometry.filterBottom,bottomGap=geometry.box.bottom-geometry.children[0].bottom;assert.ok(Math.abs(topGap-bottomGap)<1,'unequal separator spacing '+JSON.stringify({topGap,bottomGap}));const performance=p.getByRole('tab',{name:'Performance',exact:true});await performance.focus();await p.keyboard.press('ArrowRight');assert.equal(await p.getByRole('tab',{name:'Drawdown',exact:true}).getAttribute('aria-selected'),'true');await p.keyboard.press('End');assert.equal(await p.getByRole('tab',{name:'Simulation',exact:true}).getAttribute('aria-selected'),'true');await p.keyboard.press('Home');assert.equal(await performance.getAttribute('aria-selected'),'true');await list.scrollIntoViewIfNeeded()}await shot();assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth-innerWidth),0)})
 await run('fixture-dashboard-partial-'+theme+'-'+width,async()=>{await goto('overview',theme,width,'dashboard-partial');const info=p.locator('.fx-dashboard-scope-info');await info.waitFor();assert.match(await info.getAttribute('aria-label'),/3\/5/);assert.equal(await info.getAttribute('tabindex'),'0');assert.equal((await p.getByTestId('dashboard-data-state').innerText()).trim(),'');const tooltip=info.locator('.fx-dashboard-scope-tooltip');assert.equal(await tooltip.isVisible(),false);await info.hover();assert.equal(await tooltip.isVisible(),true);assert.match(await tooltip.innerText(),/3\/5/);await p.mouse.move(10,10);await info.focus();assert.equal(await tooltip.isVisible(),true);const bounds=await tooltip.boundingBox(),content=await p.locator('.fx-content').boundingBox();assert.ok(bounds.x>=content.x-1&&bounds.x+bounds.width<=content.x+content.width+1,'tooltip clipped');await shot()})
 await run('fixture-session-empty-CTA-'+theme+'-'+width,async()=>{await goto('replay',theme,width,'session-empty');const empty=p.getByTestId('session-trades-empty');await empty.waitFor();const summary=p.locator('.fxr-session-links .fxs-go-chart'),cta=empty.locator('.fxs-go-chart');assert.equal(await cta.innerText(),'Go to chart');assert.equal(await cta.locator('svg').count(),1);assert.equal(await summary.getAttribute('href'),await cta.getAttribute('href'));const href=new URL(await cta.getAttribute('href'),'http://127.0.0.1:5180');assert.equal(href.searchParams.get('session'),qaItem.record_id);assert.equal(href.searchParams.get('select'),null);assert.equal(href.searchParams.get('surface'),'workspace');assert.equal(href.searchParams.get('view'),'replay');assert.deepEqual(await style(summary),await style(cta),'empty CTA differs from summary');await cta.focus();assert.ok(await cta.evaluate(e=>e===document.activeElement));await empty.scrollIntoViewIfNeeded();await shot()})
}
for(const mode of ['dashboard-blocked','dashboard-error'])await run('fixture-'+mode,async()=>{await goto('overview','dark',1710,mode);const notice=p.getByTestId('dashboard-data-state');assert.match(await notice.innerText(),mode.endsWith('error')?/Chưa tải được/:/Chưa đủ dữ liệu/);assert.equal(await notice.getAttribute('role'),mode.endsWith('error')?'alert':'status');assert.equal(await p.locator('.fx-dashboard-scope-info').count(),0);assert.equal(await p.locator('.fx-dashboard-metric').filter({hasText:'Trades taken'}).locator('strong').innerText(),'—');await shot()})
for(const mode of ['session-archived','session-missing-dataset','session-blocked','session-error'])await run('fixture-'+mode,async()=>{await goto('replay','light',768,mode);if(mode==='session-error'){assert.match(await p.getByRole('alert').innerText(),/QA analytics error/);assert.equal(await p.getByTestId('session-performance').count(),0)}else{await p.getByTestId('session-trades-empty').waitFor();const count=await p.getByTestId('session-trades-empty').locator('.fxs-go-chart').count();assert.equal(count,mode==='session-blocked'?1:0)}await shot()})
report.after=await pins();report.sourceUnchanged=JSON.stringify(report.before)===JSON.stringify(report.after);assert.deepEqual(report.errors,[]);assert.deepEqual(report.blocked,[]);assert.deepEqual(report.failures,[]);assert.ok(report.sourceUnchanged);report.pass=true
}catch(e){report.failure=String(e);process.exitCode=1}finally{await b.close();await writeFile(path.join(out,'report.json'),JSON.stringify(report,null,2));console.log(JSON.stringify({pass:report.pass,checks:report.checks.length,failures:report.failures.map(f=>({name:f.name,error:f.error})),errors:report.errors,blocked:report.blocked,sourceUnchanged:report.sourceUnchanged}))}
