import assert from 'node:assert/strict'
import { chromium } from '../../../web/node_modules/playwright/index.mjs'
import { writeFile } from 'node:fs/promises'
import { fileURLToPath } from 'node:url'
const out=new URL('./',import.meta.url),report={scope:'Actual readonly pages; independent project palette and focused contrast QA',cases:[],errors:[],blocked:[]}
const browser=await chromium.launch({headless:true,ignoreDefaultArgs:['--hide-scrollbars']})
try{for(const theme of ['dark','light']){
 const ctx=await browser.newContext({viewport:{width:1710,height:987}});await ctx.addInitScript(theme=>{localStorage.setItem('tw-theme',theme);localStorage.setItem('tw-language','en')},theme);await ctx.routeWebSocket('**/*',s=>s.close());await ctx.route('**/*',route=>{const r=route.request(),u=new URL(r.url());if(['GET','HEAD','OPTIONS'].includes(r.method())&&['http://127.0.0.1:5180','http://127.0.0.1:8010'].includes(u.origin))return route.continue();report.blocked.push({method:r.method(),url:r.url()});return route.abort()});const p=await ctx.newPage();p.on('pageerror',e=>report.errors.push(String(e)));p.setDefaultTimeout(15000)
 for(const[name,query]of [['dashboard','view=overview&area=testing&section=dashboard'],['trades','view=trade&area=testing&section=trades&select=1&sessions=all'],['analytics','view=analytics&area=testing&section=analytics&select=1'],['market','view=market-data&area=testing&section=market-data']]){
  await p.goto(`http://127.0.0.1:5180/?workspace=tenant-a&${query}`,{waitUntil:'networkidle'});await p.locator('.fx-content > *').first().waitFor();if(name==='dashboard'){await p.reload({waitUntil:'networkidle'});await p.locator('.fx-content > *').first().waitFor()}
  await p.addScriptTag({path:'../../.artifacts/wm-integration-quality-tools/node_modules/axe-core/axe.min.js'});for(const width of name==='dashboard'?[1710,360]:[1710]){await p.setViewportSize({width,height:987});const geometry=await p.locator('.fx-app').evaluate(el=>{const s=getComputedStyle(el);return{theme:el.dataset.theme,canvas:s.getPropertyValue('--project-canvas').trim(),text:s.getPropertyValue('--project-text').trim(),positive:s.getPropertyValue('--project-positive').trim(),negative:s.getPropertyValue('--project-negative').trim(),overflow:document.documentElement.scrollWidth-innerWidth}});assert.equal(geometry.theme,theme);assert.equal(geometry.canvas,theme==='dark'?'#080808':'#FFFFFF');assert.equal(geometry.text,theme==='dark'?'#FFFFFF':'#111111');assert.equal(geometry.overflow,0);assert.equal(geometry.positive,theme==='dark'?'#72CFA1':'#24724B');assert.equal(geometry.negative,theme==='dark'?'#FF828B':'#B5373C');const axe=await p.evaluate(()=>window.axe.run({include:[['.fx-app']]},{runOnly:{type:'rule',values:['color-contrast']}}));report.cases.push({name,theme,width,geometry,contrastViolations:axe.violations.map(v=>({id:v.id,nodes:v.nodes.map(n=>({target:n.target,summary:n.failureSummary}))})),pass:!axe.violations.length});assert.equal(axe.violations.length,0);if(name==='dashboard')await p.screenshot({path:fileURLToPath(new URL(`palette-${theme}-${width}.png`,out))})}
  await p.setViewportSize({width:1710,height:987})
 }await ctx.close()
}report.pass=report.cases.every(c=>c.pass)&&!report.errors.length&&!report.blocked.length}catch(e){report.pass=false;report.failure=String(e);process.exitCode=1}finally{await browser.close();await writeFile(new URL('palette-report.json',out),JSON.stringify(report,null,2));console.log(JSON.stringify({pass:report.pass,cases:report.cases.length,errors:report.errors,failure:report.failure}))}
