import assert from 'node:assert/strict'
import {chromium} from '../../../web/node_modules/playwright/index.mjs'
import {writeFile} from 'node:fs/promises'
const browser=await chromium.launch({headless:true,ignoreDefaultArgs:['--hide-scrollbars']})
const report={scope:'Real LegacyPositions rendered with labeled execution fixtures; no persisted writes',cases:[],errors:[],blocked:[],axe:[]}
try{for(const[theme,width]of [['dark',1710],['light',360]]){
 const ctx=await browser.newContext({viewport:{width,height:987}});await ctx.addInitScript(theme=>{localStorage.setItem('tw-theme',theme);localStorage.setItem('tw-language','en')},theme);await ctx.routeWebSocket('**/*',s=>s.close());await ctx.route('**/*',route=>{const r=route.request(),u=new URL(r.url());if(['GET','HEAD','OPTIONS'].includes(r.method())&&['http://127.0.0.1:5180','http://127.0.0.1:8010'].includes(u.origin))return route.continue();report.blocked.push({method:r.method(),url:r.url()});return route.abort()})
 const p=await ctx.newPage();p.setDefaultTimeout(10000);p.on('pageerror',e=>report.errors.push(String(e)));await p.goto('http://127.0.0.1:5180/?view=overview',{waitUntil:'networkidle'})
 await p.evaluate(async theme=>{const src=await(await fetch('/src/LegacyPositions.jsx')).text(),reactUrl=src.match(/from\s+["']([^"']*\/react\.js[^"']*)["']/)[1],r=await import(reactUrl),d=await import(reactUrl.replace('react.js','react-dom_client.js')),React=r.default||r,DOM=d.default||d,Positions=(await import('/src/LegacyPositions.jsx')).default,Provider=(await import(src.match(/from\s+[\"']([^\"']*testingLocale\.jsx[^\"']*)[\"']/)[1])).TestingLocaleProvider;await import('/src/ChartWorkbench.css');const host=document.createElement('div');host.id='qa-positions';host.className='fx-app';host.dataset.theme=theme;host.style.cssText='display:block;position:fixed;inset:0;z-index:100;overflow:auto;background:var(--project-canvas);color:var(--project-text)';document.body.append(host);const root=DOM.createRoot(host);window.__qaPositionRender=execution=>root.render(React.createElement(Provider,{language:'en'},React.createElement(Positions,{execution,symbol:'FIXTURE'})))},theme)
 const fixture={position:{position_id:'open-1',side:'BUY',quantity:'0.001',take_profit:'0.12345678',stop_loss:'0.11111111'},pending_market_order:{operation_id:'pending-1',side:'SELL',quantity:'0.002',take_profit:'0.10101010',stop_loss:'0.13131313'},floating_pl:'0',cost_model:{account_ccy:'USD'},ledger:[{kind:'market_fill',sequence:1,details:{position_id:'bar-1',side:'SELL',quantity:'0.003'}},{kind:'protective_fill',sequence:2,details:{position_id:'bar-1',net_pnl:'-12.34'}},{kind:'market_fill',sequence:3,details:{position_id:'tick-1',side:'BUY',quantity:'0.004'}},{kind:'protective_fill',sequence:4,details:{position_id:'tick-1',side:'BUY',quantity:'0.004',net_pnl:'0',closed_position:{take_profit:'0.12345678',stop_loss:'0.11111111'},cost_breakdown:{commission_account:'0'}}},{kind:'order_rejected',sequence:5,details:{position_id:'rejected',net_pnl:'999'}}]}
 await p.evaluate(x=>window.__qaPositionRender(x),fixture);const host=p.locator('#qa-positions');await host.locator('table').waitFor();const cells=()=>host.locator('tbody tr').allTextContents()
 assert.ok((await cells())[0].includes('0.001'));assert.ok((await cells())[0].includes('0.12345678'));assert.ok((await cells())[0].includes('0'));report.cases.push({theme,width,name:'open fractional quantity8digits and zero floating preserved',pass:true})
 await host.getByRole('tab',{selected:true}).focus();await p.keyboard.press('ArrowRight');await p.waitForFunction(()=>document.querySelector('#qa-positions [aria-selected=true]').id==='position-tab-pending');assert.ok((await cells())[0].includes('0.002'))
 await p.keyboard.press('End');await p.waitForFunction(()=>document.querySelector('#qa-positions [aria-selected=true]').id==='position-tab-closed');const rows=await cells();assert.equal(rows.length,2);assert.ok(rows[0].includes('SELL'));assert.ok(rows[0].includes('0.003'));assert.ok(rows[0].includes('-12.34'));assert.equal((await host.locator('tbody tr').nth(0).locator('td').allTextContents())[7],'—');const tickCells=await host.locator('tbody tr').nth(1).locator('td').allTextContents();assert.equal(tickCells[3],'0.12345678');assert.equal(tickCells[6],'0');assert.equal(tickCells[7],'0');report.cases.push({theme,width,name:'BAR entry join, tick closed snapshot/costs, rejected excluded and keyboard tabs',pass:true})
 const many={...fixture,position:null,pending_market_order:null,ledger:Array.from({length:26},(_,i)=>({kind:'protective_fill',sequence:i+1,details:{position_id:`fixture-${i}`,side:'BUY',quantity:'0.001',net_pnl:String(i)}}))};await p.evaluate(x=>window.__qaPositionRender(x),many);assert.equal((await cells()).length,10);await host.getByRole('button',{name:'Next page',exact:true}).click();assert.equal((await cells()).length,10);await host.getByRole('button',{name:'Next page',exact:true}).click();assert.equal((await cells()).length,6);await host.locator('select').selectOption('25');assert.equal((await cells()).length,25);report.cases.push({theme,width,name:'pagination26 rows/page size resets without writes',pass:true})
 await p.evaluate(()=>window.__qaPositionRender(null));await p.waitForFunction(()=>document.querySelector('#qa-positions tbody').textContent.includes('Position data is unavailable at this cutoff.'));assert.ok((await cells())[0].includes('cutoff'))
 await p.addScriptTag({path:'../../.artifacts/wm-integration-quality-tools/node_modules/axe-core/axe.min.js'});const axe=await p.evaluate(()=>window.axe.run({include:[['#qa-positions .legacy-positions']]},{rules:{region:{enabled:false}}}));report.axe.push({theme,width,violations:axe.violations.map(v=>({id:v.id,impact:v.impact,nodes:v.nodes.map(n=>n.target)}))});assert.equal(axe.violations.length,0);report.cases.push({theme,width,name:'null cutoff remains explicit unknown, focusedAxe',pass:true});await ctx.close()
}report.pass=!report.errors.length&&!report.blocked.length}catch(e){report.pass=false;report.failure=String(e);process.exitCode=1}finally{await browser.close();await writeFile(new URL('./positions-report.json',import.meta.url),JSON.stringify(report,null,2))}
console.log(JSON.stringify({pass:report.pass,cases:report.cases.length,errors:report.errors,failure:report.failure}))
