import assert from 'node:assert/strict'
import { mkdir, readFile, writeFile } from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { chromium } from 'playwright'

const web = path.dirname(fileURLToPath(import.meta.url))
const workspace = path.resolve(web, '../../../..')
const seed = JSON.parse(await readFile(process.env.WM_UI_SEED || path.join(workspace, '.artifacts/wm-integration-20261001/seed.json'), 'utf8'))
assert.equal(seed.database, 'trading_workspace_v2_ui_20261001')
assert.equal(seed.scope, 'synthetic-data-real-API-Postgres-local-UI-only')
for (const origin of [seed.ui, seed.api]) assert.equal(new URL(origin).hostname, '127.0.0.1')
const out = process.env.WM_JOURNEY_OUT || path.join(workspace, '.artifacts/wm-integration-20261002-resume/journey')
await mkdir(out, { recursive: true })
const report = { scope: 'read-only real PostgreSQL and API journey across Dashboard, Analytics, Sessions, chart, Trades and local Settings preferences', checks: [], errors: [] }
const browser = await chromium.launch({ headless: true })
const context = await browser.newContext({ viewport: { width: 1440, height: 900 } })
await context.addInitScript(() => {
  if (!localStorage.getItem('tw-language')) localStorage.setItem('tw-language', 'vi')
  if (!localStorage.getItem('tw-theme')) localStorage.setItem('tw-theme', 'dark')
})
const page = await context.newPage()
page.on('pageerror', error => report.errors.push(String(error)))
await page.route('**/*', async route => {
  const request = route.request()
  const url = new URL(request.url())
  if (url.origin !== seed.ui || !['GET', 'HEAD'].includes(request.method())) {
    report.errors.push(`Blocked unexpected request: ${request.method()} ${url.origin}${url.pathname}`)
    return route.abort()
  }
  return route.continue()
})
const sessionScope = () => {
  const query = new URL(page.url()).searchParams
  assert.equal(query.get('workspace'), 'tenant-a')
  assert.equal(query.get('session'), seed.session_id)
}
try {
  const response = await fetch(`${seed.api}/api/v2/overview?session_id=${seed.session_id}`, { headers: { 'X-Workspace-Id': 'tenant-a' } })
  assert.equal(response.status, 200)
  const expected = (await response.json()).performance
  assert.equal(expected.metrics.closed_trade_count, seed.analytics.count)
  await page.goto(`${seed.ui}/?workspace=tenant-a`)
  await page.getByText('Bộ lọc và thống kê chi tiết', { exact: true }).click()
  await page.getByLabel('Phiên replay', { exact: true }).selectOption(seed.session_id)
  await page.waitForFunction(count => document.querySelector('[data-testid="dashboard-performance"] .fx-dashboard-metric strong')?.textContent === String(count), seed.analytics.count)
  assert.equal(new URL(page.url()).searchParams.get('dashboard_session'), seed.session_id)
  await page.locator('details.fx-dashboard-provenance summary').click()
  await page.locator('details.fx-dashboard-provenance a').click()
  await page.getByTestId('analytics-workspace').waitFor()
  sessionScope()
  await page.locator('.as-ledger-section').getByRole('heading', { name: `${seed.analytics.count} trade đóng`, exact: true }).waitFor()
  report.checks.push('Dashboard filtered totals match persisted analytics; drilldown retains workspace and session')

  await page.locator('.fx-subnav').getByRole('link', { name: 'Sessions', exact: true }).click()
  await page.getByTestId('replay-session-picker').waitFor()
  sessionScope()
  assert.equal(await page.getByLabel('Chọn phiên replay', { exact: true }).inputValue(), seed.session_id)
  await page.getByRole('link', { name: 'Tiếp tục trên chart →', exact: true }).click()
  const chart = page.getByTestId('replay-chart')
  await page.waitForFunction(() => Number(document.querySelector('[data-testid="replay-chart"]')?.dataset.visibleRowCount) > 0)
  sessionScope()
  assert.equal(new URL(page.url()).searchParams.get('surface'), 'workspace')
  assert.ok((await page.getByTestId('fxreplay-shell').getAttribute('class')).includes('is-chart-workspace'))
  const visibleCount = await chart.getAttribute('data-visible-row-count')
  await page.reload()
  await page.waitForFunction(count => document.querySelector('[data-testid="replay-chart"]')?.dataset.visibleRowCount === count, visibleCount)
  report.checks.push('Sessions selects the same persisted record; chart opens and reloads at its persisted cursor')
  await page.screenshot({ path: path.join(out, 'journey-chart.png'), fullPage: true })

  await page.getByRole('link', { name: 'Quay lại Sessions', exact: true }).click()
  await page.getByTestId('replay-session-picker').waitFor()
  sessionScope()
  await page.getByRole('link', { name: 'Xem Trades', exact: true }).click()
  await page.getByTestId('trade-session-picker').waitFor()
  sessionScope()
  await page.locator('.as-ledger-section').getByRole('heading', { name: `${seed.analytics.count} trade đóng`, exact: true }).waitFor()
  assert.equal(await page.locator('.as-ledger-section tbody tr').count(), 50)
  await page.locator('.fx-subnav').getByRole('link', { name: 'Analytics', exact: true }).click()
  await page.getByTestId('analytics-session-picker').waitFor()
  sessionScope()
  await page.locator('.as-ledger-section').getByRole('heading', { name: `${seed.analytics.count} trade đóng`, exact: true }).waitFor()
  await page.screenshot({ path: path.join(out, 'journey-analytics.png'), fullPage: true })
  report.checks.push('Chart return, Trades and Analytics preserve selection and agree on the persisted 60-trade ledger')
  await page.goto(`${seed.ui}/?view=settings&workspace=tenant-a`)
  const shell = page.getByTestId('fxreplay-shell')
  const themeSelect = page.getByRole('combobox', { name: 'Chế độ màu', exact: true })
  const languageSelect = page.getByRole('combobox', { name: 'Ngôn ngữ điều hướng', exact: true })
  await themeSelect.selectOption('light')
  assert.equal(await shell.getAttribute('data-theme'), 'dark', 'editing a draft does not save it')
  await page.getByRole('button', { name: 'Hủy thay đổi', exact: true }).click()
  assert.equal(await themeSelect.inputValue(), 'dark')
  await themeSelect.selectOption('light')
  await languageSelect.selectOption('en')
  await page.getByRole('button', { name: 'Lưu giao diện', exact: true }).click()
  assert.match(await page.getByTestId('settings-appearance-status').innerText(), /Đã lưu/)
  assert.equal(await shell.getAttribute('data-theme'), 'light')
  assert.equal(await shell.getAttribute('lang'), 'en')
  await page.reload()
  await themeSelect.waitFor()
  assert.equal(await themeSelect.inputValue(), 'light')
  assert.equal(await languageSelect.inputValue(), 'en')
  const second = await context.newPage()
  second.on('pageerror', error => report.errors.push(String(error)))
  await second.goto(`${seed.ui}/?view=settings&workspace=tenant-a`)
  await second.getByTestId('theme-toggle').click()
  await page.waitForFunction(() => document.querySelector('[data-testid="fxreplay-shell"]').dataset.theme === 'dark')
  assert.equal(await themeSelect.inputValue(), 'dark')
  await second.getByTestId('language-toggle').click()
  await page.waitForFunction(() => document.querySelector('[data-testid="fxreplay-shell"]').lang === 'vi')
  assert.equal(await languageSelect.inputValue(), 'vi')
  await second.close()
  report.checks.push('Settings draft/cancel/save, reload persistence and real cross-tab storage events agree with the shell')
  await page.evaluate(() => {
    Storage.prototype.setItem = function () { throw new DOMException('QA blocked preference storage', 'QuotaExceededError') }
  })
  await themeSelect.selectOption('light')
  await page.getByRole('button', { name: 'Lưu giao diện', exact: true }).click()
  assert.match(await page.getByTestId('settings-appearance-status').innerText(), /chặn lưu/)
  assert.equal(await shell.getAttribute('data-theme'), 'light')
  assert.equal(await page.getByRole('button', { name: 'Lưu giao diện', exact: true }).isEnabled(), true)
  await page.reload()
  await themeSelect.waitFor()
  assert.equal(await themeSelect.inputValue(), 'dark')
  report.checks.push('blocked preference storage reports volatile application, allows retry and does not claim persistence')
  await page.waitForFunction(() => !document.querySelector('.settings-refresh')?.disabled)
  await page.setViewportSize({ width: 390, height: 844 })
  await page.screenshot({ path: path.join(out, 'journey-settings-390.png'), fullPage: true })
  assert.deepEqual(report.errors, [])
  report.status = 'PASS'
} catch (error) {
  report.status = 'FAIL'
  report.error = String(error.stack || error)
  await page.screenshot({ path: path.join(out, 'failure.png'), fullPage: true })
  process.exitCode = 1
} finally {
  await browser.close()
  await writeFile(path.join(out, 'report.json'), JSON.stringify(report, null, 2))
  console.log(JSON.stringify({ ...report, out }))
}
