import assert from 'node:assert/strict'
import { chromium } from '../../../web/node_modules/playwright/index.mjs'
import { readFile,writeFile,mkdir } from 'node:fs/promises'
import { createHash } from 'node:crypto'
import path from 'node:path'
const out=path.dirname(new URL(import.meta.url).pathname.replace(/^\/(\w:)/,'$1'));await mkdir(out,{recursive:true})
const files=['FxSelect.jsx','fx-select.css','page-layout.css'],pins=async()=>Promise.all(files.map(async f=>({file:f,sha256:createHash('sha256').update(await readFile('foundation_v2/web/src/'+f)).digest('hex')})))
const report={checks:[],failures:[],errors:[],blocked:[],geometry:[],accessibility:[],before:await pins()}
const b=await chromium.launch({headless:true,ignoreDefaultArgs:['--hide-scrollbars']}),c=await b.newContext(),p=await c.newPage()
await c.routeWebSocket('**/*',ws=>ws.close())
await c.route('**/*',r=>{const q=r.request(),u=new URL(q.url());if(u.origin!=='http://127.0.0.1:5180'||u.pathname.startsWith('/api/')||q.method()!=='GET'){report.blocked.push({method:q.method(),url:q.url()});return r.abort()}return r.continue()})
p.on('pageerror',e=>report.errors.push(e.message))
const axe=await readFile('../../.artifacts/wm-integration-quality-tools/node_modules/axe-core/axe.min.js','utf8')
const button=name=>p.getByRole('button',{name,exact:true})
const goto=async(view,theme,width)=>{await p.setViewportSize({width,height:width===360?700:987});await p.goto('http://127.0.0.1:5180/?workspace=tenant-a&demo=1&view='+view+'&area=testing&section='+(view==='overview'?'dashboard':'analytics')+'&select=1');await p.waitForLoadState('networkidle');if(await p.getByTestId('fxreplay-shell').getAttribute('data-theme')!==theme)await p.getByTestId('theme-toggle').click()}
const fit=async()=>{const menu=await p.locator('.fx-select-menu').boundingBox(),clip=await p.locator('.fx-content').evaluate(e=>({left:e.getBoundingClientRect().left,right:e.getBoundingClientRect().left+e.clientWidth}));assert.ok(menu.x>=clip.left-1&&menu.x+menu.width<=clip.right+1,'menu client edge clipping');assert.ok(menu.y>=-1&&menu.y+menu.height<=p.viewportSize().height+1,'vertical menu clipping')}
const geometry=async locator=>locator.evaluate(e=>{const box=e.getBoundingClientRect(),check=e.querySelector('.fx-select-checkbox'),text=[...e.childNodes].find(n=>n.nodeType===3&&n.textContent.trim())||[...e.children].find(n=>!n.classList.contains('fx-select-checkbox'));const range=document.createRange();range.selectNodeContents(text);return {box:box.toJSON(),check:check?.getBoundingClientRect().toJSON(),label:range.getBoundingClientRect().toJSON(),checkCss:check?{width:getComputedStyle(check).width,height:getComputedStyle(check).height,font:getComputedStyle(check).fontSize,radius:getComputedStyle(check).borderRadius}:null,padding:getComputedStyle(e).padding,bg:getComputedStyle(e).backgroundColor,radius:getComputedStyle(e).borderRadius}})
const run=async(name,fn)=>{report.phase=name;try{await fn();report.checks.push({name,pass:true})}catch(e){report.failures.push({name,error:String(e),stack:e.stack});await p.screenshot({path:path.join(out,'failure-'+name+'.png')})}await writeFile(path.join(out,'progress.json'),JSON.stringify(report,null,2))}
try{
for(const theme of ['dark','light'])for(const width of [360,1710]){
 await run('Type-All-'+theme+'-'+width,async()=>{await goto('analytics',theme,width);await button('Type').click();const all=p.getByRole('checkbox',{name:'All',exact:true}),app=p.getByRole('option',{name:'App',exact:true}),prop=p.getByRole('option',{name:'Prop Firm',exact:true});assert.equal(await all.getAttribute('aria-checked'),'true');assert.equal(await all.locator('.fx-select-checkbox').innerText(),'✓');assert.equal(await all.locator('input').count(),0);const rows=await Promise.all([all,app,prop].map(geometry));report.geometry.push({phase:report.phase,rows});for(const row of rows.slice(1)){assert.equal(row.check.width,rows[0].check.width);assert.equal(row.check.height,rows[0].check.height);assert.deepEqual(row.checkCss,rows[0].checkCss);assert.ok(Math.abs(row.check.x-rows[0].check.x)<=1,'checkbox column misaligned');assert.ok(Math.abs(row.label.x-rows[0].label.x)<=1,'All label column misaligned')}await fit();await all.click();assert.equal(await all.getAttribute('aria-checked'),'false');assert.equal(await app.getAttribute('aria-selected'),'false');assert.equal(await prop.getAttribute('aria-selected'),'false');await app.click();assert.equal(await all.getAttribute('aria-checked'),'mixed');assert.equal(await all.locator('.fx-select-checkbox').innerText(),'−');await all.press('Space');assert.equal(await all.getAttribute('aria-checked'),'true');assert.equal(await prop.getAttribute('aria-selected'),'true');assert.ok(await p.getByRole('option',{name:/^Battles/}).isDisabled());await all.press('Enter');assert.equal(await all.getAttribute('aria-checked'),'false');await all.press('Space');await all.hover();await p.waitForTimeout(200);const allHover=await geometry(all);await app.hover();await p.waitForTimeout(200);const appHover=await geometry(app);report.geometry.push({phase:report.phase,allHover,appHover});assert.equal(allHover.bg,appHover.bg,'All hover differs from option hover');await all.hover();await p.waitForTimeout(200);await p.screenshot({path:path.join(out,report.phase+'.png')});if(width===1710){await p.evaluate(axe);const result=await p.evaluate(()=>window.axe.run({include:['.fx-select-menu']},{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21aa']}}));report.accessibility.push({phase:report.phase,violations:result.violations});assert.deepEqual(result.violations,[])}await p.keyboard.press('Escape');assert.equal(await button('Type').getAttribute('aria-expanded'),'false')})
 await run('Sort-Oldest-hover-'+theme+'-'+width,async()=>{await goto('overview',theme,width);await button('Sắp xếp phiên').click();const list=p.getByRole('listbox',{name:'Sắp xếp phiên',exact:true}),option=p.getByRole('option',{name:'Oldest to newest',exact:true});const state=await list.evaluate(e=>({offset:e.offsetWidth,client:e.clientWidth,height:e.clientHeight,scroll:e.scrollHeight,padding:getComputedStyle(e).padding}));assert.ok(state.scroll<=state.height,'short list unexpectedly scrollable');assert.equal(state.offset-state.client,0,'short list reserved native gutter');await p.mouse.move(10,10);await p.waitForTimeout(200);const before=await geometry(option);await option.hover();await p.waitForTimeout(200);const after=await geometry(option),listBox=await list.boundingBox();const left=after.box.x-listBox.x,right=listBox.x+listBox.width-after.box.x-after.box.width;report.geometry.push({phase:report.phase,list:state,row:after,insets:{left,right}});assert.ok(Math.abs(left-right)<=1,'asymmetric hover');assert.ok(left>=2&&right>=2,'hover clipped at list edge');assert.notEqual(before.bg,after.bg,'hover background missing');assert.equal(after.radius,'6px');await fit();await p.locator('.fx-select-menu').screenshot({path:path.join(out,report.phase+'.png')});await option.click();assert.match(await button('Sắp xếp phiên').innerText(),/Oldest to newest/);await button('Sắp xếp phiên').click();await p.keyboard.press('Home');assert.ok(await p.getByRole('option',{name:'Newest to oldest',exact:true}).evaluate(e=>e===document.activeElement));await p.keyboard.press('Escape')})
}
for(const theme of ['dark','light'])await run('Timezone-native-track-thumb-'+theme,async()=>{await goto('analytics',theme,1710);await button('Timezone').click();const list=p.getByRole('listbox',{name:'Timezone',exact:true}),bounds=await list.boundingBox(),state=await list.evaluate(e=>({gutter:e.offsetWidth-e.clientWidth,height:e.clientHeight,full:e.scrollHeight,top:e.scrollTop}));assert.ok(state.gutter>2&&state.full>state.height);await p.mouse.click(bounds.x+bounds.width-3,bounds.y+bounds.height*.65);await p.waitForTimeout(500);assert.ok(await list.isVisible());const scrolled=await list.evaluate(e=>e.scrollTop);assert.ok(scrolled>state.top);const thumb=Math.max(18,state.height*state.height/state.full),thumbY=bounds.y+scrolled/(state.full-state.height)*(state.height-thumb)+thumb/2;await p.mouse.move(bounds.x+bounds.width-3,thumbY);await p.mouse.down();await p.mouse.move(bounds.x+bounds.width-3,thumbY+40,{steps:5});await p.mouse.up();await p.waitForTimeout(300);const after=await list.evaluate(e=>e.scrollTop);assert.ok(await list.isVisible());assert.ok(after!==scrolled);await fit();report.geometry.push({phase:report.phase,...state,scrolled,after});await p.screenshot({path:path.join(out,report.phase+'.png')});await p.keyboard.press('Escape')})
report.after=await pins();report.sourceUnchanged=JSON.stringify(report.before)===JSON.stringify(report.after);assert.deepEqual(report.errors,[]);assert.deepEqual(report.blocked,[]);assert.deepEqual(report.failures,[]);assert.ok(report.sourceUnchanged);report.pass=true
}catch(e){report.failure=String(e);process.exitCode=1}finally{await b.close();await writeFile(path.join(out,'report.json'),JSON.stringify(report,null,2));console.log(JSON.stringify({pass:report.pass,checks:report.checks.length,failures:report.failures.map(f=>({name:f.name,error:f.error})),sourceUnchanged:report.sourceUnchanged,errors:report.errors,blocked:report.blocked}))}
