import assert from 'node:assert/strict'
import {chromium} from '../../../web/node_modules/playwright/index.mjs'
import {readFile,writeFile} from 'node:fs/promises'
import {createHash} from 'node:crypto'
const out='foundation_v2/evidence/icons-terminology-20261006/independent/final/',files=['TestingIcon.jsx','DashboardPerformance.jsx','SessionPicker.jsx','DemoPreview.jsx','FxTradeLedger.jsx','SessionPerformance.jsx','FxAnalytics.jsx','testing-copy.json','page-layout.css','dashboard.css','testing-standard.css','session-performance.css'],pins=()=>Promise.all(files.map(async file=>({file,sha256:createHash('sha256').update(await readFile('foundation_v2/web/src/'+file)).digest('hex')})))
const report={cases:[],failures:[],errors:[],blocked:[],states:[],before:await pins()},b=await chromium.launch({headless:true,ignoreDefaultArgs:['--hide-scrollbars']})
const journal='<rect x="4" y="3" width="16" height="18" rx="2"></rect><path d="M8 3v18M11 8h6M11 12h6"></path>'
async function glyph(loc,content){assert.ok(await loc.count());const v=await loc.evaluate(e=>{const box=e.getBoundingClientRect();return {width:box.width,height:box.height,hidden:e.getAttribute('aria-hidden'),html:e.innerHTML}});assert.equal(v.width,16);assert.equal(v.height,16);assert.equal(v.hidden,'true');assert.equal(v.html,content);return v}
async function run(name,theme,language,width,demo,route,fixture=false){report.phase=name;const c=await b.newContext({viewport:{width,height:987}}),p=await c.newPage();await p.addInitScript(({theme,language})=>{localStorage.setItem('tw-theme',theme);localStorage.setItem('tw-language',language)}, {theme,language});await c.routeWebSocket('**/*',ws=>ws.close());await c.route('**/*',async r=>{const q=r.request(),u=new URL(q.url());if(!['http://127.0.0.1:5180','http://127.0.0.1:8010'].includes(u.origin)||!['GET','HEAD','OPTIONS'].includes(q.method())){report.blocked.push({name,url:q.url(),method:q.method()});return r.abort()}if(fixture&&u.pathname==='/api/v2/overview'){const response=await r.fetch(),body=await response.json();body.performance.status='partial';body.performance.scope.session_count=3;body.performance.scope.readable_session_count=1;return r.fulfill({response,json:body})}return r.continue()});p.on('pageerror',e=>report.errors.push({name,error:String(e)}));try{await p.goto(`http://127.0.0.1:5180/?workspace=tenant-a&view=${{dashboard:'overview',sessions:'replay',trades:'trade'}[route]}&area=testing&section=${route}&select=1${demo?'&demo=1':''}`);await p.waitForLoadState('networkidle');assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth-innerWidth)<=1);const state={name,lang:await p.getByTestId('fxreplay-shell').getAttribute('lang'),theme:await p.getByTestId('fxreplay-shell').getAttribute('data-theme')};assert.equal(state.lang,language);assert.equal(state.theme,theme)
if(route==='dashboard'){assert.equal(await p.locator('.fx-dashboard-scope-info,.fx-dashboard-scope-tooltip').count(),0);state.description=await p.locator('.fx-dashboard-results').first().getAttribute('aria-description');if(fixture)assert.ok(state.description?.includes('1/3'));const actions=await p.locator('.fx-dashboard-quick-actions').innerText();assert.ok(actions.includes(language==='vi'?'Thử thách cấp vốn':'Prop firm session'));assert.ok(actions.includes(language==='vi'?'mô phỏng':'simulated'));const perf=p.locator('.fx-dashboard-performance-filters>.fx-select').first();state.perfLabel=await perf.innerText();assert.ok(state.perfLabel.includes(language==='vi'?'Kiểm thử lịch sử':'Backtesting'));await perf.locator('button').first().click();state.options=await p.getByRole('option').allTextContents();assert.ok(state.options.some(v=>v.includes(language==='vi'?'Thử thách cấp vốn':'Prop firm')));await p.keyboard.press('Escape')}
if(route==='sessions'){const control=p.locator('.fxr-session-actions>.fxr-button-primary').first();state.newIcon=await glyph(control.locator('svg'),'<path d="M12 5v14M5 12h14"></path>');state.newText=await control.innerText();assert.equal(state.newText,language==='vi'?'Phiên mới':'New session');assert.equal(await control.evaluate(e=>e.firstElementChild?.tagName.toLowerCase()),'svg');const ji=p.locator('.fxs-journal svg');if(await ji.count())state.journal=await glyph(ji,journal);const analytics=p.locator('.fxs-analytics-button button');await analytics.click();assert.ok((await p.getByRole('option').allTextContents()).some(t=>t.includes(language==='vi'?'Thử thách cấp vốn':'Prop firm')));await p.keyboard.press('Escape')}
if(route==='trades'){const divider=p.locator('.fxa-filter-divider');assert.equal(await divider.count(),1);state.divider=await divider.evaluate(e=>{const r=e.getBoundingClientRect();return {w:r.width,h:r.height,hidden:e.getAttribute('aria-hidden'),before:e.previousElementSibling?.className,after:e.nextElementSibling?.className}});assert.equal(state.divider.w,1);assert.equal(state.divider.h,18);assert.equal(state.divider.hidden,'true');assert.equal(state.divider.after,'fxa-filter-label');const detail=p.locator('.fxa-detail-button').first();state.rows=await p.locator('.fxa-detail-button').count();if(state.rows){state.journal=await glyph(detail.locator('svg'),journal);await detail.click();const dialog=p.getByRole('dialog');await dialog.waitFor();assert.ok((await dialog.innerText()).length>20);await p.screenshot({path:out+name+'-inspector.png'});await p.keyboard.press('Escape');assert.equal(await dialog.count(),0)}else assert.ok(!demo,'demo oracle must have trade rows')}
await p.mouse.move(1,1);await p.screenshot({path:out+name+'.png'});report.states.push(state);report.cases.push({name,pass:true})}catch(e){report.failures.push({name,error:String(e),stack:e.stack});await p.screenshot({path:out+name+'-failure.png'})}await c.close();await writeFile(out+'progress.json',JSON.stringify(report,null,2))}
try{for(const theme of ['dark','light'])for(const language of ['vi','en'])for(const width of [1710,360])for(const demo of [false,true])for(const route of ['sessions'])await run(`${demo?'demo':'actual'}-${route}-${theme}-${language}-${width}`,theme,language,width,demo,route);for(const language of ['vi','en'])await run(`fixture-partial-dark-${language}-1710`,'dark',language,1710,false,'dashboard',true);report.after=await pins();report.sourceUnchanged=JSON.stringify(report.before)===JSON.stringify(report.after);assert.equal(report.cases.length,18);assert.equal(report.failures.length,0);assert.equal(report.errors.length,0);assert.equal(report.blocked.length,0);assert.ok(report.sourceUnchanged);report.pass=true}catch(e){report.failure=String(e);process.exitCode=1}finally{await b.close();await writeFile(out+'report.json',JSON.stringify(report,null,2));console.log(JSON.stringify({pass:report.pass,cases:report.cases.length,failures:report.failures,errors:report.errors,blocked:report.blocked,sourceUnchanged:report.sourceUnchanged}))}
