import assert from 'node:assert/strict'
import {chromium} from '../../../web/node_modules/playwright/index.mjs'
import {mkdir,writeFile} from 'node:fs/promises'
import {fileURLToPath} from 'node:url'
const out=new URL('./',import.meta.url);await mkdir(out,{recursive:true});const browser=await chromium.launch({headless:true,ignoreDefaultArgs:['--hide-scrollbars']});const session='476f4b498e1a49ed9d48a75719f4d270',url=`http://127.0.0.1:5180/?workspace=tenant-a&view=replay&session=${session}&surface=workspace&cursor=500`;const report={scope:'Actual native header GET, local API actions; activity fixture only',cases:[],errors:[],blocked:[],vendorBlocked:[],axe:[]};let latest
try{for(const[width,theme,language]of[[1710,'dark','vi'],[1710,'light','en'],[768,'dark','en'],[360,'light','vi'],[1300,'dark','vi']]){
 const ctx=await browser.newContext({viewport:{width,height:987}});await ctx.addInitScript(({theme,language})=>{localStorage.setItem('tw-theme',theme);localStorage.setItem('tw-language',language)},{theme,language});await ctx.routeWebSocket('**/*',s=>s.close());await ctx.route('**/*',async route=>{const r=route.request(),u=new URL(r.url());if(r.method()==='POST'&&u.pathname===`/api/v2/replay/sessions/${session}/activity`){const e=r.postDataJSON();return route.fulfill({json:{schema_version:'replay-activity-v1',session_id:session,event_id:e.event_id,accepted_seconds:(Date.parse(e.ended_at_utc)-Date.parse(e.started_at_utc))/1000,fixture:'native-independent'}})}if(['GET','HEAD','OPTIONS'].includes(r.method())&&['http://127.0.0.1:5180','http://127.0.0.1:8010'].includes(u.origin)){if(u.pathname.endsWith('charting_library.standalone.js')){const response=await route.fetch();return route.fulfill({response,body:await response.text()+`;window.TradingView.widget=new Proxy(window.TradingView.widget,{construct(Target,args){const item=new Target(...args);window.__qaWidget=item;window.__qaOptions=args[0];return item}});`})}return route.continue()}if(r.url()==='http://www.google-analytics.com/analytics.js')report.vendorBlocked.push(r.url());else report.blocked.push({method:r.method(),url:r.url()});return route.abort()});const p=await ctx.newPage();latest=p;p.setDefaultTimeout(12000);p.on('pageerror',e=>report.errors.push(String(e)));const t=(vi,en)=>language==='vi'?vi:en;console.log('case',width,theme,language);await p.goto(url,{waitUntil:'networkidle'});await p.locator('[data-chart-status=ready]').waitFor();const f=await(await p.locator('.advanced-chart-host iframe').elementHandle()).contentFrame();await f.getByTestId('legacy-native-market').waitFor()
 const canonical=()=>p.evaluate(()=>{const e=document.querySelector('[data-chart-status=ready]');return{cutoff:e.dataset.cutoff,rows:e.dataset.visibleRowCount,symbol:window.__qaWidget.activeChart().symbol()}}),before=await canonical(),checks=[];assert.equal(await p.locator('[data-testid=legacy-chart-header]').count(),0);assert.equal(await p.evaluate(()=>window.__qaOptions.disabled_features.includes('header_widget')),false);for(const id of['header-toolbar-intervals','header-toolbar-chart-styles','header-toolbar-indicators','header-toolbar-undo-redo'])assert.equal(await f.locator(`#${id}`).count(),1);assert.equal(await f.locator('.legacy-market-host,.legacy-layout-host,.legacy-session-host,.legacy-search-host,.legacy-tools-host').count(),5);checks.push('library-owned header controls,5official extensions, no recreated row')
 const open=async label=>{const direct=f.getByRole('button',{name:label,exact:true});if(await direct.isVisible())await direct.click();else{await f.locator('.chart-header-overflow').click();await p.locator('.legacy-native-menu').getByRole('button',{name:label,exact:true}).click()}}
 for(const[tool,label]of[['compare',t('So sánh mã','Compare symbols')],['layout','New Layout'],['editor','Editor'],['mentor','AI Mentor'],['search',t('Tìm công cụ','Quick Search')]]){await open(label);const panel=p.getByTestId(`chart-preview-${tool}`);await panel.waitFor();const dock=await p.locator('.replay-side').boundingBox(),head=await f.locator('.layout__area--top').boundingBox();assert.ok(dock.y>=head.y+head.height,JSON.stringify({dock,head}));await p.keyboard.press('Escape');await panel.waitFor({state:'hidden'});const focused=await p.evaluate(()=>{let e=document.activeElement;if(e?.tagName==='IFRAME')e=e.contentDocument.activeElement;return{tag:e?.tagName,width:e?.getBoundingClientRect().width}});assert.equal(focused.tag,'BUTTON');assert.ok(focused.width>0);assert.deepEqual(await canonical(),before)}checks.push('FX previews/dock below native header/keyboard close focus')
 if(width===768){await f.locator('.chart-header-overflow').click();await p.locator('.legacy-native-menu').waitFor();await p.setViewportSize({width:1710,height:987});await p.locator('.legacy-native-menu').waitFor({state:'hidden'});const focus=await f.evaluate(()=>({tag:document.activeElement.tagName,width:document.activeElement.getBoundingClientRect().width}));assert.equal(focus.tag,'BUTTON');assert.ok(focus.width>0);await p.setViewportSize({width,height:987});checks.push('compact menu768→1710 resize returns visible focus')}
 const extensionBounds=await f.evaluate(()=>[...document.querySelectorAll('.legacy-native-extension button,.legacy-native-extension a')].filter(e=>e.getBoundingClientRect().width>0).map(e=>{const r=e.getBoundingClientRect(),hit=document.elementFromPoint(r.x+r.width/2,r.y+r.height/2);return{label:e.getAttribute('aria-label')||e.textContent,left:r.left,right:r.right,width:innerWidth,hit:e===hit||e.contains(hit)}}).filter(e=>e.left<0||e.right>e.width+1||!e.hit));assert.deepEqual(extensionBounds,[])
 const intervals=f.locator('#header-toolbar-intervals');if(await intervals.locator('[data-value="5"]').isVisible())await intervals.locator('[data-value="5"]').click();else{await intervals.locator('> [class*=menu]').click();await f.locator('[data-value="5"][class*=item-]:visible').click()}await p.waitForFunction(()=>window.__qaWidget.activeChart().resolution()==='5'&&document.querySelector('.legacy-replay-toolbar select').value==='5');assert.deepEqual(await canonical(),before);checks.push('actual native interval selector5m/replaybar sync preserves causal prefix')
 await f.locator('[data-name="header-toolbar-properties"]').click();await f.locator('[data-name="series-properties-dialog"]').waitFor();await f.locator('[data-name="series-properties-dialog"] [data-name="close"]').click();checks.push('actual native settings reachable')
 if(width<=768){await f.locator('.chart-header-overflow').click();const menu=p.locator('.legacy-native-menu');for(const label of[t('Chỉ báo','Indicators'),t('Hoàn tác','Undo'),t('Làm lại','Redo')])assert.equal(await menu.getByRole('button',{name:label,exact:true}).count(),1);await menu.getByRole('button',{name:t('Chỉ báo','Indicators'),exact:true}).click();const indicator=f.locator('[data-name="indicators-dialog"]');await indicator.waitFor();await indicator.locator('[data-name="close"]').click();await indicator.waitFor({state:'hidden'});checks.push('compact overflow Indicators native dialog + Undo/Redo present')}
 await p.locator('.legacy-replay-toolbar select').selectOption('15');await p.waitForFunction(()=>window.__qaWidget.activeChart().resolution()==='15'&&document.querySelector('.legacy-replay-toolbar select').value==='15');assert.deepEqual(await canonical(),before);assert.equal(await p.locator('.legacy-sync-toggle input').isDisabled(),true)
 const layout=await p.evaluate(()=>{const bar=document.querySelector('.legacy-replay-toolbar'),content=bar.querySelector('.chart-float-content'),q=document.querySelector('.legacy-quick-actions'),r=bar.getBoundingClientRect(),qr=q?.getBoundingClientRect(),f=document.querySelector('.advanced-chart-host iframe').getBoundingClientRect();return{overflow:document.documentElement.scrollWidth-innerWidth,replay:{client:bar.clientWidth,scroll:bar.scrollWidth,contentClient:content.clientWidth,contentScroll:content.scrollWidth},overlap:qr?.width>0&&r.x<qr.right&&r.right>qr.x&&r.y<qr.bottom&&r.bottom>qr.y,iframe:f.toJSON(),redundant:document.querySelectorAll('.chart-trading-bar .chart-sim-tag').length,scale:[...document.querySelector('.advanced-chart-host iframe').contentDocument.querySelectorAll('.price-axis-container')].map(e=>e.getBoundingClientRect().toJSON()).filter(r=>r.width>0)}});assert.equal(layout.overflow,0);assert.ok(layout.replay.scroll<=layout.replay.client);assert.ok(layout.replay.contentScroll<=layout.replay.contentClient);assert.equal(Boolean(layout.overlap),false);assert.equal(layout.redundant,0);assert.equal(await p.locator('.chart-trading-actions > button').count(),3);assert.ok(layout.scale.length);assert.ok(layout.scale.every(r=>r.right<=layout.iframe.width+1));checks.push('replaybar no overflow/quickbar overlap, footer3buttons/noSIM, price axis fits')
 await f.waitForFunction(()=>[...document.querySelectorAll('[data-name=legend-source-title]')].some(e=>e.textContent.trim()==='15'));await f.addScriptTag({path:'../../.artifacts/wm-integration-quality-tools/node_modules/axe-core/axe.min.js'});const axe=await f.evaluate(()=>window.axe.run({include:[['.legacy-native-extension']]},{rules:{region:{enabled:false}}}));assert.equal(axe.violations.length,0);report.axe.push({width,theme,language,violations:axe.violations.map(v=>v.id)});await p.screenshot({path:fileURLToPath(new URL(`actual-${theme}-${language}-${width}.png`,out))});report.cases.push({width,theme,language,checks,layout,pass:true});await ctx.close();await writeFile(new URL('progress.json',out),JSON.stringify(report,null,2))
}report.pass=!report.errors.length&&!report.blocked.length}catch(e){report.pass=false;report.failure=String(e);await latest?.screenshot({path:fileURLToPath(new URL('failure.png',out))}).catch(()=>{});process.exitCode=1}finally{await browser.close();await writeFile(new URL('report.json',out),JSON.stringify(report,null,2));console.log(JSON.stringify({pass:report.pass,cases:report.cases.length,errors:report.errors,failure:report.failure}))}
