import assert from 'node:assert/strict'
import { chromium } from '../../web/node_modules/playwright/index.mjs'
import { readFile,writeFile,mkdir } from 'node:fs/promises'
import { createHash } from 'node:crypto'
const out='foundation_v2/evidence/testing-tabs-20261006/';await mkdir(out,{recursive:true})
const files=['FxReplayShell.jsx','fx-shell-story.css','page-layout.css','testing-standard.css','component-interactions.css','visual-polish.css'],pins=()=>Promise.all(files.map(async file=>({file,sha256:createHash('sha256').update(await readFile('foundation_v2/web/src/'+file)).digest('hex')})))
const report={cases:[],failures:[],errors:[],blocked:[],requests:[],responses:[],before:await pins()},b=await chromium.launch({headless:true,ignoreDefaultArgs:['--hide-scrollbars']}),c=await b.newContext(),p=await c.newPage()
await c.routeWebSocket('**/*',ws=>ws.close());await c.route('**/*',r=>{const q=r.request(),u=new URL(q.url());if(!['http://127.0.0.1:5180','http://127.0.0.1:8010'].includes(u.origin)||!['GET','HEAD','OPTIONS'].includes(q.method())){report.blocked.push({phase:report.phase,url:u.href,method:q.method()});return r.abort()}if(u.pathname.startsWith('/api/'))report.requests.push({phase:report.phase,path:u.pathname,method:q.method(),demo:new URL(q.frame().url()).searchParams.get('demo')});return r.continue()})
p.on('pageerror',e=>report.errors.push({phase:report.phase,error:e.message}));p.on('response',r=>{if(new URL(r.url()).pathname.startsWith('/api/'))report.responses.push({phase:report.phase,url:r.url(),status:r.status()})})
const neutral=v=>{const a=v.match(/[\d.]+/g).map(Number);return a[0]===a[1]&&a[1]===a[2]}
const style=loc=>loc.evaluate(e=>{const s=getComputedStyle(e),after=getComputedStyle(e,'::after'),r=e.getBoundingClientRect();return {text:e.innerText,color:s.color,bg:s.backgroundColor,border:s.borderWidth,outline:s.outlineStyle,outlineWidth:s.outlineWidth,outlineColor:s.outlineColor,radius:s.borderRadius,height:r.height,x:r.x,right:r.right,underline:{content:after.content,height:after.height,color:after.backgroundColor},icon:e.querySelector('svg')?.getBoundingClientRect().toJSON()}})
const snapshot=()=>p.screenshot({path:out+report.phase+'.png'})
let catalog
try{
report.phase='catalog-read';await p.goto('http://127.0.0.1:5180/?workspace=tenant-a&area=testing&view=overview&section=dashboard');await p.waitForLoadState('networkidle');catalog=await p.evaluate(async()=>{const r=await fetch('/api/v2/replay/sessions',{headers:{'X-Workspace-Id':'tenant-a'}});return {status:r.status,payload:await r.json()}});assert.equal(catalog.status,200);assert.ok(catalog.payload.items.length>0);report.catalog={status:catalog.status,count:catalog.payload.items.length,selected:catalog.payload.items[0].record_id};const session=catalog.payload.items[0].record_id
for(const demo of [true,false])for(const theme of ['dark','light'])for(const lang of ['vi','en'])for(const width of [1320,768,360])for(const route of ['sessions','analytics']){
report.phase=`${demo?'demo':'actual'}-${route}-${theme}-${lang}-${width}`;const entry={name:report.phase,states:[]}
try{await p.setViewportSize({width,height:987});await p.goto(`http://127.0.0.1:5180/?workspace=tenant-a&area=testing&view=${route==='sessions'?'replay':'analytics'}&section=${route}&select=1${demo?'&demo=1':`&session=${session}`}`);await p.waitForLoadState('networkidle');const shell=p.getByTestId('fxreplay-shell');if(await shell.getAttribute('data-theme')!==theme)await p.getByTestId('theme-toggle').click();if(await shell.getAttribute('lang')!==lang)await p.getByTestId('language-toggle').click();await p.waitForTimeout(160);assert.equal(await p.locator('.fx-content .wm-skeleton').count(),0);assert.equal(await p.locator('.fx-content [role=alert]').count(),0);assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth-innerWidth),0)
const parent=p.locator('.fx-subnav-primary>a[aria-current=page]');assert.equal(await parent.count(),1);await parent.scrollIntoViewIfNeeded();await p.mouse.move(1,1);const selected=await style(parent);assert.equal(selected.bg,'rgba(0, 0, 0, 0)');assert.equal(selected.height,52);assert.equal(selected.border,'0px');assert.equal(selected.underline.height,'2px');assert.equal(selected.underline.color,selected.color);assert.ok(neutral(selected.color));if(theme==='dark')assert.equal(selected.color,'rgb(255, 255, 255)');assert.equal(selected.icon.width,18);assert.equal(selected.icon.height,18);entry.states.push({kind:'parent-selected',...selected})
for(const link of await p.locator('.fx-subnav-primary>a').all()){await p.evaluate(()=>document.activeElement?.blur());await link.scrollIntoViewIfNeeded();await link.hover();await p.waitForTimeout(160);const hover=await style(link);assert.equal(hover.border,'0px');assert.equal(hover.outline,'none');assert.ok(neutral(hover.bg));if(theme==='dark')assert.equal(hover.color,'rgb(255, 255, 255)');entry.states.push({kind:'parent-hover',...hover})}
await p.keyboard.press('Tab');await parent.focus();await p.waitForTimeout(160);const focused=await style(parent);assert.ok(await parent.evaluate(e=>e.matches(':focus-visible')));assert.equal(focused.outline,'solid');assert.equal(focused.outlineWidth,'2px');assert.ok(neutral(focused.outlineColor));entry.states.push({kind:'keyboard-focus',...focused})
if(route==='analytics'){const child=p.locator('.fx-subsubnav'),border=await child.evaluate(e=>({left:getComputedStyle(e).borderLeftWidth,right:getComputedStyle(e).borderRightWidth}));assert.deepEqual(border,{left:'0px',right:'0px'});for(const source of ['sessions','prop']){const link=child.locator(`a[href*="analytics_source=${source}"]`);await link.scrollIntoViewIfNeeded();await link.click();await p.waitForLoadState('networkidle');await p.waitForTimeout(160);assert.equal(new URL(p.url()).searchParams.get('analytics_source'),source);assert.equal(await link.getAttribute('aria-current'),'page');await p.evaluate(()=>document.activeElement?.blur());await p.mouse.move(1,1);const childSelected=await style(link);assert.equal(childSelected.height,52);assert.equal(childSelected.bg,'rgba(0, 0, 0, 0)');assert.equal(childSelected.border,'0px');assert.equal(childSelected.underline.height,'2px');assert.equal(childSelected.underline.color,childSelected.color);if(theme==='dark')assert.equal(childSelected.color,'rgb(255, 255, 255)');await link.hover();await p.waitForTimeout(160);const hover=await style(link);assert.equal(hover.border,'0px');assert.equal(hover.outline,'none');assert.ok(neutral(hover.bg));if(theme==='dark')assert.equal(hover.color,'rgb(255, 255, 255)');await p.keyboard.press('Tab');await link.focus();assert.ok(await link.evaluate(e=>e.matches(':focus-visible')));assert.equal((await style(link)).outline,'solid');entry.states.push({kind:'child-'+source,selected:childSelected,hover})}}
const nav=p.locator('.fx-subnav-primary'),scroll=await nav.evaluate(e=>({client:e.clientWidth,scroll:e.scrollWidth,left:e.scrollLeft}));if(width===360){assert.ok(scroll.scroll>scroll.client);await nav.evaluate(e=>{e.scrollLeft=0});assert.equal(await nav.evaluate(e=>e.scrollLeft),0);await nav.evaluate(e=>{e.scrollLeft=e.scrollWidth});assert.ok(await nav.evaluate(e=>e.scrollLeft)>0);const last=nav.locator(':scope>a').last();await last.focus();const box=await last.boundingBox(),navBox=await nav.boundingBox();assert.ok(box.x>=navBox.x-1&&box.x+box.width<=navBox.x+navBox.width+1,'last nav inaccessible');entry.scroll=scroll}
if((width===1320&&lang==='en')||(width===360&&lang==='vi')){await parent.scrollIntoViewIfNeeded();await p.evaluate(()=>document.activeElement?.blur());await p.mouse.move(1,1);await snapshot()}
entry.pass=true;report.cases.push(entry)
}catch(e){entry.failure=String(e);report.failures.push(entry);await snapshot()}await writeFile(out+'progress.json',JSON.stringify(report,null,2))}
report.after=await pins();report.sourceUnchanged=JSON.stringify(report.before)===JSON.stringify(report.after);assert.equal(report.cases.length,48);assert.equal(report.failures.length,0);assert.equal(report.errors.length,0);assert.equal(report.blocked.length,0);assert.ok(report.responses.every(r=>r.status<400));assert.equal(report.requests.filter(r=>r.demo==='1').length,0);assert.ok(report.sourceUnchanged);report.pass=true
}catch(e){report.failure=String(e);process.exitCode=1}finally{await b.close();await writeFile(out+'report.json',JSON.stringify(report,null,2));console.log(JSON.stringify({pass:report.pass,cases:report.cases.length,failures:report.failures.map(f=>({name:f.name,error:f.failure})),errors:report.errors,blocked:report.blocked,sourceUnchanged:report.sourceUnchanged,failure:report.failure}))}
