import assert from 'node:assert/strict'
import {chromium} from '../../../web/node_modules/playwright/index.mjs'
import {readFile,writeFile} from 'node:fs/promises'
import {createHash} from 'node:crypto'
const out='foundation_v2/evidence/peach-actions-20261007/independent/',r={cases:[],failures:[],errors:[],blocked:[]},b=await chromium.launch({headless:true,ignoreDefaultArgs:['--hide-scrollbars']})
const final=JSON.parse(await readFile(out+'progress.json')),paths=final.before.map(x=>x.file),pins=()=>Promise.all(paths.map(async file=>({file,sha256:createHash('sha256').update(await readFile('foundation_v2/web/'+file)).digest('hex')})))
r.before=await pins()
for(const theme of ['dark','light'])for(const demo of [false,true])for(const mode of ['dashboard-delete-isolation','analytics-clear-draft']){const name=`${demo?'demo':'actual'}-${mode}-${theme}`,c=await b.newContext({viewport:{width:1440,height:987}}),p=await c.newPage(),state={name};await p.addInitScript(theme=>{localStorage.setItem('tw-theme',theme);localStorage.setItem('tw-language','vi')},theme);await c.routeWebSocket('**/*',w=>w.close());await c.route('**/*',q=>{const req=q.request(),u=new URL(req.url());if(!['http://127.0.0.1:5180','http://127.0.0.1:8010'].includes(u.origin)||!['GET','HEAD','OPTIONS'].includes(req.method())){r.blocked.push({name,method:req.method(),url:req.url()});return q.abort()}return q.continue()});p.on('pageerror',e=>r.errors.push({name,error:String(e)}));try{const query=new URLSearchParams({workspace:'tenant-a',view:mode.startsWith('dashboard')?'overview':'analytics',area:'testing',section:mode.startsWith('dashboard')?'dashboard':'analytics',select:'1'});if(demo)query.set('demo','1');if(mode.startsWith('analytics')&&!demo){for(const [k,v]of Object.entries({side:'buy',outcome:'loss',from:'2026-07-01',to:'2026-10-01',analytics_timezone:'Asia/Ho_Chi_Minh',analytics_hour:'6',analytics_reportKinds:'["app"]'}))query.set(k,v)}await p.goto('http://127.0.0.1:5180/?'+query);await p.waitForLoadState('networkidle');
if(mode.startsWith('dashboard')){const card=p.locator('.fx-dashboard-session-card').first(),expand=card.locator('.fx-dashboard-card-expand');await card.locator('.fx-dashboard-card-info').click();assert.equal(await expand.getAttribute('aria-expanded'),'true');const button=card.locator('button.is-danger');await button.focus();await p.keyboard.press('Enter');const dialog=p.getByRole('dialog');await dialog.waitFor();assert.equal(await expand.getAttribute('aria-expanded'),'true');state.cardBefore=await card.getAttribute('data-session-id');if(demo){const name=await card.locator('.fx-dashboard-card-info h3').evaluate(e=>e.firstChild.textContent);await dialog.locator('input').fill(name);const confirm=dialog.locator('.fxs-delete-confirm');assert.equal(await confirm.isDisabled(),false);state.confirmEnabled=true;state.confirmPaint=await confirm.evaluate(e=>({color:getComputedStyle(e).color,bg:getComputedStyle(e).backgroundColor}));assert.equal(state.confirmPaint.color,'rgb(255, 255, 255)')}await p.screenshot({path:out+name+'-dialog.png'});await dialog.getByRole('button',{name:'Hủy',exact:true}).click();assert.equal(await dialog.count(),0);assert.equal(await expand.getAttribute('aria-expanded'),'true');assert.equal(await card.getAttribute('data-session-id'),state.cardBefore);await p.addScriptTag({path:'../../.artifacts/wm-integration-quality-tools/node_modules/axe-core/axe.min.js'});state.axe=await p.evaluate(async()=>{const x=await axe.run(document,{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21aa']}});return x.violations.map(v=>({id:v.id,nodes:v.nodes.map(n=>n.target)}))});assert.equal(state.axe.length,0)}
else{const session=p.locator('.fxa-session-trigger');await session.waitFor();state.sessionBefore=await session.getAttribute('aria-label');if(demo){const side=p.locator('.fx-select-trigger[aria-label="Hướng lệnh"]');await side.click();await p.getByRole('option').filter({hasText:'Mua'}).click();await p.locator('.fxa-apply-button').click();await p.waitForLoadState('networkidle')}state.appliedChips=await p.locator('.fxa-filter-chip').allTextContents();assert.ok(state.appliedChips.length>2,'applied filter chips present');await session.click();const options=p.locator('.fxa-session-options button');state.sessionOptions=await options.count();if(state.sessionOptions>1){const current=await options.evaluateAll(es=>es.findIndex(e=>e.getAttribute('aria-pressed')==='true'));await options.nth(current===0?1:0).click()}else await p.keyboard.press('Escape');await p.locator('.fxa-clear-filters').click();await p.waitForLoadState('networkidle');assert.equal(await session.getAttribute('aria-label'),state.sessionBefore);state.afterChips=await p.locator('.fxa-filter-chip').allTextContents();assert.equal(state.afterChips.length,2);const url=new URL(p.url());if(!demo)for(const key of ['side','outcome','from','to','analytics_timezone','analytics_hour','analytics_reportKinds'])assert.equal(url.searchParams.has(key),false);for(const label of ['Hướng lệnh','Kết quả']){await p.locator(`.fx-select-trigger[aria-label="${label}"]`).click();const selected=p.locator('[role=option][aria-selected=true]');assert.match(await selected.innerText(),/Tất cả/);await p.keyboard.press('Escape')}await p.screenshot({path:out+name+'.png'})}
r.cases.push(state)}catch(e){r.failures.push({name,error:String(e),stack:e.stack,state});await p.screenshot({path:out+name+'-failure.png'})}await c.close()}
r.after=await pins();r.sourceUnchanged=JSON.stringify(r.before)===JSON.stringify(r.after);r.pass=r.cases.length===8&&!r.failures.length&&!r.errors.length&&!r.blocked.length&&r.sourceUnchanged;await b.close();await writeFile(out+'journeys-report.json',JSON.stringify(r,null,2));console.log(JSON.stringify(r));if(!r.pass)process.exitCode=1
