import assert from 'node:assert/strict'
import { chromium } from '../../../web/node_modules/playwright/index.mjs'
import { readFile, writeFile } from 'node:fs/promises'
import { createHash } from 'node:crypto'
const out='foundation_v2/evidence/peach-actions-20261007/independent/'
const files=['public/project-palette.css',...['AnalyticsFilterBar.jsx','DashboardSessionCard.jsx','DashboardSessions.jsx','FxAnalytics.jsx','SessionPerformance.jsx','TestingIcon.jsx','component-interactions.css','dashboard-session.css','dashboard.css','fx-analytics.css','fx-select.css','fx-shell-story.css','session-performance.css','testing-copy.json','testing-standard.css','analytics-story.css','journal-analytics.css','research-story.css','research-data.css'].map(x=>'src/'+x)]
const pins=()=>Promise.all(files.map(async file=>({file,sha256:createHash('sha256').update(await readFile('foundation_v2/web/'+file)).digest('hex')})))
const report={cases:[],failures:[],errors:[],blocked:[],states:[],before:await pins()}
const browser=await chromium.launch({headless:true,ignoreDefaultArgs:['--hide-scrollbars']})
const rgb=hex=>'rgb('+hex.slice(1).match(/../g).map(x=>parseInt(x,16)).join(', ')+')'
const palettes={dark:{action:'#D6A07B',hover:'#E4B18D',on:'#171C20',highlight:'#D6A07B',blue:'#78BDE3',primary:'#8FAFC1'},light:{action:'#9A5934',hover:'#844A2A',on:'#FFFFFF',highlight:'#8F532F',blue:'#2D7195',primary:'#3E6275'}}
function contrast(a,b){const l=x=>{const v=x.match(/\d+/g).slice(0,3).map(Number).map(n=>{n/=255;return n<=.04045?n/12.92:((n+.055)/1.055)**2.4});return .2126*v[0]+.7152*v[1]+.0722*v[2]};return (Math.max(l(a),l(b))+.05)/(Math.min(l(a),l(b))+.05)}
const paint=loc=>loc.evaluate(e=>{const s=getComputedStyle(e),r=e.getBoundingClientRect();return {color:s.color,bg:s.backgroundColor,stroke:s.stroke,fill:s.fill,border:s.borderBottomColor,borderWidth:s.borderBottomWidth,radius:s.borderRadius,outline:s.outlineWidth,outlineStyle:s.outlineStyle,x:r.x,y:r.y,w:r.width,h:r.height}})
async function popup(p,control,name,state){if(!await control.count()||await control.isDisabled())return;await control.click();const menu=p.locator('.fx-select-menu,.fxa-session-menu').last();const input=menu.locator('input[type=search]');await input.waitFor();state.popups??={};state.popups[name]=await paint(input);assert.equal(state.popups[name].bg,'rgba(0, 0, 0, 0)');assert.equal(state.popups[name].radius,'0px');assert.equal(state.popups[name].outlineStyle,'none');const box=await menu.boundingBox();assert.ok(box.x>=-1&&box.x+box.width<=p.viewportSize().width+1,'popup horizontal clip');await input.fill('no-match-independent-review');assert.ok((await menu.innerText()).match(/Không|No /));await input.fill('');await p.screenshot({path:out+state.name+'-'+name+'.png'});await p.keyboard.press('Escape');assert.equal(await menu.count(),0);assert.equal(await control.evaluate(e=>document.activeElement===e),true)}
async function run(route,theme,width,demo,language='vi'){const name=`${demo?'demo':'actual'}-${route}-${theme}-${language}-${width}`;if(process.env.REVIEW_AFFECTED&&!(route==='dashboard'||route==='sessions'&&width===360))return;report.phase=name;const c=await browser.newContext({viewport:{width,height:987}}),p=await c.newPage(),colors=palettes[theme],state={name};await p.addInitScript(({theme,language})=>{localStorage.setItem('tw-theme',theme);localStorage.setItem('tw-language',language)},{theme,language});await c.routeWebSocket('**/*',ws=>ws.close());await c.route('**/*',r=>{const q=r.request(),u=new URL(q.url());if(!['http://127.0.0.1:5180','http://127.0.0.1:8010'].includes(u.origin)||!['GET','HEAD','OPTIONS'].includes(q.method())){report.blocked.push({name,url:q.url(),method:q.method()});return r.abort()}return r.continue()});p.on('pageerror',e=>report.errors.push({name,error:String(e)}));try{
const view={dashboard:'overview',sessions:'replay',trades:'trade',analytics:'analytics',prop:'analytics'}[route];await p.goto(`http://127.0.0.1:5180/?workspace=tenant-a&view=${view}&area=testing&section=${route==='prop'?'analytics':route}&select=1${route==='prop'?'&analytics_source=prop':''}${demo?'&demo=1':''}`);await p.waitForLoadState('networkidle');assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth-innerWidth)<=1);assert.equal(await p.getByTestId('fxreplay-shell').getAttribute('data-theme'),theme);
state.primaryVar=await p.getByTestId('fxreplay-shell').evaluate(e=>getComputedStyle(e).getPropertyValue('--project-primary').trim());assert.equal(state.primaryVar,colors.primary);
const primary=p.locator('.fxa-apply-button:not(:disabled),.fxs-new-session:not(:disabled),a.fx-dashboard-card-play').first();if(await primary.count()){state.primary=await paint(primary);assert.equal(state.primary.bg,rgb(colors.action));assert.equal(state.primary.color,rgb(colors.on));assert.ok(contrast(state.primary.color,state.primary.bg)>=4.5);await primary.hover();await p.waitForTimeout(180);state.primaryHover=await paint(primary);assert.equal(state.primaryHover.bg,rgb(colors.hover));assert.ok(contrast(state.primaryHover.color,state.primaryHover.bg)>=4.5)}
if(route==='dashboard'){
state.dashboardChartAccents=await p.locator('.fx-dashboard-chart-panel').evaluateAll(es=>es.map(e=>({class:e.className,accent:getComputedStyle(e).getPropertyValue('--chart-accent').trim()})));for(const chart of state.dashboardChartAccents){if(chart.class.includes('is-blue'))assert.equal(chart.accent,colors.blue)}const count=p.locator('.fx-dashboard-session-count');await count.waitFor();state.count=await count.innerText();state.progress=await count.locator('progress').evaluate(e=>({value:e.value,max:e.max}));assert.ok(state.progress.value<=state.progress.max);
const card=p.locator('.fx-dashboard-session-card').first();state.cards=await p.locator('.fx-dashboard-session-card').count();if(state.cards){const expand=card.locator('.fx-dashboard-card-expand');await card.locator('.fx-dashboard-card-info').click();assert.equal(await expand.getAttribute('aria-expanded'),'true');await card.locator('.fx-dashboard-card-progress').click();assert.equal(await expand.getAttribute('aria-expanded'),'false');await expand.focus();await p.keyboard.press('Enter');assert.equal(await expand.getAttribute('aria-expanded'),'true');await expand.focus();await p.keyboard.press('Space');assert.equal(await expand.getAttribute('aria-expanded'),'false');const edit=card.locator('button:has(svg path[d="m16 3 5 5-12 12H4v-5ZM13 6l5 5"])');if(!await edit.isDisabled()){await edit.click();const dialog=p.getByRole('dialog');await dialog.waitFor();assert.equal(await expand.getAttribute('aria-expanded'),'false');await p.keyboard.press('Escape');assert.equal(await dialog.count(),0)}await card.locator('.fx-dashboard-card-info').click();assert.equal(await expand.getAttribute('aria-expanded'),'true');await p.waitForLoadState('networkidle');state.curve=await card.locator('.fxs-curve-path').count();if(state.curve){state.curvePaint=await paint(card.locator('.fxs-curve-path').first());assert.equal(state.curvePaint.stroke,rgb(colors.blue))}else{state.emptyChart=await card.locator('.fxs-no-analytics').count();if(state.emptyChart)assert.equal(await card.locator('.fxs-charts').count(),0)}await p.screenshot({path:out+name+'-expanded.png'});await expand.click()}
const search=p.locator('.fx-dashboard-search input');await search.fill('no-match-independent-review');await p.waitForTimeout(180);assert.equal(await p.locator('.fx-dashboard-session-card').count(),0);assert.equal(await count.locator('progress').evaluate(e=>e.value),0);await search.fill('');await p.locator('.fx-dashboard-filter-toggle').click();await popup(p,p.locator('.fx-dashboard-list-filters .fx-select-trigger[aria-label="Tài sản"],.fx-select-trigger[aria-label="Assets"]'),'assets',state)
}
if(route==='sessions'){const neutral=p.locator('.fxs-analytics-button>.fx-select-trigger');state.neutralAnalytics=await paint(neutral);assert.equal(state.neutralAnalytics.h,width<=760?44:40);assert.equal(state.neutralAnalytics.radius,'999px');assert.equal(state.neutralAnalytics.border,'rgba(0, 0, 0, 0)');await popup(p,p.locator('.fx-select.is-rich>.fx-select-trigger'),'rich-sessions',state);const curves=p.locator('.fxs-curve-path');if(await curves.count()){state.curve=await paint(curves.first());assert.equal(state.curve.stroke,rgb(colors.blue))}const danger=p.locator('button.is-danger').first();if(await danger.count()){state.danger=await paint(danger);assert.equal(state.danger.color,'rgb(255, 255, 255)');assert.ok(contrast(state.danger.color,state.danger.bg)>=4.5);await danger.hover();await p.waitForTimeout(180);state.dangerHover=await paint(danger);assert.ok(contrast(state.dangerHover.color,state.dangerHover.bg)>=4.5)}}
if(route==='analytics'||route==='prop'){
const parent=p.locator('.fx-subnav-link.is-active:has(+.fx-subsubnav)'),children=p.locator('.fx-subsubnav');assert.equal(await parent.count(),1);state.parent=await paint(parent);assert.equal(state.parent.color,rgb(colors.highlight));state.line=await parent.evaluate(e=>{const s=getComputedStyle(e,'::after'),r=e.getBoundingClientRect();return {color:s.backgroundColor,height:s.height,right:s.right,left:s.left,y:r.bottom-parseFloat(s.bottom||'0')}});state.childLine=await children.evaluate(e=>{const s=getComputedStyle(e,'::after'),r=e.getBoundingClientRect();return {color:s.backgroundColor,height:s.height,x:r.x,y:r.bottom,width:r.width}});assert.equal(state.line.color,rgb(colors.highlight));assert.equal(state.childLine.color,rgb(colors.highlight));assert.equal(state.line.height,'2px');assert.equal(state.childLine.height,'2px');assert.ok(Math.abs(state.line.y-state.childLine.y)<=1,'underline vertical alignment');assert.ok(Math.abs(state.parent.x+state.parent.w-parseFloat(state.line.right)-state.childLine.x)<=1,'underline horizontal continuity');for(const a of await children.locator('a').all()){assert.notEqual((await paint(a)).color,rgb(colors.highlight));await a.hover();await p.waitForTimeout(180);assert.equal((await paint(a)).bg,'rgba(0, 0, 0, 0)')}
const clear=p.locator('.fxa-clear-filters');state.clearPresent=await clear.count();if(state.clearPresent){assert.equal(await clear.locator('svg').getAttribute('aria-hidden'),'true');await clear.hover();await p.waitForTimeout(180);state.clearHover=await paint(clear);assert.ok(contrast(state.clearHover.color,state.clearHover.bg)>=4.5);await popup(p,p.locator('.fx-select-trigger[aria-label="Tài sản"],.fx-select-trigger[aria-label="Assets"]'),'assets',state);await popup(p,p.locator('.fx-select-trigger[aria-label="Múi giờ"],.fx-select-trigger[aria-label="Timezone"]'),'timezone',state);await popup(p,p.locator('.fxa-session-trigger'),'session-filter',state);const chipBefore=await p.locator('.fxa-filter-chip').allTextContents();const side=p.locator('.fx-select-trigger[aria-label="Hướng lệnh"],.fx-select-trigger[aria-label="Side"]');if(await side.count()){await side.click();const buy=p.getByRole('option').filter({hasText:/Mua|Buy/}).first();if(await buy.count())await buy.click();else await p.keyboard.press('Escape');await p.locator('.fxa-apply-button').click();await p.waitForLoadState('networkidle');await clear.click();await p.waitForLoadState('networkidle');state.chipBefore=chipBefore;state.chipAfter=await p.locator('.fxa-filter-chip').allTextContents();assert.deepEqual(state.chipAfter,chipBefore)}const curves=p.locator('.fxa-curve:not(.is-negative)');if(await curves.count()){state.curve=await paint(curves.first());assert.equal(state.curve.color,rgb(colors.blue))}}
}
if(width===1440&&language==='vi'&&['dashboard','sessions','analytics'].includes(route)){await p.addScriptTag({path:'../../.artifacts/wm-integration-quality-tools/node_modules/axe-core/axe.min.js'});state.axe=await p.evaluate(async()=>{const r=await axe.run(document,{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21aa']}});return r.violations.map(v=>({id:v.id,impact:v.impact,nodes:v.nodes.map(n=>({target:n.target,summary:n.failureSummary}))}))});assert.equal(state.axe.length,0,'Axe violations')}await p.mouse.move(1,1);await p.screenshot({path:out+name+'.png'});report.states.push(state);report.cases.push({name,pass:true})
}catch(e){report.failures.push({name,error:String(e),stack:e.stack,state});await p.screenshot({path:out+name+'-failure.png'})}await c.close();await writeFile(out+'progress.json',JSON.stringify(report,null,2))}
try{for(const theme of ['dark','light'])for(const width of [1440,360])for(const demo of [false,true])for(const route of ['dashboard','sessions','trades','analytics','prop'])await run(route,theme,width,demo);for(const theme of ['dark','light'])for(const width of [1440,360])for(const route of ['dashboard','sessions','analytics'])await run(route,theme,width,true,'en');for(const theme of ['dark','light'])for(const demo of [false,true])await run('analytics',theme,768,demo);report.after=await pins();report.sourceUnchanged=JSON.stringify(report.before)===JSON.stringify(report.after);assert.equal(report.cases.length,process.env.REVIEW_AFFECTED?18:56);assert.equal(report.failures.length,0);assert.equal(report.errors.length,0);assert.equal(report.blocked.length,0);assert.ok(report.sourceUnchanged);report.pass=true}catch(e){report.failure=String(e);process.exitCode=1}finally{await browser.close();await writeFile(out+'report.json',JSON.stringify(report,null,2));console.log(JSON.stringify({pass:report.pass,cases:report.cases.length,failures:report.failures.map(x=>({name:x.name,error:x.error})),errors:report.errors,blocked:report.blocked,sourceUnchanged:report.sourceUnchanged}))}
