import assert from 'node:assert/strict'
import {chromium} from '../../../web/node_modules/playwright/index.mjs'
import {readFile,writeFile,readdir} from 'node:fs/promises'
import {createHash} from 'node:crypto'
const out='foundation_v2/evidence/vintage-palette-20261006/independent/', root='foundation_v2/web/'
const files=(await readdir(root+'src')).filter(f=>/\.(jsx?|css|json)$/.test(f)).map(f=>'src/'+f).concat(['public/project-palette.css','public/chart-legacy.css','index.html','tests/visual/chart-fixture.json'])
const pins=()=>Promise.all(files.sort().map(async file=>({file,sha256:createHash('sha256').update(await readFile(root+file)).digest('hex')})))
const fixtureBytes=await readFile(root+'tests/visual/chart-fixture.json'),fixture=JSON.parse(fixtureBytes)
// Existing fixture has only up candles; controlled synthetic down candles exercise both semantic roles.
fixture.latest.visible_rows=fixture.latest.visible_rows.map((row,i)=>i%5===0?{...row,close:row.open-(row.open-row.low)*.65}:row)
const report={scope:'Synthetic chart fixture only; every fifth visible candle close lowered within original low/open, tick status unavailable.',fixtureSha256:createHash('sha256').update(fixtureBytes).digest('hex'),cases:[],failures:[],errors:[],unexpected:[],before:await pins()}
const browser=await chromium.launch({headless:true,ignoreDefaultArgs:['--hide-scrollbars']})
async function palette(page){return page.getByTestId('fxreplay-shell').evaluate(e=>{const s=getComputedStyle(e);return Object.fromEntries(['canvas','text','primary','positive','negative','grid'].map(k=>[k,s.getPropertyValue('--project-'+k).trim().toUpperCase()]))})}
async function pixels(page,colors){const frames=[];for(const f of page.frames()){const rows=await f.evaluate(colors=>{const rgb=Object.fromEntries(Object.entries(colors).map(([k,h])=>[k,h.slice(1).match(/../g).map(n=>parseInt(n,16))]));return [...document.querySelectorAll('canvas')].map(c=>{try{const g=c.getContext('2d');if(!g)return null;const d=g.getImageData(0,0,c.width,c.height).data,counts=Object.fromEntries(Object.keys(rgb).map(k=>[k,0]));for(let i=0;i<d.length;i+=4)if(d[i+3]===255)for(const [k,v]of Object.entries(rgb))if(v.every((n,j)=>n===d[i+j]))counts[k]++;return {width:c.width,height:c.height,counts}}catch(e){return {error:String(e)}}}).filter(Boolean)},colors);frames.push({url:f.url(),canvases:rows})}return frames}
async function toggle(page){for(const frame of page.frames()){const toggles=frame.locator('[data-testid=theme-toggle],.legacy-mobile-theme');for(let i=0;i<await toggles.count();i++)if(await toggles.nth(i).isVisible()){await toggles.nth(i).click();return}}throw Error('No visible theme toggle')}
async function inspect(page,engine,theme){const chart=page.getByTestId('replay-chart');assert.equal(await chart.getAttribute('data-visible-row-count'),'61');if(engine==='legacy')assert.equal(await chart.getAttribute('data-chart-status'),'ready');else assert.equal(await chart.getAttribute('data-visible-object-count'),'4');assert.equal(await page.getByTestId('fxreplay-shell').getAttribute('data-theme'),theme);const colors=await palette(page),framePixels=await pixels(page,colors),counts={canvas:0,positive:0,negative:0,primary:0};for(const f of framePixels)for(const c of f.canvases)for(const k of Object.keys(counts))counts[k]+=c.counts?.[k]||0;assert.ok(counts.canvas>10000,'palette background missing '+JSON.stringify(counts));assert.ok(counts.positive>20,'positive candles missing '+JSON.stringify(counts));assert.ok(counts.negative>20,'negative candles missing '+JSON.stringify(counts));assert.ok(counts.primary>20,'palette annotations missing '+JSON.stringify(counts));assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth-innerWidth)<=1,'page overflow');return {theme,colors,counts,framePixels}}
try{for(const engine of ['lightweight','legacy'])for(const theme of ['dark','light'])for(const width of [1377,360]){
 const name=`chart-${engine}-${theme}-${width}`,context=await browser.newContext({viewport:{width,height:987}}),page=await context.newPage();report.phase=name
 await page.addInitScript(theme=>{localStorage.setItem('tw-theme',theme);localStorage.setItem('tw-language','en');localStorage.setItem('tw-shell-rail-collapsed','false')},theme)
 await context.routeWebSocket('**/*',ws=>ws.close());await context.route('**/*',r=>{const q=r.request(),u=new URL(q.url());if(u.origin!=='http://127.0.0.1:5180'||!['GET','HEAD','OPTIONS'].includes(q.method())){report.unexpected.push({name,url:q.url(),method:q.method()});return r.abort()}if(!u.pathname.startsWith('/api/'))return r.continue();let body;if(u.pathname==='/api/v2/data/datasets')body=fixture.datasets;else if(u.pathname==='/api/v2/chart/annotations')body=fixture.annotations;else if(u.pathname===`/api/v2/replay/sessions/${fixture.session}`)body=fixture.latest;else if(u.pathname===`/api/v2/replay/sessions/${fixture.session}/tick-data`)body={available:false,reason:'Synthetic visual fixture has no ticks.'};else{report.unexpected.push({name,url:q.url()});return r.abort()}return r.fulfill({status:200,json:body})});page.on('pageerror',e=>report.errors.push({name,error:String(e)}))
 try{await page.goto(`http://127.0.0.1:5180/?workspace=${fixture.workspace}&view=replay&surface=workspace&session=${fixture.session}&cursor=60&chart_engine=${engine}`);await page.waitForLoadState('networkidle');await page.getByTestId('replay-chart').waitFor();if(engine==='legacy')await page.waitForFunction(()=>document.querySelector('[data-testid=replay-chart]')?.dataset.chartStatus==='ready');await page.waitForTimeout(700);const before=await inspect(page,engine,theme);await page.screenshot({path:out+name+'.png'});await toggle(page);await page.waitForTimeout(900);const after=await inspect(page,engine,theme==='dark'?'light':'dark');await page.screenshot({path:out+name+'-switched.png'});report.cases.push({name,before,after,pass:true})}catch(e){report.failures.push({name,error:String(e),stack:e.stack});await page.screenshot({path:out+name+'-failure.png'})}await context.close();await writeFile(out+'chart-progress.json',JSON.stringify(report,null,2))
}report.after=await pins();report.sourceUnchanged=JSON.stringify(report.before)===JSON.stringify(report.after);assert.equal(report.cases.length,8);assert.equal(report.failures.length,0);assert.equal(report.errors.length,0);assert.equal(report.unexpected.length,0);assert.ok(report.sourceUnchanged);report.pass=true}catch(e){report.failure=String(e);process.exitCode=1}finally{await browser.close();await writeFile(out+'chart-report.json',JSON.stringify(report,null,2));console.log(JSON.stringify({cases:report.cases.length,failures:report.failures,errors:report.errors,unexpected:report.unexpected,sourceUnchanged:report.sourceUnchanged,pass:report.pass}))}
