import assert from 'node:assert/strict'
import { chromium } from '../../../web/node_modules/playwright/index.mjs'
import { readFile,writeFile,readdir } from 'node:fs/promises'
import { createHash } from 'node:crypto'
const out='foundation_v2/evidence/vintage-palette-20261006/independent/lazy-r4/'
const files=(await readdir('foundation_v2/web/src')).filter(f=>/\.(jsx?|css|json)$/.test(f)).map(f=>'src/'+f).concat(['public/project-palette.css','public/chart-legacy.css','index.html','tests/visual/chart-fixture.json']),pins=()=>Promise.all(files.sort().map(async file=>({file,sha256:createHash('sha256').update(await readFile('foundation_v2/web/'+file)).digest('hex')})))
const expected={dark:{canvas:'#171C20',surface:'#232B30',raised:'#2B343A',text:'#ECE9E2',muted:'#A6AFB3',primary:'#8FAFC1',positive:'#9DAF98',highlight:'#D6A07B',negative:'#D89B95'},light:{canvas:'#F4F1EB',surface:'#FBF9F4',raised:'#FEFCF8',text:'#283138',muted:'#556166',primary:'#3E6275',positive:'#4E684A',highlight:'#8F532F',negative:'#984745'}}
const lum=s=>{const a=s.startsWith('#')?s.slice(1).match(/../g).slice(0,3).map(x=>parseInt(x,16)/255):s.match(/[\d.]+/g).slice(0,3).map(x=>Number(x)/255);const c=a.map(v=>v<=.04045?v/12.92:((v+.055)/1.055)**2.4);return c[0]*.2126+c[1]*.7152+c[2]*.0722},ratio=(a,b)=>(Math.max(lum(a),lum(b))+.05)/(Math.min(lum(a),lum(b))+.05)
const report={cases:[],failures:[],blocked:[],requests:[],responses:[],errors:[],styles:[],contrast:[],axe:[],before:await pins()},b=await chromium.launch({headless:true,ignoreDefaultArgs:['--hide-scrollbars']}),c=await b.newContext(),p=await c.newPage(),axe=await readFile('../../.artifacts/wm-integration-quality-tools/node_modules/axe-core/axe.min.js','utf8')
await c.routeWebSocket('**/*',ws=>ws.close());await c.route('**/*',r=>{const q=r.request(),u=new URL(q.url());if(!['http://127.0.0.1:5180','http://127.0.0.1:8010'].includes(u.origin)||!['GET','HEAD','OPTIONS'].includes(q.method())){report.blocked.push({phase:report.phase,url:q.url(),method:q.method()});return r.abort()}if(u.pathname.startsWith('/api/'))report.requests.push({phase:report.phase,path:u.pathname,method:q.method(),demo:new URL(q.frame().url()).searchParams.get('demo')});return r.continue()});p.on('pageerror',e=>report.errors.push({phase:report.phase,message:e.message}));p.on('response',r=>{if(new URL(r.url()).pathname.startsWith('/api/'))report.responses.push({phase:report.phase,path:new URL(r.url()).pathname,status:r.status()})})
const routes=[['dashboard','overview','testing','dashboard',false],['live','live','live','calendar',false],['playbook','playbook','strategies','my-strategies',false],['research','research','strategies','research',false],['risk','risk','testing','risk',false],['order','trade','testing','trades',false,'&intent=order'],['journal','journal','testing','journal',false],['learn','learn','education','',false],['settings','settings','settings','',false],['data','data','testing','data',false],['dashboard','overview','testing','dashboard',true],['sessions','replay','testing','sessions',true],['trades','trade','testing','trades',true],['analytics','analytics','testing','analytics',true],['prop','analytics','testing','analytics',true,'&analytics_source=prop'],['market','market-data','testing','market-data',true],['live','live','live','calendar',true],['playbook','playbook','strategies','my-strategies',true],['journal','journal','testing','journal',true]]
const shot=suffix=>p.screenshot({path:out+report.phase+(suffix||'')+'.png'}),style=loc=>loc.evaluate(e=>{const s=getComputedStyle(e),a=getComputedStyle(e,'::after'),r=e.getBoundingClientRect();return {color:s.color,bg:s.backgroundColor,border:s.borderColor,outline:s.outlineStyle,outlineWidth:s.outlineWidth,outlineColor:s.outlineColor,height:r.height,after:{content:a.content,x:r.x+(parseFloat(a.left)||0),right:r.right-(parseFloat(a.right)||0),y:r.bottom-(parseFloat(a.bottom)||0)-(parseFloat(a.height)||0),height:parseFloat(a.height),color:a.backgroundColor}}})
async function run(name,fn){report.phase=name;try{await fn();report.cases.push({name,pass:true})}catch(e){report.failures.push({name,error:String(e),stack:e.stack});await shot('-failure')}await writeFile(out+'progress.json',JSON.stringify(report,null,2))}
async function shellPalette(theme){const values=await p.getByTestId('fxreplay-shell').evaluate(e=>{const s=getComputedStyle(e);return Object.fromEntries(['canvas','surface','raised','text','muted','primary','positive','negative','highlight'].map(k=>[k,s.getPropertyValue('--project-'+k).trim().toUpperCase()]))});assert.deepEqual(values,expected[theme]);const locals=await p.locator('.fx-content>.wm-page,.fx-content>.fx-dashboard').evaluateAll(es=>es.map(e=>({class:e.className,primary:getComputedStyle(e).getPropertyValue('--wm-primary').trim().toUpperCase(),text:getComputedStyle(e).getPropertyValue('--wm-content').trim().toUpperCase(),positive:getComputedStyle(e).getPropertyValue('--wm-positive').trim().toUpperCase()})));for(const local of locals){assert.equal(local.primary,expected[theme].primary,'local primary drift '+local.class);assert.equal(local.text,expected[theme].text,'local text drift '+local.class);assert.equal(local.positive,expected[theme].positive,'local positive drift '+local.class)}report.styles.push({phase:report.phase,values,locals})}
async function controlsContrast(){const samples=await p.locator('.fx-content').evaluate(e=>{const q='.fxa-button.is-primary,.fxr-button-primary,.learn-open-current,.settings-appearance-actions button[type=submit],.rs-button.is-primary,.trade-primary,.risk-primary,.fxa-metric>span,.fxs-metric>span,.settings-fact dt,.learn-progress small,.live-status-copy span';return [...e.querySelectorAll(q)].filter(n=>{const r=n.getBoundingClientRect();return r.width&&r.height&&!n.disabled}).slice(0,20).map(n=>{const s=getComputedStyle(n);let bg=s.backgroundColor,t=n;while(bg==='rgba(0, 0, 0, 0)'&&t.parentElement){t=t.parentElement;bg=getComputedStyle(t).backgroundColor}return {class:n.className,text:n.innerText.slice(0,100),color:s.color,bg,font:Number.parseFloat(s.fontSize)}})});for(const s of samples){s.ratio=ratio(s.color,s.bg);report.contrast.push({phase:report.phase,...s});assert.ok(s.ratio>=4.5,'text contrast '+JSON.stringify(s))}}
try{for(const theme of ['dark','light'])for(const width of [1377])for(const [name,view,area,section,demo,extra=''] of routes.filter((r)=>r[4]&&['dashboard','sessions','trades','analytics','prop','live','playbook','journal'].includes(r[0])))await run(`${demo?'demo':'actual'}-${name}-${theme}-${width}`,async()=>{
await p.setViewportSize({width,height:987});await p.goto(`http://127.0.0.1:5180/?workspace=tenant-a&view=${view}&area=${area}&section=${section}&select=1${demo?'&demo=1':''}${extra}`);await p.waitForLoadState('networkidle');const shell=p.getByTestId('fxreplay-shell');if(await shell.getAttribute('data-theme')!==theme)await p.getByTestId('theme-toggle').click();if(await shell.getAttribute('lang')!=='en')await p.getByTestId('language-toggle').click();await p.waitForTimeout(180);await shellPalette(theme);for(let turn=0;turn<2;turn++){await p.locator('.wm-demo-action button').click();await p.waitForLoadState('networkidle');await p.waitForTimeout(180);await shellPalette(theme);await controlsContrast();report.styles.push({phase:report.phase,toggleTurn:turn,url:p.url(),lazyStyles:await p.locator('link[rel=stylesheet]').evaluateAll(es=>es.map(e=>e.href))})}assert.equal(await p.locator('.fx-content .wm-skeleton').count(),0);assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth-innerWidth),0,'document overflow');assert.equal(await p.locator('.fxa-metric,.fxs-metric,.fx-dashboard-metric').evaluateAll(es=>es.some(e=>e.innerText.includes('ⓘ'))),false);await controlsContrast();report.styles.push({phase:report.phase,alerts:await p.locator('.fx-content [role=alert]').count(),content:(await p.locator('.fx-content').innerText()).slice(0,500)})
const menu=p.locator('.fx-menu-button');await menu.hover();await p.waitForTimeout(180);const m=await style(menu);assert.equal(m.bg,'rgba(0, 0, 0, 0)');assert.equal(m.border,'rgba(0, 0, 0, 0)');const nav=p.locator('.fx-subnav-primary>a').first();if(await nav.count()){await nav.hover();await p.waitForTimeout(180);assert.equal((await style(nav)).bg,'rgba(0, 0, 0, 0)');assert.equal((await style(nav)).color,await shell.evaluate(e=>getComputedStyle(e).getPropertyValue('--wm-control-text').trim()).then(v=>v.startsWith('#')?'rgb('+v.slice(1).match(/../g).map(x=>parseInt(x,16)).join(', ')+')':v))}
if(name==='analytics'||name==='prop'){const parent=await style(p.locator('.fx-subnav-link.is-active')),group=await style(p.locator('.fx-subsubnav')),last=await style(p.locator('.fx-subsubnav>a').last());assert.equal(parent.after.height,2);assert.ok(Math.abs(parent.after.right-group.after.x)<.51);assert.ok(Math.abs(parent.after.y-group.after.y)<.51);assert.ok(Math.abs(group.after.right-last.after.right)<.51)}
if(demo&&name==='analytics'){const tz=p.getByRole('button',{name:'Timezone',exact:true});await tz.click();const list=p.locator('.fx-select-menu [role=listbox]'),g=await list.evaluate(e=>({h:e.scrollHeight,c:e.clientHeight,gutter:e.offsetWidth-e.clientWidth,r:e.getBoundingClientRect().toJSON()}));assert.ok(g.gutter>=10&&g.h>g.c);const option=p.getByRole('option').first();await option.hover();await p.waitForTimeout(180);const os=await style(option);const menuBg=(await style(p.locator('.fx-select-menu'))).bg;const effective=os.bg==='rgba(0, 0, 0, 0)'?menuBg:os.bg;report.contrast.push({phase:report.phase,class:'timezone-option',color:os.color,bg:effective,ratio:ratio(os.color,effective)});assert.ok(ratio(os.color,effective)>=4.5);await p.mouse.click(g.r.right-g.gutter/2,g.r.y+g.r.height*.55);assert.ok(await p.locator('.fx-select-menu').isVisible());await shot('-timezone');await p.keyboard.press('Escape')}
if(width===1377&&((demo&&['dashboard','analytics'].includes(name))||!demo&&['settings','learn'].includes(name))){await p.addScriptTag({content:axe});const a=await p.evaluate(()=>axe.run(document,{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21aa']}}));report.axe.push({phase:report.phase,violations:a.violations.map(v=>({id:v.id,impact:v.impact,nodes:v.nodes.map(n=>n.target)})),passes:a.passes.length});assert.equal(a.violations.length,0,'Axe violations '+JSON.stringify(report.axe.at(-1)))}
if(width===1377||['dashboard','live','learn','settings','analytics','playbook'].includes(name)){await p.mouse.move(1,1);await p.waitForTimeout(180);await shot()}
});report.after=await pins();report.sourceUnchanged=JSON.stringify(report.before)===JSON.stringify(report.after);assert.equal(report.cases.length,16);assert.equal(report.failures.length,0);assert.equal(report.errors.length,0);assert.equal(report.blocked.length,0);assert.equal(report.requests.filter(r=>r.demo==='1').length,0);assert.ok(report.sourceUnchanged);report.pass=true
}catch(e){report.failure=String(e);process.exitCode=1}finally{await b.close();await writeFile(out+'report.json',JSON.stringify(report,null,2));console.log(JSON.stringify({pass:report.pass,cases:report.cases.length,failures:report.failures.map(f=>({name:f.name,error:f.error})),errors:report.errors,blocked:report.blocked,sourceUnchanged:report.sourceUnchanged}))}
