import assert from 'node:assert/strict'
import {chromium} from '../../../web/node_modules/playwright/index.mjs'
import {readFile,writeFile} from 'node:fs/promises'
import {createHash} from 'node:crypto'
const out='foundation_v2/evidence/testing-alignment-20261007/independent/',main=JSON.parse(await readFile(out+'report.json')),files=main.after.map(x=>x.file),pins=()=>Promise.all(files.map(async file=>({file,sha256:createHash('sha256').update(await readFile('foundation_v2/web/src/'+file)).digest('hex')}))),r={cases:[],failures:[],errors:[],blocked:[],before:await pins()},b=await chromium.launch({headless:true,ignoreDefaultArgs:['--hide-scrollbars']})
for(const [theme,language,width]of [['dark','vi',1440],['light','en',360]])for(const mode of ['settings','create','time-date']){const name=`${mode}-${theme}-${language}-${width}`,c=await b.newContext({viewport:{width,height:987}}),p=await c.newPage(),state={name};await p.addInitScript(({theme,language})=>{localStorage.setItem('tw-theme',theme);localStorage.setItem('tw-language',language)},{theme,language});await c.routeWebSocket('**/*',w=>w.close());await c.route('**/*',q=>{const req=q.request(),u=new URL(req.url());if(!['http://127.0.0.1:5180','http://127.0.0.1:8010'].includes(u.origin)||!['GET','HEAD','OPTIONS'].includes(req.method())){r.blocked.push({name,url:req.url(),method:req.method()});return q.abort()}return q.continue()});p.on('pageerror',e=>r.errors.push({name,error:String(e)}));try{const q=new URLSearchParams({workspace:'tenant-a',view:mode==='time-date'?'analytics':'replay',area:'testing',section:mode==='time-date'?'analytics':'sessions'});if(mode==='create'){q.set('surface','workspace');q.set('fresh','1')}else q.set('select','1');if(mode==='settings'&&language==='en')q.set('demo','1');await p.goto('http://127.0.0.1:5180/?'+q);await p.waitForLoadState('networkidle');assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth-innerWidth)<=1);
if(mode==='settings'){const opener=p.locator('.fxs-settings');await opener.click();const dialog=p.getByRole('dialog');await dialog.waitFor();assert.equal(await dialog.locator('.fxs-settings-save').isDisabled(),true);for(const tab of await dialog.getByRole('tab').all()){await tab.click();await p.waitForLoadState('networkidle');state.fields??=[];state.fields.push({tab:await tab.innerText(),fields:await dialog.locator('input,textarea').evaluateAll(es=>es.map(e=>({label:e.parentElement.textContent,readOnly:e.readOnly,width:e.getBoundingClientRect().width,height:e.getBoundingClientRect().height})))})}await p.screenshot({path:out+name+'.png'});await p.keyboard.press('Escape');assert.equal(await dialog.count(),0);assert.equal(await opener.evaluate(e=>document.activeElement===e),true)}
if(mode==='create'){const create=p.locator('.replay-start');await create.waitFor();state.controls=await create.locator('button,input').evaluateAll(es=>es.map(e=>({label:e.textContent||e.type,width:e.getBoundingClientRect().width,height:e.getBoundingClientRect().height,lineHeight:getComputedStyle(e).lineHeight})));const dataset=create.locator('.fx-select-trigger');await dataset.click();const menu=p.locator('.fx-select-menu');await menu.waitFor();assert.ok(await menu.getByRole('option').count()>0);await p.keyboard.press('Escape');assert.equal(await menu.count(),0);assert.equal(await dataset.evaluate(e=>document.activeElement===e),true);await p.screenshot({path:out+name+'.png'});await p.goto('http://127.0.0.1:5180/?workspace=tenant-a&view=replay&area=testing&section=sessions&select=1');await p.waitForLoadState('networkidle');assert.equal(await p.locator('.fxs-page').count(),1)}
if(mode==='time-date'){for(const [kind,label]of [['time',language==='vi'?'Giờ':'Time'],['date',language==='vi'?'Ngày backtest':'Backtesting date']]){const trigger=p.locator(`.fxa-filter-pill[aria-label="${label}"]`);await trigger.click();const popup=p.locator('.fx-filter-popover');await popup.waitFor();state.popups??=[];state.popups.push(await popup.evaluate(e=>{const z=e.getBoundingClientRect();return {text:e.textContent,x:z.x,y:z.y,width:z.width,height:z.height,controls:[...e.querySelectorAll('input,button')].map(e=>({label:e.getAttribute('aria-label')||e.textContent,w:e.getBoundingClientRect().width,h:e.getBoundingClientRect().height}))}}));const box=await popup.boundingBox();assert.ok(box.x>=-1&&box.x+box.width<=width+1);await popup.locator('input').first().focus();await p.screenshot({path:out+name+'-'+kind+'.png'});await p.keyboard.press('Escape');assert.equal(await popup.count(),0);assert.equal(await trigger.evaluate(e=>document.activeElement===e),true)}}
r.cases.push(state)}catch(e){r.failures.push({name,error:String(e),stack:e.stack,state});await p.screenshot({path:out+name+'-failure.png'})}await c.close()}
r.after=await pins();r.sourceUnchanged=JSON.stringify(r.before)===JSON.stringify(r.after);r.pass=r.cases.length===6&&!r.failures.length&&!r.errors.length&&!r.blocked.length&&r.sourceUnchanged;await b.close();await writeFile(out+'forms-report.json',JSON.stringify(r,null,2));console.log(JSON.stringify({pass:r.pass,cases:r.cases.length,failures:r.failures.map(x=>({name:x.name,error:x.error})),errors:r.errors,blocked:r.blocked,sourceUnchanged:r.sourceUnchanged}));if(!r.pass)process.exitCode=1
