import assert from 'node:assert/strict'
import {chromium} from '../../../web/node_modules/playwright/index.mjs'
import {writeFile,readFile} from 'node:fs/promises'
import {fileURLToPath} from 'node:url'
import {createHash} from 'node:crypto'
const out=new URL('./',import.meta.url),origin='http://127.0.0.1:5180',browser=await chromium.launch(),report={cases:[],errors:[],blocked:[]}
const dataset={dataset_id:'dialog-qa',instrument_id:'OFFLINE-QA',timeframe:'60s',row_count:2,instrument_spec:{asset_class:'fx'},source:{provider:'isolated-QA'},artifact_sha256:'a'.repeat(64),quality_status:'unverified'}
const catalog={provider_id:'dukascopy-catalog',configured:true,status:'cached',item_count:0,stale:false,error:null,refresh_available:true,retry_after_seconds:0}
const paused={job_id:'paused-qa',instrument_id:'EURUSD',status:'paused',from_date:'2026-01-01',to_date:'2026-01-02',completed_days:1,total_days:2,transferred_bytes:1000}
async function setup(theme,width,language,session=false){let successCsv=false,imported=false;const context=await browser.newContext({viewport:{width,height:987},reducedMotion:'reduce'}),traffic=[],gates={};await context.addInitScript(({theme,language})=>{localStorage.setItem('tw-theme',theme);localStorage.setItem('tw-language',language)},{theme,language});await context.routeWebSocket('**/*',s=>s.close());await context.route('**/*',async route=>{const r=route.request(),u=new URL(r.url());if(u.pathname.startsWith('/api/'))traffic.push({method:r.method(),path:u.pathname});if(![origin,'http://127.0.0.1:8010'].includes(u.origin)||/^\/api\/v2\/(live|data\/(market-assets|providers))/.test(u.pathname)){report.blocked.push({method:r.method(),url:r.url()});return route.abort()}
 if(r.method()==='DELETE'&&u.pathname==='/api/v2/data/datasets/dialog-qa'){await new Promise(resolve=>gates.delete=resolve);return route.fulfill({status:409,json:{detail:'dataset_in_use'}})}
 if(r.method()==='POST'&&u.pathname==='/api/v2/data/csv/preview'){if(successCsv)return route.fulfill({json:{preview:{dataset_id:'csv-dialog-qa',row_count:2,unique_row_count:2,quality:{disposition:'pass'},available_range:{},raw_sha256:'a',normalized_sha256:'b'}}});await new Promise(resolve=>gates.csv=resolve);return route.fulfill({status:422,json:{detail:'Independent rejected fixture'}})}
 if(r.method()==='POST'&&u.pathname==='/api/v2/data/csv/import'&&successCsv){imported=true;return route.fulfill({json:{dataset:{...dataset,dataset_id:'csv-dialog-qa',instrument_id:'CSV-QA'}}})}
 if(r.method()==='POST'&&u.pathname==='/api/v2/data/catalog/refresh'){await new Promise(resolve=>gates.catalog=resolve);return route.fulfill({status:503,json:{detail:'Independent rejected fixture'}})}
 if(r.method()==='POST'&&u.pathname==='/api/v2/data/downloads/paused-qa/resume'){await new Promise(resolve=>gates.progress=resolve);return route.fulfill({status:503,json:{detail:'worker_unavailable'}})}
 if(!['GET','HEAD','OPTIONS'].includes(r.method())){report.blocked.push({method:r.method(),url:r.url()});return route.abort()}
 if(u.pathname==='/api/v2/data/datasets')return route.fulfill({json:{items:imported?[dataset,{...dataset,dataset_id:'csv-dialog-qa',instrument_id:'CSV-QA'}]:[dataset],catalog_items:[],catalog_state:catalog,download_state:{available:false,supports_full:false,supported_instruments:[]}}})
 if(u.pathname==='/api/v2/data/downloads')return route.fulfill({json:{items:[paused],available:true}})
 return route.continue()});const page=await context.newPage();page.on('pageerror',e=>report.errors.push(String(e)));await page.goto(session?origin+'/?workspace=tenant-a&view=replay&area=testing&section=sessions&select=1&demo=1':origin+'/?workspace=tenant-a&view=market-data&area=testing&section=market-data');await page.locator(session?'.fxs-actions button':'.rd-table tbody tr').first().waitFor();return{context,page,traffic,gates,setSuccessCsv:()=>successCsv=true}}
const style=e=>{const s=getComputedStyle(e),r=e.getBoundingClientRect(),tokens=['--wm-control-open','--wm-hover','--wm-control-text','--wm-action-bg','--wm-action-hover','--wm-on-primary','--wm-focus','--project-danger-action','--project-danger-hover','--project-on-danger'];return{bg:s.backgroundColor,color:s.color,border:s.borderTopColor,radius:s.borderRadius,height:r.height,width:r.width,outline:s.outlineStyle,outlineWidth:s.outlineWidth,opacity:s.opacity,focusVisible:e.matches(':focus-visible'),tokens:Object.fromEntries(tokens.map(t=>[t,s.getPropertyValue(t).trim()]))}}
const rgb=c=>c.match(/[\d.]+/g).slice(0,3).map(Number),luminance=c=>rgb(c).map(n=>n/255).map(n=>n<=.04045?n/12.92:((n+.055)/1.055)**2.4).reduce((v,n,i)=>v+n*[.2126,.7152,.0722][i],0),contrast=(a,b)=>(Math.max(luminance(a),luminance(b))+.05)/(Math.min(luminance(a),luminance(b))+.05)
async function snapshot(page,button,name){await page.mouse.move(2,2);await button.evaluate(e=>e.blur());await page.waitForTimeout(100);const rest=await button.evaluate(style);await button.hover();await page.waitForTimeout(100);const hover=await button.evaluate(style);await button.click({trial:true});await button.focus();await page.keyboard.press('Shift+Tab');await page.keyboard.press('Tab');await page.mouse.move(2,2);await page.waitForTimeout(100);const focus=await button.evaluate(style);assert(focus.focusVisible);assert.equal(focus.outline,'solid');assert.equal(focus.outlineWidth,'2px');await screen(page,name);return{rest,hover,focus}}
async function screen(page,name){await page.screenshot({path:fileURLToPath(new URL(name+'.png',out)),fullPage:true})}
async function geometry(page){const g=await page.locator('dialog[open]').evaluate(e=>{const r=e.getBoundingClientRect();return{left:r.left,right:r.right,top:r.top,bottom:r.bottom,overflow:document.documentElement.scrollWidth-innerWidth,bodyOverflow:e.scrollWidth-e.clientWidth}});assert(g.left>=-.1&&g.right<=page.viewportSize().width+.1);assert.equal(g.overflow,0);assert.equal(g.bodyOverflow,0);return g}
async function close(page,opener){await page.keyboard.press('Escape');await page.locator('dialog[open]').waitFor({state:'hidden'});assert(await opener.evaluate(e=>e===document.activeElement))}
async function disabledSnapshot(page,button){assert(await button.isDisabled());await page.mouse.move(2,2);const rest=await button.evaluate(style);const r=await button.boundingBox();await page.mouse.move(r.x+r.width/2,r.y+r.height/2);const hover=await button.evaluate(style);assert.equal(rest.opacity,'0.45');assert.equal(hover.opacity,'0.45');assert.equal(hover.bg,rest.bg);return{rest,hover}}
async function focusGeometry(button){const result=await button.evaluate(e=>{const r=e.getBoundingClientRect(),s=getComputedStyle(e),extent=parseFloat(s.outlineWidth)+parseFloat(s.outlineOffset),clips=[];for(let p=e.parentElement;p;p=p.parentElement){const ps=getComputedStyle(p),pr=p.getBoundingClientRect();if([ps.overflowX,ps.overflowY].some(v=>['auto','hidden','scroll','clip'].includes(v)))clips.push({class:p.className,overflowX:ps.overflowX,overflowY:ps.overflowY,left:pr.left+p.clientLeft,right:pr.left+p.clientLeft+p.clientWidth,top:pr.top+p.clientTop,bottom:pr.top+p.clientTop+p.clientHeight});if(p.tagName==='DIALOG')break}return{left:r.left-extent,right:r.right+extent,top:r.top-extent,bottom:r.bottom+extent,extent,clips}});for(const c of result.clips){assert(result.left>=c.left-.1&&result.right<=c.right+.1,JSON.stringify(result));assert(result.top>=c.top-.1&&result.bottom<=c.bottom+.1,JSON.stringify(result))}return result}
async function run(name,fn){const item={name};report.cases.push(item);try{await fn(item);item.pass=true}catch(e){item.pass=false;item.failure=String(e);console.log(JSON.stringify({name:item.name,pass:item.pass,failure:item.failure}))}}
try{for(const theme of ['dark','light'])for(const [width,language]of [[1710,'vi'],[360,'en']]){
 await run(`library-${theme}-${language}-${width}`,async item=>{const{page,context,traffic,gates}=await setup(theme,width,language);try{
 const row=page.getByTestId('dataset-row-dialog-qa'),more=page.locator('.data-library-more'),dialog=page.locator('dialog[open]');await row.click();item.details=await geometry(page);item.detailsClose=await snapshot(page,dialog.locator('.fx-chart-icon-button'),item.name+'-details');assert.equal(item.detailsClose.rest.radius,'50%');await close(page,row)
 await more.click();await page.getByRole('menuitem').last().click();await dialog.waitFor();item.delete=await geometry(page);const danger=dialog.locator('.is-danger'),neutral=dialog.locator('.data-library-delete-actions .rd-button').first();item.danger=await snapshot(page,danger,item.name+'-delete');item.neutral=await snapshot(page,neutral,item.name+'-cancel');assert.equal(item.danger.rest.color,'rgb(255, 255, 255)');assert.equal(item.danger.rest.radius,'999px');assert(contrast(item.danger.rest.bg,item.danger.rest.color)>=4.5);assert(contrast(item.danger.hover.bg,item.danger.hover.color)>=4.5);assert.notEqual(item.danger.rest.bg,item.neutral.rest.bg);assert.notEqual(item.danger.hover.bg,item.danger.rest.bg);assert.equal(item.neutral.rest.radius,'999px');assert.equal(item.neutral.rest.border,'rgba(0, 0, 0, 0)');
 await danger.click();await page.waitForFunction(()=>document.querySelector('dialog[open]')?.getAttribute('aria-busy')==='true');assert(await danger.isDisabled());assert(await dialog.locator('.fx-chart-icon-button').isDisabled());item.deleteCloseDisabled=await disabledSnapshot(page,dialog.locator('.fx-chart-icon-button'));item.deleteNeutralDisabled=await disabledSnapshot(page,neutral);await page.keyboard.press('Escape');assert.equal(await dialog.count(),1);await screen(page,item.name+'-delete-busy');while(!gates.delete)await page.waitForTimeout(10);gates.delete();await dialog.getByRole('alert').waitFor();assert.equal(await danger.isDisabled(),false);await screen(page,item.name+'-delete-error');await close(page,more)
 const csv=page.locator('.data-library-import');await csv.click();await page.getByTestId('data-desk-file-input').waitFor();item.csv=await geometry(page);const primary=page.getByTestId('data-desk-preview-button');assert(await primary.isDisabled());item.primaryDisabled=await primary.evaluate(style);await page.getByTestId('data-desk-file-input').setInputFiles({name:'isolated.csv',mimeType:'text/csv',buffer:Buffer.from('time,open,high,low,close\n2026-01-01T00:00:00Z,1,1.1,0.9,1\n2026-01-01T00:01:00Z,1,1.1,0.9,1')});item.primary=await snapshot(page,primary,item.name+'-csv');assert.equal(item.primary.rest.radius,'999px');await primary.click();await page.waitForFunction(()=>document.querySelector('dialog[open]')?.getAttribute('aria-busy')==='true');assert(await dialog.locator('.fx-chart-icon-button').isDisabled());item.csvCloseDisabled=await disabledSnapshot(page,dialog.locator('.fx-chart-icon-button'));item.csvPrimaryBusy=await disabledSnapshot(page,primary);await page.keyboard.press('Escape');assert.equal(await dialog.count(),1);while(!gates.csv)await page.waitForTimeout(10);gates.csv();await page.getByTestId('data-desk-import-error').waitFor();await close(page,csv)
 const progress=page.locator('.data-library-catalog-trigger').filter({hasText:language==='vi'?'Tiến độ':'Download progress'});await progress.click();await dialog.waitFor();item.progress=await geometry(page);const resume=dialog.locator('.data-library-job-actions button').first();item.resume=await snapshot(page,resume,item.name+'-progress');assert.equal(item.resume.rest.radius,'999px');item.resumeFocusGeometry=await focusGeometry(resume);await resume.click();assert(await resume.isDisabled());while(!gates.progress)await page.waitForTimeout(10);gates.progress();await page.locator('.data-library-download-error').waitFor();await close(page,progress)
 const catalogTrigger=page.locator('.data-library-catalog-trigger').first();await catalogTrigger.click();await dialog.waitFor();item.catalog=await geometry(page);item.catalogClose=await snapshot(page,dialog.locator('.fx-chart-icon-button'),item.name+'-catalog');const update=dialog.locator('.fxs-settings-save');item.catalogPrimary=await snapshot(page,update,item.name+'-catalog-primary');assert.equal(item.catalogPrimary.rest.radius,'999px');assert.equal(item.catalogPrimary.rest.height,width===360?44:40);await update.click();await page.waitForFunction(()=>document.querySelector('dialog[open]')?.getAttribute('aria-busy')==='true');assert(await dialog.locator('.fx-chart-icon-button').isDisabled());item.catalogCloseDisabled=await disabledSnapshot(page,dialog.locator('.fx-chart-icon-button'));assert.equal(await dialog.locator('.fxs-settings-panel').getAttribute('inert'),'');await page.keyboard.press('Escape');assert.equal(await dialog.count(),1);await screen(page,item.name+'-catalog-busy');while(!gates.catalog)await page.waitForTimeout(10);gates.catalog();await dialog.locator('.data-library-catalog-status').waitFor();await close(page,catalogTrigger);item.traffic=traffic
 }finally{for(const release of Object.values(gates))release();await context.close()}})
 await run(`session-delete-${theme}-${language}-${width}`,async item=>{const{page,context,traffic}=await setup(theme,width,language,true);try{const opener=page.locator('.fxs-actions button');await opener.click();const dialog=page.locator('dialog[open]');await dialog.waitFor();const danger=dialog.locator('.fxs-delete-confirm');assert(await danger.isDisabled());await dialog.locator('input').fill(await dialog.locator('label strong').innerText());assert.equal(await danger.isDisabled(),false);item.danger=await snapshot(page,danger,item.name);assert.equal(item.danger.rest.color,'rgb(255, 255, 255)');assert.equal(item.danger.rest.radius,'999px');assert(contrast(item.danger.rest.bg,item.danger.rest.color)>=4.5);assert(contrast(item.danger.hover.bg,item.danger.hover.color)>=4.5);item.geometry=await geometry(page);await close(page,opener);item.traffic=traffic}finally{await context.close()}})
}
for(const [theme,width,language]of [['dark',1710,'vi'],['light',360,'en']])await run('csv-success-'+theme+'-'+language+'-'+width,async item=>{const{page,context,traffic,setSuccessCsv}=await setup(theme,width,language);try{setSuccessCsv();const status=page.locator('.data-library-filters .fx-select').nth(2),trigger=status.locator('button.fx-select-trigger');await trigger.click();await page.getByRole('option',{name:language==='vi'?'Chưa tải':'Not downloaded',exact:true}).click();assert.equal(await page.getByTestId('dataset-row-dialog-qa').count(),0);await page.locator('.data-library-import').click();await page.getByTestId('data-desk-file-input').setInputFiles({name:'isolated.csv',mimeType:'text/csv',buffer:Buffer.from('time,open,high,low,close\n2026-01-01T00:00:00Z,1,1.1,0.9,1\n2026-01-01T00:01:00Z,1,1.1,0.9,1')});await page.getByTestId('data-desk-preview-button').click();const save=page.getByTestId('data-desk-import-button');await save.waitFor();await page.waitForFunction(()=>!document.querySelector('[data-testid="data-desk-import-button"]').disabled);await save.click();const dialog=page.locator('dialog[open]');await dialog.locator('.rd-detail-grid').waitFor();assert((await dialog.innerText()).includes('CSV-QA'));item.details=await geometry(page);await screen(page,item.name+'-details');await page.keyboard.press('Escape');await dialog.waitFor({state:'hidden'});await page.getByTestId('dataset-row-csv-dialog-qa').waitFor();assert((await trigger.innerText()).includes(language==='vi'?'Tất cả trạng thái':'All statuses'));await screen(page,item.name+'-visible');item.traffic=traffic}finally{await context.close()}})
report.pass=report.cases.every(c=>c.pass)&&!report.errors.length&&!report.blocked.length}
finally{report.hashes={};for(const f of ['DataDeskWorkspace.jsx','data-library.css','testing-standard.css','component-interactions.css'])report.hashes[f]=createHash('sha256').update(await readFile(new URL('../../../web/src/'+f,out))).digest('hex');await writeFile(new URL('review.json',out),JSON.stringify(report,null,2));await browser.close();console.log(JSON.stringify({pass:report.pass,cases:report.cases.map(c=>({name:c.name,pass:c.pass,failure:c.failure})),errors:report.errors,blocked:report.blocked,hashes:report.hashes},null,2))}
