import assert from 'node:assert/strict'
import {chromium} from '../../../web/node_modules/playwright/index.mjs'
import {readFile,writeFile} from 'node:fs/promises'
import {createHash} from 'node:crypto'
import {DEMO_SESSIONS,DEMO_DATASETS,demoDashboardAnalytics,demoReplayContext} from '../../../web/src/demoFixtures.js'
const out='foundation_v2/evidence/session-controls-20261006/independent/final/',root='foundation_v2/web/src/',files=['SessionActions.jsx','SessionPicker.jsx','DashboardSessions.jsx','DashboardSessionCard.jsx','DemoPreview.jsx','fx-analytics.css','testing-standard.css','sessionCatalog.js','testing-copy.json']
const pins=()=>Promise.all(files.map(async file=>({file,sha256:createHash('sha256').update(await readFile(root+file)).digest('hex')})))
const r={cases:[],failures:[],errors:[],blocked:[],requests:[],styles:[],before:await pins()},b=await chromium.launch({headless:true,ignoreDefaultArgs:['--hide-scrollbars']}),axe=await readFile('../../.artifacts/wm-integration-quality-tools/node_modules/axe-core/axe.min.js','utf8')
const archived={...DEMO_SESSIONS[0],archived:true,name:'QA archived fixture'}
const css=loc=>loc.evaluate(e=>{const s=getComputedStyle(e),box=e.getBoundingClientRect();return {color:s.color,bg:s.backgroundColor,border:s.borderColor,w:box.width,h:box.height,x:box.x,y:box.y,align:s.alignItems,children:[...e.children].map(n=>{const b=n.getBoundingClientRect();return {w:b.width,h:b.height,y:b.y,center:b.y+b.height/2}}),negative:s.getPropertyValue('--wm-negative').trim(),icon:e.querySelector('svg')?.getBoundingClientRect().toJSON()}})
const rgb=h=>'rgb('+h.slice(1).match(/../g).map(n=>parseInt(n,16)).join(', ')+')'
async function danger(page,loc){assert.ok(await loc.count());await page.mouse.move(1,1);await page.waitForTimeout(180);const before=await css(loc);await loc.hover();await page.waitForTimeout(180);const after=await css(loc);assert.equal(before.color,rgb(before.negative));assert.equal(after.color,before.color);r.styles.push({phase:r.phase,danger:{before,after}})}
async function caseRun(name,fn,{theme,width,fixture=false}={}){r.phase=name;const c=await b.newContext({viewport:{width,height:987}}),p=await c.newPage();await p.addInitScript(theme=>{localStorage.setItem('tw-theme',theme);localStorage.setItem('tw-language','en')},theme);await c.routeWebSocket('**/*',ws=>ws.close());await c.route('**/*',route=>{const q=route.request(),u=new URL(q.url());if(!['http://127.0.0.1:5180','http://127.0.0.1:8010'].includes(u.origin)||!['GET','HEAD','OPTIONS'].includes(q.method())){r.blocked.push({phase:name,url:q.url(),method:q.method()});return route.abort()}if(u.pathname.startsWith('/api/'))r.requests.push({phase:name,path:u.pathname,method:q.method(),fixture});if(!fixture||!u.pathname.startsWith('/api/'))return route.continue();let body;if(u.pathname==='/api/v2/replay/sessions')body={items:[archived]};else if(u.pathname==='/api/v2/data/datasets')body={items:DEMO_DATASETS};else if(u.pathname===`/api/v2/replay/sessions/${archived.record_id}/analytics`)body=demoDashboardAnalytics(archived,'tenant-a');else if(u.pathname===`/api/v2/replay/sessions/${archived.record_id}`)body=demoReplayContext(archived);else{r.blocked.push({phase:name,url:q.url(),reason:'Unexpected fixture endpoint'});return route.abort()}return route.fulfill({status:200,json:body})});p.on('pageerror',e=>r.errors.push({phase:name,error:String(e)}));try{await fn(p);await p.screenshot({path:out+name+'.png'});r.cases.push({name,pass:true})}catch(e){r.failures.push({name,error:String(e),stack:e.stack});await p.screenshot({path:out+name+'-failure.png'})}await c.close();await writeFile(out+'progress.json',JSON.stringify(r,null,2))}
try{for(const theme of ['dark','light'])for(const width of [1377,360])for(const demo of [false,true])for(const route of ['dashboard','sessions','trades'])await caseRun(`${demo?'demo':'actual'}-${route}-${theme}-${width}`,async p=>{
const view={dashboard:'overview',sessions:'replay',trades:'trade'}[route];await p.goto(`http://127.0.0.1:5180/?workspace=tenant-a&view=${view}&area=testing&section=${route}&select=1${demo?'&demo=1':''}`);await p.waitForLoadState('networkidle');assert.equal(await p.getByRole('button',{name:/^(Archive|Restore)|^(Lưu trữ|Khôi phục)/}).count(),0);assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth-innerWidth)<=1)
if(route==='sessions'){const del=p.locator('.fxr-session-actions .is-danger');if(await del.count()){assert.equal(await del.innerText(),'Delete session');assert.equal(await del.locator('svg').count(),0);await danger(p,del);await del.click();const dialog=p.getByRole('dialog');await dialog.waitFor();const submit=dialog.locator('button[type=submit]');assert.equal(await submit.isDisabled(),true);const name=await dialog.locator('label strong').innerText();await dialog.getByRole('textbox').fill(name);assert.equal(await submit.isDisabled(),false);await danger(p,submit);await p.screenshot({path:out+r.phase+'-delete-confirm.png'});await p.keyboard.press('Escape');assert.equal(await dialog.count(),0)}}
if(route==='dashboard'){const filter=p.locator('.fx-dashboard-filter-toggle');await filter.scrollIntoViewIfNeeded();const fs=await css(filter);assert.equal(fs.w,fs.h);assert.ok(fs.w<=44);assert.equal(fs.icon.width,16);r.styles.push({phase:r.phase,filter:fs});const del=p.locator('.fx-dashboard-card-icon.is-danger,.fxs-action-button.is-danger').first();if(await del.count())await danger(p,del);await filter.click();const status=p.getByRole('button',{name:'Session status',exact:true});if(await status.count()){await status.click();assert.equal(await p.getByRole('option',{name:/Archived/}).count(),0);await p.keyboard.press('Escape')}}
if(route==='trades'){const actions=p.locator('.fxa-filter-actions');assert.ok(await actions.count());const s=await css(actions);assert.equal(s.align,'center');const centers=s.children.filter(n=>n.w&&n.h).map(n=>n.center);if(width>=768)assert.ok(Math.max(...centers)-Math.min(...centers)<=1);r.styles.push({phase:r.phase,actions:s})}
if(demo&&width===1377){await p.addScriptTag({content:axe});const a=await p.evaluate(()=>axe.run(document,{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21aa']}}));assert.equal(a.violations.length,0,JSON.stringify(a.violations.map(v=>({id:v.id,targets:v.nodes.map(n=>n.target)}))))}
},{theme,width})
for(const theme of ['dark','light'])for(const width of [1377,360])await caseRun(`fixture-archived-${theme}-${width}`,async p=>{
await p.goto(`http://127.0.0.1:5180/?workspace=tenant-a&view=replay&area=testing&section=sessions&select=1&session=${archived.record_id}&manage=archive`);await p.waitForLoadState('networkidle');assert.equal(await p.getByRole('dialog').count(),0);assert.equal(await p.getByRole('button',{name:/Archive|Restore/}).count(),0);assert.ok((await p.locator('.fx-content').innerText()).includes('replay and duplication are unavailable'));assert.equal(await p.locator('.fxs-go-chart').count(),0);assert.ok(await p.locator('.fxr-session-report').isVisible());await p.goto(`http://127.0.0.1:5180/?workspace=tenant-a&view=replay&area=testing&section=sessions&select=1&session=${archived.record_id}&manage=duplicate`);await p.waitForLoadState('networkidle');assert.equal(await p.locator('.fxr-session-lifecycle button').isDisabled(),true)
},{theme,width,fixture:true})
r.after=await pins();r.sourceUnchanged=JSON.stringify(r.before)===JSON.stringify(r.after);assert.equal(r.cases.length,28);assert.equal(r.failures.length,0);assert.equal(r.errors.length,0);assert.equal(r.blocked.length,0);assert.ok(r.sourceUnchanged);r.pass=true}catch(e){r.failure=String(e);process.exitCode=1}finally{await b.close();await writeFile(out+'report.json',JSON.stringify(r,null,2));console.log(JSON.stringify({pass:r.pass,cases:r.cases.length,failures:r.failures,errors:r.errors,blocked:r.blocked,sourceUnchanged:r.sourceUnchanged}))}
