import assert from 'node:assert/strict'
import { chromium } from '../../../web/node_modules/playwright/index.mjs'
import { readFile,writeFile,mkdir } from 'node:fs/promises'
import { createHash } from 'node:crypto'
const out='foundation_v2/evidence/testing-tabs-20261006/transparent-hover/';await mkdir(out,{recursive:true})
const files=['fx-shell-story.css','component-interactions.css','page-layout.css','FxReplayShell.jsx'],pins=()=>Promise.all(files.map(async file=>({file,sha256:createHash('sha256').update(await readFile('foundation_v2/web/src/'+file)).digest('hex')})))
const report={checks:[],failures:[],errors:[],blocked:[],requests:[],responses:[],before:await pins()},b=await chromium.launch({headless:true,ignoreDefaultArgs:['--hide-scrollbars']}),c=await b.newContext(),p=await c.newPage()
await c.routeWebSocket('**/*',ws=>ws.close());await c.route('**/*',r=>{const q=r.request(),u=new URL(q.url());if(!['http://127.0.0.1:5180','http://127.0.0.1:8010'].includes(u.origin)||!['GET','HEAD','OPTIONS'].includes(q.method())){report.blocked.push({method:q.method(),url:q.url()});return r.abort()}if(u.pathname.startsWith('/api/'))report.requests.push({phase:report.phase,path:u.pathname,method:q.method(),demo:new URL(q.frame().url()).searchParams.get('demo')});return r.continue()});p.on('pageerror',e=>report.errors.push({phase:report.phase,message:e.message}));p.on('response',r=>{if(new URL(r.url()).pathname.startsWith('/api/'))report.responses.push({phase:report.phase,status:r.status(),path:new URL(r.url()).pathname})})
const style=loc=>loc.evaluate(e=>{const s=getComputedStyle(e),a=getComputedStyle(e,'::after'),r=e.getBoundingClientRect();return {text:e.innerText,color:s.color,background:s.backgroundColor,border:s.borderWidth,borderColor:s.borderColor,outline:s.outlineStyle,outlineWidth:s.outlineWidth,outlineColor:s.outlineColor,svg:e.querySelector('svg')?getComputedStyle(e.querySelector('svg')).color:null,rect:r.toJSON(),after:{content:a.content,color:a.backgroundColor,height:parseFloat(a.height),width:parseFloat(a.width),x:r.x+(parseFloat(a.left)||0),right:r.right-(parseFloat(a.right)||0),y:r.bottom-(parseFloat(a.bottom)||0)-(parseFloat(a.height)||0)}}})
const neutral=color=>{const a=color.match(/[\d.]+/g).map(Number);return a[0]===a[1]&&a[1]===a[2]}
const shot=suffix=>p.screenshot({path:out+report.phase+(suffix||'')+'.png'})
async function geometry(){const parent=await style(p.locator('.fx-subnav-link.is-active')),nav=await style(p.locator('.fx-subsubnav')),first=await style(p.locator('.fx-subsubnav>a').first()),last=await style(p.locator('.fx-subsubnav>a').last());assert.equal(parent.after.height,2);assert.equal(nav.after.height,2);assert.equal(parent.after.color,nav.after.color);assert.ok(Math.abs(parent.after.right-nav.after.x)<.51,'groupline horizontal gap '+JSON.stringify({parent:parent.after,nav:nav.after}));assert.ok(Math.abs(parent.after.y-nav.after.y)<.51,'groupline vertical gap');assert.ok(nav.after.x<=first.rect.x+.51&&nav.after.right>=last.rect.right-.51,'line fails to cover both children');assert.ok(Math.abs(nav.after.right-last.rect.right)<.51,'line extends beyond Prop end');assert.equal(first.after.content,'none');assert.equal(last.after.content,'none');assert.equal(nav.border,'0px');return {parent,nav,first,last}}
const configs=[];for(const demo of [true,false])for(const theme of ['dark','light'])for(const width of [1377,360])for(const source of ['sessions','prop'])configs.push({demo,theme,width,source,lang:'en'});for(const theme of ['dark','light'])for(const source of ['sessions','prop'])configs.push({demo:true,theme,width:360,source,lang:'vi'})
try{report.phase='catalog';await p.goto('http://127.0.0.1:5180/?workspace=tenant-a&view=overview&area=testing&section=dashboard');await p.waitForLoadState('networkidle');const catalog=await p.evaluate(async()=>{const r=await fetch('/api/v2/replay/sessions',{headers:{'X-Workspace-Id':'tenant-a'}});return {status:r.status,payload:await r.json()}});assert.equal(catalog.status,200);assert.ok(catalog.payload.items.length>0);const session=catalog.payload.items[0].record_id;report.catalog={status:200,count:catalog.payload.items.length,session}
for(const config of configs){const {demo,theme,width,source,lang}=config;report.phase=`${demo?'demo':'actual'}-${theme}-${width}-${source}-${lang}`;const check={name:report.phase,config};try{
await p.setViewportSize({width,height:987});await p.goto(`http://127.0.0.1:5180/?workspace=tenant-a&view=analytics&area=testing&section=analytics&select=1&analytics_source=${source}${demo?'&demo=1':`&session=${session}`}`);await p.waitForLoadState('networkidle');const shell=p.getByTestId('fxreplay-shell');if(await shell.getAttribute('data-theme')!==theme)await p.getByTestId('theme-toggle').click();if(await shell.getAttribute('lang')!==lang)await p.getByTestId('language-toggle').click();await p.waitForTimeout(180);assert.equal(await p.locator('.fx-content .wm-skeleton').count(),0);assert.equal(await p.locator('.fx-content [role=alert]').count(),0);assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth-innerWidth),0)
check.geometry=await geometry();const selected=p.locator(`.fx-subsubnav>a[href*="analytics_source=${source}"]`),other=p.locator(`.fx-subsubnav>a[href*="analytics_source=${source==='sessions'?'prop':'sessions'}"]`);assert.equal(await selected.getAttribute('aria-current'),'page');const selectedStyle=await style(selected),otherStyle=await style(other);assert.equal(selectedStyle.background,'rgba(0, 0, 0, 0)');assert.equal(otherStyle.background,'rgba(0, 0, 0, 0)');assert.notEqual(selectedStyle.color,otherStyle.color);if(theme==='dark'){assert.equal(selectedStyle.color,'rgb(255, 255, 255)');assert.equal(check.geometry.nav.after.color,'rgb(255, 255, 255)')}
const menu=p.locator('.fx-menu-button');await p.mouse.move(1,1);check.menuDefault=await style(menu);assert.equal(check.menuDefault.background,'rgba(0, 0, 0, 0)');check.hover=[]
for(const link of [p.locator('.fx-subnav-primary>a').first(),p.locator('.fx-subnav-link.is-active'),selected,other,menu]){await p.evaluate(()=>document.activeElement?.blur());await link.scrollIntoViewIfNeeded();await link.hover();await p.waitForTimeout(180);const hover=await style(link);assert.equal(hover.background,'rgba(0, 0, 0, 0)','hover background '+hover.text);assert.equal(hover.outline,'none');assert.ok(neutral(hover.color));if(theme==='dark')assert.equal(hover.color,'rgb(255, 255, 255)');if(hover.svg)assert.equal(hover.svg,hover.color);check.hover.push(hover)}
await p.keyboard.press('Tab');await selected.focus();await p.waitForTimeout(180);const keyboard=await style(selected);assert.ok(await selected.evaluate(e=>e.matches(':focus-visible')));assert.equal(keyboard.outline,'solid');assert.equal(keyboard.outlineWidth,'2px');assert.equal(keyboard.background,'rgba(0, 0, 0, 0)');check.keyboard=keyboard;await menu.focus();assert.ok(await menu.evaluate(e=>e.matches(':focus-visible')));assert.equal((await style(menu)).outlineWidth,'2px');await p.evaluate(()=>document.activeElement?.blur());await selected.scrollIntoViewIfNeeded();await p.mouse.move(1,1);await p.waitForTimeout(180);await shot('-selected')
await selected.hover();await p.waitForTimeout(180);await shot('-hover');if(width===360){const nav=p.locator('.fx-subnav-primary');const sizes=await nav.evaluate(e=>({client:e.clientWidth,scroll:e.scrollWidth}));assert.ok(sizes.scroll>sizes.client);await other.scrollIntoViewIfNeeded();const box=await other.boundingBox(),bounds=await nav.boundingBox();assert.ok(box.x>=bounds.x-1&&box.x+box.width<=bounds.x+bounds.width+1);check.scroll=sizes}
await other.click();await p.waitForLoadState('networkidle');await p.waitForTimeout(180);assert.equal(await other.getAttribute('aria-current'),'page');const second=await geometry();assert.ok(Math.abs(check.geometry.nav.rect.width-second.nav.rect.width)<.51,'source changes line width');check.afterSwitch=second;await p.evaluate(()=>document.activeElement?.blur());await menu.hover();await p.waitForTimeout(180);await shot('-menu');check.pass=true;report.checks.push(check)
}catch(e){check.failure=String(e);report.failures.push(check);await shot('-failure')}await writeFile(out+'progress.json',JSON.stringify(report,null,2))}
report.after=await pins();report.sourceUnchanged=JSON.stringify(report.before)===JSON.stringify(report.after);assert.equal(report.checks.length,20);assert.equal(report.failures.length,0);assert.equal(report.errors.length,0);assert.equal(report.blocked.length,0);assert.ok(report.responses.every(r=>r.status<400));assert.equal(report.requests.filter(r=>r.demo==='1').length,0);assert.ok(report.sourceUnchanged);report.pass=true
}catch(e){report.failure=String(e);process.exitCode=1}finally{await b.close();await writeFile(out+'report.json',JSON.stringify(report,null,2));console.log(JSON.stringify({pass:report.pass,checks:report.checks.length,failures:report.failures.map(f=>({name:f.name,error:f.failure})),errors:report.errors,blocked:report.blocked,sourceUnchanged:report.sourceUnchanged,failure:report.failure}))}
