import assert from 'node:assert/strict'
import { readFile,writeFile } from 'node:fs/promises'
import { createHash } from 'node:crypto'
const out='foundation_v2/evidence/testing-tabs-20261006/transparent-hover/',r1=JSON.parse(await readFile(out+'r1/report.json','utf8')),r2=JSON.parse(await readFile(out+'r2/report.json','utf8'))
assert.equal(r1.checks.length,20);assert.equal(r2.pass,true);assert.equal(r2.sourceUnchanged,true)
const current=await Promise.all(r2.after.map(async x=>({file:x.file,sha256:createHash('sha256').update(await readFile('foundation_v2/web/src/'+x.file)).digest('hex')})));assert.deepEqual(current,r2.before);assert.deepEqual(current,r2.after)
const changed=r1.after.filter((x,i)=>x.sha256!==current[i].sha256).map(x=>x.file);assert.deepEqual(changed,['component-interactions.css'])
const allGeometry=[...r1.checks.flatMap(x=>[x.geometry,x.afterSwitch]),...r2.checks.flatMap(x=>x.geometry)],maxHorizontalGap=Math.max(...allGeometry.map(g=>Math.abs(g.parent.after.right-g.nav.after.x))),maxVerticalGap=Math.max(...allGeometry.map(g=>Math.abs(g.parent.after.y-g.nav.after.y))),maxPropEndGap=Math.max(...allGeometry.map(g=>Math.abs(g.nav.after.right-g.last.rect.right))),r1MenuBorders=[...new Set(r1.checks.filter(x=>x.config.theme==='light').map(x=>x.hover.at(-1).borderColor))]
const receipt={status:'PASS',scope:'Continuous Analytics group underline, transparent hover and rail toggle, retained keyboard focus/mobile read navigation',at:new Date().toISOString(),reviewer:'fx_analytics_review',r1:{cases:20,status:'Preserved earlier revision; missing menu-border oracle revealed visible hover border and owner changed source afterward',sourcePins:r1.after,menuHoverBorderColorsLight:r1MenuBorders,authority:'not final revision'},ownerCorrection:{filesChangedSinceR1:changed,behavior:'Menu hover selector specificity raised with :not(:disabled); border-color transparent'},r2:{cases:4,matrix:'actual local API, dark/light ×1377/360',checks:'Menu default/hover background+border transparent, icon/text, keyboard2pxfocus retained; both sources/group geometry spotchecked',sourceUnchanged:true,sourcePins:current,apiResponses:r2.responses.length,apiErrors:r2.responses.filter(x=>x.status>=400).length,pageErrors:r2.errors.length,unexpectedBlockedTraffic:r2.blocked.length},geometry:{snapshots:allGeometry.length,height:2,maxParentGroupGapPx:maxHorizontalGap,maxVerticalGapPx:maxVerticalGap,maxPropEndGapPx:maxPropEndGap},evidence:['r1/report.json','r2/report.json','REVIEW.md'],limitations:['UI presentation/navigation/read loading only; no financial calculation acceptance.','No API writes, MT5 sync, broker/execution or provider calls.','Only evidence files edited by reviewer; no source edit/commit. Prior receipts untouched.']}
await writeFile(out+'final-receipt.json',JSON.stringify(receipt,null,2));await writeFile(out+'REVIEW.md',`# Refinement review — final scoped PASS

R1 retained20 demo/actual cases across dark/light,1377/360px, both child sources and VI mobile. The initial harness missed the menu pointer-border oracle: light hover still showed${r1MenuBorders.join(', ')}. The owner corrected only component-interactions.css afterward; R1 is preserved evidence, not the final source authority.

R2 passed4 focused cases on the frozen final revision: actual local API ×dark/light ×1377/360px. Menu default/hover background and border are transparent, icon/text brighten, and pointer hover has no outline. Keyboard focus retains its2px solid outline. The final light360 hover image was opened and confirms the circle border is gone.

The Analytics2px line continues across both children to Prop firm’s end independently of selected source. Across40 R1 and8 R2 geometry snapshots, maximum parent/group gap=${maxHorizontalGap}px, vertical gap=${maxVerticalGap}px, and group/Prop end gap=${maxPropEndGap}px. Both sources remain clickable and mobile nav scrolls without document overflow. Parent/child transparent hover and source-only text selection passed R1; their source rules are unchanged in R2.

R2:${r2.responses.length} API read responses,0 HTTP errors,0 page JS errors and0 unexpected external/write traffic. Four source hashes match R2 before/after and receipt-time recheck. Visual evidence includes R1 desktop continuous line and mobile selected/hover images, plus R2 actual-light-360-menu-hover.png. Previous receipts remain untouched.

Read-only UI/data-loading acceptance; no server startup, MT5 synchronization, broker/execution, provider or write actions. Reviewer edited evidence only, with no product source changes or commit.
`);console.log(JSON.stringify({status:'PASS',r1:20,r2:4,ownerChanged:changed,geometry:receipt.geometry,pins:current.length}))
