import assert from 'node:assert/strict'
import { chromium } from '../../../web/node_modules/playwright/index.mjs'
import { DEMO_SESSIONS, DEMO_LEDGER } from '../../../web/src/demoFixtures.js'
import { readFile, writeFile, readdir } from 'node:fs/promises'
import { createHash } from 'node:crypto'
import path from 'node:path'
const out=path.dirname(new URL(import.meta.url).pathname.replace(/^\/(\w:)/,'$1'))
const files=(await readdir('foundation_v2/web/src')).filter(f=>/\.(jsx|css|json|js)$/.test(f)),pins=async()=>Promise.all(files.map(async f=>({file:f,sha256:createHash('sha256').update(await readFile('foundation_v2/web/src/'+f)).digest('hex')})))
const copy=JSON.parse(await readFile('foundation_v2/web/src/testing-copy.json')),tx=(s,l)=>copy[s]?.[l]||s
const report={checks:[],failures:[],blocked:[],requests:[],errors:[],geometry:[],before:await pins()}
const b=await chromium.launch({headless:true,ignoreDefaultArgs:['--hide-scrollbars']}),c=await b.newContext(),p=await c.newPage();let fixture=null
const rows=Array.from({length:237},(_,i)=>({...DEMO_LEDGER[i%60],trade_id:'qa-trade-'+i,session_id:'qa-fixture',source_provenance:{session_id:'qa-fixture',revision:1},account_currency:'USD'}))
const assets=Array.from({length:137},(_,i)=>({symbol:'QA'+String(i).padStart(3,'0'),enabled:true,metadata:i%5?{group:'Forex',description:'QA asset'}:undefined,status:'available',dataset_id:'qa-dataset-'+i,first_timestamp:'2026-07-01T00:00:00Z',last_timestamp:'2026-10-01T00:00:00Z',row_count:1000}))
await c.routeWebSocket('**/*',ws=>ws.close());await c.route('**/*',async r=>{const q=r.request(),u=new URL(q.url());if(!['http://127.0.0.1:5180','http://127.0.0.1:8010'].includes(u.origin)||!['GET','HEAD','OPTIONS'].includes(q.method())){report.blocked.push({url:q.url(),method:q.method()});return r.abort()}if(!u.pathname.startsWith('/api/'))return r.continue();report.requests.push({phase:report.phase,path:u.pathname,query:u.search,fixture});if(fixture?.startsWith('market')&&u.pathname==='/api/v2/data/market-assets'){if(fixture==='market-error')return r.fulfill({status:500,json:{detail:'QA read failure'}});if(fixture==='market-403')return r.fulfill({status:403,json:{detail:'QA unavailable'}});return r.fulfill({json:{status:'ready',source:'QA fixture',items:fixture==='market-empty'?[]:assets}})}if(fixture?.startsWith('trades')&&u.pathname==='/api/v2/replay/sessions')return r.fulfill({json:{items:[{...DEMO_SESSIONS[0],record_id:'qa-fixture'}]}});if(fixture?.startsWith('trades')&&u.pathname==='/api/v2/replay/trades'){if(fixture==='trades-error')return r.fulfill({status:500,json:{detail:'QA trade read failure'}});const page=Number(u.searchParams.get('page')||1),size=Number(u.searchParams.get('page_size')||10),unknown=fixture==='trades-blocked',count=unknown?null:fixture==='trades-empty'?0:rows.length,ledger=count?rows.slice((page-1)*size,page*size):[];return r.fulfill({json:{schema_version:'replay-trades-page-v1',status:fixture==='trades-partial'||unknown?'partial':'ready',snapshot_key:'qa-stable',scope:{session_ids:['qa-fixture']},sources:[],excluded:fixture==='trades-partial'||unknown?[{session_id:'qa-missing',reason:'replay_execution_not_initialized'}]:[],ledger,pagination:{page,page_size:size,returned_count:ledger.length,filtered_count:count,page_count:unknown?null:Math.ceil(count/size)},facets:{assets:['EURUSD','GBPUSD','XAUUSD'],tags:['breakout'],strategies:[],years:[2026],types:['app']}}})}const response=await r.fetch({url:'http://127.0.0.1:8010'+u.pathname+u.search});return r.fulfill({response})})
p.on('pageerror',e=>report.errors.push({phase:report.phase,error:e.message}))
const go=async(view,lang,theme,width,mode=null)=>{fixture=mode;await p.setViewportSize({width,height:987});await p.goto(`http://127.0.0.1:5180/?workspace=tenant-a&area=testing&section=${view==='analytics'?'analytics':view==='trade'?'trades':'market-data'}&view=${view}&select=1${mode?'':'&demo=1'}`);await p.waitForLoadState('networkidle');const shell=p.getByTestId('fxreplay-shell');if(await shell.getAttribute('lang')!==lang)await p.getByTestId('language-toggle').click();if(await shell.getAttribute('data-theme')!==theme)await p.getByTestId('theme-toggle').click()}
const run=async(name,fn)=>{report.phase=name;try{await fn();report.checks.push({name,pass:true})}catch(e){report.failures.push({name,error:String(e),stack:e.stack})}await p.screenshot({path:path.join(out,name+'.png')});await writeFile(path.join(out,'focused-progress.json'),JSON.stringify(report,null,2))}
const menu=()=>p.locator('.fx-select-menu'),body=()=>p.locator('.fx-content')
try{
for(const lang of ['vi','en'])for(const theme of ['dark','light'])for(const width of [390,1710]){
await run(`timezone-${lang}-${theme}-${width}`,async()=>{await go('analytics',lang,theme,width);const trigger=p.getByRole('button',{name:tx('Timezone',lang),exact:true});await trigger.click();const list=menu().getByRole('listbox'),g=await list.evaluate(e=>({scroll:e.scrollHeight,client:e.clientHeight,gutter:e.offsetWidth-e.clientWidth,rect:e.getBoundingClientRect().toJSON()}));report.geometry.push({phase:report.phase,...g});assert.ok(g.scroll>g.client&&g.gutter>=10,'native scrollbar absent');await p.mouse.click(g.rect.right-g.gutter/2,g.rect.bottom-20);await p.waitForTimeout(100);assert.ok(await menu().isVisible(),'track click closed menu');const before=await list.evaluate(e=>e.scrollTop),trackHeight=g.client-32,thumbHeight=Math.max(17,trackHeight*g.client/g.scroll),thumbY=g.rect.y+16+before/(g.scroll-g.client)*(trackHeight-thumbHeight)+thumbHeight/2;await p.mouse.move(g.rect.right-g.gutter/2,thumbY);await p.mouse.down();await p.mouse.move(g.rect.right-g.gutter/2,g.rect.y+g.client*.8,{steps:8});await p.mouse.up();assert.ok(await menu().isVisible(),'thumb closed menu');assert.ok(await list.evaluate(e=>e.scrollTop)>before,'thumb did not scroll');await menu().locator('input[type=search]').fill('Ho Chi Minh');await menu().getByRole('option').click();assert.equal(await menu().count(),0);assert.equal(await body().locator('.fxa-filter-chip').filter({hasText:'Asia/Ho_Chi_Minh'}).count(),0,'draft applied early');await p.getByRole('button',{name:tx('Apply',lang),exact:true}).click();assert.equal(await body().locator('.fxa-filter-chip').filter({hasText:'Asia/Ho_Chi_Minh'}).count(),1);await trigger.focus();await p.keyboard.press('Enter');await p.keyboard.press('ArrowDown');assert.ok(await menu().getByRole('option').evaluateAll(es=>es.some(e=>e===document.activeElement)));await p.keyboard.press('Escape');assert.ok(await trigger.evaluate(e=>document.activeElement===e));await trigger.click();for(let i=0;i<470&&await menu().count();i++)await p.keyboard.press('Tab');assert.equal(await menu().count(),0,'Tab did not leave menu')})
await run(`filters-${lang}-${theme}-${width}`,async()=>{await go('analytics',lang,theme,width);const type=p.getByRole('button',{name:tx('Type',lang),exact:true});await type.click();await menu().getByRole('option',{name:'App',exact:true}).click();assert.equal(await menu().getByRole('checkbox').getAttribute('aria-checked'),'mixed');await menu().getByRole('checkbox').click();assert.equal(await menu().getByRole('checkbox').getAttribute('aria-checked'),'true');await p.keyboard.press('Escape');await p.getByRole('button',{name:tx('Time',lang),exact:true}).click();const pop=p.locator('.fx-filter-popover');await pop.locator('input[type=time]').first().fill('08:00');await p.keyboard.press('Escape');assert.equal(await body().locator('.fxa-filter-chip').filter({hasText:'08:00'}).count(),0);await p.getByRole('button',{name:tx('Apply',lang),exact:true}).click();assert.equal(await body().locator('.fxa-filter-chip').filter({hasText:'08:00'}).count(),1);await p.getByRole('button',{name:tx('Backtesting Date',lang),exact:true}).click();await pop.locator('input[type=date]').first().fill('2026-09-10');await pop.locator('input[type=date]').last().fill('2026-08-01');await p.keyboard.press('Escape');assert.ok(await p.getByRole('button',{name:tx('Apply',lang),exact:true}).isDisabled());assert.equal(await body().getByRole('alert').count(),1)})
}
for(const width of [390,1710])for(const lang of ['vi','en']){
await run(`market-paging-${lang}-${width}`,async()=>{await go('market-data',lang,'dark',width,'market-large');assert.equal(await p.locator('tbody tr').count(),25);await p.getByRole('button',{name:tx('Trang sau',lang),exact:true}).click();assert.match(await p.locator('tbody tr').first().innerText(),/QA025/);const size=p.getByRole('button',{name:tx('Số dòng mỗi trang',lang),exact:true});await size.click();await menu().getByRole('option',{name:'100',exact:true}).click();assert.equal(await p.locator('tbody tr').count(),100);await p.getByRole('button',{name:tx('Trang sau',lang),exact:true}).click();assert.equal(await p.locator('tbody tr').count(),37);await p.locator('input[type=search]').fill('QA136');assert.equal(await p.locator('tbody tr').count(),1);assert.match(await p.locator('nav.fxa-pagination').innerText(),/1 \/ 1/)})
await run(`trades-paging-${lang}-${width}`,async()=>{await go('trade',lang,'light',width,'trades-large');await p.locator('tbody input[type=checkbox]').first().waitFor();assert.equal(await p.locator('tbody tr').count(),10);await p.getByRole('button',{name:tx('Trang sau',lang),exact:true}).click();await p.waitForFunction(()=>document.querySelector('.fxa-pagination [aria-current=page]')?.innerText==='2');assert.equal(await p.locator('tbody tr').count(),10);await p.getByRole('button',{name:tx('Trang cuối',lang),exact:true}).click();await p.waitForFunction(()=>document.querySelector('.fxa-pagination [aria-current=page]')?.innerText==='24');assert.equal(await p.locator('tbody tr').count(),7);const size=p.locator('.fxa-pagination .fx-select-trigger');await size.click();await menu().getByRole('option',{name:'100',exact:true}).click();await p.waitForFunction(()=>document.querySelectorAll('.fxa-table-scroll tbody tr').length===100);assert.equal(await p.locator('.fxa-pagination [aria-current=page]').innerText(),'1');await p.locator('tbody input[type=checkbox]').first().check();assert.equal(await p.locator('thead input[type=checkbox]').getAttribute('aria-checked'),'mixed');await p.locator('thead input[type=checkbox]').check();assert.equal(await p.locator('tbody input[type=checkbox]:checked').count(),100)})
}
for(const mode of ['market-empty','market-error','market-403','trades-empty','trades-error','trades-partial','trades-blocked'])for(const lang of ['vi','en'])await run(`${mode}-${lang}`,async()=>{await go(mode.startsWith('market')?'market-data':'trade',lang,'dark',1710,mode);await p.waitForTimeout(100);assert.equal(await p.locator('.wm-skeleton').count(),0,'read state remained loading');if(mode.endsWith('error'))assert.ok(await body().getByRole('alert').count());if(mode==='trades-partial')assert.ok(await body().getByRole('status').count());if(mode==='trades-blocked'){assert.equal(await p.locator('tbody input').count(),0);assert.ok(await p.getByRole('button',{name:tx('Trang sau',lang),exact:true}).isDisabled())}if(mode.endsWith('empty'))assert.equal(await p.locator('tbody input').count(),0);assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth-innerWidth),0)})
const axe=await readFile('../../.artifacts/wm-integration-quality-tools/node_modules/axe-core/axe.min.js','utf8')
for(const lang of ['vi','en'])for(const theme of ['dark','light'])await run(`axe-controls-${lang}-${theme}`,async()=>{await go('analytics',lang,theme,1710);await p.evaluate(axe);for(const [label,selector] of [['Type','.fx-select-menu'],['Timezone','.fx-select-menu'],['Backtesting Date','.fx-filter-popover']]){await p.getByRole('button',{name:tx(label,lang),exact:true}).click();const result=await p.evaluate(async selector=>window.axe.run({include:[selector]},{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21aa']}}),selector);report.geometry.push({phase:report.phase,label,violations:result.violations,incomplete:result.incomplete.map(x=>({id:x.id,nodes:x.nodes.length}))});assert.deepEqual(result.violations,[],label+' accessibility violations');await p.keyboard.press('Escape')}})
report.after=await pins();report.sourceUnchanged=JSON.stringify(report.before)===JSON.stringify(report.after);assert.deepEqual(report.errors,[]);assert.deepEqual(report.blocked,[]);assert.deepEqual(report.failures,[]);report.pass=true
}catch(e){report.failure=String(e);process.exitCode=1}finally{await b.close();await writeFile(path.join(out,'focused-report.json'),JSON.stringify(report,null,2));console.log(JSON.stringify({pass:report.pass,checks:report.checks.length,failures:report.failures.map(f=>({name:f.name,error:f.error})),errors:report.errors,blocked:report.blocked,sourceUnchanged:report.sourceUnchanged}))}
