import assert from 'node:assert/strict'
import { chromium } from '../../../web/node_modules/playwright/index.mjs'
import { readFile,writeFile,mkdir,readdir } from 'node:fs/promises'
import { createHash } from 'node:crypto'
import path from 'node:path'
const out=path.dirname(new URL(import.meta.url).pathname.replace(/^\/(\w:)/,'$1'));await mkdir(out,{recursive:true})
const files=(await readdir('foundation_v2/web/src')).filter(f=>/^(testing|Testing)|^(Dashboard|Session|Analytics|Fx|PropAnalytics|MarketAsset|DemoPreview)|^(page-layout|main\.|tradingAnalytics|market-sync|ledger-controls|session-|dashboard\.)/.test(f))
const pins=async()=>Promise.all(files.map(async f=>({file:f,sha256:createHash('sha256').update(await readFile('foundation_v2/web/src/'+f)).digest('hex')})))
const copy=JSON.parse(await readFile('foundation_v2/web/src/testing-copy.json','utf8')),tx=(key,language)=>copy[key]?.[language]||key
const report={checks:[],failures:[],errors:[],blocked:[],requests:[],geometry:[],texts:[],before:await pins()}
const b=await chromium.launch({headless:true,ignoreDefaultArgs:['--hide-scrollbars']}),c=await b.newContext(),p=await c.newPage()
await c.routeWebSocket('**/*',ws=>ws.close());await c.route('**/*',async r=>{const q=r.request(),u=new URL(q.url());if(!['http://127.0.0.1:5180','http://127.0.0.1:8010'].includes(u.origin)||!['GET','HEAD','OPTIONS'].includes(q.method())){report.blocked.push({method:q.method(),url:q.url()});return r.abort()}if(u.pathname.startsWith('/api/')){report.requests.push({phase:report.phase,path:u.pathname,method:q.method(),demo:new URL(q.frame().url()).searchParams.get('demo')});const response=await r.fetch({url:'http://127.0.0.1:8010'+u.pathname+u.search});return r.fulfill({response})}return r.continue()});p.on('pageerror',e=>report.errors.push({phase:report.phase,error:e.message}))
const routes={dashboard:['overview','dashboard'],sessions:['replay','sessions'],trades:['trade','trades'],analytics:['analytics','analytics'],prop:['analytics','analytics'],market:['market-data','market-data']}
const goto=async(route,theme,lang,width,demo)=>{await p.setViewportSize({width,height:width===390?844:987});const [view,section]=routes[route];await p.goto(`http://127.0.0.1:5180/?workspace=tenant-a&view=${view}&area=testing&section=${section}&select=1${demo?'&demo=1':''}${route==='prop'?'&analytics_source=prop':''}`);await p.waitForLoadState('networkidle');if(await p.getByTestId('fxreplay-shell').getAttribute('data-theme')!==theme)await p.getByTestId('theme-toggle').click();if(await p.getByTestId('fxreplay-shell').getAttribute('lang')!==lang)await p.getByTestId('language-toggle').click()}
const run=async(name,fn)=>{report.phase=name;try{await fn();report.checks.push({name,pass:true})}catch(e){report.failures.push({name,error:String(e),stack:e.stack});await p.screenshot({path:path.join(out,'failure-'+name+'.png')}).catch(()=>{})}await writeFile(path.join(out,'runtime-progress.json'),JSON.stringify(report,null,2))}
const fit=async loc=>{const box=await loc.boundingBox(),clip=await p.locator('.fx-content').evaluate(e=>({left:e.getBoundingClientRect().left,right:e.getBoundingClientRect().left+e.clientWidth}));assert.ok(box.x>=clip.left-1&&box.x+box.width<=clip.right+1,'popup clipped by content '+JSON.stringify({box,clip}));assert.ok(box.y>=-1&&box.y+box.height<=p.viewportSize().height+1,'popup vertically clipped')}
const body=()=>p.locator('.fx-content')
const fitViewport=async loc=>{const box=await loc.boundingBox();assert.ok(box.x>=-1&&box.x+box.width<=p.viewportSize().width+1,'modal horizontally clipped');assert.ok(box.y>=-1&&box.y+box.height<=p.viewportSize().height+1,'modal vertically clipped')}
const get=async path=>{const r=await c.request.get('http://127.0.0.1:8010'+path,{headers:{'X-Workspace-Id':'tenant-a'}});assert.ok(r.ok());return r.json()}
try{
const catalog=await get('/api/v2/replay/sessions'),recordId=catalog.items.find(x=>!x.archived)?.record_id,record=await get('/api/v2/replay/sessions/'+recordId)
for(const demo of [true,false])for(const theme of ['dark','light'])for(const lang of ['vi','en'])for(const width of (demo?[390,768,1710]:[1710]))for(const route of Object.keys(routes))await run(`${demo?'demo':'actual'}-${route}-${theme}-${lang}-${width}`,async()=>{
 await goto(route,theme,lang,width,demo);const shell=p.getByTestId('fxreplay-shell');assert.equal(await shell.getAttribute('data-ui-area'),'testing');assert.equal(await shell.getAttribute('lang'),lang)
 const snapshot=await body().evaluate(e=>({visibleTitles:[...e.querySelectorAll('h1')].filter(n=>{const r=n.getBoundingClientRect(),s=getComputedStyle(n);return r.width>2&&r.height>2&&s.clip==='auto'&&s.display!=='none'}).map(n=>n.innerText),text:e.innerText.slice(0,8500),documentOverflow:document.documentElement.scrollWidth-innerWidth,contentOverflow:e.scrollWidth-e.clientWidth,headings:[...e.querySelectorAll('h2,h3')].filter(n=>n.getBoundingClientRect().width&&n.getBoundingClientRect().height).slice(0,8).map(n=>({text:n.innerText,font:getComputedStyle(n).fontSize})),controls:[...e.querySelectorAll('.fx-select:not(.is-rich) > .fx-select-trigger')].filter(n=>n.getBoundingClientRect().width&&n.getBoundingClientRect().height).map(n=>({label:n.getAttribute('aria-label'),height:n.getBoundingClientRect().height,font:getComputedStyle(n).fontSize,border:getComputedStyle(n).borderColor})),values:[...e.querySelectorAll('.fxa-metric>strong,.fxs-metric>strong,.fx-dashboard-metric>strong')].slice(0,5).map(n=>getComputedStyle(n).fontSize)}));report.texts.push({phase:report.phase,...snapshot});assert.equal(snapshot.documentOverflow,0,'document overflow');assert.deepEqual(snapshot.visibleTitles,[],'duplicated visible page title');assert.equal(snapshot.contentOverflow,0,'content overflow');for(const control of snapshot.controls){assert.ok(control.height>=(width===390?44:40)-.5,'undersized control '+JSON.stringify(control));assert.equal(control.font,'13px')}for(const font of snapshot.values)assert.equal(font,'32px');for(const heading of snapshot.headings)assert.equal(heading.font,'16px')
 if(lang==='en')assert.ok(!/[À-ỹ]/u.test(snapshot.text.replace(/[·]/g,'')),'Vietnamese visible text in EN page')
 if(demo&&route==='dashboard'){const sort=p.getByRole('button',{name:tx('Sắp xếp phiên',lang),exact:true});await sort.click();await fit(p.locator('.fx-select-menu'));const option=p.getByRole('option',{name:tx('Oldest to newest',lang),exact:true});await p.mouse.move(10,10);await option.hover();await p.waitForTimeout(180);await p.locator('.fx-select-menu').screenshot({path:path.join(out,report.phase+'-sort.png')});await p.keyboard.press('Escape');const del=p.locator('.fxs-action-button.is-danger').first();await del.click();const dialog=p.locator('dialog[open]');await fitViewport(dialog);const confirmation=dialog.locator('input');await confirmation.waitFor();assert.ok(await confirmation.evaluate(e=>document.activeElement===e));for(let i=0;i<9;i++){await p.keyboard.press('Tab');assert.ok(await dialog.evaluate(e=>e.contains(document.activeElement)))}await p.keyboard.press('Escape')}
 if(demo&&route==='sessions'){await p.locator('.fx-select.is-rich > button').click();await fit(p.locator('.fx-select-menu'));await p.keyboard.press('Escape');assert.equal(await p.locator('.fxs-metric-info').first().locator('svg').count(),1)}
 if(demo&&route==='trades'){const row=p.locator('.fxa-table-scroll tbody input[type=checkbox]').first();await row.check();assert.ok(await p.locator('.fxa-table-scroll thead input[type=checkbox]').evaluate(e=>e.indeterminate));const detail=p.locator('.fxa-detail-button').first(),bounds=await detail.boundingBox();assert.ok(Math.abs(bounds.width-(width===390?44:32))<1);assert.ok(Math.abs(bounds.height-bounds.width)<1);await p.getByRole('button',{name:tx('Trang sau',lang),exact:true}).click();assert.equal(await p.locator('.fxa-pagination button[aria-current=page]').innerText(),'2');await p.getByRole('button',{name:tx('Trang đầu',lang),exact:true}).click()}
 if(demo&&(route==='analytics'||route==='prop')){const tabs=p.getByRole('tablist',{name:tx('Phân tích',lang),exact:true});await tabs.scrollIntoViewIfNeeded();const widths=await tabs.locator('[role=tab]').evaluateAll(es=>es.map(e=>e.getBoundingClientRect().width));assert.ok(Math.max(...widths)-Math.min(...widths)<1);const first=tabs.locator('[role=tab]').first();await first.focus();await p.keyboard.press('End');assert.equal(await tabs.locator('[role=tab]').last().getAttribute('aria-selected'),'true');await p.keyboard.press('Home');assert.equal(await first.getAttribute('aria-selected'),'true')}
 if(demo&&route==='market'){const search=p.locator('.market-sync-filters input[type=search]');await search.fill('EURUSD');assert.equal(await p.locator('.market-sync-table tbody tr').count(),1);await search.fill('NO_RESULT_QA');assert.match(await body().innerText(),new RegExp(tx('Không có asset phù hợp bộ lọc.',lang).replace(/[.*+?^${}()|[\]\\]/g,'\\$&')));await search.fill('');await p.getByRole('button',{name:tx('Nhóm asset',lang),exact:true}).click();await fit(p.locator('.fx-select-menu'));await p.keyboard.press('Escape')}
 if((width===1710&&lang==='en')||(width===390&&lang==='vi')||!demo)await p.screenshot({path:path.join(out,report.phase+'.png')})
})
assert.deepEqual(await get('/api/v2/replay/sessions'),catalog);assert.deepEqual(await get('/api/v2/replay/sessions/'+recordId),record);report.actualRecordsUnchanged=true;report.after=await pins();report.sourceUnchanged=JSON.stringify(report.before)===JSON.stringify(report.after);assert.deepEqual(report.blocked,[]);assert.deepEqual(report.errors,[]);assert.equal(report.requests.filter(x=>x.demo==='1').length,0);assert.deepEqual(report.failures,[]);assert.ok(report.sourceUnchanged);report.pass=true
}catch(e){report.failure=String(e);process.exitCode=1}finally{await b.close();await writeFile(path.join(out,'runtime-report.json'),JSON.stringify(report,null,2));console.log(JSON.stringify({pass:report.pass,checks:report.checks.length,failures:report.failures.map(x=>({name:x.name,error:x.error})),errors:report.errors,blocked:report.blocked,sourceUnchanged:report.sourceUnchanged}))}
