import assert from 'node:assert/strict'
import {chromium} from '../../../foundation_v2/web/node_modules/playwright/index.mjs'
import {mkdir,readFile,writeFile} from 'node:fs/promises'
import {createHash} from 'node:crypto'
import path from 'node:path'
import {DEMO_LEDGER,DEMO_SESSIONS} from '../../../foundation_v2/web/src/demoFixtures.js'
if(!process.argv.includes('--source-frozen'))throw new Error('SOURCE_FREEZE_REQUIRED')
const out=path.resolve('.artifacts/fx-trades-demo-layout-20261005/independent-review'),origin='http://127.0.0.1:5180',api='http://127.0.0.1:8010'
await mkdir(out,{recursive:true})
const source=['FxReplayShell.jsx','main.jsx','workspaceContext.js','page-layout.css','demoFixtures.js','demoMode.js','DemoPreview.jsx','FxTradeLedger.jsx','FxAnalytics.jsx','fx-analytics.css','SessionReports.jsx','DashboardPerformance.jsx','SessionPerformance.jsx','MarketAssetCatalog.jsx','LiveBrokerSnapshot.jsx','JournalWorkspace.jsx','PlaybookWorkspace.jsx'].map(file=>'foundation_v2/web/src/'+file)
const hashes=()=>Promise.all(source.map(async file=>({file,sha256:createHash('sha256').update(await readFile(file)).digest('hex')})))
const report={scope:'GET-only actual local UI plus explicitly labeled product demo fixtures; no broker/SDK calls, imports, downloads or data writes',before:await hashes(),cases:[],checks:[],errors:[],blocked:[],apiRequests:[],teardown:[],failures:[]}
const b=await chromium.launch({headless:true}),c=await b.newContext({viewport:{width:1440,height:987}})
await c.route('**/*',async r=>{const q=r.request(),u=new URL(q.url());if(u.origin!==origin||!['GET','HEAD','OPTIONS'].includes(q.method())){report.blocked.push({method:q.method(),path:u.pathname});return r.abort()}if(!u.pathname.startsWith('/api/'))return r.continue();report.apiRequests.push({path:u.pathname,search:u.search,mode:new URL(q.frame().url()).searchParams.get('demo')||'real'});try{return await r.fulfill({response:await r.fetch({url:api+u.pathname+u.search})})}catch(e){const error=String(e);if(/ERR_ABORTED|Route is already handled/.test(error))report.teardown.push('Canceled navigation request '+u.pathname);else report.errors.push(error);try{return await r.abort()}catch{}}})
await c.routeWebSocket('**/*',s=>s.close());const p=await c.newPage();p.setDefaultTimeout(15000);p.on('pageerror',e=>report.errors.push(String(e)));p.on('download',()=>report.blocked.push({method:'DOWNLOAD'}))
const settle=async()=>{await p.waitForLoadState('networkidle');await p.waitForFunction(()=>document.getAnimations().every(a=>a.playState!=='running'))}
const get=async endpoint=>{const r=await c.request.get(api+endpoint,{headers:{'X-Workspace-Id':'tenant-a'}});assert.equal(r.status(),200);return r.json()}
const axe=async()=>{await p.addScriptTag({path:'../../.artifacts/wm-integration-quality-tools/node_modules/axe-core/axe.min.js'});return p.evaluate(()=>window.axe.run(document,{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21aa','wcag22aa']}}).then(r=>r.violations.map(v=>({id:v.id,targets:v.nodes.map(n=>n.target)}))))}
const navigate=async(query)=>{await p.goto(origin+'/?workspace=tenant-a&'+query,{waitUntil:'networkidle'});await settle()}
const layout=async(name,query,selector,theme,width,a11y=false)=>{
 await p.setViewportSize({width,height:987});await navigate(query);if(await p.getByTestId('fxreplay-shell').getAttribute('data-theme')!==theme)await p.getByTestId('theme-toggle').click();await settle()
 const overflow=await p.evaluate(()=>document.documentElement.scrollWidth-innerWidth);assert.equal(overflow,0)
 const clip=await p.locator('.fx-content').boundingBox(),content=await p.locator(selector).first().boundingBox(),expected=width<=760?16:32
 const gutters={left:content.x-clip.x,right:clip.x+clip.width-content.x-content.width};assert.ok(Math.abs(gutters.left-expected)<1.1&&Math.abs(gutters.right-expected)<1.1,`${name} gutters ${JSON.stringify(gutters)} expected ${expected}`)
 const violations=a11y?await axe():null;report.cases.push({name,theme,width,overflow,gutters,axe:violations});if(a11y)assert.deepEqual(violations,[])
 if(['trades','analytics','dashboard','market-data','sessions'].includes(name))await p.screenshot({path:path.join(out,`${name}-${theme}-${width}.png`)})
}
const run=async(name,fn)=>{try{await fn();report.checks.push({name,pass:true})}catch(e){report.failures.push({name,error:String(e)});await p.screenshot({path:path.join(out,'failure-'+name.replace(/[^a-zA-Z0-9]/g,'-')+'.png')}).catch(()=>{})}}
const select=async(label,value)=>{const native=p.getByRole('combobox',{name:label,exact:true});if(await native.count()&&await native.evaluate(el=>el.tagName==='SELECT'))return native.selectOption(value);await p.getByRole('button',{name:label,exact:true}).click();await p.getByRole('option',{name:value,exact:true}).click();await settle()}
const tradeRows=()=>p.getByTestId('fx-trade-ledger').locator('tbody tr')
const rowIds=()=>tradeRows().locator('input[type="checkbox"]').evaluateAll(els=>els.map(el=>el.getAttribute('aria-label').replace('Chọn lệnh ','')))
const defaultOrder=rows=>[...rows].sort((a,b)=>Date.parse(b.close_time_utc)-Date.parse(a.close_time_utc)).map(r=>r.trade_id)
try{
 const old='476f4b498e1a49ed9d48a75719f4d270',filled='273a1275538c42cb95cfff16e0f9f62c'
 const baseline=await get('/api/v2/replay/sessions/'+old),inventory=await get('/api/v2/replay/sessions'),trades=await get('/api/v2/replay/trades'),prop=await get('/api/v2/prop/reports')
 report.oracle={catalog:inventory.items.length,trades:trades.ledger.length,readable:trades.scope.readable_session_count,scope:trades.scope.session_count,propReports:prop.items.length,old:{revision:baseline.revision,dataset_sha256:baseline.dataset_sha256,visibleRows:baseline.visible_rows?.length}}
 const routes=[['dashboard','view=overview&area=testing&section=dashboard&session='+old,'.fx-dashboard'],['sessions','view=replay&select=1&area=testing&section=sessions&session='+filled,'.fx-session-picker'],['trades','view=trade&area=testing&section=trades','[data-testid="aggregate-trades"]'],['analytics','view=analytics&area=testing&section=analytics&session='+filled,'[data-testid="analytics-workspace"]'],['prop','view=analytics&analytics_source=prop&area=testing&section=analytics','[data-testid="prop-analytics"]'],['market-data','view=market-data&area=testing&section=market-data','.market-data-workspace'],['live-calendar','view=live&area=live&section=calendar','.live-workspace'],['strategies','view=playbook&area=strategies&section=my-strategies','.pb-page'],['journal','view=journal&area=live&section=notes','.ja-page'],['learn','view=learn','.learn-shell'],['settings','view=settings','[data-testid="settings-workspace"]'],['research','view=research','.rs-shell'],['data-desk','view=data','.rd-shell'],['risk','view=risk','.risk-workspace']]
 for(const[name,q,selector]of routes)for(const theme of ['dark','light'])for(const width of [360,1440])await run(`${name}-${theme}-${width}`,()=>layout(name,q,selector,theme,width,['trades','analytics','prop'].includes(name)))
 await run('actual-trades-oracle',async()=>{await navigate('view=trade&area=testing&section=trades');await p.getByTestId('fx-trade-ledger').waitFor();assert.equal(await tradeRows().count(),trades.ledger.length);assert.equal(await p.locator('h1:not(.sr-only)').count(),0);assert.equal(await p.getByRole('button',{name:/Tải lại/i}).count(),0);assert.match(await p.getByTestId('aggregate-trades').innerText(),new RegExp(`${trades.scope.readable_session_count}/${trades.scope.session_count}`));assert.equal(await p.locator('.fxa-ledger-note').count(),0)})
 await run('demo-toggle-restore-real-context',async()=>{const q='view=trade&area=testing&section=trades&session='+filled+'&cursor=123&dataset=preserved-context';await navigate(q);const prior=new URL(p.url());const mark=report.apiRequests.length;await p.getByRole('button',{name:'Show demo data',exact:true}).click();await settle();assert.equal(new URL(p.url()).searchParams.get('demo'),'1');assert.equal(await tradeRows().count(),10);assert.match(await p.locator('.wm-demo-label').innerText(),/Dữ liệu mẫu/);assert.deepEqual(await rowIds(),defaultOrder(DEMO_LEDGER).slice(0,10));assert.equal(new URL(p.url()).searchParams.get('session'),filled);assert.equal(new URL(p.url()).searchParams.get('cursor'),'123');await p.reload({waitUntil:'networkidle'});await settle();assert.deepEqual(await rowIds(),defaultOrder(DEMO_LEDGER).slice(0,10));assert.equal(report.apiRequests.slice(mark).filter(x=>x.mode==='1').length,0);await p.getByRole('button',{name:'Show real data',exact:true}).click();await settle();assert.equal(new URL(p.url()).searchParams.get('demo'),null);for(const key of ['session','cursor','dataset'])assert.equal(new URL(p.url()).searchParams.get(key),prior.searchParams.get(key));assert.equal(await p.locator('.wm-demo-label').count(),0);assert.ok(!(await p.locator('.fx-content').innerText()).includes('demo-trade-'));assert.equal(await tradeRows().count(),1)})
 await run('demo-trades-pagination-sort-columns-selection',async()=>{await p.setViewportSize({width:1440,height:987});await navigate('view=trade&area=testing&section=trades&demo=1');assert.deepEqual(await rowIds(),defaultOrder(DEMO_LEDGER).slice(0,10));await p.getByRole('button',{name:'Trang sau',exact:true}).click();assert.deepEqual(await rowIds(),defaultOrder(DEMO_LEDGER).slice(10,20));await p.getByRole('button',{name:'Trang 6',exact:true}).click();assert.deepEqual(await rowIds(),defaultOrder(DEMO_LEDGER).slice(50,60));assert.ok(await p.getByRole('button',{name:'Trang sau',exact:true}).isDisabled());await select('Số dòng Trades','25');assert.equal(await tradeRows().count(),25);await p.getByRole('button',{name:/^Return \(USD\)/}).click();const sorted=[...DEMO_LEDGER].sort((a,b)=>a.net_pnl-b.net_pnl||DEMO_LEDGER.indexOf(a)-DEMO_LEDGER.indexOf(b)).map(x=>x.trade_id);assert.deepEqual(await rowIds(),sorted.slice(0,25));assert.equal(await p.locator('th[aria-sort="ascending"]').count(),1);await p.getByRole('checkbox',{name:'Chọn các lệnh trên trang',exact:true}).check();assert.match(await p.locator('.fxa-ledger-tools').innerText(),/25 đã chọn/);await p.getByRole('checkbox',{name:'Chọn các lệnh trên trang',exact:true}).uncheck();const first=(await rowIds())[0];await p.getByRole('button',{name:'Chi tiết '+first,exact:true}).click();await p.getByRole('region',{name:'Chi tiết giao dịch',exact:true}).waitFor();assert.equal(await p.locator('.fxa-trade-inspector a').count(),0);await p.getByRole('button',{name:'Đóng chi tiết',exact:true}).click();await p.getByRole('button',{name:'Cột hiển thị',exact:true}).click();await p.getByRole('checkbox',{name:'Entry price',exact:true}).check();assert.equal(await p.getByRole('button',{name:'Entry price',exact:true}).count(),1);await p.getByRole('button',{name:'Cột hiển thị',exact:true}).click();await p.screenshot({path:path.join(out,'demo-trades-desktop-details-sort.png')})})
 await run('demo-trades-filter-search-session-empty',async()=>{await navigate('view=trade&area=testing&section=trades&demo=1');await select('Số dòng Trades','100');await p.getByRole('button',{name:'Basic',exact:true}).click();await select('Side','buy');assert.deepEqual(await rowIds(),defaultOrder(DEMO_LEDGER.filter(x=>x.side==='buy')));await select('Outcome','win');assert.deepEqual(await rowIds(),defaultOrder(DEMO_LEDGER.filter(x=>x.side==='buy'&&x.net_pnl>0)));await select('Asset','EURUSD');assert.deepEqual(await rowIds(),defaultOrder(DEMO_LEDGER.filter(x=>x.side==='buy'&&x.net_pnl>0&&x.symbol==='EURUSD')));await p.getByRole('button',{name:'Xóa lọc',exact:true}).click();assert.equal(await tradeRows().count(),60);await p.getByRole('button',{name:'Mở tìm giao dịch',exact:true}).click();await p.getByRole('searchbox',{name:'Tìm giao dịch',exact:true}).fill('demo-trade-001');assert.deepEqual(await rowIds(),['demo-trade-001']);await p.getByRole('searchbox',{name:'Tìm giao dịch',exact:true}).fill('missing-no-match');assert.equal(await tradeRows().count(),0);assert.match(await p.getByTestId('fx-trade-ledger').innerText(),/Không có giao dịch khớp/);await p.getByRole('button',{name:'Xóa lọc',exact:true}).click();await p.getByRole('button',{name:'Tags',exact:true}).click();await select('Tags','review');assert.deepEqual(await rowIds(),defaultOrder(DEMO_LEDGER.filter(x=>x.tags.includes('review'))));await p.getByRole('button',{name:'Xóa lọc',exact:true}).click();await p.getByRole('button',{name:/^Session:/}).click();await p.getByRole('checkbox',{name:'Tất cả phiên',exact:true}).uncheck();await p.getByRole('checkbox',{name:/London Breakout/}).check();await p.keyboard.press('Escape');assert.deepEqual(await rowIds(),defaultOrder(DEMO_LEDGER.filter(x=>x.session_id==='demo-london')));assert.equal(new URL(p.url()).searchParams.get('session'),null);assert.equal(new URL(p.url()).searchParams.get('sessions'),null)})
 await run('analytics-inline-nav-mobile-scroll-reload-resize-switch',async()=>{await p.setViewportSize({width:360,height:987});await navigate('view=analytics&area=testing&section=analytics&analytics_source=prop&demo=1&session='+old);const expected=['Dashboard','Sessions','Trades','Analytics','Sessions','Prop firm','Market Data'];assert.deepEqual(await p.locator('.fx-subnav-primary a').allTextContents(),expected);const visible=async()=>{const box=await p.locator('.fx-subsubnav a[aria-current="page"]').boundingBox(),navbox=await p.locator('.fx-subnav').boundingBox();assert.ok(box.x>=navbox.x-1&&box.x+box.width<=navbox.x+navbox.width+1)};const sameRow=await p.locator('.fx-subnav-primary a').evaluateAll(els=>els.map(el=>el.getBoundingClientRect().y));assert.ok(Math.max(...sameRow)-Math.min(...sameRow)<1);await visible();await p.reload({waitUntil:'networkidle'});await settle();await visible();await p.setViewportSize({width:1440,height:987});await settle();await p.setViewportSize({width:360,height:987});await settle();await visible();await p.locator('.fx-subsubnav a').filter({hasText:'Sessions'}).click();await settle();assert.equal(new URL(p.url()).searchParams.get('analytics_source'),'sessions');assert.equal(new URL(p.url()).searchParams.get('demo'),'1');assert.equal(new URL(p.url()).searchParams.get('session'),old);await visible();await p.screenshot({path:path.join(out,'inline-analytics-session-source-mobile.png')});assert.deepEqual(await axe(),[])})
 await run('demo-routes-isolated-labels-gutters-accessibility',async()=>{const demos=[['dashboard','view=overview&area=testing&section=dashboard','.fx-dashboard'],['sessions','view=replay&select=1&area=testing&section=sessions','.fx-session-picker'],['trades','view=trade&area=testing&section=trades','.as-page'],['analytics','view=analytics&area=testing&section=analytics','.as-page'],['prop','view=analytics&analytics_source=prop&area=testing&section=analytics','.as-page'],['prop-practice','view=testing&area=testing&section=prop','.as-page'],['market-data','view=market-data&area=testing&section=market-data','.market-data-workspace'],['live-calendar','view=live&area=live&section=calendar','.live-workspace'],['live-trades','view=live&area=live&section=trades','.live-workspace'],['live-accounts','view=live&area=live&section=trading-accounts','.live-workspace'],['live-tags','view=live&area=live&section=tag-analytics','.as-page'],['live-notes','view=live&area=live&section=notes','.ja-page'],['strategies','view=playbook&area=strategies&section=my-strategies','.pb-page'],['journal','view=journal&area=live&section=notes','.ja-page']];const mark=report.apiRequests.length;for(const[name,q,selector]of demos)for(const theme of ['dark','light'])for(const width of [360,1440]){await run('demo-'+name+'-'+theme+'-'+width,async()=>{await layout('demo-'+name,q+'&demo=1',selector,theme,width,['trades','analytics','prop','sessions','market-data','live-tags','live-accounts','strategies','journal'].includes(name));assert.equal(await p.locator('.wm-demo-label').count(),1);if(['trades','analytics','prop','sessions'].includes(name))await p.screenshot({path:path.join(out,'demo-'+name+'-'+theme+'-'+width+'.png')});if(name==='market-data'){assert.equal(await p.locator('.market-data-workspace a').count(),0);assert.equal(await p.locator('.market-data-workspace button:not(:disabled)').count(),0)}})}assert.equal(report.apiRequests.slice(mark).length,0,'demo route read real data')})
 await run('old-session-unchanged',async()=>{const after=await get('/api/v2/replay/sessions/'+old);assert.deepEqual(after,baseline);report.preserved={revision:after.revision,wholePayloadEqual:true}})
 report.after=await hashes();report.sourceUnchanged=JSON.stringify(report.before)===JSON.stringify(report.after)
 assert.deepEqual(report.blocked,[]);assert.deepEqual(report.errors,[]);assert.deepEqual(report.failures,[]);report.pass=true
}catch(e){report.failure=String(e);report.after=await hashes();await p.screenshot({path:path.join(out,'failure.png'),fullPage:true}).catch(()=>{});process.exitCode=1;console.error(e)}finally{await c.unrouteAll({behavior:'wait'});await b.close();await writeFile(path.join(out,'browser.json'),JSON.stringify(report,null,2));console.log(JSON.stringify({pass:report.pass,cases:report.cases,checks:report.checks,failure:report.failure,errors:report.errors,blocked:report.blocked}))}
