import assert from 'node:assert/strict'
import {chromium} from '../../../foundation_v2/web/node_modules/playwright/index.mjs'
import {readFile,writeFile} from 'node:fs/promises'
import {createHash} from 'node:crypto'
import path from 'node:path'
const out=path.resolve('.artifacts/fx-trades-demo-layout-20261005/independent-review'),origin='http://127.0.0.1:5180',api='http://127.0.0.1:8010'
const report={cases:[],checks:[],errors:[],api:[],blocked:[],failures:[]}
const source=['DemoPreview.jsx','demoMode.js','demoFixtures.js','main.jsx','FxReplayShell.jsx','FxTradeLedger.jsx','FxAnalytics.jsx','JournalWorkspace.jsx','page-layout.css'].map(file=>'foundation_v2/web/src/'+file)
const hashes=()=>Promise.all(source.map(async file=>({file,sha256:createHash('sha256').update(await readFile(file)).digest('hex')})))
report.before=await hashes()
const b=await chromium.launch({headless:true}),c=await b.newContext({viewport:{width:1440,height:987}})
await c.route('**/*',async r=>{const q=r.request(),u=new URL(q.url());if(u.origin!==origin||!['GET','HEAD','OPTIONS'].includes(q.method())){report.blocked.push({method:q.method(),path:u.pathname});return r.abort()}if(!u.pathname.startsWith('/api/'))return r.continue();report.api.push({path:u.pathname,search:u.search,demo:new URL(q.frame().url()).searchParams.get('demo')});try{return await r.fulfill({response:await r.fetch({url:api+u.pathname+u.search})})}catch(e){if(!/ERR_ABORTED|Route is already handled/.test(String(e)))report.errors.push(String(e));try{return await r.abort()}catch{}}})
await c.routeWebSocket('**/*',s=>s.close());const p=await c.newPage();p.setDefaultTimeout(15000);p.on('pageerror',e=>report.errors.push(String(e)))
const settle=async()=>{await p.waitForLoadState('networkidle');await p.waitForFunction(()=>document.getAnimations().every(a=>a.playState!=='running'))}
const nav=async q=>{await p.goto(origin+'/?workspace=tenant-a&'+q,{waitUntil:'networkidle'});await settle()}
const axe=async()=>{await p.addScriptTag({path:'../../.artifacts/wm-integration-quality-tools/node_modules/axe-core/axe.min.js'});return p.evaluate(()=>window.axe.run(document,{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21aa','wcag22aa']}}).then(r=>r.violations.map(v=>({id:v.id,nodes:v.nodes.map(n=>({target:n.target,summary:n.failureSummary}))}))))}
const run=async(name,fn)=>{try{await fn();report.checks.push({name,pass:true})}catch(e){report.failures.push({name,error:String(e)});await p.screenshot({path:path.join(out,'focused-fail-'+name+'.png')}).catch(()=>{})}}
try{
 if (!process.argv.includes('--simulation-only')) {
 await run('toggle-real-ready',async()=>{await nav('view=trade&area=testing&section=trades&session=273a1275538c42cb95cfff16e0f9f62c&cursor=1061&dataset=dataset-7c63c3eb55e2e3b86522ea5e5bacbaede4f525de340a6aa555b86984484be2d4');await p.getByTestId('fx-trade-ledger').waitFor();assert.equal(await p.getByTestId('fx-trade-ledger').locator('tbody tr').count(),1);const prior=new URL(p.url()),mark=report.api.length;await p.getByRole('button',{name:'Show demo data',exact:true}).click();await settle();assert.equal(await p.getByTestId('fx-trade-ledger').locator('tbody tr').count(),10);await p.reload({waitUntil:'networkidle'});await settle();assert.equal(await p.getByTestId('fx-trade-ledger').locator('tbody tr').count(),10);assert.equal(report.api.slice(mark).filter(x=>x.demo==='1').length,0);await p.getByRole('button',{name:'Show real data',exact:true}).click();await p.getByTestId('fx-trade-ledger').waitFor();await settle();const url=new URL(p.url());for(const key of ['session','cursor','dataset'])assert.equal(url.searchParams.get(key),prior.searchParams.get(key));assert.equal(url.searchParams.get('demo'),null);assert.equal(await p.getByTestId('fx-trade-ledger').locator('tbody tr').count(),1);assert.equal(await p.locator('.wm-demo-label').count(),0);assert.ok(!(await p.locator('.fx-content').innerText()).includes('London Breakout'));await p.screenshot({path:path.join(out,'restored-real-trades-ready.png')})})
 for(const theme of ['dark','light'])for(const width of [360,1440])await run('settings-'+theme+'-'+width,async()=>{await p.setViewportSize({width,height:987});await nav('view=settings');if(await p.getByTestId('fxreplay-shell').getAttribute('data-theme')!==theme)await p.getByTestId('theme-toggle').click();await settle();const clip=await p.locator('.fx-content').boundingBox(),box=await p.getByTestId('settings-workspace').boundingBox(),gutter=width<=760?16:32;assert.equal(box.x-clip.x,gutter);assert.equal(clip.x+clip.width-box.x-box.width,gutter);assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth-innerWidth),0);assert.equal(await p.getByRole('button',{name:/Show (demo|real) data/}).count(),0);report.cases.push({name:'settings',theme,width,gutter,pass:true})})
 for(const route of ['journal','live-notes'])for(const theme of ['dark','light'])for(const width of [360,1440])await run(route+'-'+theme+'-'+width,async()=>{await p.setViewportSize({width,height:987});await nav('view='+(route==='journal'?'journal':'live')+'&area=live&section=notes&demo=1');if(await p.getByTestId('fxreplay-shell').getAttribute('data-theme')!==theme)await p.getByTestId('theme-toggle').click();await settle();await p.locator('.ja-story-rail').scrollIntoViewIfNeeded();assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth-innerWidth),0);const clip=await p.locator('.fx-content').boundingBox(),box=await p.locator('.ja-page').boundingBox(),gutter=width<=760?16:32;assert.equal(box.x-clip.x,gutter);assert.equal(clip.x+clip.width-box.x-box.width,gutter);const violations=await axe();report.cases.push({route,theme,width,violations});await p.screenshot({path:path.join(out,'focused-'+route+'-'+theme+'-'+width+'.png')});assert.deepEqual(violations,[])})
 }
 await run('demo-analytics-report-tabs-simulation',async()=>{await p.setViewportSize({width:1440,height:987});await nav('view=analytics&area=testing&section=analytics&analytics_source=sessions&demo=1');await p.getByRole('tab',{name:'Drawdown',exact:true}).click();await p.getByTestId('analytics-drawdown').waitFor();await settle();assert.equal(new URL(p.url()).searchParams.get('analytics_tab'),null);assert.equal(await p.getByRole('tab',{name:'Drawdown',exact:true}).getAttribute('aria-selected'),'true');await p.getByRole('tab',{name:'Simulation',exact:true}).click();await p.getByTestId('analytics-simulation').waitFor();const config=await p.getByRole('button',{name:'Chạy SL / RR',exact:true}).getAttribute('title');assert.match(config,/price.path|đường giá|preview/i);assert.ok(await p.getByRole('button',{name:'Chạy SL / RR',exact:true}).isDisabled());for(const label of ['Stop distance (ticks)','Stop multiplier','Target R'])assert.notEqual(await p.getByRole('spinbutton',{name:label,exact:true}).inputValue(),'');await p.getByRole('button',{name:'Chạy Monte Carlo',exact:true}).click();await p.getByText('Average balance',{exact:true}).waitFor();await p.locator('[data-testid="analytics-simulation"]').scrollIntoViewIfNeeded();await settle();await p.screenshot({path:path.join(out,'demo-montecarlo-local.png')});assert.deepEqual(await axe(),[])})
 report.after=await hashes();report.sourceUnchanged=JSON.stringify(report.before)===JSON.stringify(report.after);assert.deepEqual(report.errors,[]);assert.deepEqual(report.blocked,[]);assert.deepEqual(report.failures,[]);assert.ok(report.sourceUnchanged);report.pass=true
}catch(e){report.failure=String(e);process.exitCode=1}finally{await c.unrouteAll({behavior:'wait'});await b.close();await writeFile(path.join(out,'focused.json'),JSON.stringify(report,null,2));console.log(JSON.stringify({pass:report.pass,checks:report.checks,failures:report.failures,errors:report.errors,blocked:report.blocked,sourceUnchanged:report.sourceUnchanged}))}
