import assert from 'node:assert/strict'
import {chromium} from '../../../foundation_v2/web/node_modules/playwright/index.mjs'
import {mkdir,writeFile} from 'node:fs/promises'
import path from 'node:path'
const out=path.resolve('.artifacts/fx-trades-demo-layout-20261005/independent-review'), origin='http://127.0.0.1:5180',api='http://127.0.0.1:8010'
await mkdir(out,{recursive:true})
const report={cases:[],errors:[],api:[],blocked:[],failures:[]}
const b=await chromium.launch({headless:true}),c=await b.newContext({viewport:{width:360,height:987}})
await c.route('**/*',async r=>{const q=r.request(),u=new URL(q.url());if(u.origin!==origin||!['GET','HEAD','OPTIONS'].includes(q.method())){report.blocked.push({method:q.method(),path:u.pathname});return r.abort()}if(!u.pathname.startsWith('/api/'))return r.continue();report.api.push({path:u.pathname,search:u.search,demo:new URL(q.frame().url()).searchParams.get('demo')});try{return await r.fulfill({response:await r.fetch({url:api+u.pathname+u.search})})}catch(e){if(!/ERR_ABORTED|Route is already handled/.test(String(e)))report.errors.push(String(e));try{return await r.abort()}catch{}}})
await c.routeWebSocket('**/*',s=>s.close());const p=await c.newPage();p.setDefaultTimeout(12000);p.on('pageerror',e=>report.errors.push(String(e)))
const settle=async()=>{await p.waitForLoadState('networkidle');await p.waitForFunction(()=>document.getAnimations().every(a=>a.playState!=='running'))}
const routes=[['dashboard','view=overview&area=testing&section=dashboard','.fx-dashboard'],['sessions','view=replay&select=1&area=testing&section=sessions','.fx-session-picker'],['trades','view=trade&area=testing&section=trades','.as-page'],['analytics','view=analytics&area=testing&section=analytics','.as-page'],['prop','view=analytics&analytics_source=prop&area=testing&section=analytics','.as-page'],['market-data','view=market-data&area=testing&section=market-data','.market-data-workspace'],['live-calendar','view=live&area=live&section=calendar','.live-workspace'],['live-trades','view=live&area=live&section=trades','.live-workspace'],['strategies','view=playbook&area=strategies&section=my-strategies','.pb-page'],['journal','view=journal&area=live&section=notes','.ja-page']]
try{
for(const[name,q,selector]of routes){try{await p.goto(origin+'/?workspace=tenant-a&demo=1&'+q,{waitUntil:'networkidle'});await settle();await p.locator(selector).waitFor();assert.match(await p.locator('.wm-demo-label').innerText(),/Dữ liệu mẫu/);assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth-innerWidth),0);const clip=await p.locator('.fx-content').boundingBox(),content=await p.locator(selector).first().boundingBox();const gutters={left:content.x-clip.x,right:clip.x+clip.width-content.x-content.width};assert.ok(Math.abs(gutters.left-16)<1.1&&Math.abs(gutters.right-16)<1.1,JSON.stringify(gutters));await p.screenshot({path:path.join(out,'smoke-'+name+'-360.png')});report.cases.push({name,gutters,pass:true});if(name==='prop'){const nav=await p.locator('.fx-subnav a').evaluateAll(els=>els.map(el=>({text:el.textContent.trim(),current:el.getAttribute('aria-current'),r:{x:el.getBoundingClientRect().x,y:el.getBoundingClientRect().y,w:el.getBoundingClientRect().width}})));report.nav=nav;const source=p.locator('.fx-subsubnav a[aria-current="page"]');const box=await source.boundingBox(),navbox=await p.locator('.fx-subnav').boundingBox();assert.ok(box.x>=navbox.x-1&&box.x+box.width<=navbox.x+navbox.width+1,'selected source is clipped');assert.equal(new Set(nav.map(x=>x.r.y)).size,1,'nav not one row')}}catch(e){report.failures.push({name,error:String(e)});await p.screenshot({path:path.join(out,'smoke-fail-'+name+'.png')}).catch(()=>{})}}
await p.goto(origin+'/?workspace=tenant-a&demo=1&view=market-data&area=testing&section=market-data',{waitUntil:'networkidle'});await settle();assert.equal(await p.locator('.market-data-workspace a').count(),0);assert.equal(await p.locator('.market-data-workspace button:not(:disabled)').count(),0);report.checks=['Market demo no chart links and no enabled update/history buttons']
assert.equal(report.api.filter(x=>x.demo==='1').length,0,'real API reads during explicit demo');assert.deepEqual(report.blocked,[]);assert.deepEqual(report.errors,[]);assert.deepEqual(report.failures,[]);report.pass=true
}catch(e){report.failure=String(e);process.exitCode=1}finally{await c.unrouteAll({behavior:'wait'});await b.close();await writeFile(path.join(out,'smoke.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report))}
