import assert from 'node:assert/strict'
import { chromium } from 'playwright'
import { mkdir, writeFile } from 'node:fs/promises'
import path from 'node:path'

const out = path.resolve(process.env.TW_UI_EVIDENCE_DIR || '../evidence/fx-controls-refinement-20261006/primary')
await mkdir(out, { recursive: true })
// Native scrollbar dragging needs Chromium's default headless hiding disabled.
const browser = await chromium.launch({ ignoreDefaultArgs: ['--hide-scrollbars'] })
const page = await browser.newPage({ viewport: { width: 1571, height: 987 } })
page.setDefaultTimeout(10000)
const errors = [], writes = [], checks = []
page.on('pageerror', error => errors.push(error.message))
await page.route('**/api/**', route => {
  if (!['GET', 'HEAD', 'OPTIONS'].includes(route.request().method())) { writes.push(route.request().method()); return route.abort() }
  return route.continue()
})
const visit = async (view, demo = true, params = '') => {
  await page.goto(`http://127.0.0.1:5180/?workspace=tenant-a&view=${view}&area=testing&section=${view === 'trade' ? 'trades' : view === 'replay' ? 'sessions' : view}&select=1${demo ? '&demo=1' : ''}${params}`)
  await page.getByTestId('fxreplay-shell').waitFor()
}
const button = name => page.getByRole('button', { name, exact: true })
const trades = () => page.locator('.fxa-metric').filter({ has: page.locator('span', { hasText: /^Total trades$/ }) }).locator('strong')
const screenshot = name => page.screenshot({ path: path.join(out, name + '.png'), fullPage: true, animations: 'disabled' })
try {
  await visit('analytics')
  await trades().waitFor()
  assert.equal(await trades().innerText(), '20')
  assert.equal(await page.locator('.fxa-report-scope').count(), 0)
  await button('Type').click()
  const type = page.getByRole('dialog', { name: 'Type' })
  assert.equal(await type.locator('h3').innerText(), 'Type filter')
  assert.ok(await type.getByRole('option', { name: /Battles/ }).isDisabled())
  await type.getByRole('option', { name: 'App', exact: true }).click()
  assert.equal(await trades().innerText(), '20', 'draft has no report effect')
  await button('Apply').click()
  assert.equal(await trades().innerText(), '0', 'Prop filter must not relabel App data')
  await button('Clear filters').click()
  assert.equal(await trades().innerText(), '20')
  checks.push('Type search/checklist, disabled Battles, draft Apply and scoped source filtering')

  await button('Time').click()
  const time = page.getByRole('dialog', { name: 'Time filter', exact: true })
  await time.getByLabel('Time Start', { exact: true }).fill('00:00')
  await time.getByLabel('Time End', { exact: true }).fill('23:59')
  await screenshot('time-range')
  await button('Apply').click()
  assert.equal(await trades().innerText(), '20')
  await button('Time').click()
  await time.getByLabel('Time Start', { exact: true }).fill('09:16')
  await time.getByLabel('Time End', { exact: true }).fill('09:16')
  await button('Apply').click()
  assert.equal(await trades().innerText(), '0')
  await button('Clear filters').click()
  checks.push('Time HH:mm Start/End apply to report; clear restores original count')

  await button('Timezone').click()
  const zone = page.getByRole('dialog', { name: 'Timezone', exact: true })
  const list = zone.getByRole('listbox')
  assert.ok(await list.evaluate(e => e.scrollHeight > e.clientHeight))
  const box = await list.boundingBox()
  const scroll = await list.evaluate(e => ({ height: e.clientHeight, full: e.scrollHeight, gutter: e.offsetWidth - e.clientWidth }))
  assert.ok(scroll.gutter > 2, 'scrollbar owns a visible hit area')
  const scrollbarX = box.x + box.width - scroll.gutter / 2
  await page.mouse.click(scrollbarX, box.y + box.height * .6)
  assert.ok(await zone.isVisible(), 'click scrollbar keeps dropdown open')
  await page.waitForFunction(() => document.querySelector('.fx-select-menu [role="listbox"]')?.scrollTop > 0)
  // Chromium animates native track scrolling before the thumb is stationary.
  await page.waitForTimeout(250)
  const trackScroll = await list.evaluate(e => e.scrollTop)
  assert.ok(trackScroll > 0, 'native track click scrolls')
  const trackHeight = scroll.height - 2 * scroll.gutter
  const thumb = Math.max(18, trackHeight * scroll.height / scroll.full)
  const thumbY = box.y + scroll.gutter + trackScroll / (scroll.full - scroll.height) * (trackHeight - thumb) + thumb / 2
  await page.mouse.move(scrollbarX, thumbY)
  await page.mouse.down(); await page.mouse.move(scrollbarX, thumbY + 70, { steps: 8 }); await page.mouse.up()
  assert.ok(await zone.isVisible(), 'drag scrollbar keeps dropdown open')
  await page.waitForFunction(before => document.querySelector('.fx-select-menu [role="listbox"]')?.scrollTop > before, trackScroll)
  assert.ok(await list.evaluate(e => e.scrollTop) > trackScroll, 'native thumb drag scrolls')
  await list.hover(); await page.mouse.wheel(0, 500)
  await page.waitForFunction(() => document.querySelector('.fx-select-menu [role="listbox"]')?.scrollTop > 0)
  assert.ok(await list.evaluate(e => e.scrollTop > 0))
  await list.getByRole('option').last().focus()
  await page.keyboard.press('Tab')
  assert.equal(await zone.count(), 0, 'Tab outside still closes after scrollbar interaction')
  await button('Timezone').click()
  await zone.getByRole('searchbox', { name: 'Tìm Timezone' }).fill('Ho Chi')
  await zone.getByRole('option', { name: /Ho Chi Minh/ }).click()
  assert.equal(await page.locator('.fxa-filter-chips').getByText('Timezone · Asia/Ho_Chi_Minh').count(), 0)
  await button('Apply').click()
  await page.locator('.fxa-filter-chips').getByText('Timezone · Asia/Ho_Chi_Minh').waitFor()
  await button('Timezone').click(); await screenshot('timezone-searchable'); await page.keyboard.press('Escape')
  checks.push('Timezone searchable IANA cities, scrollbar drag/wheel, draft/apply, Escape')

  await button('Backtesting Date').click()
  const calendar = page.getByRole('dialog', { name: 'Backtesting date filter' })
  await calendar.getByLabel('Analytics from date', { exact: true }).fill('2026-07-01')
  await calendar.getByRole('button', { name: '2026-07-06', exact: true }).click()
  await calendar.getByRole('button', { name: '2026-07-09', exact: true }).click()
  assert.equal(await calendar.getByLabel('Analytics from date').inputValue(), '2026-07-06')
  assert.equal(await calendar.getByLabel('Analytics to date').inputValue(), '2026-07-09')
  await screenshot('calendar-range')
  await button('Apply').click()
  await page.locator('.fxa-filter-chips').getByText('2026-07-06 → 2026-07-09').waitFor()
  await button('Clear filters').click()
  checks.push('Calendar endpoints, range selection and Apply/clear')

  await visit('trade', true, '&sessions=all')
  await page.locator('.fxa-detail-button').first().waitFor()
  for (const control of [button('Reset table columns'), button('Cột hiển thị'), page.locator('.fxa-detail-button').first()]) {
    const css = await control.evaluate(e => { const box = e.getBoundingClientRect(); return { w: box.width, h: box.height, radius: getComputedStyle(e).borderRadius } })
    assert.ok(Math.abs(css.w - css.h) < 1, JSON.stringify(css)); assert.equal(css.radius, '50%')
  }
  const size = button('Số dòng Trades')
  const centers = await size.evaluate(e => [...e.children].map(child => { const r = child.getBoundingClientRect(); return r.y + r.height / 2 }))
  assert.ok(Math.abs(centers[0] - centers[1]) < 1)
  await page.getByRole('button', { name: 'Session: Tất cả phiên', exact: true }).click()
  const all = page.getByRole('checkbox', { name: 'Tất cả phiên', exact: true })
  const allBox = await all.boundingBox()
  await all.click({ position: { x: allBox.width - 12, y: allBox.height / 2 } })
  assert.equal(await all.getAttribute('aria-checked'), 'false')
  assert.equal(await page.locator('.fxa-table-scroll tbody tr').count(), 0)
  await all.click({ position: { x: 120, y: 20 } })
  assert.equal(await all.getAttribute('aria-checked'), 'true')
  assert.equal(await page.locator('.fxa-table-scroll tbody tr').count(), 10)
  await page.keyboard.press('Escape'); await size.click()
  await page.getByRole('option', { name: '25', exact: true }).click()
  assert.equal(await page.locator('.fxa-table-scroll tbody tr').count(), 25)
  await screenshot('trade-circles-pagination')
  checks.push('Circular icon hit areas, pagination alignment, All full-row click, page size')

  await visit('replay', false)
  await button('Chọn phiên replay').click()
  assert.equal(await page.getByRole('option', { name: 'Chọn phiên replay', exact: true }).count(), 0)
  assert.ok(await page.getByRole('option').count() > 0)
  await page.keyboard.press('Escape')
  await page.locator('.fxs-metric-info svg').first().waitFor()
  checks.push('Actual catalog contains real session options only; info glyph replaced by SVG')

  for (const width of [1440, 768, 360]) for (const theme of ['dark', 'light']) {
    await page.setViewportSize({ width, height: 987 })
    await visit('analytics')
    if (await page.getByTestId('fxreplay-shell').getAttribute('data-theme') !== theme) await page.getByTestId('theme-toggle').click()
    for (const name of ['Type', 'Time', 'Timezone', 'Backtesting Date']) {
      const content = await page.locator('.fx-content').evaluate(e => ({ left: e.getBoundingClientRect().left, width: e.clientWidth, scrollWidth: e.scrollWidth }))
      await button(name).click()
      const popup = page.locator('.fx-select-menu:visible, .fx-filter-popover:visible')
      const r = await popup.boundingBox()
      assert.ok(r.x >= 0 && r.x + r.width <= width + 1 && r.y >= 0 && r.y + r.height <= 988, `${name}/${width}/${theme}: ${JSON.stringify(r)}`)
      assert.ok(r.x + r.width <= content.left + content.width + 1, `${name}/${width}/${theme}: popup must fit content excluding native scrollbar`)
      assert.ok(await page.locator('.fx-content').evaluate((e, baseline) => e.scrollWidth <= baseline + 1, content.scrollWidth), `${name}/${width}/${theme}: popup must not increase horizontal scrolling`)
      await screenshot(`${name.replaceAll(' ', '-')}-${theme}-${width}`)
      await page.keyboard.press('Escape')
    }
    const child = page.locator('.fx-subsubnav a').first()
    await child.hover()
    assert.notEqual(await child.evaluate(e => getComputedStyle(e).borderRadius), '0px')
  }
  checks.push('Four filter popovers fit 360/768/1440 dark/light, rounded subnav hover')
  assert.deepEqual(errors, []); assert.deepEqual(writes, [])
  await writeFile(path.join(out, 'report.json'), JSON.stringify({ checks, errors, writes }, null, 2))
  console.log(JSON.stringify({ passed: checks.length, errors, writes }))
} catch (error) {
  await screenshot('failure')
  await writeFile(path.join(out, 'failure.json'), JSON.stringify({ error: error.stack, checks, errors, writes }, null, 2))
  throw error
} finally { await browser.close() }
