import assert from 'node:assert/strict'
import { chromium } from 'playwright'
import { mkdir, writeFile } from 'node:fs/promises'
import path from 'node:path'

const out = path.resolve(process.env.TW_UI_EVIDENCE_DIR || '../evidence/fx-user-refinements-20261005/dashboard')
await mkdir(out, { recursive: true })
const browser = await chromium.launch({ headless: true })
const page = await browser.newPage({ viewport: { width: 1571, height: 987 } })
const errors = [], writes = [], checks = []
page.on('pageerror', error => errors.push(error.message))
await page.route('**/api/**', route => {
  if (!['GET', 'HEAD', 'OPTIONS'].includes(route.request().method())) { writes.push(route.request().method()); return route.abort() }
  return route.continue()
})
const home = 'http://127.0.0.1:5180/?workspace=tenant-a&view=overview&area=testing&section=dashboard'
const drawer = () => page.getByRole('dialog', { name: 'Session Settings', exact: true })
const actualId = '476f4b498e1a49ed9d48a75719f4d270'
try {
  await page.goto(home + '&demo=1'); await page.waitForLoadState('networkidle')
  await page.getByRole('button', { name: 'Thời gian Performance', exact: true }).click()
  await page.getByRole('option', { name: 'Khoảng tùy chọn', exact: true }).click()
  const inputs = page.locator('.fx-dashboard-date-controls input')
  const period = await page.getByRole('button', { name: 'Thời gian Performance', exact: true }).boundingBox()
  const first = await inputs.first().boundingBox(), second = await inputs.last().boundingBox()
  await page.screenshot({ path: path.join(out, 'dashboard-custom-dates-dark.png'), fullPage: true })
  assert.ok(Math.abs(first.y - period.y) < 2 && Math.abs(second.y - period.y) < 2, 'dates align with filters: ' + JSON.stringify({ period, first, second }))
  assert.ok(first.x > period.x && second.x > first.x, 'dates stay at right')
  await page.screenshot({ path: path.join(out, 'dashboard-custom-dates-dark.png'), fullPage: true })
  checks.push('Custom date inputs align on the right with Performance filters at1571px')
  const search = page.getByRole('searchbox', { name: 'Tìm phiên gần đây', exact: true })
  await search.focus()
  const style = await search.evaluate(element => { const css = getComputedStyle(element); return [css.outlineStyle, css.boxShadow, css.borderRadius] })
  assert.deepEqual(style, ['none', 'none', '999px'])
  checks.push('Recent search uses one pill border with no protruding focus ring')
  await page.getByRole('button', { name: 'Sửa Gold Swing', exact: true }).click()
  await drawer().waitFor()
  assert.equal(await drawer().getByRole('tab').count(), 4)
  await drawer().getByLabel('Name', { exact: true }).fill('Gold Swing revised')
  await drawer().getByLabel('Description', { exact: true }).fill('Demo settings edit')
  await drawer().getByRole('button', { name: 'Save Changes', exact: true }).click()
  assert.equal(await drawer().count(), 0)
  await page.getByRole('heading', { name: /Gold Swing revised/ }).waitFor()
  checks.push('Dashboard Settings uses shared4tab drawer; demo saves name/description locally')
  await page.getByRole('button', { name: 'Thao tác Gold Swing revised', exact: true }).click()
  await page.getByRole('menuitem', { name: 'Lưu trữ phiên', exact: true }).click()
  const archive = page.getByRole('dialog', { name: 'Lưu trữ phiên', exact: true })
  await archive.getByRole('button', { name: 'Lưu trữ', exact: true }).click()
  assert.equal(await page.getByRole('heading', { name: /Gold Swing revised/ }).count(), 0)
  await page.getByRole('button', { name: 'Hiện bộ lọc phiên', exact: true }).click()
  await page.getByRole('button', { name: 'Trạng thái phiên', exact: true }).click()
  await page.getByRole('option', { name: 'Đã lưu trữ', exact: true }).click()
  await page.getByRole('button', { name: 'Thao tác Gold Swing revised', exact: true }).click()
  await page.getByRole('menuitem', { name: 'Khôi phục phiên', exact: true }).click()
  await page.getByRole('dialog', { name: 'Khôi phục phiên', exact: true }).getByRole('button', { name: 'Khôi phục', exact: true }).click()
  checks.push('Demo archive hides active card; archived filter allows restoration without deletion')
  await page.goto(home + '&demo=1'); await page.waitForLoadState('networkidle')
  await page.getByRole('link', { name: 'Summary Gold Swing', exact: true }).click()
  await page.locator('.fxr-session-summary-card h2').waitFor()
  assert.equal(new URL(page.url()).searchParams.get('demo_session'), 'demo-gold')
  assert.equal(await page.locator('.fxr-session-summary-card h2').textContent(), 'Gold Swing')
  assert.equal(await page.getByRole('dialog').count(), 0)
  await page.getByRole('button', { name: 'Sửa mô tả', exact: true }).click()
  await page.getByRole('textbox', { name: 'Mô tả phiên', exact: true }).fill('Description only demo edit')
  await page.getByRole('button', { name: 'Save', exact: true }).click()
  assert.equal(await page.locator('.fxr-session-description').textContent(), 'Description only demo edit')
  await page.getByRole('button', { name: 'Cài đặt phiên', exact: true }).click()
  await drawer().getByRole('tab', { name: 'Date Range', exact: true }).click()
  assert.equal(await drawer().getByRole('textbox', { name: 'Replay position · UTC', exact: true }).getAttribute('readonly'), '')
  await page.keyboard.press('Escape')
  await page.screenshot({ path: path.join(out, 'demo-gold-sessions-dark.png'), fullPage: true })
  checks.push('Summary navigates to selected Gold demo Sessions; shared cards/description edit/readonly range work')
  await page.goto(home); await page.waitForLoadState('networkidle')
  const card = page.locator(`[data-session-id="${actualId}"]`)
  await card.locator('.fx-dashboard-days').waitFor()
  assert.equal((await card.locator('.fx-dashboard-days').textContent()).trim(), '91 days')
  assert.equal((await card.locator('.fx-dashboard-card-progress small').textContent()).trim(), 'Remaining 91 days')
  await card.getByRole('link', { name: /^Summary / }).click()
  await page.locator('.fxr-session-summary-card').waitFor()
  assert.equal(new URL(page.url()).searchParams.get('session'), actualId)
  await page.waitForFunction(() => document.querySelector('.fxs-remaining')?.textContent.includes('91 ngày'))
  assert.match(await page.locator('.fxs-remaining').textContent(), /91 ngày/)
  assert.equal(await page.locator('.fxs-balance strong').textContent(), '—')
  checks.push('Actual no-init session91calendar days from canonical cutoff; Summary correct id; balance stays unknown')
  for (const width of [768, 390]) {
    await page.setViewportSize({ width, height: 844 }); await page.goto(home + '&demo=1'); await page.waitForLoadState('networkidle')
    await page.getByRole('button', { name: 'Thời gian Performance', exact: true }).click(); await page.getByRole('option', { name: 'Khoảng tùy chọn', exact: true }).click()
    assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1), `no page overflow at${width}`)
    const dates = page.locator('.fx-dashboard-date-controls')
    const bounds = await dates.boundingBox()
    assert.ok(bounds.x >= 0 && bounds.x + bounds.width <= width + 1)
    await page.screenshot({ path: path.join(out, `dashboard-custom-${width}.png`), fullPage: true })
  }
  checks.push('Custom dates/dashboard responsive without page overflow at768px and390px')
  assert.deepEqual(writes, []); assert.deepEqual(errors, [])
  await writeFile(path.join(out, 'report.json'), JSON.stringify({ checks, errors, blockedWrites: writes, actualWrites: 0 }, null, 2))
  console.log(JSON.stringify({ passed: checks.length, errors, writes, out }))
} finally { await browser.close() }
