import assert from 'node:assert/strict'
import { chromium } from 'playwright'
import { mkdir, writeFile } from 'node:fs/promises'
import path from 'node:path'

const out = path.resolve(process.env.TW_FILTER_QA_OUT || '../../.artifacts/fx-filter-toolbar-20261005/primary')
await mkdir(out, { recursive: true })
const browser = await chromium.launch({ headless: true })
const page = await browser.newPage({ viewport: { width: 1710, height: 987 } })
const errors = [], writes = [], demoReads = [], checks = []
page.on('pageerror', error => errors.push(error.message))
await page.route('**/api/**', async route => {
  if (route.request().method() !== 'GET') { writes.push(route.request().method()); await route.abort(); return }
  if (new URL(page.url()).searchParams.get('demo') === '1') demoReads.push(route.request().url())
  await route.continue()
})
const owner = '476f4b498e1a49ed9d48a75719f4d270'
const analytics = `http://127.0.0.1:5180/?workspace=tenant-a&view=analytics&area=testing&section=analytics&select=1&session=${owner}&cursor=500`
const goto = async url => { await page.goto(url); await page.waitForLoadState('networkidle') }
const choose = async (label, option) => { await page.getByRole('button', { name: label, exact: true }).click(); await page.getByRole('option', { name: option, exact: true }).click() }
const metric = () => page.locator('.fxa-metric').filter({ has: page.locator('span', { hasText: /^Total trades$/ }) }).locator('strong')
try {
  await goto('http://127.0.0.1:5180/?workspace=tenant-a&view=trade&area=testing&section=trades&sessions=all&demo=1')
  const columns = page.getByRole('button', { name: 'Cột hiển thị', exact: true })
  const filter = await page.locator('.fxa-filter-toolbar').boundingBox(), pencil = await columns.boundingBox()
  assert.ok(Math.abs(pencil.y + pencil.height / 2 - filter.y - filter.height / 2) < 2)
  await columns.click()
  await page.getByRole('searchbox', { name: 'Tìm Cột hiển thị' }).fill('Fees')
  await page.getByRole('option', { name: 'Fees', exact: true }).click()
  await page.getByRole('columnheader', { name: 'Fees', exact: true }).waitFor()
  await page.keyboard.press('Escape'); await columns.focus()
  assert.equal(await columns.getAttribute('aria-expanded'), 'false')
  await columns.click()
  await page.getByRole('checkbox', { name: 'Chọn tất cả', exact: true }).check()
  assert.equal(await page.locator('thead th').count(), 23)
  await page.getByRole('checkbox', { name: 'Chọn tất cả', exact: true }).uncheck()
  assert.equal(await page.locator('thead th').count(), 2)
  await page.getByRole('checkbox', { name: 'Chọn tất cả', exact: true }).check()
  await page.locator('h1').click({ force: true }).catch(() => page.keyboard.press('Escape'))
  await page.keyboard.press('Escape')
  checks.push('pencil shares filter row; column search/select-all changes table; Escape')

  await goto(analytics + '&demo=1')
  const original = page.url()
  await choose('Side', 'Buy')
  assert.equal(await metric().textContent(), '20')
  assert.equal(await page.getByRole('button', { name: 'Bỏ lọc Side' }).count(), 0)
  await page.getByRole('button', { name: 'Apply', exact: true }).click()
  assert.equal(await metric().textContent(), '10')
  await page.getByRole('button', { name: 'Bỏ lọc Side' }).waitFor()
  assert.equal(page.url(), original)
  await page.getByRole('button', { name: /^Session:/ }).click()
  await page.getByRole('button', { name: /Gold Swing/ }).click()
  assert.match(await page.locator('.fxa-filter-chips').textContent(), /London Breakout/)
  await page.getByRole('button', { name: 'Apply', exact: true }).click()
  assert.match(await page.locator('.fxa-filter-chips').textContent(), /Gold Swing/)
  assert.equal(await metric().textContent(), '10')
  assert.equal(page.url(), original)
  await page.getByRole('button', { name: 'Clear filters', exact: true }).click()
  assert.equal(await metric().textContent(), '20')
  await page.getByRole('button', { name: 'Backtesting Date', exact: true }).click()
  await page.getByLabel('Analytics from date', { exact: true }).fill('2026-09-30')
  await page.getByLabel('Analytics to date', { exact: true }).fill('2026-09-01')
  assert.equal(await page.getByRole('button', { name: 'Apply', exact: true }).isDisabled(), true)
  await page.getByLabel('Analytics from date', { exact: true }).fill('')
  await page.getByLabel('Analytics to date', { exact: true }).fill('')
  await page.keyboard.press('Escape')
  checks.push('demo Side/Session deferred until Apply; chips/clear/date validation; real URL untouched')

  for (const theme of ['dark', 'light']) for (const width of [360, 1440, 1710]) {
    await page.setViewportSize({ width, height: 987 })
    await page.evaluate(theme => localStorage.setItem('tw-theme', theme), theme)
    await goto(analytics + '&demo=1&analytics_source=prop')
    assert.equal(await page.locator('.fx-app').getAttribute('data-theme'), theme)
    const action = await page.locator('.fx-subnav-action').boundingBox(), nav = await page.locator('.fx-subnav').boundingBox()
    assert.ok(action.x >= nav.x && action.x + action.width <= width + 1)
    assert.ok(Math.abs(action.y + action.height / 2 - nav.y - nav.height / 2) < 2)
    const selected = await page.locator('.fx-subsubnav a[aria-current=page]').boundingBox()
    const scrolling = await page.locator('.fx-subnav-primary').boundingBox()
    assert.ok(selected.x >= scrolling.x - 1 && selected.x + selected.width <= scrolling.x + scrolling.width + 1)
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false)
    assert.equal(await page.locator('.fx-content .wm-demo-action').count(), 0)
    await page.getByRole('button', { name: 'Session: London Breakout' }).click()
    const popup = await page.getByRole('dialog', { name: 'Chọn session' }).boundingBox()
    const content = await page.locator('.fx-content').boundingBox()
    assert.ok(popup.x >= content.x && popup.x + popup.width <= width)
    await page.keyboard.press('Escape')
    await page.screenshot({ path: path.join(out, `analytics-${theme}-${width}.png`) })
  }
  checks.push('six desktop/mobile theme cases: right subnav action; visible selected source; bounded Session popup; no document overflow')

  await page.setViewportSize({ width: 1440, height: 987 })
  await goto(analytics)
  await page.getByTestId('analytics-blocked').waitFor()
  assert.equal(await page.getByRole('button', { name: 'Xuất CSV', exact: true }).isDisabled(), true)
  await choose('Side', 'Sell')
  await page.getByRole('button', { name: /^Session:/ }).click()
  const empty = await page.request.get('http://127.0.0.1:5180/api/v2/replay/sessions', { headers: { 'X-Workspace-Id': 'tenant-a' } })
  const catalog = await empty.json()
  const item = catalog.items.find(item => item.record_id === 'd70ee54946144605bf20ba5b8e2f4cdf')
  assert.ok(item)
  await page.getByRole('dialog', { name: 'Chọn session' }).getByRole('button').filter({ hasText: item.name }).click()
  assert.equal(new URL(page.url()).searchParams.get('session'), owner)
  await page.getByRole('button', { name: 'Apply', exact: true }).click()
  await page.waitForLoadState('networkidle')
  assert.equal(new URL(page.url()).searchParams.get('session'), item.record_id)
  assert.equal(new URL(page.url()).searchParams.get('side'), 'sell')
  assert.equal(new URL(page.url()).searchParams.has('cursor'), false)
  await page.reload(); await page.waitForLoadState('networkidle')
  assert.match(await page.locator('.fxa-filter-chips').textContent(), /Side · sell/)
  checks.push('real applied filters survive Session report remount/reload; old execution cursor removed')
  await goto('http://127.0.0.1:5180/?workspace=tenant-a&view=trade&area=testing&section=trades&sessions=all')
  await page.getByTestId('fx-trade-ledger').waitFor({ state: 'visible' })
  assert.equal(await page.getByText(/Dữ liệu một phần/).count(), 0)
  await page.getByRole('button', { name: 'Cột hiển thị', exact: true }).waitFor()
  checks.push('real aggregate Trades retains table with no visible partial badge')
  assert.deepEqual(errors, []); assert.deepEqual(writes, []); assert.deepEqual(demoReads, [])
  await writeFile(path.join(out, 'report.json'), JSON.stringify({ status: 'PASS', checks, errors, writes, demoReads }, null, 2))
  console.log(JSON.stringify({ status: 'PASS', checks }))
} catch (error) {
  await page.screenshot({ path: path.join(out, 'failure.png') }).catch(() => {})
  await writeFile(path.join(out, 'failure.json'), JSON.stringify({ error: error.stack, checks, errors, writes, demoReads }, null, 2))
  throw error
} finally { await browser.close() }
