import assert from 'node:assert/strict'
import { mkdir, readFile, writeFile, readdir } from 'node:fs/promises'
import { createHash } from 'node:crypto'
import path from 'node:path'
import { chromium } from 'playwright'
import { monteCarlo } from '../src/analyticsSimulation.js'
const apiData = await (await fetch('http://127.0.0.1:8020/api/v2/replay/sessions/39b1d068edd64e75864f692f27237852/analytics', { headers: { 'X-Workspace-Id': 'tenant-a' } })).json()
const oracle = monteCarlo({ method: 'ledger', simulations: 10, trades: 3, capital: 100000, seed: 42 }, apiData.ledger)
const oracleAverage = new Intl.NumberFormat('vi-VN', { maximumFractionDigits: 2 }).format(oracle.average) + ' USD'
const origin = 'http://127.0.0.1:5180', session = '39b1d068edd64e75864f692f27237852'
const out = path.resolve(process.env.FX_ANALYTICS_EVIDENCE || '../evidence/ui-fx-analytics-20261004/journeys')
await mkdir(out, { recursive: true })
async function fingerprint() {
  const hash = createHash('sha256')
  for (const name of (await readdir('src', { recursive: true })).filter(name => /\.(jsx?|css)$/.test(name)).sort()) hash.update(name).update(await readFile(path.join('src', name)))
  return hash.digest('hex')
}
const report = { scope: 'Actual GET-only local QA services; fixture cases explicitly labeled', sourceBefore: await fingerprint(), cases: [], errors: [], blocked: [] }
const browser = await chromium.launch({ headless: true, executablePath: process.env.TW_UI_QA_CHROMIUM || 'C:/Users/MIIKEY/AppData/Local/ms-playwright/chromium_headless_shell-1243/chrome-headless-shell-win64/chrome-headless-shell.exe' })
const axe = await readFile('../../../../.artifacts/wm-integration-quality-tools/node_modules/axe-core/axe.min.js', 'utf8')
const route = (view, extra = '') => `${origin}/?workspace=tenant-a&view=${view}&session=${session}&select=1${extra}`
try {
  for (const theme of ['dark', 'light']) for (const width of [1440, 768, 390, 360]) {
    const context = await browser.newContext({ viewport: { width, height: 987 }, reducedMotion: 'reduce', acceptDownloads: true })
    await context.addInitScript(theme => localStorage.setItem('tw-theme', theme), theme)
    await context.route('**/*', route => { const req = route.request(); if (new URL(req.url()).origin !== origin || !['GET', 'HEAD', 'OPTIONS'].includes(req.method())) { report.blocked.push(req.url()); return route.abort() } return route.continue() })
    await context.routeWebSocket('**/*', socket => socket.close())
    const page = await context.newPage()
    page.setDefaultTimeout(20000)
    page.on('pageerror', error => report.errors.push(error.message))
    await page.goto(route('analytics'), { waitUntil: 'domcontentloaded' })
    await page.getByTestId('analytics-performance').waitFor()
    assert.match(await page.locator('.fxa-metrics').first().innerText(), /75 USD/)
    assert.match(await page.locator('.fxa-metrics').first().innerText(), /100\.075 USD/)
    assert.equal(await page.getByRole('button', { name: /^(Tải lại|Làm mới)/ }).count(), 0)
    assert.equal(await page.locator('h1:not(.sr-only)').count(), 0)
    assert.equal(await page.getByRole('link', { name: 'Prop firm', exact: true }).count(), 1)
    const initialRows = await page.getByLabel('Chọn giao dịch trên biểu đồ').locator('option').count()
    assert.equal(initialRows, 61)
    await page.getByLabel('Tìm giao dịch', { exact: true }).fill('impossible-no-trade')
    assert.match(await page.locator('.fxa-report-scope').innerText(), /^0 \/ 60/)
    await page.getByRole('button', { name: 'Xóa lọc', exact: true }).click()
    assert.match(await page.locator('.fxa-report-scope').innerText(), /^60 \/ 60/)
    await page.getByRole('tab', { name: 'Performance', exact: true }).focus(); await page.keyboard.press('ArrowRight')
    await page.getByTestId('analytics-drawdown').waitFor()
    assert.equal(await page.getByRole('tab', { name: 'Drawdown' }).getAttribute('aria-selected'), 'true')
    await page.screenshot({ path: path.join(out, `drawdown-${theme}-${width}.png`), fullPage: true })
    await page.getByRole('tab', { name: 'Simulation', exact: true }).click()
    await page.getByTestId('analytics-simulation').waitFor()
    await page.getByLabel('Số lượt mô phỏng', { exact: true }).fill('10')
    await page.getByLabel('Lệnh mỗi lượt', { exact: true }).fill('3')
    await page.getByRole('button', { name: 'Chạy Monte Carlo', exact: true }).click()
    await page.getByRole('img', { name: /Monte Carlo · 10 lượt · seed 42/ }).waitFor()
    assert.ok((await page.getByTestId('analytics-simulation').innerText()).includes(oracleAverage))
    await page.getByLabel('Stop distance (ticks)', { exact: true }).fill('40')
    await page.getByRole('button', { name: 'Chạy SL / RR', exact: true }).click()
    await page.waitForFunction(() => !document.body.innerText.includes('Đang mô phỏng từ đường giá'))
    await page.screenshot({ path: path.join(out, `simulation-${theme}-${width}.png`), fullPage: true })
    await page.getByRole('tab', { name: 'Performance', exact: true }).click()
    await page.getByLabel('Timezone', { exact: true }).selectOption('Asia/Ho_Chi_Minh')
    await page.getByLabel('Chỉ số theo thời gian', { exact: true }).selectOption('count')
    await page.screenshot({ path: path.join(out, `performance-${theme}-${width}.png`), fullPage: true })
    await page.addScriptTag({ content: axe })
    const audit = await page.evaluate(() => axe.run(document, { runOnly: { type: 'tag', values: ['wcag2a', 'wcag2aa', 'wcag21a', 'wcag21aa'] } }))
    assert.deepEqual(audit.violations.map(item => ({ id: item.id, nodes: item.nodes.length })), [])
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > window.innerWidth + 1), false)
    const positiveColor = await page.locator('.fxa-metric.is-positive strong').first().evaluate(element => ({ actual: getComputedStyle(element).color, token: getComputedStyle(element).getPropertyValue('--wm-positive').trim() }))
    assert.ok(positiveColor.token, 'Positive values use an existing theme token')
    const bar = page.locator('.fxa-bars .fxa-bar-fill').filter({ visible: true }).first()
    assert.notEqual(await bar.evaluate(element => getComputedStyle(element).backgroundColor), 'rgba(0, 0, 0, 0)', 'Nonzero chart bars have a visible fill')
    if ((theme === 'dark' && width === 1440) || (theme === 'light' && [768, 390].includes(width))) {
      await page.getByRole('heading', { name: 'Performance by side', exact: true }).scrollIntoViewIfNeeded()
      await page.screenshot({ path: path.join(out, `performance-side-${theme}-${width}.png`) })
      await page.getByRole('heading', { name: 'Performance by time', exact: true }).scrollIntoViewIfNeeded()
      await page.screenshot({ path: path.join(out, `performance-time-${theme}-${width}.png`) })
      await page.getByRole('heading', { name: 'Performance calendar', exact: true }).scrollIntoViewIfNeeded()
      await page.screenshot({ path: path.join(out, `performance-calendar-${theme}-${width}.png`) })
    }
    const downloadEvent = page.waitForEvent('download')
    await page.getByRole('button', { name: 'Xuất CSV', exact: true }).click()
    const download = await downloadEvent; await download.saveAs(path.join(out, `analytics-${theme}-${width}.csv`))
    report.cases.push(`real analytics tabs, filters, MC oracle, SL config, CSV, responsive and axe: ${theme}/${width}`)
    await page.goto(route('trade'), { waitUntil: 'domcontentloaded' })
    await page.getByTestId('fx-trade-ledger').waitFor()
    assert.equal(await page.locator('.fxa-trades tbody tr').count(), 10)
    const first = await page.locator('.fxa-trades tbody tr').first().innerText()
    await page.getByRole('button', { name: 'Trang sau', exact: true }).click()
    assert.notEqual(await page.locator('.fxa-trades tbody tr').first().innerText(), first)
    await page.getByLabel('Số dòng Trades', { exact: true }).selectOption('25')
    assert.equal(await page.locator('.fxa-trades tbody tr').count(), 25)
    await page.getByRole('button', { name: 'Cột hiển thị', exact: true }).click()
    await page.getByRole('checkbox', { name: 'Return (%)', exact: true }).check()
    assert.equal(await page.getByRole('button', { name: 'Return (%)', exact: true }).count(), 1)
    await page.getByRole('button', { name: 'Return (USD)', exact: true }).click()
    await page.getByLabel('Chọn các lệnh trên trang', { exact: true }).check()
    assert.equal(await page.locator('.fxa-trades tbody input:checked').count(), 25)
    await page.getByRole('button', { name: /^Chi tiết / }).first().click()
    await page.getByRole('region', { name: 'Chi tiết giao dịch', exact: true }).waitFor()
    await page.getByRole('button', { name: 'Đóng chi tiết', exact: true }).click()
    await page.getByRole('button', { name: 'Basic', exact: true }).click()
    await page.getByRole('combobox', { name: 'Side', exact: true }).selectOption('sell')
    await page.getByTestId('analytics-empty').waitFor()
    assert.equal(await page.locator('.fxa-trades tbody tr').count(), 0)
    await page.getByRole('button', { name: 'Xóa lọc', exact: true }).click()
    await page.locator('.fxa-trades tbody tr').first().waitFor()
    await page.screenshot({ path: path.join(out, `trades-${theme}-${width}.png`), fullPage: true })
    await page.addScriptTag({ content: axe })
    const tradeAudit = await page.evaluate(() => axe.run(document, { runOnly: { type: 'tag', values: ['wcag2a', 'wcag2aa', 'wcag21a', 'wcag21aa'] } }))
    assert.deepEqual(tradeAudit.violations.map(item => ({ id: item.id, nodes: item.nodes.length })), [])
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > window.innerWidth + 1), false)
    report.cases.push(`real Trades pagination, columns, sort, selection/detail, filters and axe: ${theme}/${width}`)
    await page.goto(route('analytics', '&analytics_source=prop'), { waitUntil: 'domcontentloaded' })
    await page.getByTestId('prop-analytics').getByText('Chưa có báo cáo Prop firm.', { exact: false }).waitFor()
    await page.screenshot({ path: path.join(out, `prop-empty-${theme}-${width}.png`) })
    report.cases.push(`real Prop empty source: ${theme}/${width}`)
    await context.close()
  }
  assert.deepEqual(report.errors, [])
  report.sourceAfter = await fingerprint()
  assert.equal(report.sourceAfter, report.sourceBefore, 'Source stays unchanged during final browser journeys')
  await writeFile(path.join(out, 'report.json'), JSON.stringify(report, null, 2))
  console.log(`PASS ${report.cases.length} actual journeys; ${report.errors.length} page errors; ${report.blocked.length} blocked non-GET/external requests`)
} catch (error) { report.failure = String(error.stack || error); await writeFile(path.join(out, 'failure.json'), JSON.stringify(report, null, 2)); throw error }
finally { await browser.close() }
