import assert from 'node:assert/strict'
import { chromium } from 'playwright'
import { mkdir, writeFile } from 'node:fs/promises'
import path from 'node:path'

const out = path.resolve(process.env.TW_LEDGER_QA_OUT || '../evidence/fx-user-refinements-20261005/trades')
await mkdir(out, { recursive: true })
const browser = await chromium.launch({ headless: true })
const page = await browser.newPage({ viewport: { width: 1571, height: 987 } })
const writes = [], errors = [], checks = []
page.on('pageerror', error => errors.push(error.message))
await page.route('**/api/**', route => {
  if (route.request().method() !== 'GET') { writes.push(route.request().method()); return route.abort() }
  return route.continue()
})
const url = 'http://127.0.0.1:5180/?workspace=tenant-a&view=trade&area=testing&section=trades&sessions=all&demo=1'
const rowSides = () => page.locator('tbody tr td:nth-child(9)').allTextContents()
const open = async name => { await page.getByRole('button', { name, exact: true }).click(); await page.getByRole('dialog', { name: 'Filters', exact: true }).waitFor() }
const drawer = () => page.getByRole('dialog', { name: 'Filters', exact: true })
const apply = () => drawer().getByRole('button', { name: 'Apply Filters', exact: true }).click()
try {
  await page.goto(url); await page.waitForLoadState('networkidle')
  assert.equal(await page.locator('thead th').count(), 22)
  assert.equal(await page.getByRole('button', { name: 'Xuất CSV', exact: true }).count(), 0)
  assert.equal(await page.getByRole('button', { name: 'Mở tìm giao dịch', exact: true }).count(), 0)
  assert.equal(await page.locator('.fxa-detail-button svg').count(), 10)
  checks.push('22 default cells = checkbox + Actions + 20 source columns; no toolbar CSV/search; document icon')
  await open('Basic')
  for (const key of ['Tab', 'Shift+Tab']) for (let i = 0; i < 30; i++) { await page.keyboard.press(key); assert.equal(await drawer().evaluate(element => element.contains(document.activeElement)), true) }
  await drawer().getByRole('searchbox', { name: 'Search filter', exact: true }).fill('side')
  assert.equal(await drawer().locator('details').count(), 1)
  await drawer().locator('summary').filter({ hasText: /^Side$/ }).click()
  await drawer().getByRole('checkbox', { name: 'Buy', exact: true }).check()
  assert.ok((await rowSides()).some(side => side === 'sell'))
  await drawer().getByRole('button', { name: 'Đóng Filters', exact: true }).click()
  assert.ok((await rowSides()).some(side => side === 'sell'))
  await open('Basic'); await drawer().locator('summary').filter({ hasText: /^Side$/ }).click()
  assert.equal(await drawer().getByRole('checkbox', { name: 'Buy', exact: true }).isChecked(), false)
  await drawer().getByRole('checkbox', { name: 'Buy', exact: true }).check(); await apply()
  await page.waitForFunction(() => [...document.querySelectorAll('tbody tr td:nth-child(9)')].every(cell => cell.textContent === 'buy'))
  checks.push('searchable Basic accordions; draft does not filter until Apply; Close discards; Apply filters Buy')
  await page.getByRole('button', { name: 'Cột hiển thị', exact: true }).click()
  await page.getByRole('option', { name: 'Fees', exact: true }).click(); await page.keyboard.press('Escape')
  assert.equal(await page.locator('thead th').count(), 21)
  await page.getByRole('button', { name: 'Reset table columns', exact: true }).click()
  assert.equal(await page.locator('thead th').count(), 22)
  assert.ok((await rowSides()).every(side => side === 'buy'))
  checks.push('Reset table columns restores22 headers and leaves Buy filter unchanged')
  await open('Basic'); await drawer().getByRole('button', { name: 'Clear All', exact: true }).click(); await apply()
  assert.ok((await rowSides()).some(side => side === 'sell'))
  await open('Tags')
  await drawer().getByRole('button', { name: 'Include tags', exact: true }).click()
  await drawer().getByRole('option', { name: 'breakout', exact: true }).click()
  await drawer().getByRole('option', { name: 'planned', exact: true }).click()
  await page.keyboard.press('Escape')
  await drawer().getByRole('button', { name: 'Exclude tags', exact: true }).click()
  await drawer().getByRole('option', { name: 'review', exact: true }).click(); await page.keyboard.press('Escape')
  await page.screenshot({ path: path.join(out, 'tags-drawer-dark.png') })
  await apply()
  await page.waitForFunction(() => [...document.querySelectorAll('tbody tr td:nth-child(9)')].every(cell => cell.textContent === 'buy'))
  assert.equal(await page.locator('tbody tr').count(), 10)
  checks.push('Tags include AND plus exclude filter intersect; synthetic journal tags rendered')
  await open('Tags'); await drawer().getByRole('button', { name: 'Clear All', exact: true }).click(); await apply()
  await page.getByRole('button', { name: 'Trang cuối', exact: true }).click()
  assert.equal(await page.getByRole('button', { name: 'Trang 6', exact: true }).getAttribute('aria-current'), 'page')
  await page.getByRole('button', { name: 'Trang đầu', exact: true }).click()
  assert.equal(await page.getByRole('button', { name: 'Trang 1', exact: true }).getAttribute('aria-current'), 'page')
  const footerBefore = await page.locator('.fxa-pagination').boundingBox()
  await page.getByRole('button', { name: 'Số dòng Trades', exact: true }).click(); await page.getByRole('option', { name: '50', exact: true }).click()
  assert.equal(await page.locator('tbody tr').count(), 50)
  const headerBefore = await page.locator('thead th').first().boundingBox()
  await page.locator('.fxa-table-scroll').evaluate(element => { element.scrollTop = 800; element.scrollLeft = 1000 })
  const footerAfter = await page.locator('.fxa-pagination').boundingBox(), headerAfter = await page.locator('thead th').first().boundingBox()
  assert.ok(Math.abs(footerAfter.y - footerBefore.y) < 2)
  assert.ok(Math.abs(headerBefore.y - headerAfter.y) < 2)
  assert.ok(Math.abs(footerAfter.y + footerAfter.height - 987) < 3)
  await page.screenshot({ path: path.join(out, 'ledger-desktop-dark.png') })
  checks.push('first/last pages and page size50 work; inner rows scroll while header/footer remain viewport-pinned')
  await page.setViewportSize({ width: 390, height: 844 }); await page.goto(url); await page.waitForLoadState('networkidle')
  await open('Basic')
  const bounds = await drawer().boundingBox()
  assert.ok(bounds.x >= 0 && bounds.x + bounds.width <= 391)
  for (const key of ['Tab', 'Shift+Tab']) for (let i = 0; i < 30; i++) { await page.keyboard.press(key); assert.equal(await drawer().evaluate(element => element.contains(document.activeElement)), true) }
  await page.screenshot({ path: path.join(out, 'basic-drawer-mobile-dark.png') })
  await page.keyboard.press('Escape')
  assert.equal(await page.getByRole('dialog', { name: 'Filters', exact: true }).count(), 0)
  checks.push('390px drawer fits viewport; Escape closes')
  for (const width of [320, 360, 390, 480]) {
    await page.setViewportSize({ width, height: 844 })
    const content = await page.locator('.fx-content').boundingBox(), pagination = await page.locator('.fxa-pagination').boundingBox(), sizeControl = await page.getByRole('button', { name: 'Số dòng Trades', exact: true }).boundingBox()
    assert.ok(sizeControl.x >= content.x && sizeControl.x + sizeControl.width <= content.x + content.width + 1, `${width}px page size clipped: ${JSON.stringify({ content, pagination, sizeControl })}`)
    assert.ok(sizeControl.y >= pagination.y && sizeControl.y + sizeControl.height <= pagination.y + pagination.height + 1)
    if (width === 360) await page.screenshot({ path: path.join(out, 'ledger-mobile-360.png') })
  }
  checks.push('30 Tab/ShiftTab cycles stay in modal desktop/mobile; complete page-size control fits 320/360/390/480px')
  assert.deepEqual(writes, []); assert.deepEqual(errors, [])
  await writeFile(path.join(out, 'report.json'), JSON.stringify({ status: 'PASS', scope: 'real local UI + demo-local data; API GET only, broker not evaluated', checks, writes, errors }, null, 2))
  console.log(JSON.stringify({ status: 'PASS', checks: checks.length, out }))
} finally { await browser.close() }
