import assert from 'node:assert/strict'
import { mkdir, writeFile } from 'node:fs/promises'
import path from 'node:path'
import { chromium } from 'playwright'
const origin = process.env.SESSION_QA_ORIGIN || 'http://127.0.0.1:5173'
const output = process.env.SESSION_QA_ARTIFACTS || path.resolve('../../../../.artifacts/mt5-session-picker-20261001')
const sessions = new Map(['qa-session','qa-unknown','qa-archived'].map((id,i) => [id, { record_id:id, revision:1, name: ['Phiên fixture A','Chưa có execution','Phiên đã lưu trữ'][i], description:'Synthetic UI fixture', dataset_id:'qa-dataset', instrument_id:'EURUSD', timeframe:'1m', cursor_index:90, status:'paused', dataset_available:i!==1, has_execution:i!==1, archived:i===2 }]))
const ledger = Array.from({length:61},(_,i)=>({trade_id:`qa-trade-${i+1}`,session_id:'qa-session',side:i%2?'SELL':'BUY',open_time_utc:1710000000+i*120,close_time_utc:1710000060+i*120,net_pnl:i%2?-10:20,realized_r:i%2?-1:2,planned_risk_budget:10}))
const checks=[], requests=[], errors=[]
let conflict=false, deny=false, uncertain=false, external=0, releaseReconcile=null, reconcileBarrier=null
await mkdir(output,{recursive:true})
const browser=await chromium.launch({headless:true,executablePath:process.env.TW_UI_QA_CHROMIUM || 'C:/Users/MIIKEY/AppData/Local/ms-playwright/chromium_headless_shell-1243/chrome-headless-shell-win64/chrome-headless-shell.exe'})
const context=await browser.newContext({viewport:{width:1440,height:1000},reducedMotion:'reduce'})
await context.routeWebSocket('**/*',socket=>socket.close())
const page=await context.newPage()
page.setDefaultTimeout(10000)
page.on('pageerror',e=>errors.push(e.message))
await context.route('**/*',async route=>{
 const req=route.request(), url=new URL(req.url()), method=req.method()
 if(url.origin!==origin){external++;return route.abort()}
 if(!url.pathname.startsWith('/api/'))return route.continue()
 requests.push({method,path:url.pathname,query:url.search})
 const json=(payload,status=200)=>route.fulfill({status,contentType:'application/json',body:JSON.stringify(payload)})
 if(req.headers()['x-workspace-id']!=='tenant-qa')return json({detail:'wrong_workspace'},403)
 if(url.pathname==='/api/v2/journal')return json({items:[]})
 if(url.pathname==='/api/v2/replay/sessions'){if(reconcileBarrier)await reconcileBarrier;return deny?json({detail:'workspace_access_denied'},403):json({items:[...sessions.values()]})}
 const match=url.pathname.match(/^\/api\/v2\/replay\/sessions\/([^/]+)(?:\/(analytics(?:\.csv)?|branch))?$/)
 if(!match)return json({detail:'fixture_route_not_implemented'},404)
 const id=decodeURIComponent(match[1]), session=sessions.get(id)
 if(!session)return json({detail:'replay_not_found'},404)
 if(match[2]?.startsWith('analytics')){
  if(match[2].endsWith('.csv'))return route.fulfill({contentType:'text/csv',body:'trade_id,net_pnl\nqa-trade-1,20\n'})
  let rows=ledger.map(t=>({...t,session_id:id}))
  if(url.searchParams.get('side'))rows=rows.filter(t=>t.side.toLowerCase()===url.searchParams.get('side'))
  if(url.searchParams.get('outcome'))rows=rows.filter(t=>url.searchParams.get('outcome')==='win'?t.net_pnl>0:t.net_pnl<0)
  return json({schema_version:'analytics-read-model-v1',analytics_available:session.has_execution,blocked_by_data:session.has_execution?[]:['replay_execution_not_initialized'],ledger:session.has_execution?rows:[],metrics:session.has_execution?{total_trades:rows.length,net_pnl:rows.reduce((n,t)=>n+t.net_pnl,0),starting_balance:10000}:{},scope:{selected_trade_count:session.has_execution?rows.length:null,total_trade_count:session.has_execution?ledger.length:null,observed_range:{},balance_curve_scope:'synthetic fixture closed trades'},provenance:{workspace_id:'tenant-qa',session_id:id,dataset_id:session.dataset_id,dataset_sha256:'fixture-sha-not-market-data',revision:session.revision,source_kind:'replay',fixture:true},filters:{}})
 }
 const body=req.postDataJSON()
 if(body.expected_revision!==session.revision||conflict){if(conflict){session.revision++;conflict=false}return json({detail:'revision_conflict'},409)}
 if(method==='PATCH'){const {expected_revision,...changes}=body;Object.assign(session,changes,{revision:session.revision+1});if(uncertain){uncertain=false;return json({detail:'response_failed_after_write'},500)}return json({record_id:id,revision:session.revision,payload:{...session}})}
 if(method==='POST'&&match[2]==='branch'){assert.equal(body.cursor_index,session.cursor_index);const child={...session,record_id:'qa-branch',revision:1,parent_session_id:id,name:'',description:''};sessions.set(child.record_id,child);return json({record_id:child.record_id,revision:1,payload:{dataset_id:child.dataset_id}},201)}
 return json({detail:'fixture_mutation_blocked'},403)
})
const open=async(view,id='')=>{await page.goto(`${origin}/?workspace=tenant-qa&view=${view}&select=1${id?`&session=${id}`:''}`);await page.getByTestId('session-catalog-status').filter({hasText:'phiên đang hoạt động'}).waitFor()}
try{
 await open('replay')
 await page.getByLabel('Chọn phiên replay',{exact:true}).selectOption('qa-session')
 await page.waitForURL(/session=qa-session/)
 await page.getByRole('heading',{name:'Phiên fixture A',exact:true}).waitFor()
 assert.equal(await page.evaluate(()=>localStorage.getItem('tw:replay:last:tenant-qa')),'qa-session')
 await page.reload();await page.getByRole('heading',{name:'Phiên fixture A',exact:true}).waitFor()
 checks.push('selection navigates and survives reload')
 await page.getByRole('button',{name:'Sửa tên và mô tả'}).click()
 await page.getByLabel('Tên phiên',{exact:true}).fill('Phiên đã đổi tên')
 await page.getByLabel('Mô tả',{exact:true}).fill('Mô tả đã lưu qua PATCH')
 conflict=true;await page.getByRole('button',{name:'Lưu thay đổi'}).click()
 await page.getByRole('alert').filter({hasText:'Phiên đã thay đổi ở nơi khác'}).waitFor()
 await page.getByLabel('Tên phiên',{exact:true}).waitFor()
 assert.equal(await page.getByLabel('Tên phiên',{exact:true}).inputValue(),'Phiên đã đổi tên')
 await page.getByRole('button',{name:'Lưu thay đổi'}).click()
 await page.getByRole('heading',{name:'Phiên đã đổi tên',exact:true}).waitFor()
 await page.reload();await page.getByText('Mô tả đã lưu qua PATCH',{exact:true}).waitFor()
 checks.push('metadata persists and conflict preserves draft')
 await page.getByRole('button',{name:'Sửa tên và mô tả'}).click()
 await page.getByLabel('Mô tả',{exact:true}).fill('Server wrote but response failed')
 reconcileBarrier=new Promise(resolve=>{releaseReconcile=resolve});uncertain=true;await page.getByRole('button',{name:'Lưu thay đổi'}).click()
 await page.getByRole('alert').filter({hasText:'Chưa xác định thao tác'}).waitFor()
 assert.equal(await page.getByRole('button',{name:'Lưu thay đổi'}).isDisabled(),true)
 assert.equal(await page.getByRole('button',{name:'Tạo bản sao tại cutoff'}).isDisabled(),true)
 assert.equal(requests.filter(req=>req.method==='PATCH').length,3)
 releaseReconcile();reconcileBarrier=null
 await page.getByRole('button',{name:'Lưu thay đổi'}).waitFor()
 await page.waitForFunction(()=>!document.querySelector('.fxr-session-edit button[type=submit]').disabled)
 await page.getByRole('button',{name:'Hủy sửa'}).click()
 await page.getByText('Server wrote but response failed',{exact:true}).waitFor()
 checks.push('uncertain server response fences mutation until catalog refresh')
 await page.getByRole('button',{name:'Lưu trữ phiên',exact:true}).click()
 await page.getByRole('button',{name:'Khôi phục phiên',exact:true}).waitFor()
 assert.equal(await page.getByRole('link',{name:'Tiếp tục trên chart'}).count(),0)
 await page.getByRole('button',{name:'Khôi phục phiên',exact:true}).click()
 await page.getByRole('button',{name:'Lưu trữ phiên',exact:true}).waitFor()
 await page.getByLabel('Hiện phiên đã lưu trữ').check()
 assert.equal(await page.getByRole('option',{name:/Phiên đã lưu trữ/}).count(),1)
 checks.push('archive restore and archive filter')
 await page.getByRole('button',{name:'Tạo bản sao tại cutoff'}).click()
 await page.waitForURL(/session=qa-branch/)
 await page.getByRole('heading',{name:'qa-branch',exact:true}).waitFor()
 assert.equal(sessions.get('qa-branch').parent_session_id,'qa-session')
 checks.push('duplicate branches at saved cursor and opens child')
 await open('trade','qa-session')
 await page.getByTestId('analytics-workspace').waitFor();await page.getByText('Đang tải kết quả…',{exact:true}).waitFor({state:'hidden'})
 await page.getByRole('button',{name:'Trang sau',exact:true}).click()
 await page.getByRole('button',{name:'Chi tiết qa-trade-51',exact:true}).click()
 await page.getByRole('region',{name:'Trade detail'}).waitFor();await page.getByRole('button',{name:'Basic',exact:true}).click()
 await page.getByRole('combobox',{name:'Side',exact:true}).selectOption('buy')
 await page.getByTestId('fx-trade-ledger').locator('.fxa-report-scope').filter({hasText:'31 giao dịch đóng'}).waitFor()
 checks.push('Trades pagination detail and server filter')
 await open('analytics','qa-session')
 await page.getByTestId('analytics-workspace').waitFor();await page.getByText('Đang tải kết quả…',{exact:true}).waitFor({state:'hidden'})
 assert.equal(await page.getByText('Show demo data',{exact:true}).count(),0)
 checks.push('Analytics uses read model without demo')
 for(const width of [1440,768,390]){await page.setViewportSize({width,height:1000});for(const view of ['replay','trade','analytics']){await open(view,'qa-session');await page.getByTestId(view==='replay'?'session-performance':'analytics-workspace').waitFor();await page.getByText('Đang tải kết quả…',{exact:true}).waitFor({state:'hidden'});const overflow=await page.evaluate(()=>document.documentElement.scrollWidth-window.innerWidth);assert.ok(overflow<=1,`${view} ${width}: ${overflow}px overflow`);await page.screenshot({path:path.join(output,`${view}-${width}.png`),fullPage:true})}}
 checks.push('responsive 3 routes by 3 widths without horizontal overflow')
 await page.evaluate(()=>localStorage.setItem('tw-theme','light'))
 for(const width of [1440,390]){await page.setViewportSize({width,height:1000});for(const view of ['replay','trade','analytics']){await open(view,'qa-session');await page.getByTestId(view==='replay'?'session-performance':'analytics-workspace').waitFor();await page.getByText('Đang tải kết quả…',{exact:true}).waitFor({state:'hidden'});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth-window.innerWidth)<=1);if(view==='trade'){await page.getByTestId('fx-trade-ledger').scrollIntoViewIfNeeded()}await page.screenshot({path:path.join(output,`${view}-light-${width}.png`),fullPage:true})}}
 checks.push('light theme 3 routes by 2 widths and scrolled ledger screenshots')
 await open('replay','qa-unknown');await page.getByTestId('session-performance-blocked').waitFor();assert.equal(await page.getByText('0%',{exact:true}).count(),0)
 checks.push('missing execution stays unknown')
 deny=true;await page.evaluate(()=>window.dispatchEvent(new Event('online')));await page.getByRole('alert').filter({hasText:'workspace_access_denied'}).waitFor();assert.equal(await page.getByTestId('analytics-workspace').count(),0);assert.equal(await page.getByTestId('session-performance').count(),0);assert.equal(await page.getByTestId('session-performance-blocked').count(),0)
 deny=false;await page.waitForTimeout(2100);await page.evaluate(()=>window.dispatchEvent(new Event('online')));await page.getByTestId('session-performance-blocked').waitFor()
 checks.push('denied catalog hides stale report then recovers')
 assert.deepEqual(errors,[]);assert.equal(external,0)
 await writeFile(path.join(output,'receipt.json'),JSON.stringify({status:'PASS',scope:'synthetic browser fixture API intercepted no real backend writes',checks,browserErrors:errors,externalRequests:external,requestCount:requests.length},null,2))
 console.log(JSON.stringify({status:'PASS',checks:checks.length,output}))
}catch(error){await page.screenshot({path:path.join(output,'failure.png'),fullPage:true}).catch(()=>{});await writeFile(path.join(output,'failure.json'),JSON.stringify({checks,error:String(error),browserErrors:errors,requests},null,2));throw error}finally{await browser.close()}
