import test from 'node:test'
import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
import { fileURLToPath } from 'node:url'
import { dirname, resolve } from 'node:path'

const testsDir = dirname(fileURLToPath(import.meta.url))
const sourceDir = resolve(testsDir, '..', 'src')

test('shell exposes truthful EN/VI and theme controls with persisted preference contracts', async () => {
  const source = await readFile(resolve(sourceDir, 'FxReplayShell.jsx'), 'utf8')
  const css = await readFile(resolve(sourceDir, 'fx-shell-preferences.css'), 'utf8')
  const storyCss = await readFile(resolve(sourceDir, 'fx-shell-story.css'), 'utf8')

  assert.match(source, /LANGUAGE_STORAGE_KEY\s*=\s*['"]tw-language['"]/, 'language preference key is stable')
  assert.match(source, /THEME_STORAGE_KEY\s*=\s*['"]tw-theme['"]/, 'theme preference key is stable')
  assert.match(source, /data-testid="language-toggle"/, 'language control is discoverable')
  assert.match(source, /data-testid="theme-toggle"/, 'theme control is discoverable')
  assert.ok(source.includes("aria-controls={helpOpen ? 'fx-shell-help' : undefined}"), 'help control only references the dialog while it is mounted')
  assert.match(source, /localStorage\.setItem\(LANGUAGE_STORAGE_KEY/, 'language selection persists')
  assert.match(source, /localStorage\.setItem\(THEME_STORAGE_KEY/, 'theme selection persists')
  assert.match(source, /document\.documentElement[\s\S]*setAttribute\('lang', language\)/, 'document locale follows shell locale')
  assert.match(source, /data-theme=\{theme\}/, 'theme state is exposed to scoped CSS')
  assert.match(source, /Switch language to Vietnamese/, 'EN shell copy exists')
  assert.match(source, /Chuyển ngôn ngữ sang English/, 'VI shell copy exists')
  assert.match(source, /buildWorkspaceHref\(id, workspace, query(?:, overrides)?\)/, 'shell navigation carries the current URL context')
  assert.match(source, /query = currentQuery\(\)/, 'shell can read deep-link context when mounted directly')
  assert.match(source, /routeContext/, 'shell exposes canonical route context to child workspaces')
  assert.match(source, /product:\s*['"]WMREPLAY['"]/, 'shell uses the WMREPLAY product wordmark')
  assert.match(source, /fx-topbar-brand/, 'brand lives in the global header')
  assert.match(source, /role="img" aria-label=\{copy\.product\}/, 'wordmark has an accessible label')
  assert.match(source, /fx-wordmark/, 'shell renders the WMREPLAY wordmark')
  assert.match(source, /viewBox="0 0 242 30"/, 'wordmark uses a stable vector geometry')
  assert.match(source, /subnav: \{ overview: 'Dashboard', replay: 'Sessions', trade: 'Trades', analytics: 'Analytics' \}/, 'shell keeps the FXReplay-style naming contract')
  assert.match(source, /id: 'testing-sessions'[\s\S]*route: 'replay'[\s\S]*picker: true/, 'Sessions subnavigation opens the session picker')
  assert.match(source, /id: 'testing-trades'[\s\S]*route: 'trade'[\s\S]*picker: true/, 'Trades subnavigation opens the session picker')
  assert.match(source, /id: 'testing-analytics'[\s\S]*route: 'analytics'[\s\S]*picker: true/, 'Analytics subnavigation opens the session picker')
  assert.match(source, /id: 'testing'[\s\S]*copyKey: 'testing'/, 'rail has a Testing top-level area')
  assert.match(source, /id: 'live'[\s\S]*copyKey: 'live'/, 'rail has a Live top-level area')
  assert.match(source, /id: 'strategies'[\s\S]*copyKey: 'strategies'/, 'rail has a Strategies top-level area')
  assert.match(source, /id: 'education'[\s\S]*copyKey: 'learn'/, 'rail has an Education top-level area')
  assert.match(source, /id: 'settings'[\s\S]*copyKey: 'settings'/, 'rail has a Settings top-level area')
  assert.match(source, /const SUBNAV_GROUPS = \{[\s\S]*testing:[\s\S]*live:[\s\S]*strategies:/, 'content subheader owns each area subnavigation')
  assert.match(source, /<div className="fx-rail-spacer" \/>/, 'utility links are rendered after the flexible rail spacer')
  assert.doesNotMatch(source, /Market replay/, 'brand has no extra descriptor text')
  assert.doesNotMatch(source, /fx-context-market|fx-context-lock|fx-context-source|fx-context-cutoff|fx-context-mode/, 'header does not render market or safety chips')
  assert.doesNotMatch(source, /tenant-a/, 'header does not render the internal workspace fixture name')
  assert.doesNotMatch(source, /fx-avatar|workspaceOwner/, 'header does not render the workspace owner avatar')
  assert.doesNotMatch(source, /fx-rail-footer|dataContract|sourcePending|dataQuality|noDataset/, 'rail does not render the redundant data contract footer')
  assert.match(css, /\.fx-app\[data-theme='light'\]/, 'light theme is scoped to the mounted app')
  assert.match(storyCss, /\.fx-shell-story \.fx-rail \{[\s\S]*border-right: 1px solid/, 'rail keeps its content boundary')
  assert.match(storyCss, /\.fx-topbar-brand \{[\s\S]*border-right: 0/, 'header has no vertical separator')
  assert.match(storyCss, /\.fx-shell-story \.fx-subnav/, 'shell owns the workspace subnavigation geometry')
  assert.match(css, /prefers-reduced-motion/, 'preference transitions respect reduced motion')
})
