import assert from 'node:assert/strict'
import { chromium } from '../../../foundation_v2/web/node_modules/playwright/index.mjs'
import {readFile,writeFile} from 'node:fs/promises'
import {createHash} from 'node:crypto'
if(!process.argv.includes('--ready'))throw new Error('ROOT_READY_REQUIRED')
const dir='.artifacts/fx-dashboard-parity-20261005/independent-review',origin='http://127.0.0.1:5180',api='http://127.0.0.1:8010',old='476f4b498e1a49ed9d48a75719f4d270'
const files=['DashboardSessions.jsx','DashboardPerformance.jsx','FxSelect.jsx','SessionFilter.jsx','DashboardSessionCard.jsx','dashboard-session.css','DemoPreview.jsx','demoFixtures.js','demoMode.js','dashboardModel.js','SessionPerformance.jsx','fx-select.css','session-filter.css','component-interactions.css'].map(x=>'foundation_v2/web/src/'+x)
const hashes=()=>Promise.all(files.map(async file=>({file,sha256:createHash('sha256').update(await readFile(file)).digest('hex')})))
const report={before:await hashes(),checks:[],failures:[],errors:[],blocked:[],api:[],focus:[],cards:[]};let phase='init'
const b=await chromium.launch({headless:true}),c=await b.newContext({viewport:{width:1440,height:987}})
await c.route('**/*',async r=>{const q=r.request(),u=new URL(q.url());if(u.origin!==origin||!['GET','HEAD','OPTIONS'].includes(q.method())){report.blocked.push({phase,method:q.method(),path:u.pathname});return r.abort()}if(!u.pathname.startsWith('/api/'))return r.continue();report.api.push({phase,path:u.pathname,query:u.search,demo:new URL(q.frame().url()).searchParams.get('demo')});try{return await r.fulfill({response:await r.fetch({url:api+u.pathname+u.search})})}catch{try{await r.abort()}catch{}}})
await c.routeWebSocket('**/*',s=>s.close());const p=await c.newPage();p.setDefaultTimeout(10000);p.on('pageerror',e=>report.errors.push(String(e)));p.on('download',()=>report.blocked.push({phase,method:'DOWNLOAD'}))
const settle=async()=>{await p.waitForLoadState('networkidle');await p.waitForFunction(()=>document.getAnimations().every(a=>a.playState!=='running'))},nav=async q=>{await p.goto(origin+'/?workspace=tenant-a&view=overview&area=testing&section=dashboard&'+q);await settle()},get=async path=>{const r=await c.request.get(api+path,{headers:{'X-Workspace-Id':'tenant-a'}});assert.equal(r.status(),200);return r.json()}
const run=async(name,fn)=>{if(process.env.QA_ONLY&&!new RegExp(process.env.QA_ONLY).test(name))return;phase=name;try{await fn();report.checks.push({name,pass:true})}catch(e){report.failures.push({name,error:String(e)});await p.screenshot({path:dir+'/lifecycle-failure-'+name+'.png'}).catch(()=>{})}await writeFile(dir+'/lifecycle-progress.json',JSON.stringify(report,null,2))}
const card=id=>p.locator('.fx-dashboard-session-card[data-session-id="'+id+'"]'),button=(name)=>p.getByRole('button',{name,exact:true}),dialog=()=>p.locator('.fx-dashboard-dialog[open]')
async function close(method='Escape'){const d=dialog();assert.equal(await d.count(),1);if(method==='Escape')await p.keyboard.press('Escape');else if(method==='backdrop')await p.mouse.click(1,1);else await button('Đóng hộp thoại phiên').click();await d.waitFor({state:'hidden'});await settle();assert.equal(await dialog().count(),0)}
async function trap(tag){const d=dialog();const results=[];for(const key of ['Tab','Shift+Tab'])for(let i=0;i<34;i++){await p.keyboard.press(key);results.push(await d.evaluate((e,key)=>({key,inside:e.contains(document.activeElement),tag:document.activeElement.tagName,label:document.activeElement.getAttribute('aria-label')||document.activeElement.textContent?.slice(0,40)}),key).catch(()=>null))}report.focus.push({tag,results});assert.ok(results.every(x=>x?.inside),'focus escaped modal '+JSON.stringify(results.filter(x=>!x?.inside)))}
async function summary(name,count=20){await button('Summary '+name).click();await settle();assert.equal(await dialog().getAttribute('aria-label'),'Summary · '+name);assert.equal(await dialog().locator('.fxs-metric').count(),6);await button('Số dòng Recent Trades').click();await p.getByRole('option',{name:'20',exact:true}).click();await settle();assert.equal(await dialog().locator('tbody tr').count(),count);assert.equal(await dialog().locator('.fxs-chart-panel').count(),3)}
try{const oldBefore=await get('/api/v2/replay/sessions/'+old)
await run('demo-metadata-charts-summary',async()=>{await nav('demo=1&session='+old+'&dashboard_search=preserve-owner');const startUrl=p.url();assert.equal(await p.locator('.fx-dashboard-session-card').count(),3);for(const [id,val] of [['demo-london',1401],['demo-newyork',1901],['demo-gold',2401]]){const row=card(id);const progress=row.locator('progress');assert.equal(await progress.getAttribute('value'),String(val));assert.equal(await progress.getAttribute('max'),'30000');const text=await row.innerText();assert.match(text,/10\.960 USD/);assert.doesNotMatch(text,/— – —/);report.cards.push({id,text,value:val});}await button('Mở rộng Gold Swing').click();await settle();assert.equal(await card('demo-gold').locator('.fxs-chart-panel').count(),3);assert.equal(await card('demo-gold').locator('.fxs-metric,.fxs-recent').count(),0);await p.screenshot({path:dir+'/demo-expanded-1440.png'});await button('Thu gọn Gold Swing').click();await summary('Gold Swing');await p.screenshot({path:dir+'/demo-summary-1440.png'});await trap('summary-1440');await close();assert.equal(await button('Summary Gold Swing').evaluate(e=>e===document.activeElement),true);assert.equal(p.url(),startUrl)})
await run('demo-local-lifecycle-and-copy-ledger',async()=>{await nav('demo=1&session='+old+'&dashboard_search=preserve-owner');const startUrl=p.url(),mark=report.api.length;await button('Sửa Gold Swing').click();await p.getByRole('textbox',{name:'Tên phiên',exact:true}).fill('Gold Swing Edited');await p.getByRole('textbox',{name:'Mô tả',exact:true}).fill('Independent local preview edit');await button('Lưu thay đổi').click();await settle();await button('Sửa Gold Swing Edited').click();assert.equal(await p.getByRole('textbox',{name:'Mô tả',exact:true}).inputValue(),'Independent local preview edit');await button('Hủy').click();await button('Tạo bản sao Gold Swing Edited').click();await button('Tạo bản sao').click();await settle();assert.equal(await p.locator('.fx-dashboard-session-card').count(),4);await summary('Gold Swing Edited (copy)');assert.match(await dialog().innerText(),/960 USD/);await close();assert.equal(await p.locator('.fx-dashboard-metric').filter({hasText:'Trades taken'}).locator('strong').innerText(),'60');await button('Lưu trữ Gold Swing Edited').click();await button('Lưu trữ').click();await settle();assert.equal(await card('demo-gold').count(),0);await button('Hiện bộ lọc phiên').click();await button('Trạng thái phiên').click();await p.getByRole('option',{name:'Đã lưu trữ',exact:true}).click();await settle();assert.equal(await p.locator('.fx-dashboard-session-card').count(),1);assert.equal(await button('Tạo bản sao Gold Swing Edited').isDisabled(),true);await button('Khôi phục Gold Swing Edited').click();await button('Khôi phục').click();await settle();assert.equal(await p.locator('.fx-dashboard-session-card').count(),0);await button('Trạng thái phiên').click();await p.getByRole('option',{name:'Tất cả',exact:true}).click();await settle();assert.equal(await p.locator('.fx-dashboard-session-card').count(),4);assert.equal(report.api.length,mark);assert.equal(p.url(),startUrl);await p.screenshot({path:dir+'/demo-lifecycle-final-1440.png'})})
for(const width of [1440,360])await run('modal-closure-focus-'+width,async()=>{await p.setViewportSize({width,height:width===360?600:987});await nav('demo=1');await button('Sửa Gold Swing').click();await trap('rename-'+width);await close();assert.equal(await button('Sửa Gold Swing').evaluate(e=>e===document.activeElement),true);await button('Lưu trữ Gold Swing').click();await trap('archive-'+width);await close('backdrop');assert.equal(await button('Lưu trữ Gold Swing').evaluate(e=>e===document.activeElement),true);await summary('Gold Swing');const box=await dialog().boundingBox();assert.ok(box.x>=0&&box.x+box.width<=width);assert.ok(box.y>=0&&box.y+box.height<=(width===360?600:987));await trap('summary-'+width);await p.screenshot({path:dir+'/summary-'+width+'.png'});await close('button');assert.equal(await button('Summary Gold Swing').evaluate(e=>e===document.activeElement),true)})
for(const width of [1440,360])for(const theme of ['dark','light'])await run('modal-a11y-'+theme+'-'+width,async()=>{await p.setViewportSize({width,height:width===360?600:987});await nav('demo=1');if(await p.getByTestId('fxreplay-shell').getAttribute('data-theme')!==theme)await p.getByTestId('theme-toggle').click();await summary('Gold Swing');await dialog().evaluate(e=>e.scrollTop=0);await p.screenshot({path:dir+'/summary-top-'+theme+'-'+width+'.png'});await p.addScriptTag({path:'../../.artifacts/wm-integration-quality-tools/node_modules/axe-core/axe.min.js'});const violations=await p.evaluate(()=>window.axe.run(document,{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21aa','wcag22aa']}}).then(r=>r.violations.map(v=>({id:v.id,targets:v.nodes.map(n=>n.target)}))));assert.deepEqual(violations,[]);assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth-innerWidth),0);await close('button');await button('Sửa Gold Swing').click();const editViolations=await p.evaluate(()=>window.axe.run(document,{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21aa','wcag22aa']}}).then(r=>r.violations.map(v=>({id:v.id,targets:v.nodes.map(n=>n.target)}))));assert.deepEqual(editViolations,[]);await p.screenshot({path:dir+'/edit-'+theme+'-'+width+'.png'});await close()})
await run('demo-analytics-scoping-toggle',async()=>{await p.setViewportSize({width:1440,height:987});await nav('demo=1&session='+old);const a=p.getByRole('link',{name:'Analytics Gold Swing',exact:true}),u=new URL(await a.getAttribute('href'),origin);assert.equal(u.searchParams.get('demo_session'),'demo-gold');assert.equal(u.searchParams.get('session'),old);await a.click();await settle();const filter=p.getByRole('button',{name:/^Session:/});assert.match(await filter.getAttribute('aria-label'),/Gold Swing/);assert.match(await p.locator('main,.fx-content').last().innerText(),/20/);await button('Show real data').click();await settle();assert.equal(new URL(p.url()).searchParams.has('demo_session'),false);assert.equal(new URL(p.url()).searchParams.get('session'),old)})
await run('actual-archived-summary-read-only-cancel',async()=>{await p.setViewportSize({width:1440,height:987});await nav('session='+old+'&dashboard_status=all');assert.equal(await p.locator('.fx-dashboard-session-card').count(),6);const filled='273a1275538c42cb95cfff16e0f9f62c',row=card(filled);assert.match(await row.innerText(),/9\.999,76 USD/);await button('Mở rộng QA tick XAUUSDm').click();await settle();assert.equal(await row.locator('.fxs-chart-panel').count(),3);await summary('QA tick XAUUSDm',1);assert.match(await dialog().innerText(),/-0,24 USD/);await close();await button('Sửa QA tick XAUUSDm').click();await button('Hủy').click();await button('Khôi phục QA tick XAUUSDm').click();await close();const empty=card('d70ee54946144605bf20ba5b8e2f4cdf'),emptyName=await empty.locator('h3').evaluate(e=>e.childNodes[0].textContent);await button('Summary '+emptyName).click();await settle();assert.equal(await dialog().getByTestId('session-trades-empty').count(),1);assert.match(await dialog().locator('.fxs-metric').filter({hasText:'Total P/L'}).innerText(),/0 USD/);await close();assert.deepEqual(await get('/api/v2/replay/sessions/'+old),oldBefore);await p.screenshot({path:dir+'/actual-all-expanded-1440.png'})})
await run('actual-no-init-unknown-metadata',async()=>{await nav('session='+old);const row=card(old),name=await row.locator('h3').evaluate(e=>e.childNodes[0].textContent);assert.equal(await row.locator('progress').getAttribute('value'),'501');assert.equal(await row.locator('progress').getAttribute('max'),'93810');assert.match(await row.innerText(),/Còn 93\.309 nến/);assert.match(await row.locator('.fx-dashboard-card-facts').innerText(),/—/);await button('Mở rộng '+name).click();await settle();assert.equal(await row.locator('.fxs-chart-panel').count(),3);assert.match(await row.innerText(),/Chưa có đường số dư được xác minh/);await button('Summary '+name).click();await settle();for(const metric of await dialog().locator('.fxs-metric strong').allTextContents())assert.equal(metric,'—');assert.equal(await dialog().getByTestId('session-trades-empty').count(),1);await p.screenshot({path:dir+'/actual-uninitialized-summary-1440.png'});await close();assert.deepEqual(await get('/api/v2/replay/sessions/'+old),oldBefore)})
assert.deepEqual(report.errors,[]);assert.deepEqual(report.blocked,[]);assert.equal(report.api.filter(x=>x.demo==='1').length,0);assert.deepEqual(await get('/api/v2/replay/sessions/'+old),oldBefore);report.after=await hashes();report.sourceUnchanged=JSON.stringify(report.before)===JSON.stringify(report.after);assert.ok(report.sourceUnchanged);assert.deepEqual(report.failures,[]);report.pass=true
}catch(e){report.failure=String(e);report.after=await hashes();process.exitCode=1}finally{await c.unrouteAll({behavior:'wait'});await b.close();await writeFile(dir+'/lifecycle.json',JSON.stringify(report,null,2));console.log(JSON.stringify({pass:report.pass,checks:report.checks.length,failures:report.failures,errors:report.errors,blocked:report.blocked,sourceUnchanged:report.sourceUnchanged}))}
