import assert from 'node:assert/strict'
import { chromium } from '../../../web/node_modules/playwright/index.mjs'
import { readFile,writeFile } from 'node:fs/promises'
const out='foundation_v2/evidence/testing-standard-20261006/chrome-review/',b=await chromium.launch({headless:true,ignoreDefaultArgs:['--hide-scrollbars']}),c=await b.newContext(),p=await c.newPage(),report={scans:[],contrast:[],blocked:[]}
await c.routeWebSocket('**/*',ws=>ws.close());await c.route('**/*',r=>{const q=r.request(),u=new URL(q.url());if(u.origin!=='http://127.0.0.1:5180'||!['GET','HEAD','OPTIONS'].includes(q.method())){report.blocked.push({url:u.href,method:q.method()});return r.abort()}return r.continue()})
const axe=await readFile('../../.artifacts/wm-integration-quality-tools/node_modules/axe-core/axe.min.js','utf8')
function luminance(rgb){const a=rgb.match(/[\d.]+/g).slice(0,3).map(Number).map(x=>{x/=255;return x<=.04045?x/12.92:((x+.055)/1.055)**2.4});return a[0]*.2126+a[1]*.7152+a[2]*.0722}
try{for(const theme of ['dark','light'])for(const [route,view] of [['dashboard','overview'],['sessions','replay'],['trades','trade'],['analytics','analytics']]){
await p.setViewportSize({width:1320,height:987});await p.goto(`http://127.0.0.1:5180/?workspace=tenant-a&area=testing&view=${view}&section=${route}&select=1&demo=1`);await p.waitForLoadState('networkidle');const shell=p.getByTestId('fxreplay-shell');if(await shell.getAttribute('data-theme')!==theme)await p.getByTestId('theme-toggle').click();if(await shell.getAttribute('lang')!=='en')await p.getByTestId('language-toggle').click();await p.addScriptTag({content:axe});const scan=await p.evaluate(()=>axe.run(document,{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21aa']}}));report.scans.push({route,theme,violations:scan.violations.map(v=>({id:v.id,impact:v.impact,nodes:v.nodes.map(n=>n.target)})),passes:scan.passes.length,incomplete:scan.incomplete.map(v=>v.id)});
for(const selector of ['.fx-rail-primary .is-active','.fx-subnav-primary>a.is-active','.fx-select:not(.is-rich):not(.fxa-columns-control)>.fx-select-trigger']){const loc=p.locator(selector).first();if(!await loc.count())continue;const style=await loc.evaluate(e=>{const s=getComputedStyle(e);return {color:s.color,background:s.backgroundColor}});const a=luminance(style.color),d=luminance(style.background),ratio=(Math.max(a,d)+.05)/(Math.min(a,d)+.05);report.contrast.push({route,theme,selector,...style,ratio});assert.ok(ratio>=4.5)}
await p.screenshot({path:out+`visual-${route}-${theme}-1320.png`})
}
for(const width of [320,360]){await p.setViewportSize({width,height:987});await p.goto('http://127.0.0.1:5180/?workspace=tenant-a&area=testing&view=trade&section=trades&demo=1');await p.waitForLoadState('networkidle');const boxes=await p.locator('.fxa-pagination>div:not(.fx-select)>button,.fxa-pagination .fx-select-trigger').evaluateAll(es=>es.map(e=>{const r=e.getBoundingClientRect();return {x:r.x,right:r.right,width:r.width,height:r.height}}));assert.equal(boxes.length,4);assert.ok(boxes.every(v=>v.x>=0&&v.right<=width&&v.height===44));await p.screenshot({path:out+`visual-trades-${width}.png`});report.scans.push({route:'trades',width,geometry:boxes,pass:true})}
assert.ok(report.scans.every(s=>!s.violations?.length));assert.equal(report.blocked.length,0);report.pass=true
}catch(e){report.failure=String(e);process.exitCode=1}finally{await b.close();await writeFile(out+'accessibility.json',JSON.stringify(report,null,2));console.log(JSON.stringify({pass:report.pass,scans:report.scans.length,violations:report.scans.flatMap(s=>s.violations||[]),contrastSamples:report.contrast.length,minContrast:Math.min(...report.contrast.map(v=>v.ratio)),failure:report.failure}))}
