import assert from 'node:assert/strict'
import { chromium } from '../../../web/node_modules/playwright/index.mjs'
import { readFile,writeFile,mkdir } from 'node:fs/promises'
import { createHash } from 'node:crypto'
import path from 'node:path'
const out=path.dirname(new URL(import.meta.url).pathname.replace(/^\/(\w:)/,'$1'));await mkdir(out,{recursive:true})
const files=['FxReplayShell.jsx','fx-shell-story.css','component-interactions.css','testing-standard.css','workspace-pattern.css','dashboard.css','testing-copy.json','ledger-controls.css','FxTradeLedger.jsx','page-layout.css'],pins=async()=>Promise.all(files.map(async file=>({file,sha256:createHash('sha256').update(await readFile('foundation_v2/web/src/'+file)).digest('hex')})))
const copy=JSON.parse(await readFile('foundation_v2/web/src/testing-copy.json','utf8')),tx=(s,l)=>copy[s]?.[l]||s
const report={checks:[],findings:[],failures:[],errors:[],blocked:[],requests:[],styles:[],before:await pins()},b=await chromium.launch({headless:true,ignoreDefaultArgs:['--hide-scrollbars']}),c=await b.newContext(),p=await c.newPage()
await c.routeWebSocket('**/*',ws=>ws.close());await c.route('**/*',async r=>{const q=r.request(),u=new URL(q.url());if(!['http://127.0.0.1:5180','http://127.0.0.1:8010'].includes(u.origin)||!['GET','HEAD','OPTIONS'].includes(q.method())){report.blocked.push({method:q.method(),url:q.url()});return r.abort()}if(u.pathname.startsWith('/api/'))report.requests.push({phase:report.phase,path:u.pathname,method:q.method(),demo:new URL(q.frame().url()).searchParams.get('demo')});return r.continue()});p.on('pageerror',e=>report.errors.push({phase:report.phase,message:e.message}))
const routes={dashboard:['overview','dashboard'],sessions:['replay','sessions'],trades:['trade','trades'],analytics:['analytics','analytics'],prop:['analytics','analytics'],market:['market-data','market-data']}
const go=async(route,theme,lang,width,demo=true)=>{await p.setViewportSize({width,height:987});const [view,section]=routes[route];await p.goto(`http://127.0.0.1:5180/?workspace=tenant-a&area=testing&view=${view}&section=${section}&select=1${demo?'&demo=1':''}${route==='prop'?'&analytics_source=prop':''}`);await p.waitForLoadState('networkidle');const shell=p.getByTestId('fxreplay-shell');if(await shell.getAttribute('data-theme')!==theme)await p.getByTestId('theme-toggle').click();if(await shell.getAttribute('lang')!==lang)await p.getByTestId('language-toggle').click();if(width>760&&await shell.evaluate(e=>e.classList.contains('is-rail-collapsed')))await p.locator('.fx-menu-button').click()}
const shot=async suffix=>p.screenshot({path:path.join(out,report.phase+(suffix||'')+'.png')})
const run=async(name,fn)=>{report.phase=name;try{await fn();report.checks.push({name,pass:true})}catch(e){report.failures.push({name,error:String(e),stack:e.stack});await shot('-failure')}await writeFile(path.join(out,'progress.json'),JSON.stringify(report,null,2))}
const css=async loc=>loc.evaluate(e=>{const s=getComputedStyle(e),r=e.getBoundingClientRect();return {width:r.width,height:r.height,x:r.x,y:r.y,color:s.color,background:s.backgroundColor,border:s.borderColor,borderWidth:s.borderWidth,radius:s.borderRadius,outline:s.outlineColor,outlineWidth:s.outlineWidth}})
const neutral=s=>{const a=s.match(/[\d.]+/g)?.map(Number);return a&&a[0]===a[1]&&a[1]===a[2]}
const fit=async loc=>{const box=await loc.boundingBox(),clip=await p.locator('.fx-content').evaluate(e=>({left:e.getBoundingClientRect().left,right:e.getBoundingClientRect().left+e.clientWidth}));assert.ok(box.x>=clip.left-1&&box.x+box.width<=clip.right+1,'popup content clipping');assert.ok(box.y>=0&&box.y+box.height<=987,'popup vertical clipping')}
const icons='.fxa-icon-button,.fx-select.fxa-columns-control>.fx-select-trigger,.fxa-detail-button,.fx-dashboard-card-icon,.fx-dashboard-card-play,.fx-dashboard-refresh,.fx-dashboard-icon-button,.fxs-action-button,.fxs-edit-description'
try{
for(const theme of ['dark','light'])for(const lang of ['vi','en'])for(const width of [1320,768,390])for(const route of Object.keys(routes))await run(`demo-${route}-${theme}-${lang}-${width}`,async()=>{
await go(route,theme,lang,width);const shell=p.getByTestId('fxreplay-shell'),workspace=p.locator('.fx-rail-workspace'),menu=p.locator('.fx-menu-button'),active=p.locator('.fx-rail-primary .is-active');const wsHref=new URL(await workspace.getAttribute('href'),'http://127.0.0.1:5180');assert.equal(wsHref.searchParams.get('workspace'),'tenant-a');assert.equal(wsHref.searchParams.get('area'),'settings');assert.equal(wsHref.searchParams.get('view'),'settings');assert.match(await workspace.getAttribute('aria-label'),new RegExp(tx('Settings',lang)));assert.match(await workspace.getAttribute('title'),/tenant-a/)
const header=await css(p.locator('.fx-topbar')),rail=await css(p.locator('.fx-rail')),act=await css(active),actIcon=await css(active.locator('.fx-nav-icon')),tog=await css(menu),nav=await css(p.locator('.fx-subnav-primary>a.is-active'));report.styles.push({phase:report.phase,header,rail,act,actIcon,tog,nav,iconCenterDelta:tog.x+tog.width/2-actIcon.x-actIcon.width/2});assert.ok(neutral(header.background)&&neutral(rail.background)&&neutral(act.background)&&neutral(actIcon.color)&&neutral(nav.background),'nonneutral shell');assert.equal(act.color,actIcon.color);if(tog.width!==(width===390?44:32)||tog.height!==tog.width)report.findings.push({phase:report.phase,kind:'menu geometry',expected:width===390?44:32,actual:tog});assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth-innerWidth),0)
const controls=await p.locator('.fx-content').locator(icons).evaluateAll(es=>es.filter(e=>{const r=e.getBoundingClientRect();return r.width&&r.height}).map(e=>{const r=e.getBoundingClientRect(),s=getComputedStyle(e),svg=e.querySelector('svg');return {class:e.className,label:e.getAttribute('aria-label'),width:r.width,height:r.height,border:s.borderWidth,radius:s.borderRadius,background:s.backgroundColor,color:s.color,svg:svg?svg.getBoundingClientRect().width:null}}));report.styles.push({phase:report.phase,controls});for(const v of controls){assert.ok(Math.abs(v.width-(width===390?44:32))<.5,'icon width '+JSON.stringify(v));assert.ok(Math.abs(v.height-v.width)<.5,'circle not square '+JSON.stringify(v));if(v.svg!==null)assert.equal(v.svg,16)}
const pill=p.locator('.fx-select:not(.is-rich):not(.fxa-columns-control)>.fx-select-trigger').first();if(await pill.count()){const before=await css(pill);assert.equal(before.radius,'999px','select not pill');await pill.hover();await p.waitForTimeout(160);const hover=await css(pill);assert.ok(neutral(hover.background),'colored hover');await p.keyboard.press('Tab');await pill.focus();await p.waitForTimeout(160);assert.ok(await pill.evaluate(e=>e.matches(':focus-visible')),'keyboard focus not visible');const focus=await css(pill);const contrastMore=await p.evaluate(()=>matchMedia('(prefers-contrast: more)').matches);report.styles.push({phase:report.phase,contrastMore,pillFocus:focus});assert.ok(focus.outlineWidth==='2px'||contrastMore&&focus.outlineWidth==='3px','unexpected select focus width '+JSON.stringify({contrastMore,focus}));assert.ok(neutral(focus.outline),'colored focus');report.styles.push({phase:report.phase,pill:before,hover,focus});await p.mouse.move(2,2)}
if(route==='sessions'){const settings=p.locator('.fxr-session-actions .fxs-settings').first();if(await settings.count()){const sc=await css(settings);assert.equal(sc.background,'rgba(0, 0, 0, 0)');assert.equal(sc.borderWidth,'0px');assert.equal(sc.radius,'0px');report.styles.push({phase:report.phase,settings:sc})}}
if(route==='dashboard'){const ds=await css(p.locator('.fx-dashboard'));assert.ok(neutral(ds.background),'Dashboard nonneutral background');const sep=await p.locator('.fx-rail-primary').evaluate(e=>{const s=getComputedStyle(e);return {top:s.borderTopWidth,bottom:s.borderBottomWidth,color:s.borderTopColor}});assert.equal(sep.top,'1px');assert.equal(sep.bottom,'1px');assert.ok(neutral(sep.color));report.styles.push({phase:report.phase,dashboard:ds,separators:sep});
if(width>760){await workspace.hover();assert.ok(neutral((await css(workspace)).background));await p.keyboard.press('Tab');await workspace.focus();const wf=await css(workspace);assert.ok(['2px','3px'].includes(wf.outlineWidth),'Workspace keyboard focus missing');assert.ok(neutral(wf.outline),'Workspace focus nonneutral');report.styles.push({phase:report.phase,workspaceFocus:wf});await shot('-workspace');await menu.click();assert.ok(await shell.evaluate(e=>e.classList.contains('is-rail-collapsed')));assert.equal(await p.locator('.fx-rail-workspace-copy').isVisible(),false);assert.ok(await p.locator('.fx-wordmark,.fx-wordmark-compact').evaluateAll(es=>es.some(e=>e.getBoundingClientRect().width&&e.getBoundingClientRect().height)));await shot('-collapsed');await menu.click()}else{await menu.click();const drawer=p.locator('aside[role=dialog]');assert.equal(await drawer.getAttribute('aria-modal'),'true');assert.ok(await p.locator('.fx-rail-workspace-copy').isVisible());for(let i=0;i<11;i++){await p.keyboard.press('Tab');assert.ok(await drawer.evaluate(e=>e.contains(document.activeElement)))}await shot('-drawer');await p.keyboard.press('Escape');assert.equal(await p.locator('aside[role=dialog]').count(),0);assert.ok(await menu.evaluate(e=>e===document.activeElement))}
const sort=p.getByRole('button',{name:tx('Sắp xếp phiên',lang),exact:true});await sort.click();await fit(p.locator('.fx-select-menu'));await p.getByRole('option').last().hover();await shot('-sort');await p.keyboard.press('Escape')}
if(route==='analytics'){const tz=p.getByRole('button',{name:tx('Timezone',lang),exact:true});await tz.click();await fit(p.locator('.fx-select-menu'));const list=p.locator('.fx-select-menu [role=listbox]'),g=await list.evaluate(e=>({scroll:e.scrollHeight,client:e.clientHeight,gutter:e.offsetWidth-e.clientWidth,rect:e.getBoundingClientRect().toJSON()}));assert.ok(g.gutter>=10&&g.scroll>g.client);await p.mouse.click(g.rect.right-g.gutter/2,g.rect.y+g.rect.height*.55);assert.ok(await p.locator('.fx-select-menu').isVisible());const initialScroll=await list.evaluate(e=>e.scrollTop);const drag=await list.evaluate(e=>{const r=e.getBoundingClientRect(),usable=e.clientHeight-32,thumb=Math.max(17,usable*e.clientHeight/e.scrollHeight),position=16+e.scrollTop/(e.scrollHeight-e.clientHeight)*(usable-thumb)+thumb/2;return {x:r.right-(e.offsetWidth-e.clientWidth)/2,y:r.y+position}});await p.mouse.move(drag.x,drag.y);await p.mouse.down();await p.mouse.move(drag.x,drag.y+50,{steps:8});await p.mouse.up();assert.ok(await list.evaluate(e=>e.scrollTop)>initialScroll,'native thumb did not drag');assert.ok(await p.locator('.fx-select-menu').isVisible());await shot('-timezone');await p.keyboard.press('Escape');assert.ok(await tz.evaluate(e=>e===document.activeElement))}
if(route==='trades'){const pagination=await p.locator('.fxa-pagination>div:not(.fx-select)>button').evaluateAll(es=>es.filter(e=>e.getBoundingClientRect().width).map(e=>{const r=e.getBoundingClientRect(),s=getComputedStyle(e);return {width:r.width,height:r.height,label:e.getAttribute('aria-label'),radius:s.borderRadius}}));report.styles.push({phase:report.phase,pagination});if(pagination.some(e=>e.width!==e.height||e.height!==(width===390?44:32)))report.findings.push({phase:report.phase,kind:'pagination geometry',pagination});await p.getByRole('button',{name:tx('Trang sau',lang),exact:true}).click();assert.equal(await p.locator('.fxa-pagination [aria-current=page]').innerText(),'2');await p.getByRole('button',{name:tx(width===390?'Trang trước':'Trang đầu',lang),exact:true}).click();assert.equal(await p.locator('.fxa-pagination [aria-current=page]').innerText(),'1');const pagerBox=await p.locator('.fxa-pagination').boundingBox();assert.ok(pagerBox.x>=0&&pagerBox.x+pagerBox.width<=width,'pager footer overflows viewport');assert.equal(pagination.length,width===390?3:9)}
if((width===1320&&lang==='en')||(width===390&&lang==='vi'))await shot()
})
for(const route of Object.keys(routes))for(const lang of ['vi','en'])await run(`actual-unavailable-${route}-${lang}`,async()=>{await go(route,'dark',lang,1320,false);await p.waitForTimeout(150);const body=p.locator('.fx-content'),text=await body.innerText(),alerts=await body.locator('[role=alert]').count();report.styles.push({phase:report.phase,alerts,text:text.slice(0,1600)});assert.ok(alerts>0,'backend unavailable did not render alert');assert.equal(await body.locator('.wm-skeleton').count(),0,'stuck loading');await shot()})
const coarse=await b.newContext({hasTouch:true,viewport:{width:1320,height:987}}),cp=await coarse.newPage();await coarse.routeWebSocket('**/*',ws=>ws.close());await coarse.route('**/*',r=>{const u=new URL(r.request().url());if(u.origin!=='http://127.0.0.1:5180'||!['GET','HEAD','OPTIONS'].includes(r.request().method())){report.blocked.push({url:u.href,method:r.request().method()});return r.abort()}return r.continue()});await run('coarse-pointer-1320',async()=>{await cp.goto('http://127.0.0.1:5180/?workspace=tenant-a&area=testing&view=trade&section=trades&demo=1');await cp.waitForLoadState('networkidle');assert.ok(await cp.evaluate(()=>matchMedia('(pointer:coarse)').matches));const sizes=await cp.locator('.fx-menu-button,.fx-shell-toggle,.fxa-icon-button,.fxa-detail-button,.fxa-columns-control>.fx-select-trigger').evaluateAll(es=>es.filter(e=>e.getBoundingClientRect().width).map(e=>({class:e.className,width:e.getBoundingClientRect().width,height:e.getBoundingClientRect().height})));report.styles.push({phase:report.phase,sizes});const rowSize=await cp.locator('.fxa-pagination .fx-select-trigger').evaluate(e=>e.getBoundingClientRect().height);report.styles.push({phase:report.phase,rowSize});assert.equal(rowSize,44,'coarse row-size select target');for(const s of sizes){assert.equal(s.width,44);assert.equal(s.height,44)}await cp.screenshot({path:path.join(out,'coarse-pointer-1320.png')})});await coarse.close()
report.after=await pins();report.sourceUnchanged=JSON.stringify(report.before)===JSON.stringify(report.after);assert.deepEqual(report.findings,[]);assert.deepEqual(report.failures,[]);assert.deepEqual(report.errors,[]);assert.deepEqual(report.blocked,[]);assert.equal(report.requests.filter(r=>r.demo==='1').length,0);assert.ok(report.sourceUnchanged);report.pass=true
}catch(e){report.failure=String(e);process.exitCode=1}finally{await b.close();await writeFile(path.join(out,'report.json'),JSON.stringify(report,null,2));console.log(JSON.stringify({pass:report.pass,checks:report.checks.length,failures:report.failures.map(f=>({name:f.name,error:f.error})),errors:report.errors,blocked:report.blocked,sourceUnchanged:report.sourceUnchanged}))}
