import assert from 'node:assert/strict'
import {chromium} from '../../../web/node_modules/playwright/index.mjs'
import {readFile,writeFile} from 'node:fs/promises'
import {fileURLToPath} from 'node:url'
import {createHash} from 'node:crypto'
const out=new URL('./',import.meta.url),url='http://127.0.0.1:5180/?workspace=tenant-a&view=overview&area=testing&section=dashboard',report={scope:'Read-only local browser plus intercepted strategy/replay fixtures; no live writes',cases:[],fixtures:[],errors:[],blocked:[]},browser=await chromium.launch({headless:true})
async function setup(width,height,theme,books='empty',status=201){
 const context=await browser.newContext({viewport:{width,height}}),traffic={strategies:[],sessions:[]}
 await context.addInitScript(theme=>{localStorage.setItem('tw-theme',theme);localStorage.setItem('tw-language','vi')},theme);await context.routeWebSocket('**/*',s=>s.close())
 await context.route('**/*',async route=>{const r=route.request(),u=new URL(r.url())
  if(r.method()==='POST'&&u.pathname==='/api/v2/playbooks'){const body=r.postDataJSON();traffic.strategies.push({body,workspace:r.headers()['x-workspace-id']});await new Promise(resolve=>setTimeout(resolve,500));return route.fulfill({status,json:status===201?{record_id:'independent-new-strategy',revision:1,payload:body}:{detail:'Independent strategy rejection'}})}
  if(r.method()==='POST'&&u.pathname==='/api/v2/replay/sessions'){traffic.sessions.push(r.postDataJSON());return route.fulfill({status:422,json:{detail:'Independent stops before navigation'}})}
  if(!['GET','HEAD','OPTIONS'].includes(r.method())||!['http://127.0.0.1:5180','http://127.0.0.1:8010'].includes(u.origin)){report.blocked.push({method:r.method(),url:r.url()});return route.abort()}
  if(u.pathname==='/api/v2/playbooks')return route.fulfill({json:{items:books==='empty'?[]:[{record_id:'existing-strategy',revision:4,payload:{name:'Existing strategy'}}]}})
  return route.continue()
 });const page=await context.newPage();page.on('pageerror',e=>report.errors.push(String(e)));await page.goto(url);await page.locator('.fx-dashboard-quick-action.is-primary').waitFor();return{context,page,traffic}
}
async function open(page){await page.locator('.fx-dashboard-quick-action.is-primary').click();const d=page.locator('dialog.quick-session-dialog');await d.waitFor();return d}
const css=e=>{const s=getComputedStyle(e);return{background:s.backgroundColor,border:s.borderColor,borderWidth:s.borderWidth,outline:s.outline,shadow:s.boxShadow,color:s.color,radius:s.borderRadius,padding:s.padding,minHeight:s.minHeight,decoration:s.textDecorationLine}}
try{
 for(const [width,height,theme] of [[1368,790,'dark'],[1710,987,'dark'],[360,844,'dark'],[1368,790,'light'],[1710,987,'light'],[360,844,'light']]){
  const {context,page,traffic}=await setup(width,height,theme),item={width,theme};report.cases.push(item)
  const actions=page.locator('.fx-dashboard-quick-action');assert.equal(await actions.count(),3);item.actions=[]
  for(let i=0;i<3;i++){const a=actions.nth(i),base=await a.evaluate(css);await a.hover();await page.waitForTimeout(160);const hover=await a.evaluate(css),icon=await a.locator('svg').evaluate(e=>getComputedStyle(e).color);item.actions.push({base,hover,icon})}
  for(const a of item.actions.slice(1))for(const key of ['borderWidth','radius','padding','minHeight'])assert.equal(a.base[key],item.actions[0].base[key]);assert.equal(new Set(item.actions.map(a=>a.hover.border)).size,1);assert.equal(new Set(item.actions.map(a=>a.icon)).size,1)
  await page.screenshot({path:fileURLToPath(new URL(`dashboard-${theme}-${width}.png`,out))});const dialog=await open(page);await dialog.getByRole('button',{name:'Chiến lược',exact:true}).waitFor();item.text=await dialog.innerText();assert.match(item.text,/Tuỳ chọn/);assert.doesNotMatch(item.text,/TradingView Advanced Charts|Chưa có layout dùng chung|Chart được lưu riêng/)
  const balance=dialog.locator('.quick-session-balance input');await balance.focus();item.currency=await balance.evaluate(e=>{const s=getComputedStyle(e),p=getComputedStyle(e.parentElement);return{input:{outline:s.outlineStyle,outlineWidth:s.outlineWidth,shadow:s.boxShadow,borderWidth:s.borderWidth,border:s.borderColor},group:{outline:p.outlineStyle,outlineWidth:p.outlineWidth,shadow:p.boxShadow,border:p.borderColor},content:getComputedStyle(e.closest('dialog')).color}});assert.equal(item.currency.input.outline,'none');assert.equal(item.currency.input.shadow,'none');assert.equal(item.currency.input.borderWidth,'0px');assert.equal(item.currency.group.border,item.currency.content)
  await page.screenshot({path:fileURLToPath(new URL(`currency-focus-${theme}-${width}.png`,out))});const strategy=dialog.locator('.quick-session-strategy .fx-select-trigger');item.strategy=await strategy.evaluate(css);assert.equal(item.strategy.background,'rgba(0, 0, 0, 0)');assert.equal(item.strategy.borderWidth,'1px');assert.match(await strategy.innerText(),/Chọn chiến lược hoặc tạo mới/)
  await strategy.hover();await page.waitForTimeout(160);item.strategyHover=await strategy.evaluate(css);assert.equal(item.strategyHover.background,'rgba(0, 0, 0, 0)');assert.equal(item.strategyHover.borderWidth,'1px');assert.notEqual(item.strategyHover.border,'rgba(0, 0, 0, 0)');await strategy.click();await page.waitForTimeout(160);item.strategyOpen=await strategy.evaluate(css);assert.equal(item.strategyOpen.background,'rgba(0, 0, 0, 0)');assert.equal(item.strategyOpen.borderWidth,'1px');assert.notEqual(item.strategyOpen.border,'rgba(0, 0, 0, 0)');const menu=dialog.locator('.quick-session-strategy .fx-select-menu');await menu.waitFor();assert.equal(await menu.locator('input').count(),0);assert.equal(await menu.locator('.fx-filter-selection').count(),0);assert.equal(await menu.getByRole('option').count(),0);assert.match(await menu.innerText(),/Không tìm thấy kết quả/);await page.screenshot({path:fileURLToPath(new URL(`strategy-empty-${theme}-${width}.png`,out))});await page.keyboard.press('Escape')
  const asset=dialog.getByRole('button',{name:'Chọn tài sản',exact:true});await asset.waitFor({state:'visible'});await page.waitForFunction(()=>!document.querySelector('.quick-session-field-title')?.parentElement.querySelector('.fx-select-trigger')?.disabled);await asset.hover();await page.waitForTimeout(160);item.assetHover=await asset.evaluate(css);assert.equal(item.assetHover.background,'rgba(0, 0, 0, 0)');assert.notEqual(item.assetHover.border,'rgba(0, 0, 0, 0)');await asset.click();await page.waitForTimeout(160);item.assetOpen=await asset.evaluate(css);assert.equal(item.assetOpen.background,'rgba(0, 0, 0, 0)');assert.notEqual(item.assetOpen.border,'rgba(0, 0, 0, 0)');await page.keyboard.press('Escape');const assetLink=dialog.locator('.quick-session-field-title a');item.assetLink={base:await assetLink.evaluate(css)};assert.equal(item.assetLink.base.background,'rgba(0, 0, 0, 0)');assert.equal(item.assetLink.base.decoration,'underline');await assetLink.hover();await page.waitForTimeout(160);item.assetLink.hover=await assetLink.evaluate(css);assert.equal(item.assetLink.hover.background,'rgba(0, 0, 0, 0)');assert.notEqual(item.assetLink.hover.color,item.assetLink.base.color)
  await dialog.getByRole('radio',{name:'Legacy Chart',exact:true}).scrollIntoViewIfNeeded();await page.screenshot({path:fileURLToPath(new URL(`polish-${theme}-${width}.png`,out))});await dialog.locator('.quick-session-body').evaluate(e=>e.scrollTo(0,0));await page.keyboard.press('Escape');assert.equal(traffic.strategies.length+traffic.sessions.length,0);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth-innerWidth),0);item.pass=true;await context.close();console.log(JSON.stringify({case:theme+width,pass:true}))
 }
 for(const [books,status] of [['populated',201],['empty',201],['empty',422],['empty',500]]){
  const {context,page,traffic}=await setup(360,844,'dark',books,status),item={books,status};report.fixtures.push(item);const d=await open(page),strategy=d.locator('.quick-session-strategy .fx-select-trigger');await strategy.click();let menu=d.locator('.quick-session-strategy .fx-select-menu');await menu.waitFor()
  if(books==='populated'){assert.equal(await menu.locator('input').count(),1);assert.equal(await menu.locator('.fx-filter-selection').count(),0);assert.equal(await menu.getByRole('option').count(),1);await menu.getByRole('option',{name:'Existing strategy',exact:true}).click();assert.equal(await strategy.innerText(),'Existing strategy');await d.getByRole('button',{name:'Bỏ chọn chiến lược',exact:true}).click()}else await page.keyboard.press('Escape')
  await d.locator('.quick-session-new-strategy').click();assert.equal(await d.locator('.quick-session-strategy-create input').evaluate(e=>e===document.activeElement),true);await d.locator('.quick-session-strategy-create input').fill('Independent new strategy');await d.getByRole('button',{name:'Tạo chiến lược',exact:true}).click();assert.equal(await d.locator('.quick-session-strategy-create button').first().isDisabled(),true);assert.equal(await d.locator('.quick-session-close').isDisabled(),true);assert.equal(await d.locator('.quick-session-advanced').isDisabled(),true);assert.equal(await d.getByRole('tab').last().isDisabled(),true);assert.equal(await d.locator('.quick-session-field-title a').getAttribute('aria-disabled'),'true');await page.keyboard.press('Escape');assert.equal(await d.count(),1)
  if(status===201){await d.locator('.quick-session-strategy-create').waitFor({state:'detached'});assert.equal(await d.locator('.quick-session-new-strategy').evaluate(e=>e===document.activeElement),true);assert.equal(await strategy.innerText(),'Independent new strategy');await d.locator('.quick-session-fields > label').first().locator('input').fill('Independent replay');await d.getByRole('button',{name:'Chọn tài sản',exact:true}).click();await d.locator('.fx-select-menu input[type=search]').fill('EURUSDm');await d.getByRole('option',{name:/^EURUSDm/}).last().click();await d.locator('.quick-session-submit').click();await d.locator('.quick-session-error').waitFor();assert.equal(traffic.sessions.length,1);assert.equal(traffic.sessions[0].playbook_id,'independent-new-strategy');assert.equal(traffic.sessions[0].playbook_revision,1)}else{await d.locator('.quick-session-strategy-create [role=alert]').waitFor();assert.equal(await d.locator('.quick-session-strategy-create button').first().isDisabled(),status===500)}
  assert.equal(traffic.strategies.length,1);assert.deepEqual(traffic.strategies[0],{workspace:'tenant-a',body:{name:'Independent new strategy',status:'draft',execution_capability:'needs-definition',rules:{}}});item.traffic=traffic;item.pass=true;await page.screenshot({path:fileURLToPath(new URL(`inline-strategy-${books}-${status}.png`,out))});await page.keyboard.press('Escape');await context.close();console.log(JSON.stringify({books,status,pass:true}))
 }
 assert.deepEqual(report.errors,[]);assert.deepEqual(report.blocked,[]);report.pass=true
}catch(e){report.pass=false;report.failure=String(e);throw e}
finally{report.sourceHashes={};for(const file of ['web/src/QuickSessionDialog.jsx','web/src/quick-session.css','web/src/FxSelect.jsx','web/src/playbookApi.js','web/src/testing-copy.json','web/src/dashboard.css']){try{report.sourceHashes[file]=createHash('sha256').update(await readFile(new URL('../../../'+file,import.meta.url))).digest('hex')}catch{}}await writeFile(new URL('polish-review.json',out),JSON.stringify(report,null,2));await browser.close();console.log(JSON.stringify({pass:report.pass,cases:report.cases.length,fixtures:report.fixtures.length,failure:report.failure,errors:report.errors,blocked:report.blocked}))}
