import assert from 'node:assert/strict'
import {chromium} from '../../../web/node_modules/playwright/index.mjs'
import {readFile,writeFile} from 'node:fs/promises'
import {createHash} from 'node:crypto'
import {fileURLToPath} from 'node:url'
const out=new URL('./',import.meta.url),session='476f4b498e1a49ed9d48a75719f4d270'
const url=`http://127.0.0.1:5180/?workspace=tenant-a&view=replay&session=${session}&dataset=dataset-262639d819219431b8bbfd00a665d4fb7fde4c646a4fa0c5020608c1e1c3572d&mode=Practice&surface=workspace&cursor=500&chart_iframe=srcdoc`
const report={scope:'Positions and focus polish. Real local GET + isolated response-only 35-closed-trade fixture. No persisted replay/order/activity writes.',cases:[],fixture:[],errors:[],blocked:[]},browser=await chromium.launch({headless:true})
const styles=loc=>loc.evaluate(e=>{const s=getComputedStyle(e);return{background:s.backgroundColor,color:s.color,outlineStyle:s.outlineStyle,outlineWidth:s.outlineWidth,outlineOffset:s.outlineOffset,outlineColor:s.outlineColor,borderColor:s.borderColor,borderTop:s.borderTopWidth,borderBottom:s.borderBottomWidth,borderBottomColor:s.borderBottomColor,radius:s.borderRadius,shadow:s.boxShadow,filter:s.filter,rect:e.getBoundingClientRect().toJSON()}})
async function setup(width,height,theme,fixture=false,transport='srcdoc',forceTelemetry=false){
 const context=await browser.newContext({viewport:{width,height}})
 await context.addInitScript(theme=>{localStorage.setItem('tw-theme',theme);localStorage.setItem('tw-language','vi')},theme)
 if(forceTelemetry)await context.addInitScript(()=>{Math.random=()=>0});await context.routeWebSocket('**/*',s=>s.close())
 await context.route('**/*',async route=>{const r=route.request(),u=new URL(r.url());if(r.method()==='POST'&&u.pathname===`/api/v2/replay/sessions/${session}/activity`){const e=r.postDataJSON();return route.fulfill({status:200,json:{schema_version:'replay-activity-v1',event_id:e.event_id,session_id:session,accepted_seconds:(Date.parse(e.ended_at_utc)-Date.parse(e.started_at_utc))/1000}})}if(!['GET','HEAD','OPTIONS'].includes(r.method())||!['http://127.0.0.1:5180','http://127.0.0.1:8010'].includes(u.origin)){report.blocked.push({method:r.method(),url:r.url()});return route.abort()}if(fixture&&u.pathname===`/api/v2/replay/sessions/${session}`){const response=await route.fetch(),body=await response.json();body.payload.execution={...body.payload.execution,cursor_index:body.view_cursor_index??body.payload.cursor_index,ledger:Array.from({length:35},(_,i)=>({kind:'protective_fill',sequence:i+1,virtual_time_utc:'2026-07-05T00:00:00Z',details:{position_id:`review-${i}`,side:'BUY',quantity:i+1,net_pnl:i+1,cost_breakdown:{commission_account:0}}}))};return route.fulfill({response,json:body})}return route.continue()})
 const page=await context.newPage();page.on('pageerror',e=>report.errors.push(e.stack||String(e)));await page.goto(transport==='srcdoc'?url:url.replace('&chart_iframe=srcdoc',''));await page.locator('[data-chart-status=ready]').waitFor({timeout:30000});await page.frameLocator('.advanced-chart-host iframe').getByTestId('legacy-native-market').waitFor();return{context,page}
}
try{
 for(const [width,height,theme] of (process.env.POSITIONS_FIXTURE_ONLY?[]:[[1368,790,'dark'],[1368,790,'light'],[360,844,'dark'],[360,844,'light'],[1920,940,'dark'],[1920,940,'light']])){
  const {context,page}=await setup(width,height,theme),item={width,height,theme};report.cases.push(item)
  item.header=await page.evaluate(()=>{const d=document.querySelector('.advanced-chart-host iframe').contentDocument;return{width:d.querySelector('.layout__area--top').getBoundingClientRect().width,buttons:[...d.querySelectorAll('.layout__area--top .legacy-native-extension button,.layout__area--top .button-9pA37sIi,.layout__area--top .button-khcLBZEz,.layout__area--left .button-G7o5fBfa')].filter(e=>{const r=e.getBoundingClientRect();return r.width&&r.height}).map(e=>({title:e.title,radius:getComputedStyle(e).borderRadius})),overflow:document.documentElement.scrollWidth-innerWidth}})
  assert.equal(item.header.width,width);assert.equal(item.header.overflow,0);assert.ok(item.header.buttons.every(b=>b.radius==='6px'))
  item.grips=[];for(const cls of ['.chart-float-grip','.legacy-positions-grip']){const grip=page.locator(cls);await page.mouse.move(1,450);await page.waitForTimeout(160);const base=await styles(grip);await grip.hover();await page.waitForTimeout(160);const hover=await styles(grip);for(const k of ['background','color','shadow','filter'])assert.equal(hover[k],base[k]);item.grips.push({cls,base,hover})}
  item.quantity=[];for(const loc of [page.locator('.legacy-quantity-control input'),page.locator('.legacy-quantity-control button').first(),page.locator('.legacy-quantity-control button').last()]){await loc.focus();const child=await styles(loc),group=await styles(page.locator('.legacy-quantity-control'));assert.equal(group.outlineOffset,'-2px');assert.equal(group.outlineWidth,'2px');assert.equal(child.outlineStyle,'none');item.quantity.push({child,group})}
  await page.locator('.legacy-trading-bar .chart-trading-account > button').nth(2).click();await page.locator('.legacy-positions').waitFor()
  assert.equal(await page.locator('.legacy-position-tabs').getByText('SIM',{exact:true}).count(),0)
  const tabs=page.locator('.legacy-position-tabs'),active=tabs.locator('[aria-selected=true]'),inactive=tabs.locator('[aria-selected=false]').first();item.tabs={base:await styles(inactive),active:await styles(active),container:await styles(tabs)};await inactive.hover();await page.waitForTimeout(160);item.tabs.hover=await styles(inactive);assert.equal(item.tabs.hover.background,'rgba(0, 0, 0, 0)');assert.notEqual(item.tabs.hover.color,item.tabs.base.color);assert.equal(item.tabs.active.borderBottom,'1px');assert.equal(item.tabs.active.borderBottomColor,item.tabs.active.color);assert.equal(item.tabs.container.borderTop,'1px')
  const geometry=()=>page.evaluate(()=>{const p=document.querySelector('.legacy-position-paging'),th=document.querySelector('.legacy-positions th'),section=document.querySelector('.legacy-positions');return{paging:p.getBoundingClientRect().toJSON(),section:section.getBoundingClientRect().toJSON(),headerBg:getComputedStyle(th).backgroundColor,sectionBg:getComputedStyle(section).backgroundColor,overflow:document.documentElement.scrollWidth-innerWidth,pagingBorder:getComputedStyle(p).borderTopWidth,left:p.querySelector('label').getBoundingClientRect().toJSON(),right:p.querySelector('.legacy-position-navigation').getBoundingClientRect().toJSON()}})
  item.normal=await geometry();assert.equal(item.normal.overflow,0);assert.ok(Math.abs(item.normal.paging.bottom-height)<=1);assert.notEqual(item.normal.headerBg,item.normal.sectionBg);assert.equal(item.normal.pagingBorder,'1px');assert.ok(item.normal.left.right<=item.normal.right.x)
  await page.screenshot({path:fileURLToPath(new URL(`positions-normal-${theme}-${width}.png`,out))})
  await page.locator('.legacy-trading-bar .chart-trading-account > button').last().click();item.maximized=await geometry();item.maximized.replayVisibility=await page.locator('.legacy-replay-toolbar').evaluate(e=>getComputedStyle(e).visibility);assert.equal(item.maximized.replayVisibility,'hidden');const closed=page.locator('#position-tab-closed');await closed.click();assert.equal(await closed.getAttribute('aria-selected'),'true');assert.ok(Math.abs(item.maximized.paging.bottom-height)<=1);assert.equal(item.maximized.overflow,0);await page.screenshot({path:fileURLToPath(new URL(`positions-maximized-${theme}-${width}.png`,out))});await page.locator('.legacy-trading-bar .chart-trading-account > button').last().click();assert.equal(await page.locator('.legacy-replay-toolbar').evaluate(e=>getComputedStyle(e).visibility),'visible');await context.close()
 }
 for(const theme of ['dark','light']){
  const {context,page}=await setup(1368,790,theme,true),item={theme};report.fixture.push(item);await page.locator('.legacy-trading-bar .chart-trading-account > button').last().click();await page.locator('#position-tab-closed').click();const rows=page.locator('.legacy-position-scroll tbody tr'),size=page.locator('.legacy-position-paging label select'),current=page.getByRole('combobox',{name:'Trang hiện tại'}),prev=page.getByRole('button',{name:'Trang trước'}),next=page.getByRole('button',{name:'Trang sau'});assert.equal(await rows.count(),10);assert.equal(await current.locator('option').count(),4);assert.equal(await prev.isDisabled(),true);await next.click();assert.equal(await current.inputValue(),'1');assert.match(await rows.first().innerText(),/11/);await current.selectOption({value:'3'});await page.waitForTimeout(100);item.directPage={value:await current.inputValue(),rows:await rows.count(),table:await rows.allTextContents()};await page.waitForFunction(n=>document.querySelectorAll('.legacy-position-scroll tbody tr').length===n,5);assert.equal(await rows.count(),5);assert.equal(await next.isDisabled(),true);await size.selectOption('25');assert.equal(await current.inputValue(),'0');await page.waitForFunction(n=>document.querySelectorAll('.legacy-position-scroll tbody tr').length===n,25);assert.equal(await rows.count(),25);assert.equal(await current.locator('option').count(),2);await next.click();await page.waitForFunction(()=>document.querySelectorAll('.legacy-position-scroll tbody tr').length===10);assert.equal(await rows.count(),10);await size.selectOption('50');await page.waitForFunction(n=>document.querySelectorAll('.legacy-position-scroll tbody tr').length===n,35);assert.equal(await rows.count(),35);assert.equal(await prev.isDisabled(),true);assert.equal(await next.isDisabled(),true);await page.locator('#position-tab-open').click();await page.locator('#position-tab-open').press('End');assert.equal(await page.locator('#position-tab-closed').getAttribute('aria-selected'),'true');item.pass=true;await page.screenshot({path:fileURLToPath(new URL(`positions-fixture-${theme}.png`,out))});await context.close()
 }
 report.telemetry=[];for(const transport of ['blob','srcdoc']){const {context,page}=await setup(1368,790,'dark',false,transport,true);await page.waitForTimeout(1000);report.telemetry.push({transport,sampledRandom:0,pass:true});await context.close()}assert.deepEqual(report.errors,[]);assert.deepEqual(report.blocked,[]);report.pass=true
}catch(e){report.pass=false;report.failure=String(e);throw e}
finally{report.sourceHashes={};for(const file of ['web/public/chart-legacy.css','web/src/ChartWorkbench.css','web/src/LegacyTradingBar.css','web/src/LegacyPositions.jsx','web/src/testing-copy.json','web/src/TradingViewReplayChart.jsx'])report.sourceHashes[file]=createHash('sha256').update(await readFile(new URL('../../../'+file,import.meta.url))).digest('hex');await writeFile(new URL('positions-review.json',out),JSON.stringify(report,null,2));await browser.close();console.log(JSON.stringify({pass:report.pass,cases:report.cases.length,fixtures:report.fixture.length,failure:report.failure,errors:report.errors,blocked:report.blocked}))}
